//////////////////////////////////////////////////////////////////////
//
//  BDPTZeroDensityConnectibleTest.cpp - Pins DL-430: BDPT's MISWeight
//  must give a ZERO ratio, not 1, where a NON-delta, connectible vertex
//  generates a reverse density of exactly zero.
//
//  Author: Aravind Krishnaswamy
//  Date of Birth: 2026-10-03
//  Tabs: 4
//  Comments:
//
//    THE DEFECT.  `BDPTIntegrator::MISWeight` maps every zero `pdfRev`
//    to 1 (remap0) so the ratio chain survives a DELTA vertex, whose
//    density is a Dirac the strategies through it share.  A zero produced
//    by a NON-delta, connectible vertex means something else: that vertex
//    can never scatter toward its neighbour, so every strategy that needs
//    it to has density zero.  Remapped to 1, those impossible strategies
//    entered the power-heuristic denominator with ratio 1/pdfFwd and
//    deflated the weight of the strategies that DO generate the path.
//
//    THE FIXTURE.  A 2x2 floor lit by a 4x4 one-sided area emitter
//    behind the camera; nothing else, so every path has exactly one floor
//    vertex and PT is exact.  The floor's material is replaced, after the
//    scene loads, by one of two test-local materials whose BSDF is the
//    ordinary 0.5 Lambertian:
//      null SPF  -- `GetSPF()` returns null (`datadriven_material`'s state
//                   before DL-325): the BSDF is evaluable for connections
//                   but the vertex can never be generated by scattering.
//      half SPF  -- the Lambertian SPF restricted to world x >= 0: it emits
//                   only there and its `Pdf` reports 0 for x < 0 (a
//                   consistent sub-density), so floor points with x > 0 see
//                   the emitter through a hole in their sampling density.
//    Both have the SAME expected image as plain `lambertian_material`
//    under PT (NEE carries the hole at MIS weight 1), so the reference is
//    PT on the plain Lambertian floor, and each half of the image is
//    compared separately (the half-SPF hole covers one half only).
//
//    RED-PROOF: see docs/DEBT_LEDGER.md DL-430 for the measured numbers.
//
//  License Information: Please see the attached LICENSE.TXT file
//
//////////////////////////////////////////////////////////////////////

#include <cstdio>
#include <cstdlib>
#include <iostream>
#include <fstream>
#include <vector>
#include <cmath>
#include <string>
#include <algorithm>
#ifdef _WIN32
	#include <process.h>
	#define getpid _getpid
#else
	#include <unistd.h>
#endif

#include "../src/Library/Interfaces/IJob.h"
#include "../src/Library/Interfaces/IJobPriv.h"
#include "../src/Library/Interfaces/IObjectPriv.h"
#include "../src/Library/Interfaces/IObjectManager.h"
#include "../src/Library/Interfaces/IRasterizer.h"
#include "../src/Library/Interfaces/IRasterizerOutput.h"
#include "../src/Library/Interfaces/IRasterImage.h"
#include "../src/Library/Interfaces/IMaterial.h"
#include "../src/Library/Interfaces/ISPF.h"
#include "../src/Library/Materials/LambertianMaterial.h"
#include "../src/Library/Painters/UniformColorPainter.h"
#include "../src/Library/Utilities/Reference.h"
#include "../src/Library/Utilities/SobolSampler.h"
#include "../src/Library/Utilities/Color/Color_Template.h"

using namespace RISE;
using namespace RISE::Implementation;

namespace RISE
{
	bool RISE_CreateJobPriv( IJobPriv** ppi );
}

static int passCount = 0;
static int failCount = 0;

static void Check( bool condition, const std::string& testName )
{
	if( condition ) {
		passCount++;
	} else {
		failCount++;
		std::cout << "  FAIL: " << testName << std::endl;
	}
}

//////////////////////////////////////////////////////////////////////
// HoleMaterial -- Lambertian BSDF; SPF either absent (mode 0) or the
// Lambertian SPF restricted to world x >= 0 (mode 1).
//////////////////////////////////////////////////////////////////////
class HoleMaterial : public IMaterial, public ISPF, public Reference
{
	LambertianMaterial* inner;
	int mode;

	static bool Open( const Vector3& w ) { return w.x >= 0; }

	void Filter( const ScatteredRayContainer& in, ScatteredRayContainer& out ) const
	{
		for( unsigned int i = 0; i < in.Count(); i++ ) {
			if( Open( in[i].ray.Dir() ) ) {
				out.AddScatteredRay( in[i] );
			}
		}
	}

protected:
	virtual ~HoleMaterial() { safe_release( inner ); }

public:
	HoleMaterial( LambertianMaterial* l, int m ) : inner( l ), mode( m ) { inner->addref(); }

	using IMaterial::Pdf;
	using IMaterial::PdfNM;

	IBSDF* GetBSDF() const override { return inner->GetBSDF(); }
	ISPF* GetSPF() const override { return mode == 0 ? nullptr : const_cast<HoleMaterial*>( this ); }
	IEmitter* GetEmitter() const override { return nullptr; }

	void Scatter( const RayIntersectionGeometric& ri, ISampler& sampler,
		ScatteredRayContainer& out, const IORStack& stack ) const override
	{
		ScatteredRayContainer all;
		inner->GetSPF()->Scatter( ri, sampler, all, stack );
		Filter( all, out );
	}
	void ScatterNM( const RayIntersectionGeometric& ri, ISampler& sampler, const Scalar nm,
		ScatteredRayContainer& out, const IORStack& stack ) const override
	{
		ScatteredRayContainer all;
		inner->GetSPF()->ScatterNM( ri, sampler, nm, all, stack );
		Filter( all, out );
	}
	Scalar Pdf( const RayIntersectionGeometric& ri, const Vector3& wo,
		const IORStack& stack ) const override
	{
		return Open( wo ) ? inner->GetSPF()->Pdf( ri, wo, stack ) : Scalar( 0 );
	}
	Scalar PdfNM( const RayIntersectionGeometric& ri, const Vector3& wo, const Scalar nm,
		const IORStack& stack ) const override
	{
		return Open( wo ) ? inner->GetSPF()->PdfNM( ri, wo, nm, stack ) : Scalar( 0 );
	}
};

class CapturingRasterizerOutput
	: public virtual IRasterizerOutput
	, public virtual Reference
{
public:
	std::vector<RISEColor> pixels;
	unsigned int width, height;
	CapturingRasterizerOutput() : width( 0 ), height( 0 ) {}
protected:
	virtual ~CapturingRasterizerOutput() {}
public:
	virtual void OutputIntermediateImage( const IRasterImage&, const Rect* ) override {}
	virtual void OutputImage( const IRasterImage& pImage, const Rect*, const unsigned int ) override
	{
		width = pImage.GetWidth();
		height = pImage.GetHeight();
		pixels.resize( width * height );
		for( unsigned int y = 0; y < height; y++ ) {
			for( unsigned int x = 0; x < width; x++ ) {
				pixels[y * width + x] = pImage.GetPEL( x, y );
			}
		}
	}
};

//! Mean composited luminance of the left / right image halves.
struct Halves { double left, right; };

static Halves HalfMeans( const CapturingRasterizerOutput& cap )
{
	Halves h = { -1.0, -1.0 };
	if( cap.pixels.empty() ) return h;
	double s[2] = { 0, 0 };
	unsigned n[2] = { 0, 0 };
	for( unsigned y = 0; y < cap.height; y++ ) {
		for( unsigned x = 0; x < cap.width; x++ ) {
			const RISEColor& c = cap.pixels[y * cap.width + x];
			const double l = c.a * ( 0.2126 * c.base.r + 0.7152 * c.base.g + 0.0722 * c.base.b );
			if( !std::isfinite( l ) ) return h;
			const int k = ( 2 * x < cap.width ) ? 0 : 1;
			s[k] += l;
			n[k]++;
		}
	}
	h.left = s[0] / n[0];
	h.right = s[1] / n[1];
	return h;
}

static std::string WriteSceneToTempFile( const std::string& sceneText, const char* tag )
{
	char path[512];
	const char* tmpBase = std::getenv( "TMPDIR" );
	if( !tmpBase || !*tmpBase ) tmpBase = "/tmp";
	std::snprintf( path, sizeof(path), "%s/bdpt_zero_density_%s_%d.RISEscene",
		tmpBase, tag, static_cast<int>( ::getpid() ) );
	std::ofstream ofs( path );
	if( !ofs.is_open() ) return std::string();
	ofs << sceneText;
	return std::string( path );
}

//! Renders once; `holeMode` < 0 keeps the scene's Lambertian floor.
static Halves RenderHalves( const char* scenePath, int holeMode, unsigned salt )
{
	Halves bad = { -1.0, -1.0 };
	IJobPriv* pJob = nullptr;
	if( !RISE_CreateJobPriv( &pJob ) || !pJob ) return bad;
	if( !pJob->LoadAsciiSceneViaCst( scenePath ) ) {
		safe_release( pJob );
		return bad;
	}
	if( holeMode >= 0 ) {
		IObjectPriv* pFloor = pJob->GetObjects()->GetItem( "obj_quad" );
		if( !pFloor ) { safe_release( pJob ); return bad; }
		UniformColorPainter* pPaint = new UniformColorPainter( RISEPel( 0.5, 0.5, 0.5 ) );
		LambertianMaterial* pLamb = new LambertianMaterial( *pPaint );
		HoleMaterial* pHole = new HoleMaterial( pLamb, holeMode );
		pFloor->AssignMaterial( *pHole );
		safe_release( pHole );
		safe_release( pLamb );
		safe_release( pPaint );
	}
	pJob->RemoveRasterizerOutputs();
	CapturingRasterizerOutput* pCap = new CapturingRasterizerOutput();
	GlobalLog()->PrintNew( pCap, __FILE__, __LINE__, "test capture output" );
	pJob->GetRasterizer()->AddRasterizerOutput( pCap );
	std::srand( 430000u + salt );
	SobolSamplerTestHooks::ValueSalt().store( SobolSequence::HashCombine( 0x430u, salt ) );
	const bool bRendered = pJob->Rasterize();
	SobolSamplerTestHooks::ValueSalt().store( 0u );
	const Halves h = bRendered ? HalfMeans( *pCap ) : bad;
	safe_release( pCap );
	safe_release( pJob );
	return h;
}

struct Stat { double mean[2], sd[2]; bool ok; };

static Stat SaltedHalves( const std::string& scene, const char* tag, int holeMode, int n )
{
	Stat s = { { 0, 0 }, { 0, 0 }, false };
	const std::string path = WriteSceneToTempFile( scene, tag );
	if( path.empty() ) return s;
	double sum[2] = { 0, 0 }, sumSq[2] = { 0, 0 };
	for( int i = 0; i < n; i++ ) {
		const Halves h = RenderHalves( path.c_str(), holeMode, unsigned( i ) + 1u );
		if( h.left < 0 ) { std::remove( path.c_str() ); return s; }
		const double v[2] = { h.left, h.right };
		for( int k = 0; k < 2; k++ ) { sum[k] += v[k]; sumSq[k] += v[k] * v[k]; }
	}
	std::remove( path.c_str() );
	for( int k = 0; k < 2; k++ ) {
		s.mean[k] = sum[k] / n;
		s.sd[k] = n > 1 ? std::sqrt( std::max( 0.0, ( sumSq[k] - n * s.mean[k] * s.mean[k] ) / ( n - 1 ) ) ) : 0.0;
	}
	s.ok = true;
	return s;
}

//////////////////////////////////////////////////////////////////////
// Scene text.
//////////////////////////////////////////////////////////////////////
static const char* kScene =
	"film\n{\n\twidth 32\n\theight 32\n}\n\n"
	"pinhole_camera\n{\n\tlocation 0 0 3.5\n\tlookat 0 0 0\n\tup 0 1 0\n\tfov 30.0\n}\n\n"
	"uniformcolor_painter\n{\n\tname pnt_albedo\n\tcolor 0.5 0.5 0.5\n}\n\n"
	"lambertian_material\n{\n\tname mat_diffuse\n\treflectance pnt_albedo\n}\n\n"
	"clippedplane_geometry\n{\n\tname quad\n\tpta -1 -1 0\n\tptb 1 -1 0\n\tptc 1 1 0\n\tptd -1 1 0\n}\n\n"
	"standard_object\n{\n\tname obj_quad\n\tgeometry quad\n\tmaterial mat_diffuse\n}\n\n"
	"uniformcolor_painter\n{\n\tname pnt_emit\n\tcolor 1.0 1.0 1.0\n}\n\n"
	"lambertian_luminaire_material\n{\n\tname mat_emit\n\texitance pnt_emit\n\tscale 5.0\n\tmaterial none\n}\n\n"
	// 4x4, one-sided, facing -z (clockwise seen from +z); behind the camera.
	"clippedplane_geometry\n{\n\tname quad_emit\n\tpta -2 2 4\n\tptb 2 2 4\n\tptc 2 -2 4\n\tptd -2 -2 4\n\tdoublesided FALSE\n}\n\n"
	"standard_object\n{\n\tname obj_emit\n\tgeometry quad_emit\n\tmaterial mat_emit\n}\n";

static const char* kShader =
	"standard_shader\n{\n\tname global\n\tshaderop DefaultPathTracing\n}\n\n";

static const char* kPT =
	"pathtracing_pel_rasterizer\n{\n\tsamples 32\n\tpixel_filter box\n\toidn_denoise FALSE\n}\n\n";
static const char* kBDPT =
	"bdpt_pel_rasterizer\n{\n\tmax_eye_depth 3\n\tmax_light_depth 3\n\tsamples 32\n\tpixel_filter box\n\toidn_denoise FALSE\n}\n\n";
static const char* kVCM =
	"vcm_pel_rasterizer\n{\n\tmax_eye_depth 3\n\tmax_light_depth 3\n\tsamples 32\n\tmerge_radius 0.0\n"
	"\tvc_enabled true\n\tvm_enabled true\n\tpixel_filter box\n\toidn_denoise FALSE\n}\n\n";

static std::string Scene( const char* rasterizer )
{
	return std::string( "RISE ASCII SCENE 7\n" ) + kShader + rasterizer + kScene;
}

static const int kRepeats = 4;
// Mean band against the PT Lambertian reference, per image half.  The
// measured salted sd of a half-mean is ~0.1-0.3 % at this sample count
// (printed below); the defect it guards against is a factor of ~0.006
// (null SPF) and ~0.5 on the hole half (half SPF).
static const double kBand = 0.03;

static void Compare( const char* label, const Stat& got, const Stat& ref )
{
	for( int k = 0; k < 2; k++ ) {
		const double ratio = ref.mean[k] > 0 ? got.mean[k] / ref.mean[k] : -1.0;
		std::printf( "  %-26s %s half: %.6f (sd %.6f)   ref %.6f   ratio %.5f\n",
			label, k == 0 ? "left " : "right", got.mean[k], got.sd[k], ref.mean[k], ratio );
		Check( got.ok && std::fabs( ratio - 1.0 ) <= kBand,
			std::string( label ) + ( k == 0 ? " left" : " right" ) + " half within band of PT Lambertian" );
	}
}

int main()
{
	std::cout << "DL-430: zero sampling density at a non-delta connectible vertex" << std::endl;
	const Stat ref = SaltedHalves( Scene( kPT ), "pt_lamb", -1, kRepeats );
	Check( ref.ok && ref.mean[0] > 0 && ref.mean[1] > 0, "PT Lambertian reference renders" );
	std::printf( "  PT lambertian (reference)  left %.6f (sd %.6f)   right %.6f (sd %.6f)\n",
		ref.mean[0], ref.sd[0], ref.mean[1], ref.sd[1] );

	struct Row { const char* label; const char* rast; const char* tag; int mode; };
	const Row rows[] = {
		{ "PT null SPF",       kPT,   "pt_null",    0 },
		{ "PT half SPF",       kPT,   "pt_half",    1 },
		{ "BDPT lambertian",   kBDPT, "bdpt_lamb", -1 },
		{ "BDPT null SPF",     kBDPT, "bdpt_null",  0 },
		{ "BDPT half SPF",     kBDPT, "bdpt_half",  1 },
		{ "VCM null SPF",      kVCM,  "vcm_null",   0 },
		{ "VCM half SPF",      kVCM,  "vcm_half",   1 },
	};
	for( const Row& r : rows ) {
		Compare( r.label, SaltedHalves( Scene( r.rast ), r.tag, r.mode, kRepeats ), ref );
	}

	std::cout << std::endl << "BDPTZeroDensityConnectibleTest: " << passCount << " passed, "
		<< failCount << " failed" << std::endl;
	return failCount == 0 ? 0 : 1;
}
