//////////////////////////////////////////////////////////////////////
//
//  HairFileImportTest.cpp - Contract test for the Cem Yuksel `.hair`
//    IMPORTER: `HairFileLoader` and `hair_geometry`'s `file` mode
//    (Phase 2 slice P2-B of the hair/fur arc, docs/HAIR_FUR_DESIGN.md
//    section 7).
//
//  WHAT THIS TEST OWNS, and why it is its own file.  HairGeneratorTest
//  owns the GROW mode (recipe -> strands) and HairGuidesTest owns the
//  guide-interpolation delta on top of it.  Neither has anything to say
//  about a groom that arrives as bytes on disk, which is a different
//  risk surface entirely: a binary parser's failure modes are
//  truncation, a lying header, and silently-misread arrays, not
//  placement arithmetic.
//
//  THE FIXTURES ARE WRITTEN BY THIS TEST, and that is the point.
//  `MakeHairFile` below is an INDEPENDENT writer of the published
//  format -- it packs the 128-byte header and the arrays from the
//  specification table, with no code shared with the reader under test
//  -- so every positional assertion is a genuine writer/reader
//  round-trip rather than a reader agreeing with itself.  It is also
//  the only way to author the NEGATIVE fixtures at all: a truncated
//  file, a bad magic, a header whose segment counts contradict its
//  point count, a reserved flag bit.  Those cannot be committed assets;
//  a corrupt file in the scene corpus would be a liability, and a scene
//  referencing a file that does not exist cannot go in the corpus
//  either.
//
//  ONE fixture IS committed -- scenes/Tests/ChunkCoverage/assets/
//  tiny.hair, 392 bytes, generated by that directory's
//  gen_chunkcoverage_assets.py alongside the .3ds / .exr / .tiff / .bdf
//  it already generates -- because the ChunkCoverage scene for `file`
//  mode needs a real asset on disk.  Group 7 loads that exact file, so
//  the corpus scene cannot rot silently.
//
//  The seven groups:
//
//    1. ROUND TRIP, ALL ARRAYS PRESENT.  A 5-strand file with an
//       explicit segments array and a per-point thickness array: every
//       header field, every per-strand point count, every control point
//       and every thickness comes back exactly as written.
//
//    2. THE HEADER-DEFAULT PATHS.  The same groom with the segments
//       array absent (uniform default segment count), with the
//       thickness array absent (header default width), and with both
//       absent.
//
//    3. REFUSALS.  Fourteen malformed files, each of which must be
//       refused WITHOUT reading past the end of anything: bad magic, a
//       stub shorter than the header, a truncated array section, no
//       points flag, a reserved flag bit, zero counts, over-cap counts,
//       a segments array that does not sum to the point count, a zero
//       segment entry, a default-segments arithmetic mismatch, a
//       non-finite header thickness.  Plus the one malformation that is
//       NOT fatal: trailing bytes after the arrays, which load with a
//       warning.
//
//    4. STRAND CONSTRUCTION.  Widths come from each strand's FIRST and
//       LAST thickness (interior values are dropped, by design); the
//       two width parameters MULTIPLY rather than replace; a strand
//       with a non-finite control point or an unusable width is dropped
//       and counted while its neighbours survive; an all-bad file
//       fails; a file with no width at all falls back to RISE's
//       human-hair defaults, which the multipliers then scale.
//
//    5. THE GEOMETRY.  The strands reach `HairGeometry` intact --
//       control points, root/tip widths and the (0,0) root UV all
//       checked against the arrays this test wrote -- and the imported
//       groom is in explicit-strand mode (already realized).
//
//    6. THE CHUNK.  `hair_geometry { file ... }` parses end-to-end and
//       registers a groom of the right size; `file` + `base_geometry`,
//       `file` + `guides`, `file` + any other grow-mode parameter, and
//       a chunk with NEITHER source are each refused with a diagnostic
//       naming what was wrong; so are a missing file and a
//       non-positive width multiplier.
//
//    7. THE COMMITTED CORPUS ASSET.  tiny.hair loads and matches what
//       its generator says it contains.
//
//////////////////////////////////////////////////////////////////////

#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <iostream>
#include <limits>
#include <sstream>
#include <string>
#include <vector>
#ifdef _WIN32
	#include <process.h>
	#include <io.h>
	#define getpid _getpid
	#define RISE_TEST_DUP    _dup
	#define RISE_TEST_DUP2   _dup2
	#define RISE_TEST_CLOSE  _close
	#define RISE_TEST_FILENO _fileno
#else
	#include <unistd.h>
	#define RISE_TEST_DUP    dup
	#define RISE_TEST_DUP2   dup2
	#define RISE_TEST_CLOSE  close
	#define RISE_TEST_FILENO fileno
#endif

#include "../src/Library/RISE_API.h"
#include "../src/Library/Job.h"
#include "../src/Library/Interfaces/IJobPriv.h"
#include "../src/Library/Interfaces/IGeometryManager.h"
#include "../src/Library/Geometry/HairGeometry.h"
#include "../src/Library/Importers/HairFileLoader.h"
#include "../src/Library/SceneEditor/ChunkDescriptorRegistry.h"
#include "../src/Library/Utilities/Reference.h"

using namespace RISE;
using namespace RISE::Implementation;

static int g_checks   = 0;
static int g_failures = 0;

static void Check( const bool ok, const std::string& what )
{
	++g_checks;
	if( !ok ) {
		++g_failures;
		std::cout << "  FAIL: " << what << std::endl;
	}
}

namespace {

template<class T>
class Owned
{
public:
	explicit Owned( T* q = 0 ) : p( q ) {}
	~Owned() { if( p ) p->release(); }
	T*   operator->() const { return p; }
	T&   operator*()  const { return *p; }
	T*   get()        const { return p; }
	explicit operator bool() const { return p != 0; }
private:
	T* p;
	Owned( const Owned& );
	Owned& operator=( const Owned& );
};

//////////////////////////////////////////////////////////////////////
// An INDEPENDENT writer of the .hair format (see the file header for
// why it does not share a line with the reader).  Little-endian packing
// is done byte by byte so the writer is correct on any host, exactly as
// the reader's decode is.
//////////////////////////////////////////////////////////////////////

void PutU32( std::vector<unsigned char>& b, const unsigned int v )
{
	b.push_back( (unsigned char)( v         & 0xFF ) );
	b.push_back( (unsigned char)( ( v >>  8 ) & 0xFF ) );
	b.push_back( (unsigned char)( ( v >> 16 ) & 0xFF ) );
	b.push_back( (unsigned char)( ( v >> 24 ) & 0xFF ) );
}

void PutU16( std::vector<unsigned char>& b, const unsigned int v )
{
	b.push_back( (unsigned char)( v        & 0xFF ) );
	b.push_back( (unsigned char)( ( v >> 8 ) & 0xFF ) );
}

void PutF32( std::vector<unsigned char>& b, const float f )
{
	unsigned int bits = 0;
	memcpy( &bits, &f, sizeof(bits) );
	PutU32( b, bits );
}

//! One strand as this test wants to reason about it.
struct TestStrand
{
	std::vector<float> pts;			//!< x y z triples
	std::vector<float> thickness;	//!< one per point
};

//! Everything the writer can be told to do, INCLUDING the malformed
//! things -- the negative fixtures are the reason the header counts and
//! the flags are separately overridable from the strand list.
struct HairFileSpec
{
	std::vector<TestStrand> strands;

	bool writeSegments;
	bool writeThickness;
	bool writeTransparency;
	bool writeColors;

	unsigned int defaultSegments;
	float        defaultThickness;

	// Malformation knobs.  -1 / 0 = "derive it honestly from `strands`".
	long long    forceStrandCount;	//!< override the header's strand count
	long long    forcePointCount;	//!< override the header's point count
	unsigned int extraFlagBits;		//!< OR'd into the flags word
	bool         clearPointsFlag;
	bool         badMagic;
	unsigned int truncateBytes;		//!< drop this many bytes off the end
	unsigned int trailingBytes;		//!< append this many junk bytes
	long long    forceSegmentOfStrand0;	//!< override strand 0's segments-array entry

	HairFileSpec() :
		writeSegments( true ), writeThickness( true ),
		writeTransparency( false ), writeColors( false ),
		defaultSegments( 0 ), defaultThickness( 0.02f ),
		forceStrandCount( -1 ), forcePointCount( -1 ), extraFlagBits( 0 ),
		clearPointsFlag( false ), badMagic( false ),
		truncateBytes( 0 ), trailingBytes( 0 ), forceSegmentOfStrand0( -1 )
	{
	}
};

std::string TempDir()
{
	const char* tmp = getenv( "TMPDIR" );
	std::string dir = tmp ? tmp : "/tmp/";
	if( !dir.empty() && dir[dir.size()-1] != '/' ) dir += "/";
	return dir;
}

//! Writes `spec` to a temp file and returns its path.
std::string MakeHairFile( const std::string& tag, const HairFileSpec& spec )
{
	unsigned int numPoints = 0;
	for( size_t i = 0; i < spec.strands.size(); ++i ) {
		numPoints += (unsigned int)( spec.strands[i].pts.size() / 3 );
	}

	const unsigned int hdrStrands = ( spec.forceStrandCount >= 0 )
		? (unsigned int)spec.forceStrandCount : (unsigned int)spec.strands.size();
	const unsigned int hdrPoints  = ( spec.forcePointCount >= 0 )
		? (unsigned int)spec.forcePointCount : numPoints;

	unsigned int flags = spec.clearPointsFlag ? 0u : ( 1u << 1 );
	if( spec.writeSegments )     flags |= ( 1u << 0 );
	if( spec.writeThickness )    flags |= ( 1u << 2 );
	if( spec.writeTransparency ) flags |= ( 1u << 3 );
	if( spec.writeColors )       flags |= ( 1u << 4 );
	flags |= spec.extraFlagBits;

	std::vector<unsigned char> b;
	if( spec.badMagic ) {
		b.push_back( 'H' ); b.push_back( 'A' ); b.push_back( 'I' ); b.push_back( 'X' );
	} else {
		b.push_back( 'H' ); b.push_back( 'A' ); b.push_back( 'I' ); b.push_back( 'R' );
	}
	PutU32( b, hdrStrands );
	PutU32( b, hdrPoints );
	PutU32( b, flags );
	PutU32( b, spec.defaultSegments );
	PutF32( b, spec.defaultThickness );
	PutF32( b, 0.0f );							// default transparency
	PutF32( b, 1.0f ); PutF32( b, 1.0f ); PutF32( b, 1.0f );	// default colour
	{
		const char* info = "RISE HairFileImportTest fixture";
		for( unsigned int i = 0; i < 88; ++i ) {
			b.push_back( (unsigned char)( i < strlen( info ) ? info[i] : 0 ) );
		}
	}

	if( spec.writeSegments ) {
		for( size_t i = 0; i < spec.strands.size(); ++i ) {
			unsigned int segs = (unsigned int)( spec.strands[i].pts.size() / 3 ) - 1u;
			if( i == 0 && spec.forceSegmentOfStrand0 >= 0 ) {
				segs = (unsigned int)spec.forceSegmentOfStrand0;
			}
			PutU16( b, segs );
		}
	}
	for( size_t i = 0; i < spec.strands.size(); ++i ) {
		for( size_t k = 0; k < spec.strands[i].pts.size(); ++k ) { PutF32( b, spec.strands[i].pts[k] ); }
	}
	if( spec.writeThickness ) {
		for( size_t i = 0; i < spec.strands.size(); ++i ) {
			for( size_t k = 0; k < spec.strands[i].thickness.size(); ++k ) { PutF32( b, spec.strands[i].thickness[k] ); }
		}
	}
	if( spec.writeTransparency ) {
		for( unsigned int i = 0; i < numPoints; ++i ) { PutF32( b, 0.0f ); }
	}
	if( spec.writeColors ) {
		for( unsigned int i = 0; i < numPoints; ++i ) { PutF32( b, 0.5f ); PutF32( b, 0.5f ); PutF32( b, 0.5f ); }
	}

	for( unsigned int i = 0; i < spec.trailingBytes; ++i ) { b.push_back( 0xAB ); }
	if( spec.truncateBytes > 0 ) {
		const size_t keep = ( spec.truncateBytes < b.size() ) ? b.size() - spec.truncateBytes : 0;
		b.resize( keep );
	}

	char pid[32];
	std::snprintf( pid, sizeof(pid), "%d", (int)::getpid() );
	const std::string path = TempDir() + "rise_hairfile_" + tag + "_" + pid + ".hair";
	std::ofstream f( path.c_str(), std::ios::binary | std::ios::trunc );
	if( !b.empty() ) { f.write( (const char*)&b[0], (std::streamsize)b.size() ); }
	f.close();
	return path;
}

//! The canonical positive fixture: five upright strands with 4, 3, 5, 2
//! and 6 points respectively -- deliberately RAGGED, because a uniform
//! strand length is exactly the shape in which an off-by-one in the
//! per-strand cursor stays invisible.
std::vector<TestStrand> CanonicalStrands()
{
	const unsigned int counts[5] = { 4, 3, 5, 2, 6 };
	std::vector<TestStrand> out;
	for( unsigned int s = 0; s < 5; ++s ) {
		TestStrand ts;
		for( unsigned int k = 0; k < counts[s]; ++k ) {
			const float t = (float)k / (float)( counts[s] - 1 );
			ts.pts.push_back( 0.25f * (float)s + 0.1f * t * t );	// x: leans with height
			ts.pts.push_back( 0.5f * t );							// y: grows up
			ts.pts.push_back( -0.125f * (float)s );					// z
			ts.thickness.push_back( 0.02f - 0.012f * t );			// 0.02 -> 0.008
		}
		out.push_back( ts );
	}
	return out;
}

bool NearF( const double a, const double b, const double tol = 1e-6 )
{
	return std::fabs( a - b ) <= tol;
}

//////////////////////////////////////////////////////////////////////
// Scene plumbing (HairGeneratorTest's pattern)
//////////////////////////////////////////////////////////////////////

std::string WriteTempScene( const std::string& tag, const std::string& body )
{
	char pid[32];
	std::snprintf( pid, sizeof(pid), "%d", (int)::getpid() );
	const std::string path = TempDir() + "rise_hairfileimp_" + tag + "_" + pid + ".RISEscene";
	std::ofstream f( path.c_str(), std::ios::binary | std::ios::trunc );
	f << body;
	f.close();
	return path;
}

bool ParseBodyInto( const std::string& tag, const std::string& body, IJobPriv& job )
{
	const std::string path = WriteTempScene( tag, "RISE ASCII SCENE 7\n" + body );
	const bool ok = job.LoadAsciiSceneViaCst( path.c_str() );
	remove( path.c_str() );
	return ok;
}

bool ParseBodyCapturing( const std::string& tag, const std::string& body, IJobPriv& job,
                         std::string& capturedOutput )
{
	char pid[32];
	std::snprintf( pid, sizeof(pid), "%d", (int)::getpid() );
	const std::string capPath = TempDir() + "rise_hairfileimp_stdout_" + tag + "_" + pid + ".txt";

	std::fflush( stdout );
	const int savedFd = RISE_TEST_DUP( RISE_TEST_FILENO( stdout ) );
	FILE* capFile = std::fopen( capPath.c_str(), "w" );
	if( capFile ) RISE_TEST_DUP2( RISE_TEST_FILENO( capFile ), RISE_TEST_FILENO( stdout ) );

	const bool ok = ParseBodyInto( tag, body, job );

	std::fflush( stdout );
	if( savedFd >= 0 ) { RISE_TEST_DUP2( savedFd, RISE_TEST_FILENO( stdout ) ); RISE_TEST_CLOSE( savedFd ); }
	if( capFile ) std::fclose( capFile );

	std::ifstream ifs( capPath.c_str() );
	if( ifs.is_open() ) { std::ostringstream oss; oss << ifs.rdbuf(); capturedOutput = oss.str(); }
	remove( capPath.c_str() );

	return ok;
}

//! Same stdout-capture idiom as `ParseBodyCapturing`, generalized to any
//! callable -- used by group 3 to pin WHICH diagnostic `LoadHairFile`
//! actually printed for each malformed fixture, the same "message-
//! substring" discipline group 6 already applies to the chunk-parser
//! path. `GlobalLog`'s default sink is a stdout stream printer (see
//! Utilities/Log/Log.cpp), so this captures exactly what an author
//! watching the console would see.
template<class F>
std::string CaptureStdout( const std::string& tag, F fn )
{
	char pid[32];
	std::snprintf( pid, sizeof(pid), "%d", (int)::getpid() );
	static int counter = 0;
	std::ostringstream nameSs;
	nameSs << TempDir() << "rise_hairfileimp_cap_" << tag << "_" << pid << "_" << ( counter++ ) << ".txt";
	const std::string capPath = nameSs.str();

	std::fflush( stdout );
	const int savedFd = RISE_TEST_DUP( RISE_TEST_FILENO( stdout ) );
	FILE* capFile = std::fopen( capPath.c_str(), "w" );
	if( capFile ) RISE_TEST_DUP2( RISE_TEST_FILENO( capFile ), RISE_TEST_FILENO( stdout ) );

	fn();

	std::fflush( stdout );
	if( savedFd >= 0 ) { RISE_TEST_DUP2( savedFd, RISE_TEST_FILENO( stdout ) ); RISE_TEST_CLOSE( savedFd ); }
	if( capFile ) std::fclose( capFile );

	std::string capturedOutput;
	std::ifstream ifs( capPath.c_str() );
	if( ifs.is_open() ) { std::ostringstream oss; oss << ifs.rdbuf(); capturedOutput = oss.str(); }
	remove( capPath.c_str() );

	return capturedOutput;
}

} // namespace

// ============================================================
//  1. Round trip, all arrays present
// ============================================================

static void RunRoundTrip()
{
	std::cout << "=== 1. Round trip (segments + points + thickness) ===" << std::endl;

	HairFileSpec spec;
	spec.strands = CanonicalStrands();
	const std::string path = MakeHairFile( "roundtrip", spec );

	HairFileData d;
	const bool ok = LoadHairFile( path.c_str(), d, "rt" );
	Check( ok, "a well-formed .hair file loads" );
	if( !ok ) { remove( path.c_str() ); return; }

	Check( d.numStrands == 5,  "the strand count comes back" );
	Check( d.numPoints  == 20, "the point count comes back (4+3+5+2+6)" );
	Check( d.hasSegmentsArray && d.hasThicknessArray,
	       "the two present optional arrays are reported present" );
	Check( !d.hasTransparencyArray && !d.hasColorArray,
	       "the two absent optional arrays are reported absent" );
	Check( d.info == "RISE HairFileImportTest fixture",
	       "the header's 88-byte info block is read and NUL-trimmed" );
	Check( NearF( d.defaultThickness, 0.02 ), "the header's default thickness is read" );

	const unsigned int expected[5] = { 4, 3, 5, 2, 6 };
	bool countsOk = ( d.pointsPerStrand.size() == 5 );
	for( unsigned int s = 0; s < 5 && countsOk; ++s ) {
		countsOk = ( d.pointsPerStrand[s] == expected[s] );
	}
	Check( countsOk, "MONEY: the RAGGED per-strand point counts come back exactly (segments + 1 each)" );

	// Every control point and every thickness, bit for bit against what
	// the independent writer packed.
	size_t cursor = 0;
	unsigned int badPt = 0, badTh = 0;
	for( unsigned int s = 0; s < spec.strands.size() && countsOk; ++s ) {
		const TestStrand& ts = spec.strands[s];
		for( size_t k = 0; k < ts.pts.size(); ++k ) {
			if( d.points[ cursor * 3 + k ] != ts.pts[k] ) ++badPt;
		}
		for( size_t k = 0; k < ts.thickness.size(); ++k ) {
			if( d.thickness[ cursor + k ] != ts.thickness[k] ) ++badTh;
		}
		cursor += ts.thickness.size();
	}
	Check( badPt == 0, "MONEY: every control point round-trips BIT-EXACTLY through the little-endian decode" );
	Check( badTh == 0, "every per-point thickness round-trips bit-exactly" );

	remove( path.c_str() );
}

// ============================================================
//  2. The header-default paths
// ============================================================

static void RunHeaderDefaults()
{
	std::cout << "=== 2. Header-default paths (absent optional arrays) ===" << std::endl;

	// -- no segments array: every strand carries the header default.
	//    The strands must therefore be UNIFORM for the file to be
	//    self-consistent, which is the format's own constraint.
	{
		HairFileSpec spec;
		spec.writeSegments   = false;
		spec.defaultSegments = 3;			// 4 points per strand
		for( unsigned int s = 0; s < 4; ++s ) {
			TestStrand ts;
			for( unsigned int k = 0; k < 4; ++k ) {
				ts.pts.push_back( 0.1f * (float)s );
				ts.pts.push_back( 0.2f * (float)k );
				ts.pts.push_back( 0.0f );
				ts.thickness.push_back( 0.01f );
			}
			spec.strands.push_back( ts );
		}
		const std::string path = MakeHairFile( "nosegs", spec );

		HairFileData d;
		const bool ok = LoadHairFile( path.c_str(), d, "nosegs" );
		Check( ok, "a file with NO segments array loads on the header default" );
		if( ok ) {
			Check( !d.hasSegmentsArray, "the absent segments array is reported absent" );
			bool all4 = ( d.pointsPerStrand.size() == 4 );
			for( size_t i = 0; i < d.pointsPerStrand.size() && all4; ++i ) {
				all4 = ( d.pointsPerStrand[i] == 4 );
			}
			Check( all4, "the header's default segment count expands to (default + 1) points on every strand" );
		}
		remove( path.c_str() );
	}

	// -- no thickness array: the header default is the only width.
	{
		HairFileSpec spec;
		spec.strands          = CanonicalStrands();
		spec.writeThickness   = false;
		spec.defaultThickness = 0.007f;
		const std::string path = MakeHairFile( "nothick", spec );

		HairFileData d;
		const bool ok = LoadHairFile( path.c_str(), d, "nothick" );
		Check( ok, "a file with NO thickness array loads" );
		if( ok ) {
			Check( !d.hasThicknessArray && d.thickness.empty(),
			       "the absent thickness array leaves the per-point vector empty" );
			Check( NearF( d.defaultThickness, 0.007 ), "the header default carries the width instead" );

			std::vector<HairGeometry::StrandDesc> strands;
			const bool built = BuildStrandsFromHairFile( d, 1.0, 1.0, strands, "nothick" );
			Check( built && strands.size() == 5, "the strands build off the header default" );
			if( built && !strands.empty() ) {
				Check( NearF( strands[0].rootWidth, 0.007 ) && NearF( strands[0].tipWidth, 0.007 ),
				       "both ends take the header's default thickness when there is no array" );
			}
		}
		remove( path.c_str() );
	}

	// -- both absent, and per-point colours/transparency present: the
	//    two discarded arrays must not disturb the two honoured ones.
	{
		HairFileSpec spec;
		spec.writeSegments      = false;
		spec.writeThickness     = false;
		spec.writeTransparency  = true;
		spec.writeColors        = true;
		spec.defaultSegments    = 1;		// 2 points per strand
		spec.defaultThickness   = 0.05f;
		for( unsigned int s = 0; s < 3; ++s ) {
			TestStrand ts;
			ts.pts.push_back( (float)s ); ts.pts.push_back( 0.0f ); ts.pts.push_back( 0.0f );
			ts.pts.push_back( (float)s ); ts.pts.push_back( 1.0f ); ts.pts.push_back( 0.0f );
			spec.strands.push_back( ts );
		}
		const std::string path = MakeHairFile( "discarded", spec );

		HairFileData d;
		const bool ok = LoadHairFile( path.c_str(), d, "discarded" );
		Check( ok, "a file carrying transparency + colours loads (they are read for their LENGTH and dropped)" );
		if( ok ) {
			Check( d.hasTransparencyArray && d.hasColorArray,
			       "the two discarded arrays are still REPORTED present (so the warning can name them)" );
			Check( d.numPoints == 6 && d.points.size() == 18, "the points array is unaffected by them" );
			Check( d.points[3] == 0.0f && d.points[4] == 1.0f,
			       "MONEY: the points read back correct with two trailing arrays present -- i.e. the "
			       "byte-length arithmetic did not shift the read" );
		}
		remove( path.c_str() );
	}
}

// ============================================================
//  3. Refusals
// ============================================================

static void RunRefusals()
{
	std::cout << "=== 3. Refusals ===" << std::endl;

	// Each case names WHICH diagnostic it expects, and the loop below
	// asserts the substring is actually present in what `LoadHairFile`
	// printed -- not just that it refused SOMETHING.  Every substring
	// below is unique enough among these fifteen cases to pin the
	// intended branch (group-6's message-substring discipline, applied
	// here to the loader's own refusals rather than the chunk parser's).
	struct RefusalCase { std::string tag; HairFileSpec spec; std::string mustSay; };
	std::vector<RefusalCase> cases;

	{	// bad magic
		RefusalCase c; c.tag = "bad_magic"; c.spec.strands = CanonicalStrands(); c.spec.badMagic = true;
		c.mustSay = "bad magic";
		cases.push_back( c );
	}
	{	// a 100-byte stub: shorter than the 128-byte header, so the
		//   header read itself must be refused before it happens.  The
		//   canonical fixture is 458 bytes (128 header + 10 segments +
		//   240 points + 80 thickness).
		RefusalCase c; c.tag = "header_stub_100_bytes"; c.spec.strands = CanonicalStrands(); c.spec.truncateBytes = 358;
		c.mustSay = "shorter than the format's 128-byte header";
		cases.push_back( c );
	}
	{	// a completely empty file
		RefusalCase c; c.tag = "empty_file"; c.spec.strands = CanonicalStrands(); c.spec.truncateBytes = 100000;
		c.mustSay = "shorter than the format's 128-byte header";
		cases.push_back( c );
	}
	{	// arrays truncated: the header describes more than the file has
		RefusalCase c; c.tag = "truncated_arrays"; c.spec.strands = CanonicalStrands(); c.spec.truncateBytes = 40;
		c.mustSay = "TRUNCATED";
		cases.push_back( c );
	}
	{	// points flag clear
		RefusalCase c; c.tag = "no_points_flag"; c.spec.strands = CanonicalStrands(); c.spec.clearPointsFlag = true;
		c.mustSay = "declares no POINTS array";
		cases.push_back( c );
	}
	{	// a reserved flag bit -- layout after it is unknowable
		RefusalCase c; c.tag = "reserved_flag"; c.spec.strands = CanonicalStrands(); c.spec.extraFlagBits = ( 1u << 7 );
		c.mustSay = "reserved flag bits";
		cases.push_back( c );
	}
	{	// zero strands
		RefusalCase c; c.tag = "zero_strands"; c.spec.strands = CanonicalStrands(); c.spec.forceStrandCount = 0;
		c.mustSay = "must be non-zero";
		cases.push_back( c );
	}
	{	// zero points
		RefusalCase c; c.tag = "zero_points"; c.spec.strands = CanonicalStrands(); c.spec.forcePointCount = 0;
		c.mustSay = "must be non-zero";
		cases.push_back( c );
	}
	{	// strand count over the cap -- refused on the HEADER, before any
		//   allocation, so the fixture stays 392 bytes
		RefusalCase c; c.tag = "over_strand_cap"; c.spec.strands = CanonicalStrands();
		c.spec.forceStrandCount = (long long)kMaxHairFileStrands + 1;
		c.mustSay = "strands exceeds the";
		cases.push_back( c );
	}
	{	// point count over the cap, likewise
		RefusalCase c; c.tag = "over_point_cap"; c.spec.strands = CanonicalStrands();
		c.spec.forcePointCount = (long long)kMaxHairFilePoints + 1;
		c.mustSay = "points exceeds the";
		cases.push_back( c );
	}
	{	// segments array that does not sum to the declared point count
		RefusalCase c; c.tag = "segment_sum_mismatch"; c.spec.strands = CanonicalStrands(); c.spec.forceSegmentOfStrand0 = 9;
		c.mustSay = "the segments array accounts for";
		cases.push_back( c );
	}
	{	// no segments array and no usable default
		RefusalCase c; c.tag = "no_segments_no_default"; c.spec.strands = CanonicalStrands();
		c.spec.writeSegments = false; c.spec.defaultSegments = 0;
		c.mustSay = "default segment count is 0";
		cases.push_back( c );
	}
	{	// no segments array, default that does not divide the point count
		RefusalCase c; c.tag = "default_segments_mismatch"; c.spec.strands = CanonicalStrands();
		c.spec.writeSegments = false; c.spec.defaultSegments = 7;
		c.mustSay = "no segments array, so every strand carries the header's default";
		cases.push_back( c );
	}
	{	// non-finite header default thickness (poisons every strand when
		//   there is no thickness array)
		RefusalCase c; c.tag = "nan_default_thickness"; c.spec.strands = CanonicalStrands();
		c.spec.writeThickness = false;
		c.spec.defaultThickness = std::numeric_limits<float>::quiet_NaN();
		c.mustSay = "default thickness is not finite";
		cases.push_back( c );
	}
	// NOTE: a strand declaring 0 segments (a lone point) used to be a
	// refusal case here.  It is no longer one -- see group 4's
	// "zero-segment strand" fixture below, and the header/loader
	// comments: a segments-array 0-entry is now a per-strand DROP
	// (BuildStrandsFromHairFile), not a whole-file refusal.

	for( size_t i = 0; i < cases.size(); ++i ) {
		const std::string path = MakeHairFile( cases[i].tag, cases[i].spec );
		HairFileData d;
		bool ok = true;
		const std::string captured = CaptureStdout( cases[i].tag, [&]() {
			ok = LoadHairFile( path.c_str(), d, cases[i].tag.c_str() );
		} );
		Check( !ok, std::string( "REFUSED: " ) + cases[i].tag );
		Check( captured.find( cases[i].mustSay ) != std::string::npos,
		       "  ...and the diagnostic for " + cases[i].tag + " names `" + cases[i].mustSay + "`" );
		remove( path.c_str() );
	}

	// A file that does not exist at all.
	{
		HairFileData d;
		Check( !LoadHairFile( "/definitely/not/a/real/path/nope.hair", d, "missing" ),
		       "REFUSED: a file that does not exist" );
		Check( !LoadHairFile( "", d, "empty" ), "REFUSED: an empty file name" );
		Check( !LoadHairFile( 0, d, "null" ),   "REFUSED: a null file name" );
	}

	// -- the one malformation that is NOT fatal: surplus bytes.
	{
		HairFileSpec s; s.strands = CanonicalStrands(); s.trailingBytes = 64;
		const std::string path = MakeHairFile( "trailing", s );
		HairFileData d;
		const bool ok = LoadHairFile( path.c_str(), d, "trailing" );
		Check( ok, "ACCEPTED (with a warning): trailing bytes after the arrays the header describes" );
		Check( ok && d.numStrands == 5 && d.numPoints == 20,
		       "the surplus does not disturb what was read" );
		remove( path.c_str() );
	}
}

// ============================================================
//  4. Strand construction
// ============================================================

static void RunStrandConstruction()
{
	std::cout << "=== 4. Strand construction ===" << std::endl;

	// -- widths come from the FIRST and LAST thickness; the interior is
	//    dropped.  Strand 0's thickness runs 0.02 -> 0.008 across four
	//    points, so a bulge in the middle must not change the answer.
	{
		HairFileSpec spec;
		spec.strands = CanonicalStrands();
		spec.strands[0].thickness[1] = 5.0f;		// an absurd mid-strand bulge
		const std::string path = MakeHairFile( "endpoints", spec );

		HairFileData d;
		std::vector<HairGeometry::StrandDesc> strands;
		const bool ok = LoadHairFile( path.c_str(), d, "endpoints" ) &&
		                BuildStrandsFromHairFile( d, 1.0, 1.0, strands, "endpoints" );
		Check( ok && strands.size() == 5, "all five strands convert" );
		if( ok && strands.size() == 5 ) {
			Check( NearF( strands[0].rootWidth, 0.02 ) && NearF( strands[0].tipWidth, 0.008 ),
			       "MONEY: root/tip width come from the strand's FIRST and LAST thickness" );
			Check( strands[0].rootUV.x == 0.0 && strands[0].rootUV.y == 0.0,
			       ".hair has no root UVs, so every imported strand reports (0,0)" );
			Check( strands[0].controlPoints.size() == 4 && strands[4].controlPoints.size() == 6,
			       "the ragged control-point counts survive the conversion" );
			// The per-strand cursor: strand 3 has 2 points and starts at
			// point 12 of the concatenated array.
			Check( strands[3].controlPoints.size() == 2 &&
			       NearF( strands[3].controlPoints[0].x, 0.75, 1e-5 ) &&
			       NearF( strands[3].controlPoints[1].y, 0.5,  1e-5 ),
			       "MONEY: the per-strand cursor lands on the right points in a ragged file" );
		}
		remove( path.c_str() );
	}

	// -- the two width parameters MULTIPLY.
	{
		HairFileSpec spec;
		spec.strands = CanonicalStrands();
		const std::string path = MakeHairFile( "scale", spec );

		HairFileData d;
		std::vector<HairGeometry::StrandDesc> strands;
		const bool ok = LoadHairFile( path.c_str(), d, "scale" ) &&
		                BuildStrandsFromHairFile( d, 2.0, 0.5, strands, "scale" );
		Check( ok && !strands.empty(), "the scaled conversion succeeds" );
		if( ok && !strands.empty() ) {
			Check( NearF( strands[0].rootWidth, 0.04 ) && NearF( strands[0].tipWidth, 0.004 ),
			       "MONEY: width_root / width_tip MULTIPLY the file's thickness (x2 root, x0.5 tip)" );
		}

		std::vector<HairGeometry::StrandDesc> junk;
		Check( !BuildStrandsFromHairFile( d,  0.0, 1.0, junk, "scale" ), "a zero width multiplier is refused" );
		Check( !BuildStrandsFromHairFile( d, -1.0, 1.0, junk, "scale" ), "a negative width multiplier is refused" );
		Check( !BuildStrandsFromHairFile( d, 1.0,
		           std::numeric_limits<double>::quiet_NaN(), junk, "scale" ),
		       "a NaN width multiplier is refused" );
		remove( path.c_str() );
	}

	// -- one poisoned strand is dropped; its neighbours survive.
	{
		HairFileSpec spec;
		spec.strands = CanonicalStrands();
		spec.strands[1].pts[4] = std::numeric_limits<float>::quiet_NaN();	// strand 1, point 1, y
		spec.strands[2].thickness[0] = 0.0f;								// strand 2, unusable root width
		const std::string path = MakeHairFile( "poisoned", spec );

		HairFileData d;
		std::vector<HairGeometry::StrandDesc> strands;
		const bool ok = LoadHairFile( path.c_str(), d, "poisoned" ) &&
		                BuildStrandsFromHairFile( d, 1.0, 1.0, strands, "poisoned" );
		Check( ok, "a file with two bad strands still converts (the defect is per-strand)" );
		Check( ok && strands.size() == 3,
		       "MONEY: the NaN strand and the zero-width strand are dropped; the other three survive" );
		if( ok && strands.size() == 3 ) {
			// The survivors are strands 0, 3 and 4 -- check by their
			// distinctive control-point counts (4, 2, 6).
			Check( strands[0].controlPoints.size() == 4 &&
			       strands[1].controlPoints.size() == 2 &&
			       strands[2].controlPoints.size() == 6,
			       "the survivors are exactly strands 0, 3 and 4 (their point counts identify them)" );
		}
		remove( path.c_str() );
	}

	// -- a strand declaring 0 segments (a lone point) is a per-strand
	//    DROP now, not a whole-file refusal (group 3's "zero_segment_-
	//    strand" case used to live there; see the header/loader comments
	//    for why it moved).  A single-point TestStrand naturally writes 0
	//    segments (the writer derives segs = points - 1), so no
	//    `forceSegmentOfStrand0` override is needed -- the fixture is
	//    self-consistent by construction, exactly the kind of file a
	//    real degenerate groom export would produce.
	//
	//    The lone strand is inserted at index 2 (NOT appended last): a
	//    missing point-cursor advance after a 0-segment strand can only
	//    corrupt strands read AFTER it, so putting it last left nothing
	//    downstream to catch exactly that bug class.  Placing it in the
	//    middle makes the three surviving strands read after it into
	//    witnesses -- their point counts and control-point counts are
	//    checked below and would come back wrong if the loader/builder
	//    failed to advance past the degenerate strand correctly.
	{
		HairFileSpec spec;
		spec.strands = CanonicalStrands();
		TestStrand lone;
		lone.pts.push_back( 9.0f ); lone.pts.push_back( 9.0f ); lone.pts.push_back( 9.0f );
		lone.thickness.push_back( 0.01f );
		spec.strands.insert( spec.strands.begin() + 2, lone );	// strand 2: one point, 0 segments
		const std::string path = MakeHairFile( "zerosegdrop", spec );

		HairFileData d;
		bool loadOk = false;
		const std::string loadCaptured = CaptureStdout( "zerosegdrop_load", [&]() {
			loadOk = LoadHairFile( path.c_str(), d, "zerosegdrop" );
		} );
		Check( loadOk, "MONEY: a file with one 0-segment strand among good ones still LOADS -- a per-strand "
		               "defect, not a whole-file refusal" );
		if( loadOk ) {
			Check( d.numStrands == 6 && d.pointsPerStrand.size() == 6,
			       "the degenerate strand is still counted and recorded" );
			Check( d.pointsPerStrand[2] == 1,
			       "the degenerate strand's recorded point count is exactly 1 (segments+1 with 0 segments)" );
			Check( d.pointsPerStrand[0] == 4 && d.pointsPerStrand[1] == 3 &&
			       d.pointsPerStrand[3] == 5 && d.pointsPerStrand[4] == 2 &&
			       d.pointsPerStrand[5] == 6,
			       "MONEY: the three strands read AFTER the degenerate one (indices 3, 4, 5) still report "
			       "their correct point counts -- catches a missing point-cursor advance for a 0-segment "
			       "strand, which a fixture with the degenerate strand last couldn't detect" );
			Check( loadCaptured.find( "0 segments" ) != std::string::npos,
			       "LoadHairFile warns about the 0-segment strand (counted, not silent)" );

			std::vector<HairGeometry::StrandDesc> strands;
			bool buildOk = false;
			const std::string buildCaptured = CaptureStdout( "zerosegdrop_build", [&]() {
				buildOk = BuildStrandsFromHairFile( d, 1.0, 1.0, strands, "zerosegdrop" );
			} );
			Check( buildOk && strands.size() == 5,
			       "MONEY: BuildStrandsFromHairFile drops the 0-segment strand and counts it; the other five "
			       "convert" );
			if( buildOk && strands.size() == 5 ) {
				Check( strands[0].controlPoints.size() == 4 && strands[1].controlPoints.size() == 3 &&
				       strands[2].controlPoints.size() == 5 && strands[3].controlPoints.size() == 2 &&
				       strands[4].controlPoints.size() == 6,
				       "the five survivors keep their original relative order and control-point counts "
				       "(4, 3, 5, 2, 6) once the degenerate strand at index 2 is dropped" );
			}
			Check( buildCaptured.find( "fewer than 2 points" ) != std::string::npos,
			       "the drop is named in BuildStrandsFromHairFile's summary warning (\"counted\", not silent)" );
		}
		remove( path.c_str() );
	}

	// -- every strand bad => the whole conversion fails, because an
	//    empty groom is a failure the author has to see.
	{
		HairFileSpec spec;
		spec.strands = CanonicalStrands();
		for( size_t s = 0; s < spec.strands.size(); ++s ) {
			spec.strands[s].pts[0] = std::numeric_limits<float>::quiet_NaN();
		}
		const std::string path = MakeHairFile( "allbad", spec );

		HairFileData d;
		std::vector<HairGeometry::StrandDesc> strands;
		const bool loaded = LoadHairFile( path.c_str(), d, "allbad" );
		Check( loaded, "a file whose every strand has a NaN still PARSES (the format is intact)" );
		Check( loaded && !BuildStrandsFromHairFile( d, 1.0, 1.0, strands, "allbad" ),
		       "...but converting it fails rather than yielding an empty groom" );
		remove( path.c_str() );
	}

	// -- a file with no width at all: the documented fallback to RISE's
	//    human-hair defaults, which the multipliers then scale.
	{
		HairFileSpec spec;
		spec.strands          = CanonicalStrands();
		spec.writeThickness   = false;
		spec.defaultThickness = 0.0f;
		const std::string path = MakeHairFile( "nowidth", spec );

		HairFileData d;
		std::vector<HairGeometry::StrandDesc> strands;
		const bool ok = LoadHairFile( path.c_str(), d, "nowidth" ) &&
		                BuildStrandsFromHairFile( d, 10.0, 10.0, strands, "nowidth" );
		Check( ok && !strands.empty(), "a file with no usable thickness still converts (with a warning)" );
		if( ok && !strands.empty() ) {
			Check( NearF( strands[0].rootWidth, 0.001, 1e-9 ) && NearF( strands[0].tipWidth, 0.0003, 1e-9 ),
			       "MONEY: the human-hair fallback (0.0001 / 0.00003) is what the multipliers then scale" );
		}
		remove( path.c_str() );
	}
}

// ============================================================
//  5. The geometry
// ============================================================

static void RunGeometry()
{
	std::cout << "=== 5. The geometry ===" << std::endl;

	HairFileSpec spec;
	spec.strands = CanonicalStrands();
	const std::string path = MakeHairFile( "geom", spec );

	HairFileGroomDescriptor desc;
	desc.file           = path.c_str();
	desc.widthRootScale = 1.0;
	desc.widthTipScale  = 1.0;

	IGeometry* raw = 0;
	const bool built = RISE_API_CreateHairGeometryFromFile( &raw, desc, "geom_groom" );
	Check( built && raw, "the factory builds a geometry from a .hair file" );
	if( !built || !raw ) { remove( path.c_str() ); return; }

	Owned<HairGeometry> g( dynamic_cast<HairGeometry*>( raw ) );
	Check( g.get() != 0, "the geometry really is a HairGeometry" );
	if( !g ) { remove( path.c_str() ); return; }

	Check( g->IsRealized(),
	       "an IMPORTED groom is in explicit-strand mode -- already built, Realize() is a no-op" );
	Check( g->numStrands() == 5, "all five strands reached the geometry" );
	Check( g->numRejectedStrands() == 0, "none were rejected at the geometry layer" );
	Check( g->numControlPoints() == 20, "all twenty control points reached the geometry" );

	// Control points, against the arrays this test wrote.  HairGeometry
	// stores FLOAT, and the writer wrote float, so the comparison is
	// exact up to the float->double widening on both sides.
	unsigned int bad = 0;
	for( unsigned int s = 0; s < 5 && s < g->numStrands(); ++s ) {
		const TestStrand& ts = spec.strands[s];
		if( g->numControlPointsOfStrand( s ) != ts.pts.size() / 3 ) { ++bad; continue; }
		for( unsigned int k = 0; k < g->numControlPointsOfStrand( s ); ++k ) {
			const Point3 p = g->ControlPoint( s, k );
			if( p.x != (double)ts.pts[k*3+0] ||
			    p.y != (double)ts.pts[k*3+1] ||
			    p.z != (double)ts.pts[k*3+2] ) { ++bad; }
		}
	}
	Check( bad == 0, "MONEY: every imported control point reaches HairGeometry unchanged" );

	Check( NearF( g->StrandWidthAt( 0, 0.0 ), 0.02,  1e-7 ) &&
	       NearF( g->StrandWidthAt( 0, 1.0 ), 0.008, 1e-7 ),
	       "the file's root and tip thickness reach the geometry as the strand's widths" );
	Check( g->StrandRootUV( 0 ).x == 0.0 && g->StrandRootUV( 0 ).y == 0.0,
	       "the synthesized (0,0) root UV reaches the geometry" );

	// A groom is never an area light and never tessellates, whatever
	// its source.
	Check( !g->CanBeAreaLight(), "an imported groom refuses to serve as an area light" );
	Check( !g->CanTessellate(),  "an imported groom refuses to tessellate" );

	// -- the factory refuses what the loader refuses.
	{
		HairFileSpec bs; bs.strands = CanonicalStrands(); bs.badMagic = true;
		const std::string bpath = MakeHairFile( "geom_bad", bs );
		HairFileGroomDescriptor bd;
		bd.file = bpath.c_str();
		IGeometry* braw = 0;
		Check( !RISE_API_CreateHairGeometryFromFile( &braw, bd, "geom_bad" ) && !braw,
		       "the factory refuses a bad file and hands back no geometry" );
		remove( bpath.c_str() );
	}
	{
		HairFileGroomDescriptor bd;
		bd.file           = path.c_str();
		bd.widthRootScale = 0.0;
		IGeometry* braw = 0;
		Check( !RISE_API_CreateHairGeometryFromFile( &braw, bd, "geom_zero_w" ) && !braw,
		       "the factory refuses a zero width multiplier" );
	}

	remove( path.c_str() );
}

// ============================================================
//  6. The chunk
// ============================================================

static void RunChunk()
{
	std::cout << "=== 6. The hair_geometry `file` mode chunk ===" << std::endl;

	// -- DRIFT GUARD.  ChunkParserRegistry.cpp's `HairGeometryAsciiChunk-
	//    Parser::GrowOnlyParameters()` is the list of parameters `file`
	//    mode REFUSES; it is a private static list, not something this
	//    test can call directly, so this walks the REAL registered
	//    descriptor instead and asserts every declared parameter name is
	//    either one of the four file-mode-accepted names or on a mirror
	//    of that grow-only list kept HERE.  If someone adds a new
	//    `hair_geometry` parameter and forgets to add it to
	//    GrowOnlyParameters() in the real parser, this still passes (the
	//    new name would silently fall through file mode's refusal loop);
	//    if they add it to the test's mirror but not the real list, or
	//    change one without the other, THIS assertion is what forces the
	//    developer to update both -- it fails, naming the offending
	//    parameter, if the live descriptor and the mirror below ever
	//    disagree on the FULL set (declared-but-not-in-either-list is the
	//    case that actually protects against; a genuine list disagreement
	//    would need `HairGeometryAsciiChunkParser::GrowOnlyParameters()`
	//    read back too, which this test cannot do).
	{
		static const char* const kGrowOnlyMirror[] = {
			"base_geometry", "count", "length", "segments", "seed", "base_detail",
			"density", "length_painter", "comb", "guides",
			"gravity", "frizz", "clump", "clump_size", "curl_radius", "curl_step"
		};
		static const char* const kFileModeAccepted[] = { "name", "file", "width_root", "width_tip" };

		const ChunkDescriptor* d = DescriptorForKeyword( String( "hair_geometry" ) );
		Check( d != nullptr, "the hair_geometry descriptor is registered" );
		if( d ) {
			for( size_t i = 0; i < d->parameters.size(); ++i ) {
				const std::string pname = d->parameters[i].name;
				bool known = false;
				for( size_t g = 0; g < sizeof( kGrowOnlyMirror ) / sizeof( kGrowOnlyMirror[0] ) && !known; ++g ) {
					if( pname == kGrowOnlyMirror[g] ) known = true;
				}
				for( size_t g = 0; g < sizeof( kFileModeAccepted ) / sizeof( kFileModeAccepted[0] ) && !known; ++g ) {
					if( pname == kFileModeAccepted[g] ) known = true;
				}
				Check( known, "DRIFT GUARD: hair_geometry.`" + pname + "` is declared on the descriptor but is "
				       "neither in this test's grow-only mirror nor in the four file-mode-accepted names -- "
				       "classify it in both ChunkParserRegistry.cpp's GrowOnlyParameters() and here" );
			}
		}
	}

	HairFileSpec spec;
	spec.strands = CanonicalStrands();
	const std::string path = MakeHairFile( "chunk", spec );

	// -- the happy path, end to end through the scene language.
	{
		IJobPriv* job = 0;
		if( !RISE_CreateJobPriv( &job ) || !job ) { Check( false, "job created (file mode)" ); remove( path.c_str() ); return; }
		const std::string body =
			"hair_geometry\n{\n\tname\tcc_import\n\tfile\t" + path + "\n}\n";
		const bool ok = ParseBodyInto( "filemode", body, *job );
		Check( ok, "MONEY: a `hair_geometry { file ... }` chunk parses" );
		IGeometry* geom = job->GetGeometries() ? job->GetGeometries()->GetItem( "cc_import" ) : 0;
		Check( geom != 0, "the chunk registers a geometry under its own name" );
		if( geom ) {
			HairGeometry* hg = dynamic_cast<HairGeometry*>( geom );
			Check( hg != 0, "the registered geometry is a HairGeometry" );
			if( hg ) {
				Check( hg->IsRealized(), "an imported groom is built at PARSE time, not deferred" );
				Check( hg->numStrands() == 5, "the file's five strands are in the groom" );
			}
		}
		safe_release( job );
	}

	// -- the width multipliers reach the loader through the chunk.
	{
		IJobPriv* job = 0;
		if( RISE_CreateJobPriv( &job ) && job ) {
			const std::string body =
				"hair_geometry\n{\n\tname\tcc_import\n\tfile\t" + path +
				"\n\twidth_root\t3.0\n\twidth_tip\t3.0\n}\n";
			const bool ok = ParseBodyInto( "filewidth", body, *job );
			Check( ok, "the chunk accepts width_root / width_tip in file mode" );
			IGeometry* geom = job->GetGeometries() ? job->GetGeometries()->GetItem( "cc_import" ) : 0;
			HairGeometry* hg = dynamic_cast<HairGeometry*>( geom );
			Check( hg && NearF( hg->StrandWidthAt( 0, 0.0 ), 0.06, 1e-6 ),
			       "MONEY: `width_root 3.0` reaches the loader as a MULTIPLIER (0.02 x 3)" );
			safe_release( job );
		}
	}

	// -- negatives.  Each must be refused, with a diagnostic naming the
	//    offending parameter.
	struct Neg { std::string tag; std::string body; std::string mustSay; };
	std::vector<Neg> negs;
	{
		Neg n; n.tag = "file_and_base"; n.mustSay = "mutually exclusive";
		n.body = "sphere_geometry\n{\n\tname\tcc_base\n\tradius\t1.0\n}\n"
		         "hair_geometry\n{\n\tname\tg\n\tfile\t" + path +
		         "\n\tbase_geometry\tcc_base\n\tcount\t10\n\tlength\t0.1\n}\n";
		negs.push_back( n );
	}
	{
		Neg n; n.tag = "file_and_guides"; n.mustSay = "guides";
		n.body = "hair_guides\n{\n\tname\tcc_guides\n\tguide\t0 0 0 0 1 0\n}\n"
		         "hair_geometry\n{\n\tname\tg\n\tfile\t" + path + "\n\tguides\tcc_guides\n}\n";
		negs.push_back( n );
	}
	{
		Neg n; n.tag = "file_and_count"; n.mustSay = "count";
		n.body = "hair_geometry\n{\n\tname\tg\n\tfile\t" + path + "\n\tcount\t100\n}\n";
		negs.push_back( n );
	}
	{
		Neg n; n.tag = "file_and_comb"; n.mustSay = "comb";
		n.body = "uniformcolor_painter\n{\n\tname\tcc_comb\n\tcolor\t0.5 0.5 0.5\n}\n"
		         "hair_geometry\n{\n\tname\tg\n\tfile\t" + path + "\n\tcomb\tcc_comb\n}\n";
		negs.push_back( n );
	}
	{
		Neg n; n.tag = "file_and_frizz"; n.mustSay = "frizz";
		n.body = "hair_geometry\n{\n\tname\tg\n\tfile\t" + path + "\n\tfrizz\t0.2\n}\n";
		negs.push_back( n );
	}
	{
		Neg n; n.tag = "no_source"; n.mustSay = "base_geometry";
		n.body = "hair_geometry\n{\n\tname\tg\n\twidth_root\t1.0\n}\n";
		negs.push_back( n );
	}
	{
		Neg n; n.tag = "missing_file"; n.mustSay = "cannot open the file";
		n.body = "hair_geometry\n{\n\tname\tg\n\tfile\t/no/such/groom_xyzzy.hair\n}\n";
		negs.push_back( n );
	}
	{
		Neg n; n.tag = "zero_width"; n.mustSay = "width";
		n.body = "hair_geometry\n{\n\tname\tg\n\tfile\t" + path + "\n\twidth_root\t0\n}\n";
		negs.push_back( n );
	}

	for( size_t i = 0; i < negs.size(); ++i ) {
		IJobPriv* job = 0;
		if( !RISE_CreateJobPriv( &job ) || !job ) { Check( false, "job created (" + negs[i].tag + ")" ); continue; }
		std::string captured;
		const bool ok = ParseBodyCapturing( negs[i].tag, negs[i].body, *job, captured );
		Check( !ok, "REFUSED: " + negs[i].tag );
		Check( captured.find( negs[i].mustSay ) != std::string::npos,
		       "  ...and the diagnostic for " + negs[i].tag + " names `" + negs[i].mustSay + "`" );
		IGeometry* geom = job->GetGeometries() ? job->GetGeometries()->GetItem( "g" ) : 0;
		Check( geom == 0, "  ...and no geometry was registered for " + negs[i].tag );
		safe_release( job );
	}

	remove( path.c_str() );
}

// ============================================================
//  7. The committed corpus asset
// ============================================================

static void RunCorpusAsset()
{
	std::cout << "=== 7. The committed ChunkCoverage asset ===" << std::endl;

	// Relative to the repo root, which is where the suite runs -- the
	// same path the scene file names.  The media-path locator resolves
	// it against $RISE_MEDIA_PATH otherwise.
	const char* kAsset = "scenes/Tests/ChunkCoverage/assets/tiny.hair";

	HairFileData d;
	const bool ok = LoadHairFile( kAsset, d, "corpus" );
	Check( ok, "the committed tiny.hair loads (guards cc_hair_file_geometry.RISEscene against asset rot)" );
	if( !ok ) return;

	Check( d.numStrands == 4 && d.numPoints == 16,
	       "tiny.hair is the 4-strand / 16-point groom its generator documents" );
	Check( d.hasSegmentsArray && d.hasThicknessArray,
	       "tiny.hair exercises the optional-array-PRESENT path (which the header-default fixtures do not)" );

	std::vector<HairGeometry::StrandDesc> strands;
	Check( BuildStrandsFromHairFile( d, 1.0, 1.0, strands, "corpus" ) && strands.size() == 4,
	       "every strand of tiny.hair converts" );
	if( strands.size() == 4 ) {
		Check( NearF( strands[0].rootWidth, 0.02, 1e-7 ) && NearF( strands[0].tipWidth, 0.008, 1e-7 ),
		       "tiny.hair's documented 0.02 -> 0.008 taper is what comes out" );
	}
}

int main()
{
	std::cout << "HairFileImportTest -- Cem Yuksel .hair import (Phase 2 slice P2-B)" << std::endl;
	std::cout << "==================================================================" << std::endl;

	RunRoundTrip();
	RunHeaderDefaults();
	RunRefusals();
	RunStrandConstruction();
	RunGeometry();
	RunChunk();
	RunCorpusAsset();

	std::cout << std::endl;
	std::cout << "Checks: " << g_checks << ", failures: " << g_failures << std::endl;
	if( g_failures == 0 ) {
		std::cout << "ALL TESTS PASSED" << std::endl;
		return 0;
	}
	std::cout << "TESTS FAILED" << std::endl;
	return 1;
}
