// PLYLoaderExtraPropertiesTest.cpp
//
// Regression test for the schema-driven PLY parser.  Before the fix,
// TriangleMeshLoaderPLY ignored the 'property' lines in the header and
// hardcoded 3 floats per vertex / 1 byte + N uints per face.  Any PLY
// with extra declared properties (normals, colors, anything) silently
// corrupted the read.  This test writes synthetic PLYs with extra
// vertex properties — declared in the header — and verifies the
// loader still extracts the correct positions.
//
// Coverage:
//   - Binary little-endian PLY with float position + float normal
//   - ASCII PLY with float position + uchar red/green/blue
//   - Old PLY using 'vertex_index' (singular) face list name

#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <iostream>
#include <string>

#include "../src/Library/Geometry/TriangleMeshLoaderPLY.h"
#include "../src/Library/Geometry/TriangleMeshGeometryIndexed.h"

using namespace RISE;
using namespace RISE::Implementation;

namespace
{
	bool IsClose( const Scalar a, const Scalar b, const Scalar eps = 1e-5 )
	{
		return std::fabs( a - b ) <= eps;
	}

	std::string TempPath( const char* suffix )
	{
		char buf[L_tmpnam];
		// tmpnam is portable enough for a deterministic-ish path; the
		// content is what matters, not the filename.
		const char* p = std::tmpnam( buf );
		std::string path = p ? p : "rise_ply_test";
		path += suffix;
		return path;
	}

	void RemoveQuiet( const std::string& p )
	{
		std::remove( p.c_str() );
	}

	// Write a binary little-endian PLY with position + normal per vertex.
	// 4 vertices forming a quad in the XY plane; one quad face.
	void WriteBinaryPLYWithNormals( const std::string& path )
	{
		FILE* f = std::fopen( path.c_str(), "wb" );
		assert( f );

		// Header.
		std::fprintf( f, "ply\n" );
		std::fprintf( f, "format binary_little_endian 1.0\n" );
		std::fprintf( f, "element vertex 4\n" );
		std::fprintf( f, "property float x\n" );
		std::fprintf( f, "property float y\n" );
		std::fprintf( f, "property float z\n" );
		std::fprintf( f, "property float nx\n" );
		std::fprintf( f, "property float ny\n" );
		std::fprintf( f, "property float nz\n" );
		std::fprintf( f, "element face 1\n" );
		std::fprintf( f, "property list uchar uint vertex_indices\n" );
		std::fprintf( f, "end_header\n" );

		// Vertex data: 4 vertices, each with 3 position floats + 3 normal
		// floats, totaling 24 bytes per vertex.  Old loader would read 12.
		struct V { float x, y, z, nx, ny, nz; };
		const V verts[4] = {
			{ 0.0f, 0.0f, 0.0f,  0.0f, 0.0f, 1.0f },
			{ 1.0f, 0.0f, 0.0f,  0.0f, 0.0f, 1.0f },
			{ 1.0f, 1.0f, 0.0f,  0.0f, 0.0f, 1.0f },
			{ 0.0f, 1.0f, 0.0f,  0.0f, 0.0f, 1.0f },
		};
		std::fwrite( verts, sizeof(V), 4, f );

		// Face: count=4, then 4 uints.
		const unsigned char count = 4;
		const unsigned int idx[4] = { 0, 1, 2, 3 };
		std::fwrite( &count, 1, 1, f );
		std::fwrite( idx, sizeof(unsigned int), 4, f );

		std::fclose( f );
	}

	// Write an ASCII PLY with position + uchar RGB per vertex.
	void WriteAsciiPLYWithColors( const std::string& path )
	{
		FILE* f = std::fopen( path.c_str(), "wb" );
		assert( f );

		std::fprintf( f, "ply\n" );
		std::fprintf( f, "format ascii 1.0\n" );
		std::fprintf( f, "comment generated by PLYLoaderExtraPropertiesTest\n" );
		std::fprintf( f, "element vertex 3\n" );
		std::fprintf( f, "property float x\n" );
		std::fprintf( f, "property float y\n" );
		std::fprintf( f, "property float z\n" );
		std::fprintf( f, "property uchar red\n" );
		std::fprintf( f, "property uchar green\n" );
		std::fprintf( f, "property uchar blue\n" );
		std::fprintf( f, "element face 1\n" );
		std::fprintf( f, "property list uchar int vertex_indices\n" );
		std::fprintf( f, "end_header\n" );

		std::fprintf( f, "0.0 0.0 0.0  255 0 0\n" );
		std::fprintf( f, "1.0 0.0 0.0  0 255 0\n" );
		std::fprintf( f, "0.0 1.0 0.0  0 0 255\n" );
		std::fprintf( f, "3 0 1 2\n" );

		std::fclose( f );
	}

	// Write an ASCII PLY using the legacy 'vertex_index' (singular) face
	// list name.  Some old Stanford PLYs still use this form.
	void WriteAsciiPLYLegacyFaceList( const std::string& path )
	{
		FILE* f = std::fopen( path.c_str(), "wb" );
		assert( f );

		std::fprintf( f, "ply\n" );
		std::fprintf( f, "format ascii 1.0\n" );
		std::fprintf( f, "element vertex 3\n" );
		std::fprintf( f, "property float x\n" );
		std::fprintf( f, "property float y\n" );
		std::fprintf( f, "property float z\n" );
		std::fprintf( f, "element face 1\n" );
		std::fprintf( f, "property list uchar int vertex_index\n" );
		std::fprintf( f, "end_header\n" );

		std::fprintf( f, "5.0 6.0 7.0\n" );
		std::fprintf( f, "8.0 9.0 10.0\n" );
		std::fprintf( f, "11.0 12.0 13.0\n" );
		std::fprintf( f, "3 0 1 2\n" );

		std::fclose( f );
	}

	void TestBinaryWithNormals()
	{
		std::cout << "Testing binary PLY with declared normal properties..." << std::endl;
		const std::string path = TempPath( "_rise_ply_bin_norm.ply" );
		WriteBinaryPLYWithNormals( path );

		TriangleMeshGeometryIndexed* pMesh =
			new TriangleMeshGeometryIndexed( false, false );
		pMesh->addref();

		TriangleMeshLoaderPLY* pLoader =
			new TriangleMeshLoaderPLY( path.c_str(), false );
		pLoader->addref();

		const bool ok = pLoader->LoadTriangleMesh( pMesh );
		assert( ok && "binary PLY with normals failed to load" );

		const auto& pts = pMesh->getVertices();
		assert( pts.size() == 4 );
		assert( IsClose( pts[0].x, 0.0 ) && IsClose( pts[0].y, 0.0 ) && IsClose( pts[0].z, 0.0 ) );
		assert( IsClose( pts[1].x, 1.0 ) && IsClose( pts[1].y, 0.0 ) && IsClose( pts[1].z, 0.0 ) );
		assert( IsClose( pts[2].x, 1.0 ) && IsClose( pts[2].y, 1.0 ) && IsClose( pts[2].z, 0.0 ) );
		assert( IsClose( pts[3].x, 0.0 ) && IsClose( pts[3].y, 1.0 ) && IsClose( pts[3].z, 0.0 ) );

		// Quad => two triangles.
		assert( pMesh->getFaces().size() == 2 );

		pLoader->release();
		pMesh->release();
		RemoveQuiet( path );
		std::cout << "  Passed!" << std::endl;
	}

	void TestAsciiWithColors()
	{
		std::cout << "Testing ASCII PLY with declared color properties..." << std::endl;
		const std::string path = TempPath( "_rise_ply_ascii_rgb.ply" );
		WriteAsciiPLYWithColors( path );

		TriangleMeshGeometryIndexed* pMesh =
			new TriangleMeshGeometryIndexed( false, false );
		pMesh->addref();

		TriangleMeshLoaderPLY* pLoader =
			new TriangleMeshLoaderPLY( path.c_str(), false );
		pLoader->addref();

		const bool ok = pLoader->LoadTriangleMesh( pMesh );
		assert( ok && "ASCII PLY with colors failed to load" );

		const auto& pts = pMesh->getVertices();
		assert( pts.size() == 3 );
		assert( IsClose( pts[0].x, 0.0 ) && IsClose( pts[0].y, 0.0 ) && IsClose( pts[0].z, 0.0 ) );
		assert( IsClose( pts[1].x, 1.0 ) && IsClose( pts[1].y, 0.0 ) && IsClose( pts[1].z, 0.0 ) );
		assert( IsClose( pts[2].x, 0.0 ) && IsClose( pts[2].y, 1.0 ) && IsClose( pts[2].z, 0.0 ) );

		assert( pMesh->getFaces().size() == 1 );

		// The PLY had pure red, green, blue uchar values (255,0,0 / 0,255,0 / 0,0,255).
		// After load they should appear as three RISEPel entries; the exact
		// channel values depend on the sRGB→ROMM RGB conversion, but the
		// dominant channel of each must be the largest of its triplet.
		const auto& cols = pMesh->getColors();
		assert( cols.size() == 3 && "PLY colors not extracted into pColors" );
		assert( cols[0].r > cols[0].g && cols[0].r > cols[0].b ); // red-dominant
		assert( cols[1].g > cols[1].r && cols[1].g > cols[1].b ); // green-dominant
		assert( cols[2].b > cols[2].r && cols[2].b > cols[2].g ); // blue-dominant

		pLoader->release();
		pMesh->release();
		RemoveQuiet( path );
		std::cout << "  Passed!" << std::endl;
	}

	void TestNoColorsWhenSourceHasNone()
	{
		std::cout << "Testing PLY without colors leaves pColors empty..." << std::endl;
		const std::string path = TempPath( "_rise_ply_no_color.ply" );
		WriteAsciiPLYLegacyFaceList( path );

		TriangleMeshGeometryIndexed* pMesh =
			new TriangleMeshGeometryIndexed( false, false );
		pMesh->addref();

		TriangleMeshLoaderPLY* pLoader =
			new TriangleMeshLoaderPLY( path.c_str(), false );
		pLoader->addref();

		const bool ok = pLoader->LoadTriangleMesh( pMesh );
		assert( ok );
		// No red/green/blue properties were declared, so pColors must be empty.
		assert( pMesh->getColors().empty() );

		pLoader->release();
		pMesh->release();
		RemoveQuiet( path );
		std::cout << "  Passed!" << std::endl;
	}

	void TestLegacyFaceListName()
	{
		std::cout << "Testing legacy 'vertex_index' (singular) face list name..." << std::endl;
		const std::string path = TempPath( "_rise_ply_legacy_facelist.ply" );
		WriteAsciiPLYLegacyFaceList( path );

		TriangleMeshGeometryIndexed* pMesh =
			new TriangleMeshGeometryIndexed( false, false );
		pMesh->addref();

		TriangleMeshLoaderPLY* pLoader =
			new TriangleMeshLoaderPLY( path.c_str(), false );
		pLoader->addref();

		const bool ok = pLoader->LoadTriangleMesh( pMesh );
		assert( ok && "PLY with legacy 'vertex_index' face list failed to load" );

		const auto& pts = pMesh->getVertices();
		assert( pts.size() == 3 );
		assert( IsClose( pts[0].x, 5.0 ) && IsClose( pts[0].y, 6.0 ) );
		assert( IsClose( pts[2].z, 13.0 ) );
		assert( pMesh->getFaces().size() == 1 );

		pLoader->release();
		pMesh->release();
		RemoveQuiet( path );
		std::cout << "  Passed!" << std::endl;
	}
}

int main()
{
	std::cout << "Running PLYLoaderExtraPropertiesTest..." << std::endl;
	TestBinaryWithNormals();
	TestAsciiWithColors();
	TestLegacyFaceListName();
	TestNoColorsWhenSourceHasNone();
	std::cout << "All PLYLoaderExtraPropertiesTest cases passed." << std::endl;
	return 0;
}
