#include "RiseBridge.h"
#include "RiseCallbacks.h"
#include "RiseLogPrinter.h"
#include "jni_util.h"

#include <android/log.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <cerrno>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>

// RISE library headers — included only in .cpp files so the .h stays thin.
#include "RISE_API.h"
#include "Interfaces/IJobPriv.h"
#include "Interfaces/IJob.h"
#include "Interfaces/IRasterizer.h"
#include "Interfaces/IRasterizerOutput.h"
#include "Interfaces/IRasterImage.h"
#include "Interfaces/IScene.h"
#include "Interfaces/ILogPriv.h"
#include "Interfaces/IFrameEncoder.h"
#include "Utilities/MediaPathLocator.h"
#include "Utilities/Reference.h"
#include "SceneEditor/SceneEditController.h"
#include "Rendering/InteractivePelRasterizer.h"

// L4d — ViewportFrameStore-driven production-render path.
// The rasterizer feeds pixels into a canonical HDR FrameStore wrapped
// by ViewportFrameStore; on each tile/frame observer callback the
// bridge RenderToBuffer(RGBA8_sRGB)s directly into m_framebuffer
// (saving the RGBA16-then->>8 hop the legacy RasterizerOutputAdapter
// performed) and fires the existing onRegionInvalidated JNI
// notification.  Adds live exposure scrubbing (setViewExposureEV)
// and multi-format Save-As without re-render.
#include "Rendering/ViewportFrameStore.h"
#include "Rendering/FrameStore.h"
#include "Rendering/FrameEncoders.h"
#include "Rendering/TargetFormat.h"
#include "Rendering/ViewTransform.h"

using namespace RISE::FrameStoreOutput;

#define LOG_TAG "RISE-Bridge"
#define LOGI(...) __android_log_print(ANDROID_LOG_INFO,  LOG_TAG, __VA_ARGS__)
#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR, LOG_TAG, __VA_ARGS__)

namespace rise_jni {

RiseBridge& getBridge() {
    static RiseBridge instance;
    return instance;
}

RiseBridge::RiseBridge() = default;

RiseBridge::~RiseBridge() {
    teardownJob();
    // Tear-down ordering: teardownJob() destroys the Job (which destroys
    // the rasterizer, joining its worker pool en route).  By the time
    // teardownJob() returns no callbacks can be in flight against
    // either VFS.  Now safely release the bridge's VFS references,
    // after defensively nulling the callbacks (L4 round-4 P2-B) so
    // any future late-fire bypasses the captured `this` lambda.
    // Round-5: same treatment for both production and interactive VFS.
    auto teardownVFS = [](RISE::Implementation::ViewportFrameStore*& vfs) {
        if (vfs) {
            vfs->SetTileCompleteCallback(nullptr);
            vfs->SetFrameCompleteCallback(nullptr);
            vfs->SetPreDenoiseCompleteCallback(nullptr);
            vfs->SetDenoiseCompleteCallback(nullptr);
            vfs->release();
            vfs = nullptr;
        }
    };
    teardownVFS(m_productionVFS);
    teardownVFS(m_interactiveVFS);
    {
        std::lock_guard<std::mutex> lock(m_fbMutex);
        std::free(m_framebuffer);
        m_framebuffer = nullptr;
    }
    {
        // L4 round-5 P1-A — serialise vs any in-flight worker
        // CallVoidMethod.  By this dtor point teardownJob() has
        // already joined the rasterizer's worker pool (via
        // m_job->release() → ~Rasterizer), so in practice no worker
        // can still be inside a CallVoidMethod here.  Defensive
        // mutex acquisition costs nothing.
        std::lock_guard<std::mutex> lock(m_kotlinCallbackMutex);
        if (m_kotlinCallback) {
            JNIEnv* env = getJniEnv();
            if (env) {
                env->DeleteGlobalRef(m_kotlinCallback);
            }
            m_kotlinCallback = nullptr;
        }
    }
}

void RiseBridge::writeGlobalOptionsFile(const std::string& path, int threadCount) {
    // Minimal RISE options file format: "<key> <value>" per line. See
    // Options::Options() in src/Library/Options.cpp — it tokenizes and
    // stores the first two tokens as key/value.
    std::ofstream out(path.c_str(), std::ios::out | std::ios::trunc);
    if (!out.is_open()) {
        LOGE("writeGlobalOptionsFile: failed to open %s", path.c_str());
        return;
    }
    out << "# Generated by RISE Android bridge on initialize()\n";
    out << "force_number_of_threads " << threadCount << "\n";
    out << "support_hyperthreading false\n";
    out.close();
}

void RiseBridge::initialize(const std::string& projectRoot,
                            const std::string& logFile,
                            int                threadCount) {
    if (m_initialized) {
        LOGI("initialize: already initialized; updating options file only");
    }
    m_projectRoot = projectRoot;
    m_logFile     = logFile;
    m_threadCount = threadCount > 0 ? threadCount : 1;
    m_optionsFile = projectRoot + "/global.options";

    // Write the options file BEFORE any GlobalOptions() call. The library
    // caches the Options singleton on first access.
    writeGlobalOptionsFile(m_optionsFile, m_threadCount);

    // Point the library at our options file. setenv is POSIX so this works
    // under NDK. Must happen before the first GlobalOptions() call.
    ::setenv("RISE_OPTIONS_FILE", m_optionsFile.c_str(), 1);
    ::setenv("RISE_MEDIA_PATH",  projectRoot.c_str(),    1);

    // Redirect the logger BEFORE any Rasterize / LoadScene / Options access
    // so the file path is never stale.
    RISE::SetGlobalLogFileName(logFile.c_str());

    // Register the media path so scene files can resolve relative asset
    // paths like "textures/foo.png" against filesDir/rise/textures/foo.png.
    RISE::GlobalMediaPathLocator().AddPath(projectRoot.c_str());

    // Attach our logcat forwarder so RISE log output shows up in `adb logcat`.
    if (!m_logPrinter) {
        m_logPrinter = new LogPrinterImpl(this);
        RISE::GlobalLogPriv()->AddPrinter(m_logPrinter);
    }

    // Many bundled scenes use file_rasterizeroutput with a pattern like
    // "rendered/<name>". The library's FileRasterizerOutput does NOT create
    // the parent directory, so we pre-create the directories the bundled
    // scenes need. Harmless if they already exist.
    //
    // Add to this list whenever a new bundled scene writes to a NESTED
    // output pattern (e.g. "rendered/foo/frame" needs "rendered/foo").
    // Plain "rendered/<sceneName>" only needs the top-level "rendered"
    // directory, which is already covered.
    static const char* kRenderedDirs[] = {
        "rendered",
    };
    for (const char* sub : kRenderedDirs) {
        const std::string dir = projectRoot + "/" + sub;
        if (::mkdir(dir.c_str(), 0755) != 0 && errno != EEXIST) {
            LOGI("mkdir %s (non-fatal): %s", dir.c_str(), std::strerror(errno));
        }
    }

    m_initialized = true;
    LOGI("RiseBridge initialized: root=%s log=%s threads=%d",
         projectRoot.c_str(), logFile.c_str(), m_threadCount);
}

void RiseBridge::setCallback(JNIEnv* env, jobject kotlinCallback) {
    if (!env) return;
    // L4 round-5 P1-A — serialise the global-ref swap against
    // worker-thread CallVoidMethod sites.  RenderViewModel
    // (RenderViewModel.kt:327) calls nativeSetCallback(null) at
    // ViewModel onCleared without first joining the
    // Dispatchers.IO-launched nativeRasterize coroutine, so this
    // path can race the rasterizer worker pool firing
    // onProgressTick / onLogLine / onProductionVFSTileComplete.  Without
    // the mutex the pre-L4d setCallback would
    // DeleteGlobalRef under the worker's nose and the next
    // CallVoidMethod would UAF the jobject.
    std::lock_guard<std::mutex> lock(m_kotlinCallbackMutex);
    if (m_kotlinCallback) {
        env->DeleteGlobalRef(m_kotlinCallback);
        m_kotlinCallback = nullptr;
    }
    if (kotlinCallback) {
        m_kotlinCallback = env->NewGlobalRef(kotlinCallback);
    }
}

void RiseBridge::teardownJob() {
    // Tear down viewport (which holds rasterizer/caster references back into
    // the job) BEFORE releasing the job itself.  Otherwise we'd leak.
    stopViewport();

    if (m_job) {
        // L4d: drop the rasterizer's VFS reference before destroying
        // the rasterizer.  The bridge's VFS reference keeps the VFS
        // alive across scene reloads — the next rasterize call will
        // re-Attach to the new scene's rasterizer.
        if (RISE::IRasterizer* rasterizer = m_job->GetRasterizer()) {
            rasterizer->FreeRasterizerOutputs();
        }
        m_productionVFSAttachedToRasterizer = false;
        // RISE_CreateJobPriv returns a refcounted pointer; the safe cleanup
        // is to release the reference we hold. The library's Reference
        // implementation will delete the job when refcount hits zero.
        m_job->release();
        m_job = nullptr;
    }
}

bool RiseBridge::loadScene(const std::string& absPath) {
    if (!m_initialized) {
        LOGE("loadScene: bridge not initialized");
        return false;
    }
    m_cancel.store(false);
    teardownJob();

    // Lazily create the progress callback adapter.  The legacy
    // IJobRasterizerOutput adapter is gone — VFS replaces it (created
    // lazily inside ensureProductionVFSAttachedToRasterizer on the first
    // rasterize call once the rasterizer exists).
    if (!m_progress) m_progress.reset(newProgressCallback(this));

    if (!RISE::RISE_CreateJobPriv(&m_job) || !m_job) {
        LOGE("loadScene: RISE_CreateJobPriv failed");
        return false;
    }

    // L5d — interactive GUI: drop file_rasterizeroutput chunks at
    // parse time so loading a scene doesn't auto-write PNG/EXR/etc.
    // on every Render tap.  Users save via the Save action (writes
    // to a user-picked path through the L2 IFrameEncoder pipeline).
    m_job->SetSuppressFileRasterizerOutputs(true);

    // Progress callback must be attached BEFORE LoadAsciiScene — the parser
    // itself reports progress.
    m_job->SetProgress(m_progress.get());

    if (!m_job->LoadAsciiScene(absPath.c_str())) {
        LOGE("loadScene: LoadAsciiScene failed for %s", absPath.c_str());
        teardownJob();
        return false;
    }
    LOGI("loadScene: loaded %s", absPath.c_str());
    return true;
}

bool RiseBridge::rasterize() {
    if (!m_job) {
        LOGE("rasterize: no job loaded");
        return false;
    }

    m_cancel.store(false);

    // Attach VFS to the rasterizer for this render.  The bridge owns
    // the persistent VFS reference; FreeRasterizerOutputs drops the
    // rasterizer's reference and re-Attach below bumps it again.
    // Library wipes the rasterizer's output list during scene load
    // (so the first rasterize after a load has an empty outs list),
    // but later rasterize calls need the explicit Free → Attach
    // dance to avoid stacking duplicate references.
    if (RISE::IRasterizer* raster = m_job->GetRasterizer()) {
        raster->FreeRasterizerOutputs();
        m_productionVFSAttachedToRasterizer = false;
    }
    ensureProductionVFSAttachedToRasterizer();

    // BLOCKING. Library spawns its own pthread worker pool, dispatches tiles,
    // joins on completion. Tile callbacks fire from the workers; cancellation
    // is via the progress callback return value.
    const bool ok = m_job->Rasterize();
    LOGI("rasterize: returned %d", ok ? 1 : 0);
    return ok;
}

void RiseBridge::requestCancel() {
    m_cancel.store(true);
}

bool RiseBridge::hasAnimatedObjects() const {
    if (!m_job) return false;
    return m_job->AreThereAnyKeyframedObjects();
}

void RiseBridge::setSceneTime(double t) {
    if (!m_job) return;
    RISE::IScenePriv* scene = m_job->GetScene();
    if (!scene) return;
    // Full SetSceneTime: advances the animator AND regenerates every
    // populated photon map at time `t`.  The interactive viewport's
    // scrub path calls SetSceneTimeForPreview (animator-only, no
    // photon regen) for responsiveness; this method runs the
    // expensive photon regen so the next production render gets
    // caustics consistent with the scrubbed scene state.
    scene->SetSceneTime(static_cast<RISE::Scalar>(t));
}

void RiseBridge::ensureFramebuffer(unsigned w, unsigned h) {
    bool fired = false;
    {
        std::lock_guard<std::mutex> lock(m_fbMutex);
        if (m_fbWidth == w && m_fbHeight == h && m_framebuffer) {
            return;
        }
        std::free(m_framebuffer);
        m_framebuffer = static_cast<uint8_t*>(std::calloc(static_cast<size_t>(w) * h * 4, 1));
        m_fbWidth  = w;
        m_fbHeight = h;
        fired = true;
    }
    if (fired) {
        // L4 round-5 P1-A — hold m_kotlinCallbackMutex across
        // CallVoidMethod so a concurrent setCallback(null) on the
        // UI thread can't DeleteGlobalRef the jobject mid-call.
        std::lock_guard<std::mutex> lock(m_kotlinCallbackMutex);
        if (m_kotlinCallback) {
            JNIEnv* env = getJniEnv();
            if (env) {
                ScopedLocalFrame frame(env, 8);
                env->CallVoidMethod(m_kotlinCallback, g_cb.onSceneReady,
                                    static_cast<jint>(w), static_cast<jint>(h));
                if (env->ExceptionCheck()) {
                    env->ExceptionDescribe();
                    env->ExceptionClear();
                }
            }
        }
    }
}

void RiseBridge::writeDirtyRegion(const unsigned short* src16,
                                  unsigned w, unsigned h,
                                  unsigned top, unsigned left,
                                  unsigned bottom, unsigned right) {
    ensureFramebuffer(w, h);

    if (right < left || bottom < top) return;
    if (right >= w) right = w - 1;
    if (bottom >= h) bottom = h - 1;

    {
        std::lock_guard<std::mutex> lock(m_fbMutex);
        if (!m_framebuffer || m_fbWidth != w || m_fbHeight != h) return;

        // Source is RGBA16, packed. Destination is RGBA8. Simple >> 8
        // downconvert matches what Mac and Windows bridges do; the library's
        // GetColorSpace() returns sRGB so gamma is already applied.
        for (unsigned y = top; y <= bottom; ++y) {
            const unsigned short* srow = src16 + (static_cast<size_t>(y) * w + left) * 4;
            uint8_t*              drow = m_framebuffer + (static_cast<size_t>(y) * w + left) * 4;
            for (unsigned x = left; x <= right; ++x) {
                drow[0] = static_cast<uint8_t>(srow[0] >> 8);
                drow[1] = static_cast<uint8_t>(srow[1] >> 8);
                drow[2] = static_cast<uint8_t>(srow[2] >> 8);
                drow[3] = static_cast<uint8_t>(srow[3] >> 8);
                srow += 4;
                drow += 4;
            }
        }
    }

    {
        // L4 round-5 P1-A — see ensureFramebuffer rationale.
        std::lock_guard<std::mutex> lock(m_kotlinCallbackMutex);
        if (m_kotlinCallback) {
            JNIEnv* env = getJniEnv();
            if (env) {
                ScopedLocalFrame frame(env, 4);
                env->CallVoidMethod(m_kotlinCallback, g_cb.onRegionInvalidated,
                                    packRect(top, left, bottom, right));
                if (env->ExceptionCheck()) {
                    env->ExceptionDescribe();
                    env->ExceptionClear();
                }
            }
        }
    }
}

// L4d — VFS-driven production-render path.
// VFS observer callbacks fire from rasterizer worker threads.  We
// take m_fbMutex (the same mutex writeDirtyRegion takes), call
// ViewportFrameStore::RenderToBuffer at RGBA8_sRGB directly into
// m_framebuffer, then notify Kotlin via the same onRegionInvalidated
// JNI hop the legacy path used.  Net change: no RGBA16 staging
// buffer, no per-pixel `>> 8` walk in the bridge — the LDR path
// runs once inside RenderToBuffer.
void RiseBridge::ensureProductionVFSAttachedToRasterizer() {
    if (!m_job) return;
    RISE::IRasterizer* rasterizer = m_job->GetRasterizer();
    if (!rasterizer) return;

    if (!m_productionVFS) {
        m_productionVFS = new RISE::Implementation::ViewportFrameStore();

        // Lambda captures `this` raw; the bridge is a process-wide
        // singleton (getBridge()) — its lifetime spans the whole
        // process, so any VFS callback always finds `this` valid.
        //
        // L8 round 9 — tile-complete callback DELIBERATELY NOT WIRED.
        // The previous design ran a synchronous `OnTileComplete`
        // from every rasterizer worker thread, acquiring
        // `m_bufferMutex` for ~85 µs per tile + calling
        // `RenderToBuffer` inside the lock (taking FrameStore
        // shared_locks).  Two worker blocks landing on the same
        // FrameStore tile produced a `m_bufferMutex ↔ tile-mutex`
        // inversion that hung the render after a handful of blocks.
        //
        // Lockless replacement: the Kotlin side's `Choreographer`
        // callback (post-L8 round 9 wiring in MainActivity.kt) calls
        // `Java_..._pollProductionVFS()` at the display refresh
        // cadence.  That JNI hop reads `vfs->Generation()` and only
        // does a full-image emit when the counter advances.  Workers
        // never block on the JNI / Kotlin side; their per-tile
        // EndTile calls just bump the atomic generation counter in
        // FrameStore.  See `pollProductionVFS` impl below for the
        // architecture rationale (cross-references the macOS bridge
        // doc which is the spec).
        m_productionVFS->SetFrameCompleteCallback(
            [this](unsigned int /*frame*/, uint64_t /*gen*/) {
                this->onProductionVFSFrameComplete();
            });
        m_productionVFS->SetPreDenoiseCompleteCallback(
            [this](unsigned int /*frame*/, uint64_t /*gen*/) {
                this->onProductionVFSFrameComplete();
            });
        m_productionVFS->SetDenoiseCompleteCallback(
            [this](unsigned int /*frame*/, uint64_t /*gen*/) {
                this->onProductionVFSFrameComplete();
            });
    }

    // L6e-2b/c — `Attach` auto-binds the VFS to the rasterizer's
    // canonical FrameStore via `BindFrameStore(rasterizer->GetFrameStore())`.
    // Subsequent `Rasterizer::SetFrameStore` swaps (camera-dim change,
    // active-camera switch) re-bind via the new
    // `OnRasterizerFrameStoreChanged` notification, dispatched on
    // every attached output.  Net effect: for PT / BDPT / VCM the VFS
    // now observes the rasterizer's mFrameStore directly — no
    // VFS-internal FrameStore allocation, no FrameSink cross-store
    // copy.  MLT rasterizers opt out of the FrameStore push (per
    // L6e-1.1's `AcceptsFrameStorePush()` virtual) and stay on the
    // legacy FrameSink path until L6d-2.
    if (!m_productionVFSAttachedToRasterizer) {
        m_productionVFS->Attach(rasterizer);
        m_productionVFSAttachedToRasterizer = true;
    }
}

// L4 round-7 P1 perf fix: render only the changed region into the
// matching slice of m_framebuffer, and notify Kotlin with that
// region's bounds.  Per-tile work is now O(tile-area) not O(image-
// area) — was a ~4× regression vs the legacy `>> 8`-of-tile path.
// `halfOpenRoi == nullptr` → render full image (used by frame-
// complete and exposure-scrub paths).
void RiseBridge::onProductionVFSTileComplete(const RISE::Rect* halfOpenRoi,
                                             bool nonBlocking) {
    if (!m_productionVFS) return;
    // GetDimensions takes chainMutex_ shared internally — safe against
    // a concurrent resolution-change reallocation in the rasterizer
    // thread (see L4 round-4 P2-D adversarial review).
    unsigned int W = 0, H = 0;
    m_productionVFS->GetDimensions(W, H);
    if (W == 0 || H == 0) return;

    // Make sure m_framebuffer is sized + Kotlin has been notified
    // of dims (onSceneReady) BEFORE the first RenderToBuffer write.
    ensureFramebuffer(W, H);

    // Compute the inclusive bounds we'll send to Kotlin AFTER
    // clipping to image dims.  (0,0,H-1,W-1) for full-image emits.
    unsigned int emitTop = 0, emitLeft = 0, emitBottom = H - 1, emitRight = W - 1;
    if (halfOpenRoi) {
        const unsigned int y0 = halfOpenRoi->top;
        const unsigned int x0 = halfOpenRoi->left;
        const unsigned int y1 = std::min<unsigned int>(halfOpenRoi->bottom, H);
        const unsigned int x1 = std::min<unsigned int>(halfOpenRoi->right,  W);
        if (y1 <= y0 || x1 <= x0) return;
        emitTop    = y0;
        emitLeft   = x0;
        emitBottom = y1 - 1;
        emitRight  = x1 - 1;
    }

    {
        std::lock_guard<std::mutex> lock(m_fbMutex);
        if (!m_framebuffer || m_fbWidth != W || m_fbHeight != H) return;
        // L5e — bake in the user-selected tone curve (default ACES).
        const RISE::DISPLAY_TRANSFORM tc =
            static_cast<RISE::DISPLAY_TRANSFORM>(m_viewToneCurve.load());
        const ViewTransform xf = ViewTransform::ForLDRDisplay(
            static_cast<float>(m_viewExposureEV.load()), tc);
        if (halfOpenRoi) {
            // Region path — see RISEBridge.mm:EmitRegion_locked
            // and FrameStore.cpp:748-750 for the dst-offset rationale:
            // RenderToBuffer writes pixels at
            //   dst[(y - y0) * dstStride + (x - x0) * bpp]
            // so we point dst at the (y0, x0) pixel of the framebuffer
            // and pass the FULL row stride.
            uint8_t* base = m_framebuffer
                            + (static_cast<size_t>(emitTop) * W + emitLeft) * 4;
            m_productionVFS->RenderToBuffer(
                base, static_cast<size_t>(W) * 4,
                *halfOpenRoi, TargetFormat::RGBA8_sRGB, xf, nonBlocking);
        } else {
            m_productionVFS->RenderToBuffer(
                m_framebuffer, static_cast<size_t>(W) * 4,
                RISE::Rect(0, 0, H, W), TargetFormat::RGBA8_sRGB, xf, nonBlocking);
        }
    }

    // Notify Kotlin of the dirty region (inclusive bounds).
    // L4 round-5 P1-A — guard the global ref against a concurrent
    // setCallback(null) UAF.
    {
        std::lock_guard<std::mutex> lock(m_kotlinCallbackMutex);
        if (m_kotlinCallback) {
            JNIEnv* env = getJniEnv();
            if (env) {
                ScopedLocalFrame frame(env, 4);
                env->CallVoidMethod(m_kotlinCallback, g_cb.onRegionInvalidated,
                                    packRect(emitTop, emitLeft, emitBottom, emitRight));
                if (env->ExceptionCheck()) {
                    env->ExceptionDescribe();
                    env->ExceptionClear();
                }
            }
        }
    }
}

void RiseBridge::onProductionVFSFrameComplete() {
    // Frame-complete fires once per frame (not per tile) — full-image
    // emit guarantees post-denoise / post-resolve coherence.
    onProductionVFSTileComplete(nullptr);
    // L8 round 9 — sync the poll sentinel so a subsequent
    // pollProductionVFS doesn't redo the same work.
    if (m_productionVFS) {
        m_lastSeenGeneration = m_productionVFS->Generation();
    }
}

void RiseBridge::pollProductionVFS() {
    // L8 round 9 — UI-thread polling entry point.  Driven by the
    // Kotlin side's `Choreographer` callback at the display refresh
    // cadence during an active render.  See companion comment in
    // `ensureProductionVFSAttachedToRasterizer` for the architecture
    // rationale; the Mac (`RISEBridge.mm`) impl is the spec.
    //
    // Reads `vfs->Generation()` atomically.  No-ops when the counter
    // matches the last-emitted sentinel (workers haven't produced
    // new pixels since the previous poll).  Otherwise routes through
    // the same full-image emit path that `onProductionVFSFrameComplete`
    // uses — the lock + RenderToBuffer + onRegionInvalidated JNI hop.
    // Workers never block on this; they only bump the atomic
    // generation counter inside `FrameStore` via `EndTile`.
    if (!m_productionVFS) return;
    const uint64_t gen = m_productionVFS->Generation();
    if (gen == m_lastSeenGeneration) return;  // no new pixels
    // L8 round 14 — `nonBlocking=true`.  See FrameStore::Render doc;
    // prevents the Choreographer / poll path from blocking on a
    // slow worker block's tile exclusive.
    onProductionVFSTileComplete(nullptr, /*nonBlocking=*/true);
    m_lastSeenGeneration = gen;
}

// L5a round-5 — interactive VFS lazy-create.  ONLY frame-complete
// observers are bound; tile-complete is intentionally left
// unwired so per-tile OutputIntermediateImage events from the
// interactive rasterizer don't drive m_framebuffer writes (no
// DrawToggles flash, no preview-scale resolution-thrash visible
// to Compose).  Mirrors macOS RISEBridge.mm:ensureInteractiveVFSCreated.
void RiseBridge::ensureInteractiveVFSCreated() {
    if (m_interactiveVFS) return;
    m_interactiveVFS = new RISE::Implementation::ViewportFrameStore();
    // Tile-complete deliberately NOT bound — see method doc.
    m_interactiveVFS->SetFrameCompleteCallback(
        [this](unsigned int /*frame*/, uint64_t /*gen*/) {
            this->onInteractiveVFSFrameComplete();
        });
    m_interactiveVFS->SetPreDenoiseCompleteCallback(
        [this](unsigned int /*frame*/, uint64_t /*gen*/) {
            this->onInteractiveVFSFrameComplete();
        });
    m_interactiveVFS->SetDenoiseCompleteCallback(
        [this](unsigned int /*frame*/, uint64_t /*gen*/) {
            this->onInteractiveVFSFrameComplete();
        });
}

RISE::Implementation::ViewportFrameStore* RiseBridge::getOrCreateInteractiveVFS() {
    ensureInteractiveVFSCreated();
    return m_interactiveVFS;
}

// L5a round-5 — interactive VFS frame-complete observer.  Same
// shape as `onProductionVFSTileComplete(nullptr)` (full-image
// path) but reads dims + RenderToBuffer's from the interactive
// VFS, so the production VFS's pixels are not disturbed.  Both
// VFSes currently render into the same `m_framebuffer` for
// Compose display — a future landing can give interactive its
// own overlay framebuffer; this method is the single Android-
// side site that would change for that.
void RiseBridge::onInteractiveVFSFrameComplete() {
    if (!m_interactiveVFS) return;
    unsigned int W = 0, H = 0;
    m_interactiveVFS->GetDimensions(W, H);
    if (W == 0 || H == 0) return;

    ensureFramebuffer(W, H);

    {
        std::lock_guard<std::mutex> lock(m_fbMutex);
        if (!m_framebuffer || m_fbWidth != W || m_fbHeight != H) return;
        // L5e — same tone-curve snapshot as the production path.
        const RISE::DISPLAY_TRANSFORM tc =
            static_cast<RISE::DISPLAY_TRANSFORM>(m_viewToneCurve.load());
        const ViewTransform xf = ViewTransform::ForLDRDisplay(
            static_cast<float>(m_viewExposureEV.load()), tc);
        m_interactiveVFS->RenderToBuffer(
            m_framebuffer, static_cast<size_t>(W) * 4,
            RISE::Rect(0, 0, H, W), TargetFormat::RGBA8_sRGB, xf);
    }

    // Full-image dirty notification — interactive always emits the
    // whole frame (no per-tile observer wiring), so we tell Compose
    // the entire image is dirty.
    {
        std::lock_guard<std::mutex> lock(m_kotlinCallbackMutex);
        if (m_kotlinCallback) {
            JNIEnv* env = getJniEnv();
            if (env) {
                ScopedLocalFrame frame(env, 4);
                env->CallVoidMethod(m_kotlinCallback, g_cb.onRegionInvalidated,
                                    packRect(0, 0, H - 1, W - 1));
                if (env->ExceptionCheck()) {
                    env->ExceptionDescribe();
                    env->ExceptionClear();
                }
            }
        }
    }
}

void RiseBridge::setViewExposureEV(double ev) {
    m_viewExposureEV.store(ev);
    // Re-render BOTH VFS surfaces at the new EV.  Production
    // re-runs through the full-image tile-complete path; interactive
    // re-runs through its frame-complete path.  Round-5: round-trip
    // both so the slider works whichever surface is currently
    // displayed (Compose currently shows whichever wrote to
    // m_framebuffer last; future split-buffer compose will pick
    // per-layer).
    onProductionVFSTileComplete(nullptr);
    onInteractiveVFSFrameComplete();
}

void RiseBridge::setViewToneCurve(int curve) {
    // L5e — same lifecycle as setViewExposureEV: atomic store,
    // re-render both VFS surfaces.  No-op for VFSes that haven't
    // allocated yet.
    m_viewToneCurve.store(curve);
    onProductionVFSTileComplete(nullptr);
    onInteractiveVFSFrameComplete();
}

bool RiseBridge::saveAs(const std::string& path,
                        const std::string& formatName,
                        double             ev) {
    if (!m_productionVFS) return false;
    RISE::IFrameEncoder* enc =
        RISE::Implementation::FrameEncoderRegistry::Get().ByFormatName(
            formatName.c_str());
    if (!enc) {
        LOGE("saveAs: unknown format '%s'", formatName.c_str());
        return false;
    }
    // L5d — format-aware EncodeOpts.  HDR archival formats (EXR /
    // .hdr / RGBEA) preserve scene-referred linear values > 1.0;
    // their encoders ignore `viewTransform` and `bpp`, but pass
    // identity anyway so a future encoder change can't clip.  LDR
    // formats (PNG / TIFF-8 / TGA / PPM) get the user's current
    // display EV baked in via `ForLDRDisplay(ev)`.
    RISE::EncodeOpts opts;
    opts.colorSpace = RISE::eColorSpace_sRGB;
    if (enc->SupportsHDR()) {
        opts.bpp           = 0;
        opts.viewTransform = ViewTransform::Identity();
    } else {
        // L5e — bake the user's currently-active tone curve into
        // the LDR save so the file matches the on-screen viewport.
        const RISE::DISPLAY_TRANSFORM tc =
            static_cast<RISE::DISPLAY_TRANSFORM>(m_viewToneCurve.load());
        opts.bpp           = 8;
        opts.viewTransform = ViewTransform::ForLDRDisplay(
            static_cast<float>(ev), tc);
    }
    return m_productionVFS->SaveAs(path, enc, opts);
}

bool RiseBridge::onProgressTick(double progress, double total) {
    if (m_cancel.load()) {
        return false;
    }
    {
        std::lock_guard<std::mutex> lock(m_etaMutex);
        m_eta.Update(progress, total);
    }
    {
        // L4 round-5 P1-A — guard against concurrent
        // setCallback(null) UAF on the JNI global ref.  This is the
        // hottest call site (rasterizer fires onProgress hundreds
        // of times per render) so we want minimum lock time, but
        // dropping the lock around CallVoidMethod would re-open
        // the UAF window the mutex was added to close.
        std::lock_guard<std::mutex> lock(m_kotlinCallbackMutex);
        if (m_kotlinCallback) {
            JNIEnv* env = getJniEnv();
            if (env) {
                ScopedLocalFrame frame(env, 4);
                const float p = (total > 0.0)
                    ? static_cast<float>(progress / total)
                    : 0.0f;
                env->CallVoidMethod(m_kotlinCallback, g_cb.onProgress, p);
                if (env->ExceptionCheck()) {
                    env->ExceptionDescribe();
                    env->ExceptionClear();
                }
            }
        }
    }
    return true;
}

void RiseBridge::etaBegin() {
    std::lock_guard<std::mutex> lock(m_etaMutex);
    m_eta.Begin();
}

int64_t RiseBridge::etaElapsedMs() const {
    std::lock_guard<std::mutex> lock(m_etaMutex);
    return static_cast<int64_t>(m_eta.ElapsedSeconds() * 1000.0 + 0.5);
}

int64_t RiseBridge::etaRemainingMs() const {
    std::lock_guard<std::mutex> lock(m_etaMutex);
    double s = 0.0;
    if (!m_eta.RemainingSeconds(s)) return -1;
    if (s < 0.0) s = 0.0;
    return static_cast<int64_t>(s * 1000.0 + 0.5);
}

void RiseBridge::onLogLine(int level, const char* message) {
    if (!message) return;
    // L4 round-5 P1-A — log lines fire from any thread; serialise
    // jobject access against a concurrent setCallback(null).
    std::lock_guard<std::mutex> lock(m_kotlinCallbackMutex);
    if (!m_kotlinCallback) return;
    JNIEnv* env = getJniEnv();
    if (!env) return;
    ScopedLocalFrame frame(env, 8);
    jstring jmsg = env->NewStringUTF(message);
    if (!jmsg) return;
    env->CallVoidMethod(m_kotlinCallback, g_cb.onLog, static_cast<jint>(level), jmsg);
    if (env->ExceptionCheck()) {
        env->ExceptionDescribe();
        env->ExceptionClear();
    }
}

jobject RiseBridge::getFramebufferByteBuffer(JNIEnv* env) const {
    std::lock_guard<std::mutex> lock(m_fbMutex);
    if (!env || !m_framebuffer || m_fbWidth == 0 || m_fbHeight == 0) {
        return nullptr;
    }
    const jlong size = static_cast<jlong>(m_fbWidth) * m_fbHeight * 4;
    return env->NewDirectByteBuffer(m_framebuffer, size);
}

// ===========================================================================
// Interactive viewport
// ===========================================================================

namespace {

// IRasterizerOutput that, on end-of-frame, blits the rendered image into
// RiseBridge's RGBA8 framebuffer and signals onRegionInvalidated for the
// whole image.  Reuses the existing Compose redraw path — production
// renders and viewport-preview renders both flow through the same
// framebuffer, so the UI doesn't need to know which one it's seeing.
//
// Two end-of-pass guards keep stale or undesirable buffers off the
// screen (mirroring the macOS / Windows sinks):
//   * Cancel guard: the rasterizer's FlushToOutputs fires
//     unconditionally even when the dispatcher returned early for a
//     cancel.  Without this check, every cancel-restart would flash a
//     partially-rendered (mostly-black) buffer before the next pass.
//   * Suppress-next: drops exactly one upcoming dispatch.  Used right
//     after a production render returns so the production image stays
//     on screen until the user actually starts interacting.
class ViewportPreviewSink : public RISE::IRasterizerOutput,
                            public RISE::Implementation::Reference {
public:
    explicit ViewportPreviewSink(RiseBridge* b) : m_bridge(b) {}
    ~ViewportPreviewSink() override {
        if (m_fanoutVFS) {
            m_fanoutVFS->release();
            m_fanoutVFS = nullptr;
        }
    }

    // Borrowed; the bridge keeps the controller alive for the sink's
    // lifetime.  Used to query IsCancelRequested at end-of-pass.
    void SetController(RISE::SceneEditController* c) { m_controller = c; }

    // L5a round-5 — INTERACTIVE VFS to fan-out OutputImage into.
    // The interactive rasterizer's per-pass output is fed into
    // this VFS's frame-complete observer, which writes
    // m_framebuffer + fires onRegionInvalidated.  Per-tile fires
    // (OutputIntermediateImage) DELIBERATELY do NOT fan into VFS
    // — they would drive per-tile observer fires (DrawToggles
    // flash) AND would force the VFS to reallocate on every
    // preview-scale change.  Frame-complete-only keeps it smooth.
    // Mirrors macOS RISEViewportBridge.mm:ViewportPreviewSink::
    // SetFanoutVFS.  Strong ref (addref'd here, released in dtor).
    void SetFanoutVFS(RISE::Implementation::ViewportFrameStore* vfs) {
        if (m_fanoutVFS == vfs) return;
        if (vfs) vfs->addref();
        if (m_fanoutVFS) m_fanoutVFS->release();
        m_fanoutVFS = vfs;
    }

    // Drop the very next OutputImage call.  Auto-clears after one drop.
    void SuppressNextFrame() { m_suppressNext.store(true); }

    // Per-tile callback fires many times per render — explicitly ignore
    // (matches the macOS / Windows policy: avoid distracting tile fills).
    // L5a round-5: ALSO do not fan into VFS at this level — see
    // SetFanoutVFS doc.  The interactive VFS's tile-complete observer
    // is intentionally not bound (see RiseBridge::ensureInteractiveVFSCreated).
    void OutputIntermediateImage(const RISE::IRasterImage& /*pImage*/,
                                 const RISE::Rect* /*pRegion*/) override {}

    // Every dispatch reaches the screen.  We do NOT drop cancelled-
    // mid-pass frames: during fast manipulation the cancel flag trips
    // on every pointer move, and dropping the resulting partial
    // buffers makes the viewport feel throttled (the user only sees
    // post-pause refinement frames).  Center-out tile order keeps
    // partial buffers visually usable.  The one-shot suppress is kept
    // for the post-production case.
    void OutputImage(const RISE::IRasterImage& pImage,
                     const RISE::Rect* pRegion,
                     const unsigned int frame) override {
        if (!m_bridge) return;
        if (m_suppressNext.exchange(false)) {
            // One-shot suppression (post-production) — skip exactly
            // this dispatch.  The next render's frame goes through.
            return;
        }
        const unsigned int W = pImage.GetWidth();
        const unsigned int H = pImage.GetHeight();
        if (W == 0 || H == 0) return;

        // L5a round-5 — fan into the interactive VFS if wired.
        // VFS's OutputImage path copies pixels into the FrameStore
        // and fires the frame-complete observer, which is what
        // updates m_framebuffer + the JNI notification (single
        // unified pixel-conversion + Compose-notify path).  When
        // VFS isn't wired (e.g. very early / Metal-incapable build),
        // fall back to the legacy manual blit so the viewport still
        // shows pixels.
        if (m_fanoutVFS) {
            m_fanoutVFS->OutputImage(pImage, pRegion, frame);
            return;
        }

        // Legacy fallback path — kept for back-compat in the
        // unlikely case the interactive VFS isn't yet allocated.
        m_bridge->ensureFramebuffer(W, H);
        std::vector<unsigned short> rgba16;
        rgba16.resize(static_cast<size_t>(W) * H * 4);
        for (unsigned int y = 0; y < H; ++y) {
            unsigned short* row = &rgba16[static_cast<size_t>(y) * W * 4];
            for (unsigned int x = 0; x < W; ++x) {
                RISE::RISEColor c = pImage.GetPEL(x, y);
                auto clamp16 = [](double v) -> unsigned short {
                    if (v <= 0.0) return 0;
                    if (v >= 1.0) return 65535;
                    return static_cast<unsigned short>(v * 65535.0 + 0.5);
                };
                *row++ = clamp16(c.base.r);
                *row++ = clamp16(c.base.g);
                *row++ = clamp16(c.base.b);
                *row++ = 65535;
            }
        }
        m_bridge->writeDirtyRegion(rgba16.data(), W, H, 0, 0, H - 1, W - 1);
    }

private:
    RiseBridge*                                  m_bridge = nullptr;
    RISE::SceneEditController*                   m_controller = nullptr;   // borrowed
    RISE::Implementation::ViewportFrameStore*    m_fanoutVFS = nullptr;    // strong (addref'd in SetFanoutVFS)
    std::atomic<bool>                            m_suppressNext{false};
};

}  // anonymous namespace

void RiseBridge::buildViewportLivePreview() {
    if (!m_job) return;

    RISE::IRasterizer* interactive = nullptr;
    RISE::IRayCaster* pCaster = nullptr;
    RISE::IRayCaster* pPolishCaster = nullptr;
    if (!RISE::Implementation::CreateInteractiveMaterialPreviewPipeline(
            &interactive, &pCaster, &pPolishCaster)) {
        return;
    }

    m_viewportCaster = pCaster;
    m_viewportPolishCaster = pPolishCaster;
    m_viewportRasterizer = interactive;

    auto* sink = new ViewportPreviewSink(this);
    sink->addref();
    // L5a round-5 — fan the interactive sink's OutputImage into the
    // bridge's interactive VFS.  Mirrors macOS round-5 architecture:
    // production and interactive paths feed independent VFSes so
    // cancel preserves production output, no per-tile DrawToggles
    // flash on interactive, no preview-scale resolution thrash
    // interfering with production buffers.
    if (auto* iVFS = getOrCreateInteractiveVFS()) {
        sink->SetFanoutVFS(iVFS);
    }
    m_viewportSink = sink;
}

void RiseBridge::releaseViewportLivePreview() {
    if (m_viewportSink)         { m_viewportSink->release();      m_viewportSink = nullptr; }
    if (m_viewportRasterizer)   { m_viewportRasterizer->release(); m_viewportRasterizer = nullptr; }
    if (m_viewportPolishCaster) { m_viewportPolishCaster->release(); m_viewportPolishCaster = nullptr; }
    if (m_viewportCaster)       { m_viewportCaster->release();     m_viewportCaster = nullptr; }
}

bool RiseBridge::startViewport(bool suppressFirstFrame) {
    if (m_viewportController) return true;
    if (!m_job) return false;

    buildViewportLivePreview();

    if (!RISE::RISE_API_CreateSceneEditController(m_job, m_viewportRasterizer, &m_viewportController)) {
        m_viewportController = nullptr;
        releaseViewportLivePreview();
        return false;
    }
    if (m_viewportSink) {
        // The sink queries the controller's cancel state at end-of-pass
        // so it can drop a stale dispatch.  Wire the pointer before
        // installing the sink as a rasterizer output.  The downcast is
        // safe — m_viewportSink is only ever populated with a freshly
        // constructed ViewportPreviewSink in buildViewportLivePreview().
        auto* previewSink = static_cast<ViewportPreviewSink*>(m_viewportSink);
        previewSink->SetController(m_viewportController);

        // Latch the first-frame suppression BEFORE Start kicks the
        // render thread.  The Android sink is freshly constructed on
        // every start, so a follow-up SuppressNextFrame() from the UI
        // layer races the freshly-spawned worker pool — on a cheap
        // preview scene the first OutputImage call can fire before
        // the JNI hop returns.  Setting the flag inline here closes
        // that window: by the time Start signals the render thread,
        // the sink already knows to drop pass #1.
        if (suppressFirstFrame) {
            previewSink->SuppressNextFrame();
        }
        RISE::RISE_API_SceneEditController_SetPreviewSink(m_viewportController, m_viewportSink);
    }
    RISE::RISE_API_SceneEditController_Start(m_viewportController);
    m_viewportRunning = true;
    return true;
}

void RiseBridge::viewportSuppressNextFrame() {
    if (m_viewportSink) {
        static_cast<ViewportPreviewSink*>(m_viewportSink)->SuppressNextFrame();
    }
}

void RiseBridge::stopViewport() {
    if (!m_viewportController) return;
    RISE::RISE_API_SceneEditController_Stop(m_viewportController);
    m_viewportRunning = false;
    RISE::RISE_API_DestroySceneEditController(m_viewportController);
    m_viewportController = nullptr;
    releaseViewportLivePreview();
}

void RiseBridge::viewportSetTool(int t) {
    if (m_viewportController) RISE::RISE_API_SceneEditController_SetTool(m_viewportController, t);
}
void RiseBridge::viewportPointerDown(double x, double y) {
    if (m_viewportController) RISE::RISE_API_SceneEditController_OnPointerDown(m_viewportController, x, y);
}
void RiseBridge::viewportPointerMove(double x, double y) {
    if (m_viewportController) RISE::RISE_API_SceneEditController_OnPointerMove(m_viewportController, x, y);
}
void RiseBridge::viewportPointerUp(double x, double y) {
    if (m_viewportController) RISE::RISE_API_SceneEditController_OnPointerUp(m_viewportController, x, y);
}
void RiseBridge::viewportGetCameraDimensions(unsigned int& outW, unsigned int& outH) const {
    outW = 0;
    outH = 0;
    if (!m_viewportController) return;
    unsigned int w = 0, h = 0;
    if (RISE::RISE_API_SceneEditController_GetCameraDimensions(m_viewportController, &w, &h)) {
        outW = w;
        outH = h;
    }
}

bool RiseBridge::viewportGetAnimationOptions(double& outTimeStart, double& outTimeEnd,
                                             unsigned int& outNumFrames) const {
    outTimeStart = 0;
    outTimeEnd = 0;
    outNumFrames = 0;
    if (!m_viewportController) return false;
    return RISE::RISE_API_SceneEditController_GetAnimationOptions(
        m_viewportController, &outTimeStart, &outTimeEnd, &outNumFrames);
}
void RiseBridge::viewportScrubBegin() {
    if (m_viewportController) RISE::RISE_API_SceneEditController_OnTimeScrubBegin(m_viewportController);
}
void RiseBridge::viewportScrub(double t) {
    if (m_viewportController) RISE::RISE_API_SceneEditController_OnTimeScrub(m_viewportController, t);
}
void RiseBridge::viewportScrubEnd() {
    if (m_viewportController) RISE::RISE_API_SceneEditController_OnTimeScrubEnd(m_viewportController);
}
void RiseBridge::viewportBeginPropertyScrub() {
    if (m_viewportController) RISE::RISE_API_SceneEditController_BeginPropertyScrub(m_viewportController);
}
void RiseBridge::viewportEndPropertyScrub() {
    if (m_viewportController) RISE::RISE_API_SceneEditController_EndPropertyScrub(m_viewportController);
}
void RiseBridge::viewportUndo() {
    if (m_viewportController) RISE::RISE_API_SceneEditController_Undo(m_viewportController);
}
void RiseBridge::viewportRedo() {
    if (m_viewportController) RISE::RISE_API_SceneEditController_Redo(m_viewportController);
}
double RiseBridge::viewportLastSceneTime() const {
    if (!m_viewportController) return 0.0;
    double t = 0.0;
    RISE::RISE_API_SceneEditController_LastSceneTime(m_viewportController, &t);
    return t;
}
bool RiseBridge::viewportProductionRender() {
    if (!m_viewportController) return false;
    return RISE::RISE_API_SceneEditController_RequestProductionRender(m_viewportController);
}

void RiseBridge::viewportRefreshProperties() {
    if (m_viewportController) RISE::RISE_API_SceneEditController_RefreshProperties(m_viewportController);
}
int RiseBridge::viewportPanelMode() const {
    if (!m_viewportController) return 0;
    return RISE::RISE_API_SceneEditController_PanelMode(m_viewportController);
}
std::string RiseBridge::viewportPanelHeader() const {
    if (!m_viewportController) return {};
    char buf[256] = {0};
    RISE::RISE_API_SceneEditController_PanelHeader(m_viewportController, buf, sizeof(buf));
    return std::string(buf);
}
unsigned int RiseBridge::viewportPropertyCount() const {
    if (!m_viewportController) return 0;
    return RISE::RISE_API_SceneEditController_PropertyCount(m_viewportController);
}
std::string RiseBridge::viewportPropertyName(unsigned int idx) const {
    if (!m_viewportController) return {};
    char buf[128] = {0};
    RISE::RISE_API_SceneEditController_PropertyName(m_viewportController, idx, buf, sizeof(buf));
    return std::string(buf);
}
std::string RiseBridge::viewportPropertyValue(unsigned int idx) const {
    if (!m_viewportController) return {};
    char buf[256] = {0};
    RISE::RISE_API_SceneEditController_PropertyValue(m_viewportController, idx, buf, sizeof(buf));
    return std::string(buf);
}
std::string RiseBridge::viewportPropertyDescription(unsigned int idx) const {
    if (!m_viewportController) return {};
    char buf[512] = {0};
    RISE::RISE_API_SceneEditController_PropertyDescription(m_viewportController, idx, buf, sizeof(buf));
    return std::string(buf);
}
int RiseBridge::viewportPropertyKind(unsigned int idx) const {
    if (!m_viewportController) return -1;
    return RISE::RISE_API_SceneEditController_PropertyKind(m_viewportController, idx);
}
bool RiseBridge::viewportPropertyEditable(unsigned int idx) const {
    if (!m_viewportController) return false;
    return RISE::RISE_API_SceneEditController_PropertyEditable(m_viewportController, idx);
}
unsigned int RiseBridge::viewportPropertyPresetCount(unsigned int idx) const {
    if (!m_viewportController) return 0;
    return RISE::RISE_API_SceneEditController_PropertyPresetCount(m_viewportController, idx);
}
std::string RiseBridge::viewportPropertyPresetLabel(unsigned int idx, unsigned int presetIdx) const {
    if (!m_viewportController) return {};
    char buf[256] = {0};
    RISE::RISE_API_SceneEditController_PropertyPresetLabel(m_viewportController, idx, presetIdx, buf, sizeof(buf));
    return std::string(buf);
}
std::string RiseBridge::viewportPropertyPresetValue(unsigned int idx, unsigned int presetIdx) const {
    if (!m_viewportController) return {};
    char buf[256] = {0};
    RISE::RISE_API_SceneEditController_PropertyPresetValue(m_viewportController, idx, presetIdx, buf, sizeof(buf));
    return std::string(buf);
}
bool RiseBridge::viewportSetProperty(const std::string& name, const std::string& value) {
    if (!m_viewportController) return false;
    return RISE::RISE_API_SceneEditController_SetProperty(m_viewportController,
        name.c_str(), value.c_str());
}

unsigned int RiseBridge::viewportCategoryEntityCount(int category) const {
    if (!m_viewportController) return 0;
    return RISE::RISE_API_SceneEditController_CategoryEntityCount(m_viewportController, category);
}

std::string RiseBridge::viewportCategoryEntityName(int category, unsigned int idx) const {
    if (!m_viewportController) return {};
    char buf[128] = {0};
    if (!RISE::RISE_API_SceneEditController_CategoryEntityName(m_viewportController,
            category, idx, buf, sizeof(buf))) {
        return {};
    }
    return std::string(buf);
}

std::string RiseBridge::viewportCategoryActiveName(int category) const {
    if (!m_viewportController) return {};
    char buf[128] = {0};
    if (!RISE::RISE_API_SceneEditController_CategoryActiveName(m_viewportController,
            category, buf, sizeof(buf))) {
        return {};
    }
    return std::string(buf);
}

int RiseBridge::viewportSelectionCategory() const {
    if (!m_viewportController) return 0;
    const int c = RISE::RISE_API_SceneEditController_GetSelectionCategory(m_viewportController);
    return c < 0 ? 0 : c;
}

std::string RiseBridge::viewportSelectionName() const {
    if (!m_viewportController) return {};
    char buf[128] = {0};
    if (!RISE::RISE_API_SceneEditController_GetSelectionName(m_viewportController,
            buf, sizeof(buf))) {
        return {};
    }
    return std::string(buf);
}

bool RiseBridge::viewportSetSelection(int category, const std::string& name) {
    if (!m_viewportController) return false;
    return RISE::RISE_API_SceneEditController_SetSelection(m_viewportController,
        category, name.c_str());
}

unsigned int RiseBridge::viewportSceneEpoch() const {
    if (!m_viewportController) return 0;
    return RISE::RISE_API_SceneEditController_SceneEpoch(m_viewportController);
}

void RiseBridge::onViewportFramePainted() {
    // Not used in the current implementation — the sink already calls
    // writeDirtyRegion which fires onRegionInvalidated.  Reserved for
    // future use if we want a single bulk-invalidate signal.
}

} // namespace rise_jni
