#include "RiseBridge.h"
#include "RiseCallbacks.h"
#include "RiseLogPrinter.h"
#include "jni_util.h"

#include <android/log.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <cerrno>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>

// RISE library headers — included only in .cpp files so the .h stays thin.
#include "RISE_API.h"
#include "Interfaces/IJobPriv.h"
#include "Interfaces/IJob.h"
#include "Interfaces/IRasterizer.h"
#include "Interfaces/ILogPriv.h"
#include "Utilities/MediaPathLocator.h"

#define LOG_TAG "RISE-Bridge"
#define LOGI(...) __android_log_print(ANDROID_LOG_INFO,  LOG_TAG, __VA_ARGS__)
#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR, LOG_TAG, __VA_ARGS__)

namespace rise_jni {

RiseBridge& getBridge() {
    static RiseBridge instance;
    return instance;
}

RiseBridge::RiseBridge() = default;

RiseBridge::~RiseBridge() {
    teardownJob();
    {
        std::lock_guard<std::mutex> lock(m_fbMutex);
        std::free(m_framebuffer);
        m_framebuffer = nullptr;
    }
    if (m_kotlinCallback) {
        JNIEnv* env = getJniEnv();
        if (env) {
            env->DeleteGlobalRef(m_kotlinCallback);
        }
        m_kotlinCallback = nullptr;
    }
}

void RiseBridge::writeGlobalOptionsFile(const std::string& path, int threadCount) {
    // Minimal RISE options file format: "<key> <value>" per line. See
    // Options::Options() in src/Library/Options.cpp — it tokenizes and
    // stores the first two tokens as key/value.
    std::ofstream out(path.c_str(), std::ios::out | std::ios::trunc);
    if (!out.is_open()) {
        LOGE("writeGlobalOptionsFile: failed to open %s", path.c_str());
        return;
    }
    out << "# Generated by RISE Android bridge on initialize()\n";
    out << "force_number_of_threads " << threadCount << "\n";
    out << "support_hyperthreading false\n";
    out.close();
}

void RiseBridge::initialize(const std::string& projectRoot,
                            const std::string& logFile,
                            int                threadCount) {
    if (m_initialized) {
        LOGI("initialize: already initialized; updating options file only");
    }
    m_projectRoot = projectRoot;
    m_logFile     = logFile;
    m_threadCount = threadCount > 0 ? threadCount : 1;
    m_optionsFile = projectRoot + "/global.options";

    // Write the options file BEFORE any GlobalOptions() call. The library
    // caches the Options singleton on first access.
    writeGlobalOptionsFile(m_optionsFile, m_threadCount);

    // Point the library at our options file. setenv is POSIX so this works
    // under NDK. Must happen before the first GlobalOptions() call.
    ::setenv("RISE_OPTIONS_FILE", m_optionsFile.c_str(), 1);
    ::setenv("RISE_MEDIA_PATH",  projectRoot.c_str(),    1);

    // Redirect the logger BEFORE any Rasterize / LoadScene / Options access
    // so the file path is never stale.
    RISE::SetGlobalLogFileName(logFile.c_str());

    // Register the media path so scene files can resolve relative asset
    // paths like "textures/foo.png" against filesDir/rise/textures/foo.png.
    RISE::GlobalMediaPathLocator().AddPath(projectRoot.c_str());

    // Attach our logcat forwarder so RISE log output shows up in `adb logcat`.
    if (!m_logPrinter) {
        m_logPrinter = new LogPrinterImpl(this);
        RISE::GlobalLogPriv()->AddPrinter(m_logPrinter);
    }

    // Many bundled scenes use file_rasterizeroutput with a pattern like
    // "rendered/<name>". The library's FileRasterizerOutput does NOT create
    // the parent directory, so we pre-create the directories the bundled
    // scenes need. Harmless if they already exist.
    //
    // Add to this list whenever a new bundled scene writes to a nested
    // output pattern. Plain "rendered/<sceneName>" only needs the top-level
    // "rendered" directory to exist.
    static const char* kRenderedDirs[] = {
        "rendered",
        "rendered/teapot",   // teapot.RISEscene writes "rendered/teapot/frame"
    };
    for (const char* sub : kRenderedDirs) {
        const std::string dir = projectRoot + "/" + sub;
        if (::mkdir(dir.c_str(), 0755) != 0 && errno != EEXIST) {
            LOGI("mkdir %s (non-fatal): %s", dir.c_str(), std::strerror(errno));
        }
    }

    m_initialized = true;
    LOGI("RiseBridge initialized: root=%s log=%s threads=%d",
         projectRoot.c_str(), logFile.c_str(), m_threadCount);
}

void RiseBridge::setCallback(JNIEnv* env, jobject kotlinCallback) {
    if (!env) return;
    if (m_kotlinCallback) {
        env->DeleteGlobalRef(m_kotlinCallback);
        m_kotlinCallback = nullptr;
    }
    if (kotlinCallback) {
        m_kotlinCallback = env->NewGlobalRef(kotlinCallback);
    }
}

void RiseBridge::teardownJob() {
    if (m_job) {
        // RISE_CreateJobPriv returns a refcounted pointer; the safe cleanup
        // is to release the reference we hold. The library's Reference
        // implementation will delete the job when refcount hits zero.
        m_job->release();
        m_job = nullptr;
    }
}

bool RiseBridge::loadScene(const std::string& absPath) {
    if (!m_initialized) {
        LOGE("loadScene: bridge not initialized");
        return false;
    }
    m_cancel.store(false);
    teardownJob();

    // Lazily create the callback adapters. They hold a bare back-pointer to
    // the bridge and never outlive it (the bridge owns the unique_ptrs).
    if (!m_progress) m_progress.reset(newProgressCallback(this));
    if (!m_output)   m_output.reset(newRasterizerOutput(this));

    if (!RISE::RISE_CreateJobPriv(&m_job) || !m_job) {
        LOGE("loadScene: RISE_CreateJobPriv failed");
        return false;
    }

    // Progress callback must be attached BEFORE LoadAsciiScene — the parser
    // itself reports progress.
    m_job->SetProgress(m_progress.get());

    if (!m_job->LoadAsciiScene(absPath.c_str())) {
        LOGE("loadScene: LoadAsciiScene failed for %s", absPath.c_str());
        teardownJob();
        return false;
    }
    LOGI("loadScene: loaded %s", absPath.c_str());
    return true;
}

bool RiseBridge::rasterize() {
    if (!m_job) {
        LOGE("rasterize: no job loaded");
        return false;
    }

    m_cancel.store(false);

    // Mac bridge precedent: attach the output AFTER LoadAsciiScene — the
    // library wipes the rasterizer's output list during scene load.
    // Clear any prior outputs to avoid the leak bug in RISEBridge.mm.
    if (RISE::IRasterizer* raster = m_job->GetRasterizer()) {
        raster->FreeRasterizerOutputs();
    }
    if (!m_job->AddCallbackRasterizerOutput(m_output.get())) {
        LOGE("rasterize: AddCallbackRasterizerOutput failed");
        return false;
    }

    // BLOCKING. Library spawns its own pthread worker pool, dispatches tiles,
    // joins on completion. Tile callbacks fire from the workers; cancellation
    // is via the progress callback return value.
    const bool ok = m_job->Rasterize();
    LOGI("rasterize: returned %d", ok ? 1 : 0);
    return ok;
}

void RiseBridge::requestCancel() {
    m_cancel.store(true);
}

void RiseBridge::ensureFramebuffer(unsigned w, unsigned h) {
    bool fired = false;
    {
        std::lock_guard<std::mutex> lock(m_fbMutex);
        if (m_fbWidth == w && m_fbHeight == h && m_framebuffer) {
            return;
        }
        std::free(m_framebuffer);
        m_framebuffer = static_cast<uint8_t*>(std::calloc(static_cast<size_t>(w) * h * 4, 1));
        m_fbWidth  = w;
        m_fbHeight = h;
        fired = true;
    }
    if (fired && m_kotlinCallback) {
        JNIEnv* env = getJniEnv();
        if (env) {
            ScopedLocalFrame frame(env, 8);
            env->CallVoidMethod(m_kotlinCallback, g_cb.onSceneReady,
                                static_cast<jint>(w), static_cast<jint>(h));
            if (env->ExceptionCheck()) {
                env->ExceptionDescribe();
                env->ExceptionClear();
            }
        }
    }
}

void RiseBridge::writeDirtyRegion(const unsigned short* src16,
                                  unsigned w, unsigned h,
                                  unsigned top, unsigned left,
                                  unsigned bottom, unsigned right) {
    ensureFramebuffer(w, h);

    if (right < left || bottom < top) return;
    if (right >= w) right = w - 1;
    if (bottom >= h) bottom = h - 1;

    {
        std::lock_guard<std::mutex> lock(m_fbMutex);
        if (!m_framebuffer || m_fbWidth != w || m_fbHeight != h) return;

        // Source is RGBA16, packed. Destination is RGBA8. Simple >> 8
        // downconvert matches what Mac and Windows bridges do; the library's
        // GetColorSpace() returns sRGB so gamma is already applied.
        for (unsigned y = top; y <= bottom; ++y) {
            const unsigned short* srow = src16 + (static_cast<size_t>(y) * w + left) * 4;
            uint8_t*              drow = m_framebuffer + (static_cast<size_t>(y) * w + left) * 4;
            for (unsigned x = left; x <= right; ++x) {
                drow[0] = static_cast<uint8_t>(srow[0] >> 8);
                drow[1] = static_cast<uint8_t>(srow[1] >> 8);
                drow[2] = static_cast<uint8_t>(srow[2] >> 8);
                drow[3] = static_cast<uint8_t>(srow[3] >> 8);
                srow += 4;
                drow += 4;
            }
        }
    }

    if (m_kotlinCallback) {
        JNIEnv* env = getJniEnv();
        if (env) {
            ScopedLocalFrame frame(env, 4);
            env->CallVoidMethod(m_kotlinCallback, g_cb.onRegionInvalidated,
                                packRect(top, left, bottom, right));
            if (env->ExceptionCheck()) {
                env->ExceptionDescribe();
                env->ExceptionClear();
            }
        }
    }
}

bool RiseBridge::onProgressTick(double progress, double total) {
    if (m_cancel.load()) {
        return false;
    }
    {
        std::lock_guard<std::mutex> lock(m_etaMutex);
        m_eta.Update(progress, total);
    }
    if (m_kotlinCallback) {
        JNIEnv* env = getJniEnv();
        if (env) {
            ScopedLocalFrame frame(env, 4);
            const float p = (total > 0.0)
                ? static_cast<float>(progress / total)
                : 0.0f;
            env->CallVoidMethod(m_kotlinCallback, g_cb.onProgress, p);
            if (env->ExceptionCheck()) {
                env->ExceptionDescribe();
                env->ExceptionClear();
            }
        }
    }
    return true;
}

void RiseBridge::etaBegin() {
    std::lock_guard<std::mutex> lock(m_etaMutex);
    m_eta.Begin();
}

int64_t RiseBridge::etaElapsedMs() const {
    std::lock_guard<std::mutex> lock(m_etaMutex);
    return static_cast<int64_t>(m_eta.ElapsedSeconds() * 1000.0 + 0.5);
}

int64_t RiseBridge::etaRemainingMs() const {
    std::lock_guard<std::mutex> lock(m_etaMutex);
    double s = 0.0;
    if (!m_eta.RemainingSeconds(s)) return -1;
    if (s < 0.0) s = 0.0;
    return static_cast<int64_t>(s * 1000.0 + 0.5);
}

void RiseBridge::onLogLine(int level, const char* message) {
    if (!m_kotlinCallback || !message) return;
    JNIEnv* env = getJniEnv();
    if (!env) return;
    ScopedLocalFrame frame(env, 8);
    jstring jmsg = env->NewStringUTF(message);
    if (!jmsg) return;
    env->CallVoidMethod(m_kotlinCallback, g_cb.onLog, static_cast<jint>(level), jmsg);
    if (env->ExceptionCheck()) {
        env->ExceptionDescribe();
        env->ExceptionClear();
    }
}

jobject RiseBridge::getFramebufferByteBuffer(JNIEnv* env) const {
    std::lock_guard<std::mutex> lock(m_fbMutex);
    if (!env || !m_framebuffer || m_fbWidth == 0 || m_fbHeight == 0) {
        return nullptr;
    }
    const jlong size = static_cast<jlong>(m_fbWidth) * m_fbHeight * 4;
    return env->NewDirectByteBuffer(m_framebuffer, size);
}

} // namespace rise_jni
