#include "RiseBridge.h"
#include "RiseCallbacks.h"
#include "RiseLogPrinter.h"
#include "jni_util.h"

#include <android/log.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <cerrno>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>

// RISE library headers — included only in .cpp files so the .h stays thin.
#include "RISE_API.h"
#include "Interfaces/IJobPriv.h"
#include "Interfaces/IJob.h"
#include "Interfaces/IRasterizer.h"
#include "Interfaces/IRasterizerOutput.h"
#include "Interfaces/IRasterImage.h"
#include "Interfaces/IScene.h"
#include "Interfaces/ILogPriv.h"
#include "Utilities/MediaPathLocator.h"
#include "Utilities/Reference.h"
#include "SceneEditor/SceneEditController.h"
#include "Rendering/InteractivePelRasterizer.h"

#define LOG_TAG "RISE-Bridge"
#define LOGI(...) __android_log_print(ANDROID_LOG_INFO,  LOG_TAG, __VA_ARGS__)
#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR, LOG_TAG, __VA_ARGS__)

namespace rise_jni {

RiseBridge& getBridge() {
    static RiseBridge instance;
    return instance;
}

RiseBridge::RiseBridge() = default;

RiseBridge::~RiseBridge() {
    teardownJob();
    {
        std::lock_guard<std::mutex> lock(m_fbMutex);
        std::free(m_framebuffer);
        m_framebuffer = nullptr;
    }
    if (m_kotlinCallback) {
        JNIEnv* env = getJniEnv();
        if (env) {
            env->DeleteGlobalRef(m_kotlinCallback);
        }
        m_kotlinCallback = nullptr;
    }
}

void RiseBridge::writeGlobalOptionsFile(const std::string& path, int threadCount) {
    // Minimal RISE options file format: "<key> <value>" per line. See
    // Options::Options() in src/Library/Options.cpp — it tokenizes and
    // stores the first two tokens as key/value.
    std::ofstream out(path.c_str(), std::ios::out | std::ios::trunc);
    if (!out.is_open()) {
        LOGE("writeGlobalOptionsFile: failed to open %s", path.c_str());
        return;
    }
    out << "# Generated by RISE Android bridge on initialize()\n";
    out << "force_number_of_threads " << threadCount << "\n";
    out << "support_hyperthreading false\n";
    out.close();
}

void RiseBridge::initialize(const std::string& projectRoot,
                            const std::string& logFile,
                            int                threadCount) {
    if (m_initialized) {
        LOGI("initialize: already initialized; updating options file only");
    }
    m_projectRoot = projectRoot;
    m_logFile     = logFile;
    m_threadCount = threadCount > 0 ? threadCount : 1;
    m_optionsFile = projectRoot + "/global.options";

    // Write the options file BEFORE any GlobalOptions() call. The library
    // caches the Options singleton on first access.
    writeGlobalOptionsFile(m_optionsFile, m_threadCount);

    // Point the library at our options file. setenv is POSIX so this works
    // under NDK. Must happen before the first GlobalOptions() call.
    ::setenv("RISE_OPTIONS_FILE", m_optionsFile.c_str(), 1);
    ::setenv("RISE_MEDIA_PATH",  projectRoot.c_str(),    1);

    // Redirect the logger BEFORE any Rasterize / LoadScene / Options access
    // so the file path is never stale.
    RISE::SetGlobalLogFileName(logFile.c_str());

    // Register the media path so scene files can resolve relative asset
    // paths like "textures/foo.png" against filesDir/rise/textures/foo.png.
    RISE::GlobalMediaPathLocator().AddPath(projectRoot.c_str());

    // Attach our logcat forwarder so RISE log output shows up in `adb logcat`.
    if (!m_logPrinter) {
        m_logPrinter = new LogPrinterImpl(this);
        RISE::GlobalLogPriv()->AddPrinter(m_logPrinter);
    }

    // Many bundled scenes use file_rasterizeroutput with a pattern like
    // "rendered/<name>". The library's FileRasterizerOutput does NOT create
    // the parent directory, so we pre-create the directories the bundled
    // scenes need. Harmless if they already exist.
    //
    // Add to this list whenever a new bundled scene writes to a nested
    // output pattern. Plain "rendered/<sceneName>" only needs the top-level
    // "rendered" directory to exist.
    static const char* kRenderedDirs[] = {
        "rendered",
        "rendered/teapot",   // teapot.RISEscene writes "rendered/teapot/frame"
    };
    for (const char* sub : kRenderedDirs) {
        const std::string dir = projectRoot + "/" + sub;
        if (::mkdir(dir.c_str(), 0755) != 0 && errno != EEXIST) {
            LOGI("mkdir %s (non-fatal): %s", dir.c_str(), std::strerror(errno));
        }
    }

    m_initialized = true;
    LOGI("RiseBridge initialized: root=%s log=%s threads=%d",
         projectRoot.c_str(), logFile.c_str(), m_threadCount);
}

void RiseBridge::setCallback(JNIEnv* env, jobject kotlinCallback) {
    if (!env) return;
    if (m_kotlinCallback) {
        env->DeleteGlobalRef(m_kotlinCallback);
        m_kotlinCallback = nullptr;
    }
    if (kotlinCallback) {
        m_kotlinCallback = env->NewGlobalRef(kotlinCallback);
    }
}

void RiseBridge::teardownJob() {
    // Tear down viewport (which holds rasterizer/caster references back into
    // the job) BEFORE releasing the job itself.  Otherwise we'd leak.
    stopViewport();

    if (m_job) {
        // RISE_CreateJobPriv returns a refcounted pointer; the safe cleanup
        // is to release the reference we hold. The library's Reference
        // implementation will delete the job when refcount hits zero.
        m_job->release();
        m_job = nullptr;
    }
}

bool RiseBridge::loadScene(const std::string& absPath) {
    if (!m_initialized) {
        LOGE("loadScene: bridge not initialized");
        return false;
    }
    m_cancel.store(false);
    teardownJob();

    // Lazily create the callback adapters. They hold a bare back-pointer to
    // the bridge and never outlive it (the bridge owns the unique_ptrs).
    if (!m_progress) m_progress.reset(newProgressCallback(this));
    if (!m_output)   m_output.reset(newRasterizerOutput(this));

    if (!RISE::RISE_CreateJobPriv(&m_job) || !m_job) {
        LOGE("loadScene: RISE_CreateJobPriv failed");
        return false;
    }

    // Progress callback must be attached BEFORE LoadAsciiScene — the parser
    // itself reports progress.
    m_job->SetProgress(m_progress.get());

    if (!m_job->LoadAsciiScene(absPath.c_str())) {
        LOGE("loadScene: LoadAsciiScene failed for %s", absPath.c_str());
        teardownJob();
        return false;
    }
    LOGI("loadScene: loaded %s", absPath.c_str());
    return true;
}

bool RiseBridge::rasterize() {
    if (!m_job) {
        LOGE("rasterize: no job loaded");
        return false;
    }

    m_cancel.store(false);

    // Mac bridge precedent: attach the output AFTER LoadAsciiScene — the
    // library wipes the rasterizer's output list during scene load.
    // Clear any prior outputs to avoid the leak bug in RISEBridge.mm.
    if (RISE::IRasterizer* raster = m_job->GetRasterizer()) {
        raster->FreeRasterizerOutputs();
    }
    if (!m_job->AddCallbackRasterizerOutput(m_output.get())) {
        LOGE("rasterize: AddCallbackRasterizerOutput failed");
        return false;
    }

    // BLOCKING. Library spawns its own pthread worker pool, dispatches tiles,
    // joins on completion. Tile callbacks fire from the workers; cancellation
    // is via the progress callback return value.
    const bool ok = m_job->Rasterize();
    LOGI("rasterize: returned %d", ok ? 1 : 0);
    return ok;
}

void RiseBridge::requestCancel() {
    m_cancel.store(true);
}

bool RiseBridge::hasAnimatedObjects() const {
    if (!m_job) return false;
    return m_job->AreThereAnyKeyframedObjects();
}

void RiseBridge::setSceneTime(double t) {
    if (!m_job) return;
    RISE::IScenePriv* scene = m_job->GetScene();
    if (!scene) return;
    // Full SetSceneTime: advances the animator AND regenerates every
    // populated photon map at time `t`.  The interactive viewport's
    // scrub path calls SetSceneTimeForPreview (animator-only, no
    // photon regen) for responsiveness; this method runs the
    // expensive photon regen so the next production render gets
    // caustics consistent with the scrubbed scene state.
    scene->SetSceneTime(static_cast<RISE::Scalar>(t));
}

void RiseBridge::ensureFramebuffer(unsigned w, unsigned h) {
    bool fired = false;
    {
        std::lock_guard<std::mutex> lock(m_fbMutex);
        if (m_fbWidth == w && m_fbHeight == h && m_framebuffer) {
            return;
        }
        std::free(m_framebuffer);
        m_framebuffer = static_cast<uint8_t*>(std::calloc(static_cast<size_t>(w) * h * 4, 1));
        m_fbWidth  = w;
        m_fbHeight = h;
        fired = true;
    }
    if (fired && m_kotlinCallback) {
        JNIEnv* env = getJniEnv();
        if (env) {
            ScopedLocalFrame frame(env, 8);
            env->CallVoidMethod(m_kotlinCallback, g_cb.onSceneReady,
                                static_cast<jint>(w), static_cast<jint>(h));
            if (env->ExceptionCheck()) {
                env->ExceptionDescribe();
                env->ExceptionClear();
            }
        }
    }
}

void RiseBridge::writeDirtyRegion(const unsigned short* src16,
                                  unsigned w, unsigned h,
                                  unsigned top, unsigned left,
                                  unsigned bottom, unsigned right) {
    ensureFramebuffer(w, h);

    if (right < left || bottom < top) return;
    if (right >= w) right = w - 1;
    if (bottom >= h) bottom = h - 1;

    {
        std::lock_guard<std::mutex> lock(m_fbMutex);
        if (!m_framebuffer || m_fbWidth != w || m_fbHeight != h) return;

        // Source is RGBA16, packed. Destination is RGBA8. Simple >> 8
        // downconvert matches what Mac and Windows bridges do; the library's
        // GetColorSpace() returns sRGB so gamma is already applied.
        for (unsigned y = top; y <= bottom; ++y) {
            const unsigned short* srow = src16 + (static_cast<size_t>(y) * w + left) * 4;
            uint8_t*              drow = m_framebuffer + (static_cast<size_t>(y) * w + left) * 4;
            for (unsigned x = left; x <= right; ++x) {
                drow[0] = static_cast<uint8_t>(srow[0] >> 8);
                drow[1] = static_cast<uint8_t>(srow[1] >> 8);
                drow[2] = static_cast<uint8_t>(srow[2] >> 8);
                drow[3] = static_cast<uint8_t>(srow[3] >> 8);
                srow += 4;
                drow += 4;
            }
        }
    }

    if (m_kotlinCallback) {
        JNIEnv* env = getJniEnv();
        if (env) {
            ScopedLocalFrame frame(env, 4);
            env->CallVoidMethod(m_kotlinCallback, g_cb.onRegionInvalidated,
                                packRect(top, left, bottom, right));
            if (env->ExceptionCheck()) {
                env->ExceptionDescribe();
                env->ExceptionClear();
            }
        }
    }
}

bool RiseBridge::onProgressTick(double progress, double total) {
    if (m_cancel.load()) {
        return false;
    }
    {
        std::lock_guard<std::mutex> lock(m_etaMutex);
        m_eta.Update(progress, total);
    }
    if (m_kotlinCallback) {
        JNIEnv* env = getJniEnv();
        if (env) {
            ScopedLocalFrame frame(env, 4);
            const float p = (total > 0.0)
                ? static_cast<float>(progress / total)
                : 0.0f;
            env->CallVoidMethod(m_kotlinCallback, g_cb.onProgress, p);
            if (env->ExceptionCheck()) {
                env->ExceptionDescribe();
                env->ExceptionClear();
            }
        }
    }
    return true;
}

void RiseBridge::etaBegin() {
    std::lock_guard<std::mutex> lock(m_etaMutex);
    m_eta.Begin();
}

int64_t RiseBridge::etaElapsedMs() const {
    std::lock_guard<std::mutex> lock(m_etaMutex);
    return static_cast<int64_t>(m_eta.ElapsedSeconds() * 1000.0 + 0.5);
}

int64_t RiseBridge::etaRemainingMs() const {
    std::lock_guard<std::mutex> lock(m_etaMutex);
    double s = 0.0;
    if (!m_eta.RemainingSeconds(s)) return -1;
    if (s < 0.0) s = 0.0;
    return static_cast<int64_t>(s * 1000.0 + 0.5);
}

void RiseBridge::onLogLine(int level, const char* message) {
    if (!m_kotlinCallback || !message) return;
    JNIEnv* env = getJniEnv();
    if (!env) return;
    ScopedLocalFrame frame(env, 8);
    jstring jmsg = env->NewStringUTF(message);
    if (!jmsg) return;
    env->CallVoidMethod(m_kotlinCallback, g_cb.onLog, static_cast<jint>(level), jmsg);
    if (env->ExceptionCheck()) {
        env->ExceptionDescribe();
        env->ExceptionClear();
    }
}

jobject RiseBridge::getFramebufferByteBuffer(JNIEnv* env) const {
    std::lock_guard<std::mutex> lock(m_fbMutex);
    if (!env || !m_framebuffer || m_fbWidth == 0 || m_fbHeight == 0) {
        return nullptr;
    }
    const jlong size = static_cast<jlong>(m_fbWidth) * m_fbHeight * 4;
    return env->NewDirectByteBuffer(m_framebuffer, size);
}

// ===========================================================================
// Interactive viewport
// ===========================================================================

namespace {

// IRasterizerOutput that, on end-of-frame, blits the rendered image into
// RiseBridge's RGBA8 framebuffer and signals onRegionInvalidated for the
// whole image.  Reuses the existing Compose redraw path — production
// renders and viewport-preview renders both flow through the same
// framebuffer, so the UI doesn't need to know which one it's seeing.
//
// Two end-of-pass guards keep stale or undesirable buffers off the
// screen (mirroring the macOS / Windows sinks):
//   * Cancel guard: the rasterizer's FlushToOutputs fires
//     unconditionally even when the dispatcher returned early for a
//     cancel.  Without this check, every cancel-restart would flash a
//     partially-rendered (mostly-black) buffer before the next pass.
//   * Suppress-next: drops exactly one upcoming dispatch.  Used right
//     after a production render returns so the production image stays
//     on screen until the user actually starts interacting.
class ViewportPreviewSink : public RISE::IRasterizerOutput,
                            public RISE::Implementation::Reference {
public:
    explicit ViewportPreviewSink(RiseBridge* b) : m_bridge(b) {}
    ~ViewportPreviewSink() override = default;

    // Borrowed; the bridge keeps the controller alive for the sink's
    // lifetime.  Used to query IsCancelRequested at end-of-pass.
    void SetController(RISE::SceneEditController* c) { m_controller = c; }

    // Drop the very next OutputImage call.  Auto-clears after one drop.
    void SuppressNextFrame() { m_suppressNext.store(true); }

    // Per-tile callback fires many times per render — explicitly ignore
    // (matches the macOS / Windows policy: avoid distracting tile fills).
    void OutputIntermediateImage(const RISE::IRasterImage& /*pImage*/,
                                 const RISE::Rect* /*pRegion*/) override {}

    // Every dispatch reaches the screen.  We do NOT drop cancelled-
    // mid-pass frames: during fast manipulation the cancel flag trips
    // on every pointer move, and dropping the resulting partial
    // buffers makes the viewport feel throttled (the user only sees
    // post-pause refinement frames).  Center-out tile order keeps
    // partial buffers visually usable.  The one-shot suppress is kept
    // for the post-production case.
    void OutputImage(const RISE::IRasterImage& pImage,
                     const RISE::Rect* /*pRegion*/,
                     const unsigned int /*frame*/) override {
        if (!m_bridge) return;
        if (m_suppressNext.exchange(false)) {
            // One-shot suppression (post-production) — skip exactly
            // this dispatch.  The next render's frame goes through.
            return;
        }
        const unsigned int W = pImage.GetWidth();
        const unsigned int H = pImage.GetHeight();
        if (W == 0 || H == 0) return;

        // Reuse the bridge's framebuffer: ensure it's allocated for these
        // dimensions, then blit pixel by pixel.
        m_bridge->ensureFramebuffer(W, H);

        // Read into a temporary RGBA16 then call writeDirtyRegion which
        // already handles RGBA16 → RGBA8 conversion + Kotlin notification.
        // This keeps a single conversion + notification path for both
        // production and viewport renders.
        std::vector<unsigned short> rgba16;
        rgba16.resize(static_cast<size_t>(W) * H * 4);
        for (unsigned int y = 0; y < H; ++y) {
            unsigned short* row = &rgba16[static_cast<size_t>(y) * W * 4];
            for (unsigned int x = 0; x < W; ++x) {
                RISE::RISEColor c = pImage.GetPEL(x, y);
                auto clamp16 = [](double v) -> unsigned short {
                    if (v <= 0.0) return 0;
                    if (v >= 1.0) return 65535;
                    return static_cast<unsigned short>(v * 65535.0 + 0.5);
                };
                *row++ = clamp16(c.base.r);
                *row++ = clamp16(c.base.g);
                *row++ = clamp16(c.base.b);
                *row++ = 65535;
            }
        }
        m_bridge->writeDirtyRegion(rgba16.data(), W, H, 0, 0, H - 1, W - 1);
    }

private:
    RiseBridge*                m_bridge = nullptr;
    RISE::SceneEditController* m_controller = nullptr;   // borrowed
    std::atomic<bool>          m_suppressNext{false};
};

}  // anonymous namespace

void RiseBridge::buildViewportLivePreview() {
    if (!m_job) return;

    RISE::IRasterizer* interactive = nullptr;
    RISE::IRayCaster* pCaster = nullptr;
    RISE::IRayCaster* pPolishCaster = nullptr;
    if (!RISE::Implementation::CreateInteractiveMaterialPreviewPipeline(
            &interactive, &pCaster, &pPolishCaster)) {
        return;
    }

    m_viewportCaster = pCaster;
    m_viewportPolishCaster = pPolishCaster;
    m_viewportRasterizer = interactive;

    auto* sink = new ViewportPreviewSink(this);
    sink->addref();
    m_viewportSink = sink;
}

void RiseBridge::releaseViewportLivePreview() {
    if (m_viewportSink)         { m_viewportSink->release();      m_viewportSink = nullptr; }
    if (m_viewportRasterizer)   { m_viewportRasterizer->release(); m_viewportRasterizer = nullptr; }
    if (m_viewportPolishCaster) { m_viewportPolishCaster->release(); m_viewportPolishCaster = nullptr; }
    if (m_viewportCaster)       { m_viewportCaster->release();     m_viewportCaster = nullptr; }
}

bool RiseBridge::startViewport(bool suppressFirstFrame) {
    if (m_viewportController) return true;
    if (!m_job) return false;

    buildViewportLivePreview();

    if (!RISE::RISE_API_CreateSceneEditController(m_job, m_viewportRasterizer, &m_viewportController)) {
        m_viewportController = nullptr;
        releaseViewportLivePreview();
        return false;
    }
    if (m_viewportSink) {
        // The sink queries the controller's cancel state at end-of-pass
        // so it can drop a stale dispatch.  Wire the pointer before
        // installing the sink as a rasterizer output.  The downcast is
        // safe — m_viewportSink is only ever populated with a freshly
        // constructed ViewportPreviewSink in buildViewportLivePreview().
        auto* previewSink = static_cast<ViewportPreviewSink*>(m_viewportSink);
        previewSink->SetController(m_viewportController);

        // Latch the first-frame suppression BEFORE Start kicks the
        // render thread.  The Android sink is freshly constructed on
        // every start, so a follow-up SuppressNextFrame() from the UI
        // layer races the freshly-spawned worker pool — on a cheap
        // preview scene the first OutputImage call can fire before
        // the JNI hop returns.  Setting the flag inline here closes
        // that window: by the time Start signals the render thread,
        // the sink already knows to drop pass #1.
        if (suppressFirstFrame) {
            previewSink->SuppressNextFrame();
        }
        RISE::RISE_API_SceneEditController_SetPreviewSink(m_viewportController, m_viewportSink);
    }
    RISE::RISE_API_SceneEditController_Start(m_viewportController);
    m_viewportRunning = true;
    return true;
}

void RiseBridge::viewportSuppressNextFrame() {
    if (m_viewportSink) {
        static_cast<ViewportPreviewSink*>(m_viewportSink)->SuppressNextFrame();
    }
}

void RiseBridge::stopViewport() {
    if (!m_viewportController) return;
    RISE::RISE_API_SceneEditController_Stop(m_viewportController);
    m_viewportRunning = false;
    RISE::RISE_API_DestroySceneEditController(m_viewportController);
    m_viewportController = nullptr;
    releaseViewportLivePreview();
}

void RiseBridge::viewportSetTool(int t) {
    if (m_viewportController) RISE::RISE_API_SceneEditController_SetTool(m_viewportController, t);
}
void RiseBridge::viewportPointerDown(double x, double y) {
    if (m_viewportController) RISE::RISE_API_SceneEditController_OnPointerDown(m_viewportController, x, y);
}
void RiseBridge::viewportPointerMove(double x, double y) {
    if (m_viewportController) RISE::RISE_API_SceneEditController_OnPointerMove(m_viewportController, x, y);
}
void RiseBridge::viewportPointerUp(double x, double y) {
    if (m_viewportController) RISE::RISE_API_SceneEditController_OnPointerUp(m_viewportController, x, y);
}
void RiseBridge::viewportGetCameraDimensions(unsigned int& outW, unsigned int& outH) const {
    outW = 0;
    outH = 0;
    if (!m_viewportController) return;
    unsigned int w = 0, h = 0;
    if (RISE::RISE_API_SceneEditController_GetCameraDimensions(m_viewportController, &w, &h)) {
        outW = w;
        outH = h;
    }
}

bool RiseBridge::viewportGetAnimationOptions(double& outTimeStart, double& outTimeEnd,
                                             unsigned int& outNumFrames) const {
    outTimeStart = 0;
    outTimeEnd = 0;
    outNumFrames = 0;
    if (!m_viewportController) return false;
    return RISE::RISE_API_SceneEditController_GetAnimationOptions(
        m_viewportController, &outTimeStart, &outTimeEnd, &outNumFrames);
}
void RiseBridge::viewportScrubBegin() {
    if (m_viewportController) RISE::RISE_API_SceneEditController_OnTimeScrubBegin(m_viewportController);
}
void RiseBridge::viewportScrub(double t) {
    if (m_viewportController) RISE::RISE_API_SceneEditController_OnTimeScrub(m_viewportController, t);
}
void RiseBridge::viewportScrubEnd() {
    if (m_viewportController) RISE::RISE_API_SceneEditController_OnTimeScrubEnd(m_viewportController);
}
void RiseBridge::viewportBeginPropertyScrub() {
    if (m_viewportController) RISE::RISE_API_SceneEditController_BeginPropertyScrub(m_viewportController);
}
void RiseBridge::viewportEndPropertyScrub() {
    if (m_viewportController) RISE::RISE_API_SceneEditController_EndPropertyScrub(m_viewportController);
}
void RiseBridge::viewportUndo() {
    if (m_viewportController) RISE::RISE_API_SceneEditController_Undo(m_viewportController);
}
void RiseBridge::viewportRedo() {
    if (m_viewportController) RISE::RISE_API_SceneEditController_Redo(m_viewportController);
}
double RiseBridge::viewportLastSceneTime() const {
    if (!m_viewportController) return 0.0;
    double t = 0.0;
    RISE::RISE_API_SceneEditController_LastSceneTime(m_viewportController, &t);
    return t;
}
bool RiseBridge::viewportProductionRender() {
    if (!m_viewportController) return false;
    return RISE::RISE_API_SceneEditController_RequestProductionRender(m_viewportController);
}

void RiseBridge::viewportRefreshProperties() {
    if (m_viewportController) RISE::RISE_API_SceneEditController_RefreshProperties(m_viewportController);
}
int RiseBridge::viewportPanelMode() const {
    if (!m_viewportController) return 0;
    return RISE::RISE_API_SceneEditController_PanelMode(m_viewportController);
}
std::string RiseBridge::viewportPanelHeader() const {
    if (!m_viewportController) return {};
    char buf[256] = {0};
    RISE::RISE_API_SceneEditController_PanelHeader(m_viewportController, buf, sizeof(buf));
    return std::string(buf);
}
unsigned int RiseBridge::viewportPropertyCount() const {
    if (!m_viewportController) return 0;
    return RISE::RISE_API_SceneEditController_PropertyCount(m_viewportController);
}
std::string RiseBridge::viewportPropertyName(unsigned int idx) const {
    if (!m_viewportController) return {};
    char buf[128] = {0};
    RISE::RISE_API_SceneEditController_PropertyName(m_viewportController, idx, buf, sizeof(buf));
    return std::string(buf);
}
std::string RiseBridge::viewportPropertyValue(unsigned int idx) const {
    if (!m_viewportController) return {};
    char buf[256] = {0};
    RISE::RISE_API_SceneEditController_PropertyValue(m_viewportController, idx, buf, sizeof(buf));
    return std::string(buf);
}
std::string RiseBridge::viewportPropertyDescription(unsigned int idx) const {
    if (!m_viewportController) return {};
    char buf[512] = {0};
    RISE::RISE_API_SceneEditController_PropertyDescription(m_viewportController, idx, buf, sizeof(buf));
    return std::string(buf);
}
int RiseBridge::viewportPropertyKind(unsigned int idx) const {
    if (!m_viewportController) return -1;
    return RISE::RISE_API_SceneEditController_PropertyKind(m_viewportController, idx);
}
bool RiseBridge::viewportPropertyEditable(unsigned int idx) const {
    if (!m_viewportController) return false;
    return RISE::RISE_API_SceneEditController_PropertyEditable(m_viewportController, idx);
}
unsigned int RiseBridge::viewportPropertyPresetCount(unsigned int idx) const {
    if (!m_viewportController) return 0;
    return RISE::RISE_API_SceneEditController_PropertyPresetCount(m_viewportController, idx);
}
std::string RiseBridge::viewportPropertyPresetLabel(unsigned int idx, unsigned int presetIdx) const {
    if (!m_viewportController) return {};
    char buf[256] = {0};
    RISE::RISE_API_SceneEditController_PropertyPresetLabel(m_viewportController, idx, presetIdx, buf, sizeof(buf));
    return std::string(buf);
}
std::string RiseBridge::viewportPropertyPresetValue(unsigned int idx, unsigned int presetIdx) const {
    if (!m_viewportController) return {};
    char buf[256] = {0};
    RISE::RISE_API_SceneEditController_PropertyPresetValue(m_viewportController, idx, presetIdx, buf, sizeof(buf));
    return std::string(buf);
}
bool RiseBridge::viewportSetProperty(const std::string& name, const std::string& value) {
    if (!m_viewportController) return false;
    return RISE::RISE_API_SceneEditController_SetProperty(m_viewportController,
        name.c_str(), value.c_str());
}

void RiseBridge::onViewportFramePainted() {
    // Not used in the current implementation — the sink already calls
    // writeDirtyRegion which fires onRegionInvalidated.  Reserved for
    // future use if we want a single bulk-invalidate signal.
}

} // namespace rise_jni
