// GENERATED by tools/generate_fire_production_fp64_mirror.py.
// Do not edit; run the generator and commit its deterministic output.
//////////////////////////////////////////////////////////////////////
//
//  FireProductionForce.h - strict-binary32 production force primitives
//
//  License Information: Please see the attached LICENSE.TXT file
//
//////////////////////////////////////////////////////////////////////

#ifndef FP64_FIRE_PRODUCTION_FORCE_H
#define FP64_FIRE_PRODUCTION_FORCE_H

#include "FireProductionProjection.h"
#include "FireProductionTransport.h"
#include "../../src/Library/Utilities/FireSimulationRecords.h"

#include <array>
#include <cstdint>
#include <string>
#include <vector>

namespace RISEFireProductionFP64
{
	struct FireProductionVremanInput
	{
		std::array<double,9> velocityGradientPerS;
		std::array<double,3> directionalWidthsM;
		double coefficient;

		FireProductionVremanInput() : coefficient(0.07)
		{
			velocityGradientPerS.fill(0.0);
			directionalWidthsM.fill(1.0);
		}
	};

	//! Strict-binary32 transcription of the record Vreman expression. The
	//! caller supplies the coefficient obtained from the certified record.
	bool EvaluateFireProductionVremanEddyViscosity(
		const FireProductionVremanInput& input,
		double& eddyViscosityM2PerS,
		std::string* error=0 );

	struct FireProductionViscousSchedule
	{
		std::uint32_t substepCount;
		double substepTimeS;
		double outwardWork;
		double representedProductUpper;

		FireProductionViscousSchedule() : substepCount(0u),substepTimeS(0.0),
			outwardWork(0.0),representedProductUpper(0.0) {}
	};

	//! Host half of the r90/r91 outward stability certificate. Both inputs are
	//! stored fp32 bytes; selection certifies the represented fp32 dt/N and
	//! rejects a required ninth substep before any physical update.
	bool SelectFireProductionViscousSchedule(
		double timeStepS,
		double outwardLambdaPerS,
		FireProductionViscousSchedule& schedule,
		std::string* error=0 );

	struct FireProductionFrozenForceRequest
	{
		FireProductionProjectionShape shape;
		double timeStepS;
		double ambientDensityKGPerM3;
		double vremanCoefficient;
		std::array<double,3> gravityMPerS2;
		std::array<FireProductionProjectionBoundary,6> boundary;
		std::vector<double> cellGasDensityKGPerM3;
		std::vector<double> molecularKinematicViscosityM2PerS;
		std::array<std::vector<double>,3> faceDensityKGPerM3;
		std::array<std::vector<double>,3> beginningMomentumKGPerM2S;

		FireProductionFrozenForceRequest() : timeStepS(0.0),ambientDensityKGPerM3(1.0),
			vremanCoefficient(0.07)
		{
			gravityMPerS2.fill(0.0);
			boundary.fill(FireProductionProjectionPeriodic);
		}
	};

	struct FireProductionFrozenForceResult
	{
		std::vector<double> eddyKinematicViscosityM2PerS;
		std::vector<double> effectiveDynamicViscosityPaS;
		std::array<std::vector<double>,3> beginningViscousMomentumRateKGPerM2S2;
		std::array<std::vector<double>,3> gravityMomentumIncrementKGPerM2S;
	};

	//! Logical peak of the CPU frozen-force comparator, including caller input,
	//! local work, and the atomically published result payload.
	bool FireProductionFrozenForceWorkingSetBytes(
		const FireProductionProjectionShape& shape,
		std::uint64_t& bytes );

	//! Complete standalone Metal-wrapper peak: live caller/result arrays plus
	//! every MTLBuffer rounded outward to the M4 allocation quantum.
	bool FireProductionFrozenForceMetalWorkingSetBytes(
		const FireProductionProjectionShape& shape,
		std::uint64_t& bytes );

	bool FireProductionResidentForceMetalWorkingSetBytes(
		const FireProductionProjectionShape& shape,
		bool captureIntermediateStates,
		std::uint64_t& bytes );

	//! Conservative force-owned plus resident-P2 peak, including the two target
	//! buffers retained by the composed owner. Used before any Metal allocation.
	bool FireProductionResidentForceProjectionWorkingSetBytes(
		const FireProductionProjectionShape& shape,
		std::uint64_t& bytes );

	bool FireProductionFrozenForceAdvanceWorkingSetBytes(
		const FireProductionProjectionShape& shape,
		std::uint64_t& bytes );

	//! Complete full resident-step certificate. This query is shape/boundary
	//! only so the owner can reject the two-GiB limit before inspecting payloads.
	bool FireProductionResidentStepWorkingSetBytes(
		const FireProductionProjectionShape& shape,
		const std::array<FireProductionProjectionBoundary,6>& boundary,
		std::uint64_t& bytes );

	//! Allocation-free structural and payload preflight shared by every frozen-
	//! force owner. It performs no physical work and publishes no partial state.
	bool ValidateFireProductionFrozenForceRequest(
		const FireProductionFrozenForceRequest& request,
		std::string* error=0 );

	//! Beginning-state, strict-binary32 force field used by the production P3
	//! comparator. Vreman and mu are frozen; viscous rates update only interior
	//! normal faces, relative gravity also owns pressure-open endpoint faces,
	//! and wall-normal endpoints remain prescribed zero.
	bool BuildFireProductionFrozenForceFieldsCPU(
		const FireProductionFrozenForceRequest& request,
		FireProductionFrozenForceResult& result,
		std::string* error=0 );

	//! Standalone Metal comparison wrapper for the same beginning-state frozen
	//! fields. Platforms without Metal fail honestly; no CPU fallback is hidden
	//! behind this entry point. The later resident P3 seam reuses these kernels.
	bool BuildFireProductionFrozenForceFieldsMetal(
		const FireProductionFrozenForceRequest& request,
		FireProductionFrozenForceResult& result,
		double& deviceElapsedMS,
		std::string* error=0 );

	struct FireProductionFrozenForceAdvanceResult
	{
		FireProductionFrozenForceResult frozenFields;
		FireProductionViscousSchedule schedule;
		std::array<std::vector<double>,3> momentumKGPerM2S;
		std::array<std::uint64_t,8> intermediateMomentumByteDigests;
		std::uint32_t intermediateMomentumDigestCount;
		std::uint32_t executedViscousSubstepCount;

		FireProductionFrozenForceAdvanceResult() :
			intermediateMomentumDigestCount(0u),executedViscousSubstepCount(0u)
		{
			intermediateMomentumByteDigests.fill(0u);
		}
	};

	//! Strict-binary32 force comparator after the resident preflight has supplied
	//! its outward Lambda scalar. mu_eff and face density stay frozen through all
	//! viscous substeps; relative gravity is added exactly once afterward.
	bool AdvanceFireProductionFrozenForceCPU(
		const FireProductionFrozenForceRequest& request,
		double outwardLambdaPerS,
		FireProductionFrozenForceAdvanceResult& result,
		std::string* error=0 );

	struct FireProductionResidentForceDiagnostics
	{
		double outwardLambdaPerS;
		std::uint32_t scalarDiagnosticTransferCount;
		std::uint32_t substepLoopDeviceToHostTransferCount;
		std::uint32_t terminalStagingCount;
		std::uint32_t commandCommitCount;
		std::uint64_t certifiedWorkingSetBytes;
		std::uint64_t actualMetalAllocationBytes;
		double preflightDeviceElapsedMS;
		double advanceDeviceElapsedMS;

		FireProductionResidentForceDiagnostics() : outwardLambdaPerS(0.0),
			scalarDiagnosticTransferCount(0u),substepLoopDeviceToHostTransferCount(0u),
			terminalStagingCount(0u),commandCommitCount(0u),certifiedWorkingSetBytes(0u),
			actualMetalAllocationBytes(0u),preflightDeviceElapsedMS(0.0),
			advanceDeviceElapsedMS(0.0) {}
	};

	//! Standalone oracle wrapper around the resident force sequence. Full-grid
	//! resources remain Private through every viscous substep and the gravity
	//! update. Optional Private snapshots stage only after command completion.
	bool AdvanceFireProductionFrozenForceMetal(
		const FireProductionFrozenForceRequest& request,
		bool captureIntermediateStates,
		FireProductionFrozenForceAdvanceResult& result,
		FireProductionResidentForceDiagnostics& diagnostics,
		std::string* error=0 );

	//! Oracle wrapper for the no-staging resident-state branch. It performs one
	//! terminal momentum tap after the resident call and leaves the force
	//! diagnostics' terminal-staging count at zero for that measured interval.
	bool AdvanceFireProductionFrozenForceMetalResidentStateComparator(
		const FireProductionFrozenForceRequest& request,
		FireProductionFrozenForceAdvanceResult& result,
		FireProductionResidentForceDiagnostics& diagnostics,
		std::string* error=0 );

#if defined(__OBJC__) && defined(__APPLE__)
	struct FireProductionMetalFrozenForceResidentState
	{
		id<MTLBuffer> cellGasDensityKGPerM3;
		id<MTLBuffer> packedFaceDensityKGPerM3;
		id<MTLBuffer> packedMomentumKGPerM2S;
		std::array<std::size_t,3> faceByteOffset;
		FireProductionViscousSchedule schedule;
		FireProductionResidentForceDiagnostics diagnostics;

		FireProductionMetalFrozenForceResidentState() : cellGasDensityKGPerM3(nil),
			packedFaceDensityKGPerM3(nil),packedMomentumKGPerM2S(nil)
		{
			faceByteOffset.fill(0u);
		}
	};

	//! Internal full-grid Private state seam. It executes preflight, every
	//! selected viscous substep, and gravity, then returns the still-resident
	//! density/momentum owners without terminal staging or projection.
	bool AdvanceFireProductionFrozenForceMetalResidentState(
		const FireProductionFrozenForceRequest& request,
		FireProductionMetalFrozenForceResidentState& state,
		std::string* error=0 );
#endif

	struct FireProductionResidentForceProjectionResult
	{
		FireProductionViscousSchedule forceSchedule;
		FireProductionProjectionResult projection;
		FireProductionResidentForceDiagnostics forceDiagnostics;
		std::uint32_t forceToProjectionDeviceToHostTransferCount;
		std::uint32_t residentProjectionInvocationCount;
		std::uint64_t combinedCertifiedWorkingSetBytes;
		std::uint64_t combinedActualMetalAllocationBytes;

		FireProductionResidentForceProjectionResult() :
			forceToProjectionDeviceToHostTransferCount(0u),residentProjectionInvocationCount(0u),
			combinedCertifiedWorkingSetBytes(0u),combinedActualMetalAllocationBytes(0u) {}
	};

	//! Resident production seam: frozen force substeps, gravity, and exactly one
	//! P2 projection without a full-grid host transfer between the operators.
	bool AdvanceFireProductionForceProjectionMetal(
		const FireProductionFrozenForceRequest& forceRequest,
		const std::vector<double>& divergenceTargetPerS,
		FireProductionResidentForceProjectionResult& result,
		std::string* error=0 );

	struct FireProductionResidentStepRequest
	{
		FireProductionFrozenForceRequest force;
		FireProductionCellPalindromeRequest cellTransport;
		FireProductionDualMomentumRequest dualTransport;
		std::vector<double> cellSourceIncrement;
		std::array<std::vector<double>,3> momentumSourceIncrement;
		std::vector<double> divergenceTargetPerS;
		std::vector<double> restorationDivergenceTargetPerS;
	};

	struct FireProductionResidentStepResult
	{
		std::vector<double> conservativeValues;
		FireProductionDualMomentumResult transportedDual;
		FireProductionProjectionResult physicalProjection;
		FireProductionProjectionResult projection;
		FireProductionViscousSchedule forceSchedule;
		FireProductionResidentForceDiagnostics forceDiagnostics;
		std::uint32_t cellSubmapCount;
		std::uint32_t dualSubmapCount;
		std::uint32_t sourceCommandCommitCount;
		std::uint32_t residentProjectionInvocationCount;
		std::uint32_t interstageFullGridTransferCount;
		std::uint32_t terminalStagingCount;
		std::uint64_t combinedCertifiedWorkingSetBytes;
		std::uint64_t combinedActualMetalAllocationBytes;
		double deviceElapsedMS;
		RISE::FireStateProducerPrecision conservativeProducerPrecision;

		FireProductionResidentStepResult() : cellSubmapCount(0u),dualSubmapCount(0u),
			sourceCommandCommitCount(0u),residentProjectionInvocationCount(0u),
			interstageFullGridTransferCount(0u),terminalStagingCount(0u),
			combinedCertifiedWorkingSetBytes(0u),combinedActualMetalAllocationBytes(0u),
			deviceElapsedMS(0.0),
			conservativeProducerPrecision(RISE::FireStateProducerPrecision::Unknown) {}
	};

	//! Full resident P3 shadow step: frozen force, cell and dual transport,
	//! explicit source operands, one physical P2 projection, and one deadbeat
	//! manifold-restoration projection. Full-grid host access is limited to the
	//! terminal step-boundary oracle tap after restoration.
	bool AdvanceFireProductionResidentStepMetal(
		const FireProductionResidentStepRequest& request,
		FireProductionResidentStepResult& result,
		std::string* error=0 );

	//! Thread-local observed Metal commits, exposed only to bind fail-before-work
	//! owner gates. Unsupported builds return zero.
	std::uint64_t FireProductionResidentStepMetalCommandCommitCount();
}

#endif
