// GENERATED by tools/generate_fire_production_fp64_mirror.py.
// Do not edit; run the generator and commit its deterministic output.
//////////////////////////////////////////////////////////////////////
//
//  FireProductionForce.cpp - strict-binary32 production force primitives
//
//  License Information: Please see the attached LICENSE.TXT file
//
//////////////////////////////////////////////////////////////////////

#include "FireProductionForce.h"

#include <algorithm>
#include <cmath>
#include <cstring>
#include <limits>
#include <new>
#include <utility>

namespace RISEFireProductionFP64
{
	namespace
	{
		constexpr double ManifoldEOSCeiling=0.001;
		constexpr double ManifoldHeadroom=0.25;
		bool Fail( std::string* error, const char* message ) noexcept
		{
			if( error ) try { *error=message; } catch( const std::bad_alloc& ) {}
			return false;
		}

		std::size_t CellIndex( const FireProductionProjectionShape& shape,
			std::size_t x, std::size_t y, std::size_t z )
		{
			return (z*shape.ny+y)*shape.nx+x;
		}

		std::size_t FaceIndex( const FireProductionProjectionShape& shape,
			unsigned int axis, std::size_t x, std::size_t y, std::size_t z )
		{
			if( axis==0u ) return (z*shape.ny+y)*(shape.nx+1u)+x;
			if( axis==1u ) return (z*(shape.ny+1u)+y)*shape.nx+x;
			return (z*shape.ny+y)*shape.nx+x;
		}

		std::size_t AxisExtent( const FireProductionProjectionShape& shape,
			unsigned int axis )
		{
			return axis==0u?shape.nx:(axis==1u?shape.ny:shape.nz);
		}

		bool SameFloatBytes( double first, double second )
		{
			return std::memcmp(&first,&second,sizeof(double))==0;
		}

		std::uint64_t MomentumByteDigest(
			const std::array<std::vector<double>,3>& momentum )
		{
			// FNV-1a over explicitly little-endian binary64 words. This is a fixed,
			// allocation-free diagnostic topology, not a record identity hash.
			std::uint64_t digest=UINT64_C(14695981039346656037);
			for( unsigned int axis=0u;axis<3u;++axis ) for( const double value : momentum[axis] ) {
				std::uint64_t bits=0u;
				std::memcpy(&bits,&value,sizeof(bits));
				for( unsigned int byte=0u;byte<8u;++byte ) {
					digest^=static_cast<unsigned char>(bits>>(8u*byte));
					digest*=UINT64_C(1099511628211);
				}
			}
			return digest;
		}
	}

	bool SelectFireProductionStableTimeStep(
		const double cellWidthM,
		const double maximumVelocityMPerS,
		const double maximumPositiveReducedGravityMPerS2,
		const double maximumKinematicTransportM2PerS,
		const double previousStepS,
		const FireProductionAcceptedManifoldObservation& previousManifold,
		FireProductionStableTimeStep& result,
		std::string* error )
	{
		result=FireProductionStableTimeStep();
		if( !std::isfinite(cellWidthM)||cellWidthM<=0.0||
			!std::isfinite(maximumVelocityMPerS)||maximumVelocityMPerS<0.0||
			!std::isfinite(maximumPositiveReducedGravityMPerS2)||
			maximumPositiveReducedGravityMPerS2<0.0||
			!std::isfinite(maximumKinematicTransportM2PerS)||
			maximumKinematicTransportM2PerS<0.0||!std::isfinite(previousStepS)||
			previousStepS<0.0 ) return Fail(error,"production timestep inputs are invalid");
		if( previousManifold.available_ ) {
			if( previousStepS<=0.0||!std::isfinite(previousManifold.timeStepS_)||
				previousManifold.timeStepS_<=0.0||previousManifold.timeStepS_!=previousStepS||
				!std::isfinite(previousManifold.maximumGeneration_)||
				previousManifold.maximumGeneration_<0.0||
				!std::isfinite(previousManifold.restorationDrainFraction_)||
				previousManifold.restorationDrainFraction_<0.0||
				previousManifold.restorationDrainFraction_>1.0 )
				return Fail(error,"production accepted manifold metadata is invalid");
		} else if( previousStepS>0.0 ) {
			return Fail(error,"production manifold metadata is unavailable after the first step");
		} else if( previousManifold.timeStepS_!=0.0||
			previousManifold.maximumGeneration_!=0.0||
			previousManifold.restorationDrainFraction_!=0.0 ) {
			return Fail(error,"production manifold metadata is partial");
		}
		result.seconds=std::numeric_limits<double>::infinity();
		result.activeLimit="unbounded_static_state";
		auto accept=[&]( const double candidate, const char* label ) {
			if( candidate<result.seconds ) { result.seconds=candidate;result.activeLimit=label; }
		};
		if( maximumVelocityMPerS>0.0 )
			accept(0.5*cellWidthM/maximumVelocityMPerS,"advective_CFL");
		if( maximumPositiveReducedGravityMPerS2>0.0 ) accept(
			0.5*std::sqrt(2.0*cellWidthM/maximumPositiveReducedGravityMPerS2),
			"buoyant_acceleration");
		if( maximumKinematicTransportM2PerS>0.0 ) accept(
			cellWidthM*cellWidthM/(8.0*maximumKinematicTransportM2PerS),
			"explicit_diffusion");
		if( previousStepS>0.0 ) accept(1.1*previousStepS,"growth_limit");
		if( previousManifold.available_&&previousManifold.maximumGeneration_>0.0 ) {
			const double candidate=previousManifold.timeStepS_*
				((1.0-ManifoldHeadroom)*ManifoldEOSCeiling*
				previousManifold.restorationDrainFraction_)/previousManifold.maximumGeneration_;
			if( !std::isfinite(candidate)||candidate<=0.0 )
				return Fail(error,"production manifold timestep is invalid");
			accept(candidate,"manifold_plateau");
		}
		return (result.seconds>0.0&&!std::isnan(result.seconds))||
			Fail(error,"production timestep selection failed");
	}

	bool EvaluateFireProductionVremanEddyViscosity(
		const FireProductionVremanInput& input,
		double& eddyViscosityM2PerS,
		std::string* error )
	{
		eddyViscosityM2PerS=0.0;
		if( !(input.coefficient>=0.0)||!std::isfinite(input.coefficient) )
			return Fail(error,"production Vreman coefficient is invalid");
		double alphaSquared=0.0;
		double beta[3][3]={};
		for( unsigned int i=0u;i<3u;++i ) for( unsigned int j=0u;j<3u;++j ) {
			const double alpha=input.velocityGradientPerS[3u*i+j];
			if( !std::isfinite(alpha) )
				return Fail(error,"production Vreman gradient is nonfinite");
			alphaSquared+=alpha*alpha;
			if( !std::isfinite(alphaSquared) )
				return Fail(error,"production Vreman gradient norm overflowed");
		}
		for( unsigned int m=0u;m<3u;++m ) {
			const double width=input.directionalWidthsM[m];
			if( !(width>0.0)||!std::isfinite(width) )
				return Fail(error,"production Vreman filter width is invalid");
			const double widthSquared=width*width;
			if( !std::isfinite(widthSquared) )
				return Fail(error,"production Vreman filter width overflowed");
			for( unsigned int i=0u;i<3u;++i ) for( unsigned int j=0u;j<3u;++j ) {
				beta[i][j]+=widthSquared*input.velocityGradientPerS[3u*m+i]*
					input.velocityGradientPerS[3u*m+j];
				if( !std::isfinite(beta[i][j]) )
					return Fail(error,"production Vreman beta tensor overflowed");
			}
		}
		if( alphaSquared==0.0 ) {
			if( error ) error->clear();
			return true;
		}
		const double rawBBeta=
			beta[0][0]*beta[1][1]-beta[0][1]*beta[0][1]+
			beta[0][0]*beta[2][2]-beta[0][2]*beta[0][2]+
			beta[1][1]*beta[2][2]-beta[1][2]*beta[1][2];
		if( !std::isfinite(rawBBeta) )
			return Fail(error,"production Vreman B_beta overflowed");
		const double bBeta=std::max(0.0,rawBBeta);
		eddyViscosityM2PerS=input.coefficient*std::sqrt(bBeta/alphaSquared);
		if( !(eddyViscosityM2PerS>=0.0)||!std::isfinite(eddyViscosityM2PerS) ) {
			eddyViscosityM2PerS=0.0;
			return Fail(error,"production Vreman viscosity is invalid");
		}
		if( error ) error->clear();
		return true;
	}

	bool SelectFireProductionViscousSchedule(
		double timeStepS,
		double outwardLambdaPerS,
		FireProductionViscousSchedule& schedule,
		std::string* error )
	{
		schedule=FireProductionViscousSchedule();
		if( !(timeStepS>0.0)||!std::isfinite(timeStepS)||
			!(outwardLambdaPerS>=0.0)||!std::isfinite(outwardLambdaPerS) )
			return Fail(error,"production viscous schedule input is invalid");
		const double infinity=std::numeric_limits<double>::infinity();
		const double work=std::nextafter((static_cast<double>(timeStepS)*
			static_cast<double>(outwardLambdaPerS))*0.5,infinity);
		if( !std::isfinite(work)||work>
			static_cast<double>(std::numeric_limits<std::uint32_t>::max()) )
			return Fail(error,"production viscous schedule overflowed");
		std::uint32_t count=std::max<std::uint32_t>(1u,
			static_cast<std::uint32_t>(std::ceil(work)));
		for( ;; ) {
			if( count>8u ) return Fail(error,
				"production viscous schedule exceeds eight substeps");
			const double substep=timeStepS/static_cast<double>(count);
			const double product=std::nextafter(static_cast<double>(substep)*
				static_cast<double>(outwardLambdaPerS),infinity);
			if( !std::isfinite(substep)||!(substep>0.0)||!std::isfinite(product) )
				return Fail(error,"production viscous represented substep is invalid");
			if( product<=2.0 ) {
				schedule.substepCount=count;schedule.substepTimeS=substep;
				schedule.outwardWork=work;schedule.representedProductUpper=product;
				if( error ) error->clear();
				return true;
			}
			++count;
		}
	}

	bool FireProductionFrozenForceWorkingSetBytes(
		const FireProductionProjectionShape& shape,
		std::uint64_t& bytes )
	{
		bytes=0u;
		if( shape.nx<4u||shape.nx>1024u||shape.ny<4u||shape.ny>1024u||
			shape.nz<4u||shape.nz>1024u ) return false;
		const std::uint64_t nx=shape.nx,ny=shape.ny,nz=shape.nz;
		const std::uint64_t cells=nx*ny*nz;
		const std::uint64_t allFaces=(nx+1u)*ny*nz+
			nx*(ny+1u)*nz+nx*ny*(nz+1u);
		// Peak includes caller-owned inputs and the local atomic result:
		// 16 cell arrays (2 input, 14 work/result) and 5 face arrays
		// (2 input, velocity work, viscous result, gravity result).
		bytes=(16u*cells+5u*allFaces)*sizeof(double);
		return true;
	}

	bool FireProductionFrozenForceAdvanceWorkingSetBytes(
		const FireProductionProjectionShape& shape,
		std::uint64_t& bytes )
	{
		bytes=0u;
		if( shape.nx<4u||shape.nx>1024u||shape.ny<4u||shape.ny>1024u||
			shape.nz<4u||shape.nz>1024u ) return false;
		const std::uint64_t nx=shape.nx,ny=shape.ny,nz=shape.nz;
		const std::uint64_t cells=nx*ny*nz;
		const std::uint64_t allFaces=(nx+1u)*ny*nz+
			nx*(ny+1u)*nz+nx*ny*(nz+1u);
		// At a substep peak the original request, frozen fields, evolving
		// momentum, copied substep request, and atomic substep result/work coexist.
		bytes=(20u*cells+10u*allFaces)*sizeof(double);
		return true;
	}

	bool FireProductionFrozenForceMetalWorkingSetBytes(
		const FireProductionProjectionShape& shape,
		std::uint64_t& bytes )
	{
		bytes=0u;
		if( shape.nx<4u||shape.nx>1024u||shape.ny<4u||shape.ny>1024u||
			shape.nz<4u||shape.nz>1024u ) return false;
		const std::uint64_t nx=shape.nx,ny=shape.ny,nz=shape.nz;
		const std::uint64_t cells=nx*ny*nz;
		const std::uint64_t faces=(nx+1u)*ny*nz+
			nx*(ny+1u)*nz+nx*ny*(nz+1u);
		const std::uint64_t quantum=UINT64_C(16384);
		auto rounded=[&](std::uint64_t count) -> std::uint64_t {
			const std::uint64_t raw=count*sizeof(double);
			return ((raw+quantum-1u)/quantum)*quantum;
		};
		// Host request, packed face staging, and atomic result: 4C+6F. Metal owns four C buffers,
		// one 3C buffer, one 9C buffer, five F buffers, and one 88-byte record.
		bytes=(4u*cells+6u*faces)*sizeof(double)+4u*rounded(cells)+
			rounded(3u*cells)+rounded(9u*cells)+5u*rounded(faces)+quantum;
		return true;
	}

	bool FireProductionResidentForceMetalWorkingSetBytes(
		const FireProductionProjectionShape& shape,
		bool captureIntermediateStates,
		std::uint64_t& bytes )
	{
		bytes=0u;
		if( shape.nx<4u||shape.nx>1024u||shape.ny<4u||shape.ny>1024u||
			shape.nz<4u||shape.nz>1024u ) return false;
		const std::uint64_t nx=shape.nx,ny=shape.ny,nz=shape.nz;
		const std::uint64_t cells=nx*ny*nz;
		const std::uint64_t faces=(nx+1u)*ny*nz+
			nx*(ny+1u)*nz+nx*ny*(nz+1u);
		std::uint64_t padded=1u;
		while( padded<std::max(cells,faces) ) padded*=2u;
		const std::uint64_t quantum=UINT64_C(16384);
		auto rounded=[&](std::uint64_t count) -> std::uint64_t {
			const std::uint64_t raw=count*sizeof(double);
			return ((raw+quantum-1u)/quantum)*quantum;
		};
		// Host caller, packing, and atomic publication coexist with all resident
		// buffers.  Optional snapshots exist once Private and once in terminal
		// Shared staging; neither is present in production execution.
		bytes=(4u*cells+7u*faces)*sizeof(double)+18u*rounded(cells)+
			9u*rounded(faces)+2u*rounded(padded)+3u*quantum;
		if( captureIntermediateStates ) bytes+=16u*rounded(faces);
		return true;
	}

	bool FireProductionResidentForceProjectionWorkingSetBytes(
		const FireProductionProjectionShape& shape,
		std::uint64_t& bytes )
	{
		bytes=0u;std::uint64_t forceBytes=0u,projectionBytes=0u;
		if( !FireProductionResidentForceMetalWorkingSetBytes(shape,false,forceBytes)||
			!FireProductionProjectionWorkingSetBytes(shape,projectionBytes) ) return false;
		const std::uint64_t cells=static_cast<std::uint64_t>(shape.nx)*shape.ny*shape.nz;
		if( cells>std::numeric_limits<std::uint64_t>::max()/sizeof(double) ) return false;
		const std::uint64_t raw=cells*sizeof(double),alignment=UINT64_C(16384);
		if( raw>std::numeric_limits<std::uint64_t>::max()-(alignment-1u) ) return false;
		const std::uint64_t targetAllocation=(raw+alignment-1u)&~(alignment-1u);
		std::uint64_t residentProvisionalStage=0u;
		for( unsigned int axis=0u;axis<3u;++axis ) {
			const std::uint64_t faces=axis==0u?static_cast<std::uint64_t>(shape.nx+1u)*shape.ny*shape.nz:
				(axis==1u?static_cast<std::uint64_t>(shape.nx)*(shape.ny+1u)*shape.nz:
				static_cast<std::uint64_t>(shape.nx)*shape.ny*(shape.nz+1u));
			if( faces>std::numeric_limits<std::uint64_t>::max()/sizeof(double) ) return false;
			const std::uint64_t faceRaw=faces*sizeof(double);
			if( faceRaw>std::numeric_limits<std::uint64_t>::max()-(alignment-1u) ) return false;
			const std::uint64_t allocation=(faceRaw+alignment-1u)&~(alignment-1u);
			if( residentProvisionalStage>std::numeric_limits<std::uint64_t>::max()-allocation )
				return false;
			residentProvisionalStage+=allocation;
		}
		if( forceBytes>std::numeric_limits<std::uint64_t>::max()-projectionBytes||
			forceBytes+projectionBytes>std::numeric_limits<std::uint64_t>::max()-
				2u*targetAllocation||
			forceBytes+projectionBytes+2u*targetAllocation>
				std::numeric_limits<std::uint64_t>::max()-residentProvisionalStage ) return false;
		bytes=forceBytes+projectionBytes+2u*targetAllocation+residentProvisionalStage;return true;
	}

	bool FireProductionResidentStepWorkingSetBytes(
		const FireProductionProjectionShape& shape,
		const std::array<FireProductionProjectionBoundary,6>& boundary,
		std::uint64_t& bytes )
	{
		bytes=0u;
		std::uint64_t forceProjectionBytes=0u,restorationProjectionBytes=0u,
			cellBytes=0u,dualBytes=0u;
		if( !FireProductionResidentForceProjectionWorkingSetBytes(shape,forceProjectionBytes)||
			!FireProductionProjectionWorkingSetBytes(shape,restorationProjectionBytes)||
			!FireProductionCellPalindromeWorkingSetBytes(shape,9u,cellBytes)||
			!FireProductionDualMomentumResidentWorkingSetBytes(shape,boundary,dualBytes) )
			return false;
		const std::uint64_t cells=static_cast<std::uint64_t>(shape.nx)*shape.ny*shape.nz;
		const std::uint64_t allFaces=static_cast<std::uint64_t>(shape.nx+1u)*shape.ny*shape.nz+
			static_cast<std::uint64_t>(shape.nx)*(shape.ny+1u)*shape.nz+
			static_cast<std::uint64_t>(shape.nx)*shape.ny*(shape.nz+1u);
		if( cells>(std::numeric_limits<std::uint64_t>::max()-3u*allFaces)/19u ) return false;
		const std::uint64_t extraValues=19u*cells+3u*allFaces;
		const std::uint64_t rawTarget=cells*sizeof(double),alignment=UINT64_C(16384);
		if( rawTarget>std::numeric_limits<std::uint64_t>::max()-(alignment-1u) ) return false;
		const std::uint64_t targetAllocation=(rawTarget+alignment-1u)&~(alignment-1u);
		if( extraValues>std::numeric_limits<std::uint64_t>::max()/sizeof(double)||
			forceProjectionBytes>std::numeric_limits<std::uint64_t>::max()-cellBytes||
			forceProjectionBytes+cellBytes>std::numeric_limits<std::uint64_t>::max()-dualBytes||
			forceProjectionBytes+cellBytes+dualBytes>
				std::numeric_limits<std::uint64_t>::max()-extraValues*sizeof(double)||
			forceProjectionBytes+cellBytes+dualBytes+extraValues*sizeof(double)>
				std::numeric_limits<std::uint64_t>::max()-restorationProjectionBytes||
			forceProjectionBytes+cellBytes+dualBytes+extraValues*sizeof(double)+
				restorationProjectionBytes>std::numeric_limits<std::uint64_t>::max()-
					2u*targetAllocation ) return false;
		bytes=forceProjectionBytes+cellBytes+dualBytes+extraValues*sizeof(double)+
			restorationProjectionBytes+2u*targetAllocation;return true;
	}

	bool ValidateFireProductionFrozenForceRequest(
		const FireProductionFrozenForceRequest& request,
		std::string* error )
	{
		const FireProductionProjectionShape& shape=request.shape;
		if( shape.nx<4u||shape.nx>1024u||shape.ny<4u||shape.ny>1024u||
			shape.nz<4u||shape.nz>1024u||!(shape.cellWidthM>0.0)||
			!std::isfinite(shape.cellWidthM)||!(request.timeStepS>0.0)||
			!std::isfinite(request.timeStepS)||!(request.ambientDensityKGPerM3>0.0)||
			!std::isfinite(request.ambientDensityKGPerM3)||
			!(request.vremanCoefficient>=0.0)||!std::isfinite(request.vremanCoefficient) )
			return Fail(error,"production frozen-force shape or scalar is invalid");
		for( const double gravity : request.gravityMPerS2 ) if( !std::isfinite(gravity) )
			return Fail(error,"production frozen-force gravity is nonfinite");
		for( unsigned int axis=0u;axis<3u;++axis ) {
			const FireProductionProjectionBoundary lower=request.boundary[2u*axis];
			const FireProductionProjectionBoundary upper=request.boundary[2u*axis+1u];
			if( lower<FireProductionProjectionPeriodic||lower>FireProductionProjectionWall||
				upper<FireProductionProjectionPeriodic||upper>FireProductionProjectionWall||
				((lower==FireProductionProjectionPeriodic)!=(upper==FireProductionProjectionPeriodic)) )
				return Fail(error,"production frozen-force boundary pairing is invalid");
		}
		std::uint64_t workingBytes=0u;
		if( !FireProductionFrozenForceWorkingSetBytes(shape,workingBytes)||
			workingBytes>(UINT64_C(1)<<31u) )
			return Fail(error,"production frozen-force working set exceeds two GiB");
		const std::size_t cells=shape.CellCount();
		if( request.cellGasDensityKGPerM3.size()!=cells||
			request.molecularKinematicViscosityM2PerS.size()!=cells )
			return Fail(error,"production frozen-force cell shape is invalid");
		for( const double density : request.cellGasDensityKGPerM3 )
			if( !(density>0.0)||!std::isfinite(density) )
				return Fail(error,"production frozen-force cell density is invalid");
		for( const double viscosity : request.molecularKinematicViscosityM2PerS )
			if( !(viscosity>=0.0)||!std::isfinite(viscosity) )
				return Fail(error,"production frozen-force molecular viscosity is invalid");
		for( unsigned int axis=0u;axis<3u;++axis ) {
			const std::size_t faces=FireProductionProjectionFaceCount(shape,axis);
			if( request.faceDensityKGPerM3[axis].size()!=faces||
				request.beginningMomentumKGPerM2S[axis].size()!=faces )
				return Fail(error,"production frozen-force face shape is invalid");
			for( std::size_t face=0u;face<faces;++face ) {
				const double density=request.faceDensityKGPerM3[axis][face];
				const double momentum=request.beginningMomentumKGPerM2S[axis][face];
				if( !(density>0.0)||!std::isfinite(density)||!std::isfinite(momentum) )
					return Fail(error,"production frozen-force face state is invalid");
				if( !std::isfinite(momentum/density) )
					return Fail(error,"production frozen-force velocity overflowed");
			}
			if( request.boundary[2u*axis]==FireProductionProjectionPeriodic ) {
				const std::size_t extent=AxisExtent(shape,axis);
				const std::size_t firstExtent=AxisExtent(shape,(axis+1u)%3u);
				const std::size_t secondExtent=AxisExtent(shape,(axis+2u)%3u);
				for( std::size_t second=0u;second<secondExtent;++second )
					for( std::size_t first=0u;first<firstExtent;++first ) {
						std::size_t xyz[]={0u,0u,0u};
						xyz[(axis+1u)%3u]=first;xyz[(axis+2u)%3u]=second;
						const std::size_t low=FaceIndex(shape,axis,xyz[0],xyz[1],xyz[2]);
						xyz[axis]=extent;
						const std::size_t high=FaceIndex(shape,axis,xyz[0],xyz[1],xyz[2]);
						if( !SameFloatBytes(request.faceDensityKGPerM3[axis][low],
							request.faceDensityKGPerM3[axis][high])||
							!SameFloatBytes(request.beginningMomentumKGPerM2S[axis][low],
								request.beginningMomentumKGPerM2S[axis][high]) )
							return Fail(error,"production frozen-force periodic face seam differs");
					}
			}
		}
		if( error ) error->clear();return true;
	}

	static bool BuildFireProductionFrozenForceFieldsImpl(
		const FireProductionFrozenForceRequest& request,
		const std::vector<double>* fixedDynamicViscosityPaS,
		bool propagateAllocationFailure,
		FireProductionFrozenForceResult& result,
		std::string* error )
	{
		result=FireProductionFrozenForceResult();
		try {
			FireProductionFrozenForceResult computed;
			if( !ValidateFireProductionFrozenForceRequest(request,error) ) return false;
			const FireProductionProjectionShape& shape=request.shape;
			if( shape.nx<4u||shape.nx>1024u||shape.ny<4u||shape.ny>1024u||
				shape.nz<4u||shape.nz>1024u||!(shape.cellWidthM>0.0)||
				!std::isfinite(shape.cellWidthM)||!(request.timeStepS>0.0)||
				!std::isfinite(request.timeStepS)||!(request.ambientDensityKGPerM3>0.0)||
				!std::isfinite(request.ambientDensityKGPerM3)||
				!(request.vremanCoefficient>=0.0)||
				!std::isfinite(request.vremanCoefficient) )
				return Fail(error,"production frozen-force shape or scalar is invalid");
			for( const double gravity : request.gravityMPerS2 ) if( !std::isfinite(gravity) )
				return Fail(error,"production frozen-force gravity is nonfinite");
			for( unsigned int axis=0u;axis<3u;++axis ) {
				const FireProductionProjectionBoundary lower=request.boundary[2u*axis];
				const FireProductionProjectionBoundary upper=request.boundary[2u*axis+1u];
				if( lower<FireProductionProjectionPeriodic||lower>FireProductionProjectionWall||
					upper<FireProductionProjectionPeriodic||upper>FireProductionProjectionWall||
					((lower==FireProductionProjectionPeriodic)!=
					 (upper==FireProductionProjectionPeriodic)) )
					return Fail(error,"production frozen-force boundary pairing is invalid");
			}
			const std::size_t cells=shape.CellCount();
			std::uint64_t workingBytes=0u;
			if( !FireProductionFrozenForceWorkingSetBytes(shape,workingBytes)||
				workingBytes>(UINT64_C(1)<<31u) )
				return Fail(error,"production frozen-force working set exceeds two GiB");
			if( request.cellGasDensityKGPerM3.size()!=cells||
				request.molecularKinematicViscosityM2PerS.size()!=cells )
				return Fail(error,"production frozen-force cell shape is invalid");
			if( fixedDynamicViscosityPaS&&fixedDynamicViscosityPaS->size()!=cells )
				return Fail(error,"production frozen-force fixed-mu shape is invalid");
			for( const double density : request.cellGasDensityKGPerM3 )
				if( !(density>0.0)||!std::isfinite(density) )
					return Fail(error,"production frozen-force cell density is invalid");
			for( const double viscosity : request.molecularKinematicViscosityM2PerS )
				if( !(viscosity>=0.0)||!std::isfinite(viscosity) )
					return Fail(error,"production frozen-force molecular viscosity is invalid");
			std::array<std::vector<double>,3> faceVelocity;
			for( unsigned int axis=0u;axis<3u;++axis ) {
				const std::size_t faces=FireProductionProjectionFaceCount(shape,axis);
				if( request.faceDensityKGPerM3[axis].size()!=faces||
					request.beginningMomentumKGPerM2S[axis].size()!=faces )
					return Fail(error,"production frozen-force face shape is invalid");
				faceVelocity[axis].resize(faces);
				for( std::size_t face=0u;face<faces;++face ) {
					const double density=request.faceDensityKGPerM3[axis][face];
					const double momentum=request.beginningMomentumKGPerM2S[axis][face];
					if( !(density>0.0)||!std::isfinite(density)||!std::isfinite(momentum) )
						return Fail(error,"production frozen-force face state is invalid");
					faceVelocity[axis][face]=momentum/density;
					if( !std::isfinite(faceVelocity[axis][face]) )
						return Fail(error,"production frozen-force velocity overflowed");
				}
				const std::size_t extent=AxisExtent(shape,axis);
				const std::size_t firstExtent=AxisExtent(shape,(axis+1u)%3u);
				const std::size_t secondExtent=AxisExtent(shape,(axis+2u)%3u);
				for( std::size_t second=0u;second<secondExtent;++second )
					for( std::size_t first=0u;first<firstExtent;++first ) {
						std::size_t xyz[]={0u,0u,0u};
						xyz[(axis+1u)%3u]=first;xyz[(axis+2u)%3u]=second;
						if( request.boundary[2u*axis]==FireProductionProjectionPeriodic ) {
							xyz[axis]=0u;
							const std::size_t low=FaceIndex(shape,axis,xyz[0],xyz[1],xyz[2]);
							xyz[axis]=extent;
							const std::size_t high=FaceIndex(shape,axis,xyz[0],xyz[1],xyz[2]);
							if( !SameFloatBytes(request.faceDensityKGPerM3[axis][low],
								request.faceDensityKGPerM3[axis][high])||
								!SameFloatBytes(request.beginningMomentumKGPerM2S[axis][low],
									request.beginningMomentumKGPerM2S[axis][high]) )
								return Fail(error,
									"production frozen-force periodic face seam differs");
						}
						if( request.boundary[2u*axis]==FireProductionProjectionWall ) {
							xyz[axis]=0u;faceVelocity[axis][FaceIndex(shape,axis,
								xyz[0],xyz[1],xyz[2])]=0.0;
						}
						if( request.boundary[2u*axis+1u]==FireProductionProjectionWall ) {
							xyz[axis]=extent;faceVelocity[axis][FaceIndex(shape,axis,
								xyz[0],xyz[1],xyz[2])]=0.0;
						}
					}
			}
			std::array<std::vector<double>,3> cellVelocity;
			for( unsigned int component=0u;component<3u;++component )
				cellVelocity[component].resize(cells);
			for( std::size_t z=0u;z<shape.nz;++z ) for( std::size_t y=0u;y<shape.ny;++y )
				for( std::size_t x=0u;x<shape.nx;++x ) {
					const std::size_t cell=CellIndex(shape,x,y,z);
					const std::size_t xyz[]={x,y,z};
					for( unsigned int component=0u;component<3u;++component ) {
						std::size_t upperXYZ[]={x,y,z};++upperXYZ[component];
						cellVelocity[component][cell]=0.5*(faceVelocity[component][
							FaceIndex(shape,component,xyz[0],xyz[1],xyz[2])]+
							faceVelocity[component][FaceIndex(shape,component,
								upperXYZ[0],upperXYZ[1],upperXYZ[2])]);
					}
				}
			computed.eddyKinematicViscosityM2PerS.resize(cells);
			computed.effectiveDynamicViscosityPaS.resize(cells);
			std::array<std::array<std::vector<double>,3>,3> stress;
			for( unsigned int i=0u;i<3u;++i ) for( unsigned int j=0u;j<3u;++j )
				stress[i][j].resize(cells);
			for( std::size_t z=0u;z<shape.nz;++z ) for( std::size_t y=0u;y<shape.ny;++y )
				for( std::size_t x=0u;x<shape.nx;++x ) {
					const std::size_t cell=CellIndex(shape,x,y,z);
					const std::size_t coordinate[]={x,y,z};
					double gradient[3][3]={};double divergence=0.0;
					for( unsigned int derivative=0u;derivative<3u;++derivative ) {
						const std::size_t extent=AxisExtent(shape,derivative);
						for( unsigned int component=0u;component<3u;++component ) {
							double previous=cellVelocity[component][cell];
							double next=cellVelocity[component][cell];
							if( coordinate[derivative]>0u ) {
								std::size_t xyz[]={x,y,z};--xyz[derivative];
								previous=cellVelocity[component][CellIndex(shape,xyz[0],xyz[1],xyz[2])];
							} else if( request.boundary[2u*derivative]==FireProductionProjectionPeriodic ) {
								std::size_t xyz[]={x,y,z};xyz[derivative]=extent-1u;
								previous=cellVelocity[component][CellIndex(shape,xyz[0],xyz[1],xyz[2])];
							} else if( request.boundary[2u*derivative]==FireProductionProjectionWall )
								previous=-cellVelocity[component][cell];
							if( coordinate[derivative]+1u<extent ) {
								std::size_t xyz[]={x,y,z};++xyz[derivative];
								next=cellVelocity[component][CellIndex(shape,xyz[0],xyz[1],xyz[2])];
							} else if( request.boundary[2u*derivative+1u]==FireProductionProjectionPeriodic ) {
								std::size_t xyz[]={x,y,z};xyz[derivative]=0u;
								next=cellVelocity[component][CellIndex(shape,xyz[0],xyz[1],xyz[2])];
							} else if( request.boundary[2u*derivative+1u]==FireProductionProjectionWall )
								next=-cellVelocity[component][cell];
							gradient[derivative][component]=(next-previous)/
								(2.0*shape.cellWidthM);
						}
						divergence+=gradient[derivative][derivative];
					}
					FireProductionVremanInput vreman;
					vreman.coefficient=request.vremanCoefficient;
					vreman.directionalWidthsM.fill(shape.cellWidthM);
					for( unsigned int i=0u;i<3u;++i ) for( unsigned int j=0u;j<3u;++j )
						vreman.velocityGradientPerS[3u*i+j]=gradient[i][j];
					double mu=0.0;
					if( fixedDynamicViscosityPaS ) {
						computed.eddyKinematicViscosityM2PerS[cell]=0.0;
						mu=(*fixedDynamicViscosityPaS)[cell];
						if( !(mu>=0.0)||!std::isfinite(mu) )
							return Fail(error,"production frozen-force fixed mu is invalid");
					} else {
						if( !EvaluateFireProductionVremanEddyViscosity(vreman,
							computed.eddyKinematicViscosityM2PerS[cell],error) ) return false;
						const double effectiveKinematic=
							request.molecularKinematicViscosityM2PerS[cell]+
							computed.eddyKinematicViscosityM2PerS[cell];
						mu=request.cellGasDensityKGPerM3[cell]*effectiveKinematic;
						if( !std::isfinite(effectiveKinematic)||!std::isfinite(mu) )
							return Fail(error,"production frozen-force viscosity overflowed");
					}
					computed.effectiveDynamicViscosityPaS[cell]=mu;
					for( unsigned int component=0u;component<3u;++component )
						for( unsigned int derivative=0u;derivative<3u;++derivative )
							stress[component][derivative][cell]=mu*(
								gradient[derivative][component]+
								gradient[component][derivative]-
								(component==derivative?(2.0/3.0)*divergence:0.0));
				}
			for( unsigned int component=0u;component<3u;++component ) {
				const std::size_t faces=FireProductionProjectionFaceCount(shape,component);
				computed.beginningViscousMomentumRateKGPerM2S2[component].assign(faces,0.0);
				computed.gravityMomentumIncrementKGPerM2S[component].resize(faces);
				const std::size_t normalExtent=AxisExtent(shape,component);
				const bool periodicNormal=request.boundary[2u*component]==
					FireProductionProjectionPeriodic;
				const unsigned int firstAxis=(component+1u)%3u,secondAxis=(component+2u)%3u;
				const std::size_t firstExtent=AxisExtent(shape,firstAxis);
				const std::size_t secondExtent=AxisExtent(shape,secondAxis);
				for( std::size_t second=0u;second<secondExtent;++second )
					for( std::size_t first=0u;first<firstExtent;++first )
						for( std::size_t normal=0u;normal<=normalExtent;++normal ) {
							std::size_t xyz[]={0u,0u,0u};xyz[component]=normal;
							xyz[firstAxis]=first;xyz[secondAxis]=second;
							const std::size_t face=FaceIndex(shape,component,xyz[0],xyz[1],xyz[2]);
							if( periodicNormal&&normal==normalExtent ) continue;
							const bool prescribedWall=(normal==0u&&request.boundary[2u*component]==
								FireProductionProjectionWall)||(normal==normalExtent&&
								request.boundary[2u*component+1u]==FireProductionProjectionWall);
							computed.gravityMomentumIncrementKGPerM2S[component][face]=prescribedWall?
								0.0:request.timeStepS*(request.faceDensityKGPerM3[component][face]-
									request.ambientDensityKGPerM3)*request.gravityMPerS2[component];
							if( !std::isfinite(
								computed.gravityMomentumIncrementKGPerM2S[component][face]) )
								return Fail(error,"production frozen-force output is nonfinite");
							if( (normal==0u&&!periodicNormal)||normal==normalExtent ) continue;
							std::size_t leftXYZ[]={xyz[0],xyz[1],xyz[2]};
							leftXYZ[component]=normal==0u?normalExtent-1u:normal-1u;
							const std::size_t left=CellIndex(shape,leftXYZ[0],leftXYZ[1],leftXYZ[2]);
							const std::size_t right=CellIndex(shape,xyz[0],xyz[1],xyz[2]);
							double viscous=(stress[component][component][right]-
								stress[component][component][left])/shape.cellWidthM;
							for( unsigned int derivative=0u;derivative<3u;++derivative ) {
								if( derivative==component ) continue;
								const std::size_t position=xyz[derivative];
								const std::size_t extent=AxisExtent(shape,derivative);
								std::size_t leftPrevious=left,rightPrevious=right;
								std::size_t leftNext=left,rightNext=right;
								const bool hasPrevious=position>0u||request.boundary[2u*derivative]==
									FireProductionProjectionPeriodic;
								const bool hasNext=position+1u<extent||
									request.boundary[2u*derivative+1u]==FireProductionProjectionPeriodic;
								if( hasPrevious ) {
									std::size_t lp[]={leftXYZ[0],leftXYZ[1],leftXYZ[2]};
									std::size_t rp[]={xyz[0],xyz[1],xyz[2]};
									lp[derivative]=position?position-1u:extent-1u;
									rp[derivative]=position?position-1u:extent-1u;
									leftPrevious=CellIndex(shape,lp[0],lp[1],lp[2]);
									rightPrevious=CellIndex(shape,rp[0],rp[1],rp[2]);
								}
								if( hasNext ) {
									std::size_t ln[]={leftXYZ[0],leftXYZ[1],leftXYZ[2]};
									std::size_t rn[]={xyz[0],xyz[1],xyz[2]};
									ln[derivative]=position+1u<extent?position+1u:0u;
									rn[derivative]=position+1u<extent?position+1u:0u;
									leftNext=CellIndex(shape,ln[0],ln[1],ln[2]);
									rightNext=CellIndex(shape,rn[0],rn[1],rn[2]);
								}
								const double distance=(hasPrevious&&hasNext)?
									4.0*shape.cellWidthM:2.0*shape.cellWidthM;
								viscous+=(stress[component][derivative][leftNext]+
									stress[component][derivative][rightNext]-
									stress[component][derivative][leftPrevious]-
									stress[component][derivative][rightPrevious])/distance;
							}
							if( !std::isfinite(viscous) )
								return Fail(error,"production frozen-force output is nonfinite");
							computed.beginningViscousMomentumRateKGPerM2S2[component][face]=viscous;
						}
				if( periodicNormal )
					for( std::size_t second=0u;second<secondExtent;++second )
						for( std::size_t first=0u;first<firstExtent;++first ) {
							std::size_t lowXYZ[]={0u,0u,0u};
							lowXYZ[firstAxis]=first;lowXYZ[secondAxis]=second;
							std::size_t highXYZ[]={lowXYZ[0],lowXYZ[1],lowXYZ[2]};
							highXYZ[component]=normalExtent;
							const std::size_t low=FaceIndex(shape,component,
								lowXYZ[0],lowXYZ[1],lowXYZ[2]);
							const std::size_t high=FaceIndex(shape,component,
								highXYZ[0],highXYZ[1],highXYZ[2]);
							computed.beginningViscousMomentumRateKGPerM2S2[component][high]=
								computed.beginningViscousMomentumRateKGPerM2S2[component][low];
							computed.gravityMomentumIncrementKGPerM2S[component][high]=
								computed.gravityMomentumIncrementKGPerM2S[component][low];
						}
			}
			result=std::move(computed);
			if( error ) error->clear();
			return true;
		} catch( const std::bad_alloc& ) {
			if( propagateAllocationFailure ) throw;
			result=FireProductionFrozenForceResult();
			Fail(error,"production frozen-force allocation failed");
			return false;
		}
	}

	bool BuildFireProductionFrozenForceFieldsCPU(
		const FireProductionFrozenForceRequest& request,
		FireProductionFrozenForceResult& result,
		std::string* error )
	{
		return BuildFireProductionFrozenForceFieldsImpl(request,0,false,result,error);
	}

	bool AdvanceFireProductionFrozenForceCPU(
		const FireProductionFrozenForceRequest& request,
		double outwardLambdaPerS,
		FireProductionFrozenForceAdvanceResult& result,
		std::string* error )
	{
		result=FireProductionFrozenForceAdvanceResult();
		try {
			FireProductionFrozenForceAdvanceResult computed;
			std::uint64_t workingBytes=0u;
			if( !FireProductionFrozenForceAdvanceWorkingSetBytes(
				request.shape,workingBytes)||workingBytes>(UINT64_C(1)<<31u) )
				return Fail(error,
					"production frozen-force advance working set exceeds two GiB");
			if( !BuildFireProductionFrozenForceFieldsImpl(
				request,0,true,computed.frozenFields,error)||
				!SelectFireProductionViscousSchedule(request.timeStepS,
					outwardLambdaPerS,computed.schedule,error) ) return false;
			computed.momentumKGPerM2S=request.beginningMomentumKGPerM2S;
			auto publishBoundaries=[&]() {
				for( unsigned int axis=0u;axis<3u;++axis ) {
					const std::size_t extent=AxisExtent(request.shape,axis);
					const std::size_t firstExtent=AxisExtent(request.shape,(axis+1u)%3u);
					const std::size_t secondExtent=AxisExtent(request.shape,(axis+2u)%3u);
					for( std::size_t second=0u;second<secondExtent;++second )
						for( std::size_t first=0u;first<firstExtent;++first ) {
							std::size_t lowXYZ[]={0u,0u,0u};
							lowXYZ[(axis+1u)%3u]=first;lowXYZ[(axis+2u)%3u]=second;
							std::size_t highXYZ[]={lowXYZ[0],lowXYZ[1],lowXYZ[2]};
							highXYZ[axis]=extent;
							const std::size_t low=FaceIndex(request.shape,axis,
								lowXYZ[0],lowXYZ[1],lowXYZ[2]);
							const std::size_t high=FaceIndex(request.shape,axis,
								highXYZ[0],highXYZ[1],highXYZ[2]);
							if( request.boundary[2u*axis]==FireProductionProjectionPeriodic )
								computed.momentumKGPerM2S[axis][high]=
									computed.momentumKGPerM2S[axis][low];
							if( request.boundary[2u*axis]==FireProductionProjectionWall )
								computed.momentumKGPerM2S[axis][low]=0.0;
							if( request.boundary[2u*axis+1u]==FireProductionProjectionWall )
								computed.momentumKGPerM2S[axis][high]=0.0;
						}
				}
			};
			publishBoundaries();
			FireProductionFrozenForceRequest substepRequest=request;
			substepRequest.timeStepS=computed.schedule.substepTimeS;
			substepRequest.gravityMPerS2.fill(0.0);
			for( std::uint32_t substep=0u;substep<computed.schedule.substepCount;++substep ) {
				substepRequest.beginningMomentumKGPerM2S=computed.momentumKGPerM2S;
				FireProductionFrozenForceResult substepFields;
				if( !BuildFireProductionFrozenForceFieldsImpl(substepRequest,
					&computed.frozenFields.effectiveDynamicViscosityPaS,
					true,substepFields,error) ) return false;
				for( unsigned int axis=0u;axis<3u;++axis )
					for( std::size_t face=0u;face<computed.momentumKGPerM2S[axis].size();++face ) {
						const double value=computed.momentumKGPerM2S[axis][face]+
							computed.schedule.substepTimeS*
							substepFields.beginningViscousMomentumRateKGPerM2S2[axis][face];
						if( !std::isfinite(value) )
							return Fail(error,"production frozen-force substep overflowed");
						computed.momentumKGPerM2S[axis][face]=value;
					}
				publishBoundaries();
				computed.intermediateMomentumByteDigests[
					computed.intermediateMomentumDigestCount++]=
					MomentumByteDigest(computed.momentumKGPerM2S);
				++computed.executedViscousSubstepCount;
			}
			for( unsigned int axis=0u;axis<3u;++axis )
				for( std::size_t face=0u;face<computed.momentumKGPerM2S[axis].size();++face ) {
					const double value=computed.momentumKGPerM2S[axis][face]+
						computed.frozenFields.gravityMomentumIncrementKGPerM2S[axis][face];
					if( !std::isfinite(value) )
						return Fail(error,"production frozen-force gravity update overflowed");
					computed.momentumKGPerM2S[axis][face]=value;
				}
			publishBoundaries();
			result=std::move(computed);
			if( error ) error->clear();
			return true;
		} catch( const std::bad_alloc& ) {
			result=FireProductionFrozenForceAdvanceResult();
			Fail(error,"production frozen-force advance allocation failed");
			return false;
		}
	}
}
