// GENERATED by tools/generate_fire_production_fp64_mirror.py.
// Do not edit; run the generator and commit its deterministic output.
//////////////////////////////////////////////////////////////////////
//
//  FireProductionProjection.h - one-pass fp32 production MAC projection
//
//  License Information: Please see the attached LICENSE.TXT file
//
//////////////////////////////////////////////////////////////////////

#ifndef FP64_FIREPRODUCTIONPROJECTION_
#define FP64_FIREPRODUCTIONPROJECTION_

#include <array>
#include <cstddef>
#include <cstdint>
#include <string>
#include <vector>

#if defined(__OBJC__) && defined(__APPLE__)
#import <Metal/Metal.h>
#endif

namespace RISEFireProductionFP64
{
	enum FireProductionProjectionBoundary
	{
		FireProductionProjectionPeriodic,
		FireProductionProjectionPressureOpen,
		FireProductionProjectionWall
	};

	struct FireProductionProjectionShape
	{
		std::size_t nx,ny,nz;
		double cellWidthM;

		FireProductionProjectionShape() : nx(0),ny(0),nz(0),cellWidthM(0.0) {}
		std::size_t CellCount() const {return nx*ny*nz;}
	};

	struct FireProductionProjectionRequest
	{
		FireProductionProjectionShape shape;
		double timeStepS;
		double ambientDensityKGPerM3;
		std::array<FireProductionProjectionBoundary,6> boundary;
		std::vector<double> gasDensityKGPerM3;
		std::array<std::vector<double>,3> provisionalMomentumKGPerM2S;
		std::vector<double> divergenceTargetPerS;

		FireProductionProjectionRequest() : timeStepS(0.0),ambientDensityKGPerM3(0.0)
		{
			boundary.fill(FireProductionProjectionWall);
		}
	};

	struct FireProductionProjectionResult
	{
		std::array<std::vector<double>,3> faceDensityKGPerM3;
		std::array<std::vector<double>,3> velocityMPerS;
		std::array<std::vector<double>,3> momentumKGPerM2S;
		std::vector<double> pressurePa;
		std::array<std::vector<unsigned char>,6> pressureOpenInflow;
		double maximumPreProjectionResidualPerS;
		double maximumPostProjectionResidualPerS;
		double maximumOpenComplementarityDiscrepancyMPerS;
		double removedFineRightHandSideMean;
		std::uint32_t executedVCycleCount;
		std::uint64_t executedJacobiSweepCount;
		std::uint32_t residentUploadStagingCount;
		std::uint32_t residentInterstageDeviceToHostTransferCount;
		std::uint32_t residentTerminalStagingCount;
		std::uint32_t residentCommandCommitCount;
		std::uint32_t residentProjectionInvocationCount;
		std::uint64_t residentCertifiedWorkingSetBytes;
		std::uint64_t residentActualMetalAllocationBytes;
		bool validationPassed;
		double deviceElapsedMS;

		FireProductionProjectionResult() : maximumPreProjectionResidualPerS(0.0),
			maximumPostProjectionResidualPerS(0.0),
			maximumOpenComplementarityDiscrepancyMPerS(0.0),
			removedFineRightHandSideMean(0.0),executedVCycleCount(0u),
			executedJacobiSweepCount(0u),residentUploadStagingCount(0u),
			residentInterstageDeviceToHostTransferCount(0u),residentTerminalStagingCount(0u),
			residentCommandCommitCount(0u),residentProjectionInvocationCount(0u),
			residentCertifiedWorkingSetBytes(0u),residentActualMetalAllocationBytes(0u),validationPassed(false),
			deviceElapsedMS(0.0) {}
	};

	std::size_t FireProductionProjectionFaceCount(
		const FireProductionProjectionShape& shape, unsigned int axis );

	bool FireProductionProjectionWorkingSetBytes(
		const FireProductionProjectionShape& shape,
		std::uint64_t& bytes );

	bool FireProductionProjectionResidualWithinBand(
		double maximumResidualPerS,
		double maximumVelocityMPerS,
		double domainLengthM,
		bool& withinBand );

	bool ValidateFireProductionProjectionRequest(
		const FireProductionProjectionRequest& request,
		std::string* error=0 );

	//! Strict-binary32 comparator implementing the stored P2 schedule.
	bool ProjectFireProductionCPU(
		const FireProductionProjectionRequest& request,
		FireProductionProjectionResult& result,
		std::string* error=0 );

#if defined(__OBJC__) && defined(__APPLE__)
	struct FireProductionMetalProjectionResidentInput
	{
		id<MTLBuffer> gasDensityKGPerM3;
		std::array<id<MTLBuffer>,3> provisionalMomentumKGPerM2S;
		std::array<std::size_t,3> provisionalMomentumByteOffset;
		id<MTLBuffer> divergenceTargetPerS;

		FireProductionMetalProjectionResidentInput() : gasDensityKGPerM3(nil),
			divergenceTargetPerS(nil)
		{
			provisionalMomentumKGPerM2S.fill(nil);
			provisionalMomentumByteOffset.fill(0u);
		}
	};

	//! Internal full-grid Private-buffer seam for the composed resident P3 step.
	bool ProjectFireProductionMetalResident(
		const FireProductionProjectionRequest& request,
		const FireProductionMetalProjectionResidentInput& input,
		FireProductionProjectionResult& result,
		std::string* error=0 );
#endif

	//! Metal-resident implementation of the same fixed P2 schedule.  Platforms
	//! without Metal provide an honest fail-closed definition; there is no CPU
	//! fallback behind this entry point.
	bool ProjectFireProductionMetal(
		const FireProductionProjectionRequest& request,
		FireProductionProjectionResult& result,
		std::string* error=0 );

}

#endif
