// GENERATED by tools/generate_fire_production_fp64_mirror.py.
// Do not edit; run the generator and commit its deterministic output.
//////////////////////////////////////////////////////////////////////
//
//  FireProductionAdvection.h - fp32 conservative production remap
//
//  License Information: Please see the attached LICENSE.TXT file
//
//////////////////////////////////////////////////////////////////////

#ifndef FP64_FIREPRODUCTIONADVECTION_
#define FP64_FIREPRODUCTIONADVECTION_

#include <cstddef>
#include <cstdint>
#include <string>
#include <vector>

namespace RISEFireProductionFP64
{
	//! r204 byte-payload digest namespace (distinct from historical manifold
	//! token digest variants). SHA-256 Merkle tree: 4096-byte leaves, fan-in 16.
	struct FireProductionPayloadDigestV2
	{
		std::uint32_t digestVersion=2u;
		std::uint32_t chunkBytes=4096u;
		std::uint32_t fanIn=16u;
		std::uint64_t payloadBytes=0u;
		std::string rootSHA256;
	};
	//! Parallelism is execution metadata, never part of the digest preimage.
	bool FireProductionPayloadDigestCPU(const unsigned char* bytes,std::size_t count,
		unsigned int parallelism,FireProductionPayloadDigestV2& result,std::string* error=0);
	//! Qualification entry; live producers use the same kernels on private
	//! resident buffers, without a CPU-produced digest authority.
	bool FireProductionPayloadDigestMetal(const std::vector<unsigned char>& bytes,
		unsigned int dispatchWidth,FireProductionPayloadDigestV2& result,
		double& deviceMS,std::string* error=0);

	enum FireProductionRemapBoundary
	{
		FireProductionRemapPeriodic,
		FireProductionRemapPressureOpen,
		FireProductionRemapWall
	};

	//! One batch of logically independent uniform-grid lines. Values are SoA:
	//! [component][line][cell], velocities are [line][face], ambient is one
	//! authored value per component.
	struct FireProductionRemapRequest
	{
		std::size_t lineLength;
		std::size_t lineCount;
		std::size_t componentCount;
		double cellWidthM;
		double timeStepS;
		FireProductionRemapBoundary boundary;
		bool asymmetricBoundaries;
		FireProductionRemapBoundary lowerBoundary;
		FireProductionRemapBoundary upperBoundary;
		std::vector<double> values;
		std::vector<double> faceVelocityMPerS;
		std::vector<double> ambientValues;
		bool lineSpecificAmbientValues;
		std::vector<double> lowerAmbientValues;
		std::vector<double> upperAmbientValues;

		FireProductionRemapRequest() : lineLength(0), lineCount(0),
			componentCount(0), cellWidthM(0.0), timeStepS(0.0),
			boundary(FireProductionRemapPeriodic), asymmetricBoundaries(false),
			lowerBoundary(FireProductionRemapPeriodic),
			upperBoundary(FireProductionRemapPeriodic),lineSpecificAmbientValues(false) {}
	};

	struct FireProductionRemapResult
	{
		std::vector<double> updatedValues;
		std::vector<double> faceFluxes;
		std::vector<double> sharedLimiterAlpha;
		double deviceElapsedMS;

		FireProductionRemapResult() : deviceElapsedMS(0.0) {}
	};

	//! Outward-rounded Metal allocation bytes for the request's buffer topology.
	bool FireProductionRemapWorkingSetBytes(
		const FireProductionRemapRequest& request,
		std::uint64_t& bytes );

	bool ValidateFireProductionRemapRequest(
		const FireProductionRemapRequest& request,
		std::string* error=0 );

	//! r124 continuous common-alpha cap. Exposed for independent contract gates.
	double FireProductionContinuousSharedLimiterAlpha(
		double alpha, double headroom, double signedConsumption,
		double center, double envelope ) noexcept;

	//! r127 continuous open-boundary donor transition. Exposed for contract gates.
	double FireProductionContinuousInflowValue(
		double nearest, double ambient, double velocity, bool positiveInflow,
		double cellWidthM, double timeStepS ) noexcept;

	//! Binary32 CPU oracle with the same stored intermediates as the Metal path.
	bool RemapFireProductionCPU(
		const FireProductionRemapRequest& request,
		FireProductionRemapResult& result,
		std::string* error=0 );

	//! Metal implementation. Non-Metal builds fail explicitly without CPU fallback.
	bool RemapFireProductionMetal(
		const FireProductionRemapRequest& request,
		FireProductionRemapResult& result,
		std::string* error=0 );
}

#endif
