// GENERATED by tools/generate_fire_production_fp64_mirror.py.
// Do not edit; run the generator and commit its deterministic output.
//////////////////////////////////////////////////////////////////////
//
//  FireProductionForce.h - strict-binary32 production force primitives
//
//  License Information: Please see the attached LICENSE.TXT file
//
//////////////////////////////////////////////////////////////////////

#ifndef FP64_FIRE_PRODUCTION_FORCE_H
#define FP64_FIRE_PRODUCTION_FORCE_H

#include "FireProductionProjection.h"
#include "FireProductionTransport.h"
#include "../../src/Library/Utilities/FireSimulationRecords.h"

#include <array>
#include <cmath>
#include <cstdint>
#include <cstring>
#include <string>
#include <vector>

namespace RISEFireProductionFP64
{
	//! Shared bound for fail-closed step reductions.  The binary64 trajectory
	//! owner and the production manifold owner use the same rejection budget.
	constexpr unsigned int FireStepRejectionRetryCap=20u;

	struct FireProductionVremanInput
	{
		std::array<double,9> velocityGradientPerS;
		std::array<double,3> directionalWidthsM;
		double coefficient;

		FireProductionVremanInput() : coefficient(0.07)
		{
			velocityGradientPerS.fill(0.0);
			directionalWidthsM.fill(1.0);
		}
	};

	//! Strict-binary32 transcription of the record Vreman expression. The
	//! caller supplies the coefficient obtained from the certified record.
	bool EvaluateFireProductionVremanEddyViscosity(
		const FireProductionVremanInput& input,
		double& eddyViscosityM2PerS,
		std::string* error=0 );

	struct FireProductionViscousSchedule
	{
		std::uint32_t substepCount;
		double substepTimeS;
		double outwardWork;
		double representedProductUpper;

		FireProductionViscousSchedule() : substepCount(0u),substepTimeS(0.0),
			outwardWork(0.0),representedProductUpper(0.0) {}
	};

	//! Host half of the r90/r91 outward stability certificate. Both inputs are
	//! stored fp32 bytes; selection certifies the represented fp32 dt/N and
	//! rejects a required ninth substep before any physical update.
	bool SelectFireProductionViscousSchedule(
		double timeStepS,
		double outwardLambdaPerS,
		FireProductionViscousSchedule& schedule,
		std::string* error=0 );

	struct FireProductionFrozenForceRequest
	{
		FireProductionProjectionShape shape;
		double timeStepS;
		double ambientDensityKGPerM3;
		double vremanCoefficient;
		std::array<double,3> gravityMPerS2;
		std::array<FireProductionProjectionBoundary,6> boundary;
		std::vector<double> cellGasDensityKGPerM3;
		std::vector<double> molecularKinematicViscosityM2PerS;
		std::array<std::vector<double>,3> faceDensityKGPerM3;
		std::array<std::vector<double>,3> beginningMomentumKGPerM2S;

		FireProductionFrozenForceRequest() : timeStepS(0.0),ambientDensityKGPerM3(1.0),
			vremanCoefficient(0.07)
		{
			gravityMPerS2.fill(0.0);
			boundary.fill(FireProductionProjectionPeriodic);
		}
	};

	struct FireProductionFrozenForceResult
	{
		std::vector<double> eddyKinematicViscosityM2PerS;
		std::vector<double> effectiveDynamicViscosityPaS;
		std::array<std::vector<double>,3> beginningViscousMomentumRateKGPerM2S2;
		std::array<std::vector<double>,3> gravityMomentumRateKGPerM2S2;
		std::array<std::vector<double>,3> gravityMomentumIncrementKGPerM2S;
	};

	//! Logical peak of the CPU frozen-force comparator, including caller input,
	//! local work, and the atomically published result payload.
	bool FireProductionFrozenForceWorkingSetBytes(
		const FireProductionProjectionShape& shape,
		std::uint64_t& bytes );

	//! Complete standalone Metal-wrapper peak: live caller/result arrays plus
	//! every MTLBuffer rounded outward to the M4 allocation quantum.
	bool FireProductionFrozenForceMetalWorkingSetBytes(
		const FireProductionProjectionShape& shape,
		std::uint64_t& bytes );

	bool FireProductionResidentForceMetalWorkingSetBytes(
		const FireProductionProjectionShape& shape,
		bool captureIntermediateStates,
		std::uint64_t& bytes );

	//! Conservative force-owned plus resident-P2 peak, including the two target
	//! buffers retained by the composed owner. Used before any Metal allocation.
	bool FireProductionResidentForceProjectionWorkingSetBytes(
		const FireProductionProjectionShape& shape,
		std::uint64_t& bytes );

	bool FireProductionFrozenForceAdvanceWorkingSetBytes(
		const FireProductionProjectionShape& shape,
		std::uint64_t& bytes );

	//! Complete full resident-step certificate. This query is shape/boundary
	//! only so the owner can reject the two-GiB limit before inspecting payloads.
	bool FireProductionResidentStepWorkingSetBytes(
		const FireProductionProjectionShape& shape,
		const std::array<FireProductionProjectionBoundary,6>& boundary,
		std::uint64_t& bytes );

	//! Allocation-free structural and payload preflight shared by every frozen-
	//! force owner. It performs no physical work and publishes no partial state.
	bool ValidateFireProductionFrozenForceRequest(
		const FireProductionFrozenForceRequest& request,
		std::string* error=0 );

	//! Beginning-state, strict-binary32 force field used by the production P3
	//! comparator. Vreman and mu are frozen; viscous rates update only interior
	//! normal faces, relative gravity also owns pressure-open endpoint faces,
	//! and wall-normal endpoints remain prescribed zero.
	bool BuildFireProductionFrozenForceFieldsCPU(
		const FireProductionFrozenForceRequest& request,
		FireProductionFrozenForceResult& result,
		std::string* error=0 );

	//! Instantaneous nonpressure momentum owner for one projected stage state.
	//! The gas-phase source is a cell rate, not a step increment.  Every
	//! published momentum quantity is consequently a rate and is independent of
	//! request.force.timeStepS; the retained time step only serves the legacy
	//! frozen-force increment returned by the shared field builder.
	struct FireProductionNonpressureMomentumRHSRequest
	{
		FireProductionFrozenForceRequest force;
		std::vector<double> cellGasPhaseSourceRateKGPerM3S;
	};

	struct FireProductionNonpressureMomentumRHSResult
	{
		std::vector<double> eddyKinematicViscosityM2PerS;
		std::vector<double> effectiveDynamicViscosityPaS;
		std::array<std::vector<double>,3> buoyancyMomentumRateKGPerM2S2;
		std::array<std::vector<double>,3> stressMomentumRateKGPerM2S2;
		std::array<std::vector<double>,3> phaseSourceMomentumRateKGPerM2S2;
		std::array<std::vector<double>,3> combinedMomentumRateKGPerM2S2;
	};

	//! Evaluate buoyancy, Vreman stress divergence, and compatible phase-source
	//! momentum at the supplied stage state without advancing momentum.
	bool EvaluateFireProductionNonpressureMomentumRHSCPU(
		const FireProductionNonpressureMomentumRHSRequest& request,
		FireProductionNonpressureMomentumRHSResult& result,
		std::string* error=0 );

	//! Ordered stages of the complete Section 3.7 projected-Heun owner.  These
	//! values are identity-bearing protocol ordinals, not interchangeable labels.
	enum class FireProductionProjectedHeunStage : std::uint8_t
	{
		R0=1u,
		R1=2u,
		R2=3u
	};

	struct FireProductionProjectedHeunTransportContext
	{
		FireProductionProjectedHeunStage stage;
		std::uint64_t attemptIdentity;
		std::uint64_t parentCandidateIdentity;
		std::uint64_t projectionIdentity;
		const std::vector<double>* conservativeValues;
		const std::vector<double>* temperatureK;
		const std::array<std::vector<double>,3>* projectedVelocityMPerS;

		FireProductionProjectedHeunTransportContext() :
			stage(static_cast<FireProductionProjectedHeunStage>(0u)),attemptIdentity(0u),
			parentCandidateIdentity(0u),projectionIdentity(0u),conservativeValues(0),temperatureK(0),
			projectedVelocityMPerS(0) {}
	};

	//! Stage transport publication.  The echoed protocol lineage is checked
	//! before any coefficient can enter f_N, A-hat, or the next Picard iterate.
	struct FireProductionProjectedHeunTransportCoefficients
	{
		FireProductionProjectedHeunStage stage;
		std::uint64_t attemptIdentity;
		std::uint64_t parentCandidateIdentity;
		std::uint64_t projectionIdentity;
		std::uint64_t publicationIdentity;
		std::vector<double> diffusivityM2PerS;
		std::vector<double> conductivityWPerMK;
		std::vector<double> molecularKinematicViscosityM2PerS;

		FireProductionProjectedHeunTransportCoefficients() :
			stage(static_cast<FireProductionProjectedHeunStage>(0u)),attemptIdentity(0u),
			parentCandidateIdentity(0u),projectionIdentity(0u),publicationIdentity(0u) {}
	};

	//! Identity of the exact projected state, coefficient payload, and protocol
	//! parents. A provider that replays stale bytes cannot retain a current seal.
	std::uint64_t FireProductionProjectedHeunTransportPublicationIdentity(
		const FireProductionProjectedHeunTransportContext& context,
		const FireProductionProjectedHeunTransportCoefficients& result );

	class FireProductionProjectedHeunTransportProvider
	{
	public:
		virtual ~FireProductionProjectedHeunTransportProvider() {}
		virtual bool Evaluate(
			const FireProductionProjectedHeunTransportContext& context,
			FireProductionProjectedHeunTransportCoefficients& result,
			std::string* error=0 ) const=0;
	};

	//! Raw step inputs plus invariant scalar/force contracts.  State-, velocity-,
	//! target-, classification-, coefficient-, and force-owned arrays in the
	//! template requests must be empty: the owner fills them from the immediately
	//! preceding authenticated publication.
	struct FireProductionProjectedHeunOwnerRequest
	{
		std::uint64_t attemptIdentity;
		FireProductionFrozenSourcePacketSeal source;
		RISE::RISECBOR64::Bytes caseRecordEnvelope;
		std::vector<double> beginningConservativeValues;
		std::array<std::vector<double>,3> beginningMomentumKGPerM2S;
		FireProductionScalarFCTRequest scalarContract;
		FireProductionScalarPhysicalFluxPrerequisiteRequest physicalContract;
		FireProductionFrozenForceRequest forceContract;
		double projectionTolerancePerS;
		double endpointVelocityToleranceMPerS;
		std::uint32_t maximumPicardIterations;
		//! Qualification-only Picard-map trace.  It never changes an accepted
		//! state or its owner identity; the sealed evidence artifact binds it.
		bool qualificationCaptureIterationTrace;

		FireProductionProjectedHeunOwnerRequest() : attemptIdentity(0u),
			projectionTolerancePerS(0.0),endpointVelocityToleranceMPerS(0.0),
			maximumPicardIterations(64u),qualificationCaptureIterationTrace(false) {}
	};

	//! One evaluation of the coupled Picard map.  The fields are the actual
	//! operands consumed by that evaluation, before any terminal publication.
	//! This is qualification evidence, not a second authority surface.
	struct FireProductionProjectedHeunIterationTrace
	{
		std::uint32_t iteration;
		std::vector<double> projectionTargetPerS;
		std::vector<double> producedTargetPerS;
		std::array<std::vector<unsigned char>,6> activeClass;
		std::array<std::vector<unsigned char>,6> nextActiveClass;
		std::array<std::vector<double>,3> sharedFaceAlpha;
		std::array<std::vector<double>,3> projectedVelocityMPerS;
		//! Force-inclusive momentum consumed by this exact projection application.
		//! Qualification captures it so the projection enclosure walks the actual
		//! resident DAG instead of substituting an output-derived norm estimate.
		std::array<std::vector<double>,3> provisionalMomentumKGPerM2S;
		//! R2's sealed physical-open head; empty on R0/R1 where the projection
		//! derives its current open head from the same provisional state.
		std::array<std::vector<double>,6> sealedPressureOpenDynamicPressurePa;
		std::vector<double> transportConservativeValues;
		//! Candidate published by this Picard-map evaluation.  The qualification
		//! trace binds these bytes to acceptedCandidateIdentity so the next stage's
		//! input chord cannot be self-authored or swapped.
		std::vector<double> acceptedConservativeValues;
		std::uint64_t acceptedCandidateIdentity;
		std::vector<double> transportTemperatureK;
		std::vector<double> diffusivityM2PerS;
		std::vector<double> conductivityWPerMK;
		std::vector<double> molecularKinematicViscosityM2PerS;
		std::vector<double> gasDensityKGPerM3;
		//! Exact resident low-order and antidiffusive candidates consumed by the
		//! scalar limiter.  Qualification uses these device-produced bytes to bind
		//! the accepted-state enclosure to the actual coupled trajectory.
		std::vector<double> scalarLowFlux;
		std::vector<double> scalarFluxDelta;
		std::vector<double> physicalMassFluxKGPerM2S;
		std::vector<double> physicalEnergyFluxWPerM2;
		std::vector<double> representedPressureRatio;
		std::array<std::vector<double>,3> faceDensityKGPerM3;
		std::array<std::vector<double>,3> projectedMomentumKGPerM2S;
		//! Separately captured parents of the force-inclusive provisional
		//! momentum.  They are qualification evidence for the owner DAG: the
		//! projection input may not author its own comparison radius.
		std::array<std::vector<double>,3> advectionMomentumRateKGPerM2S2;
		std::array<std::vector<double>,3> buoyancyMomentumRateKGPerM2S2;
		std::array<std::vector<double>,3> stressMomentumRateKGPerM2S2;
		std::array<std::vector<double>,3> phaseSourceMomentumRateKGPerM2S2;
		double maximumPostProjectionResidualPerS;

		FireProductionProjectedHeunIterationTrace() : iteration(0u),
			acceptedCandidateIdentity(0u),
			maximumPostProjectionResidualPerS(0.0) {}
	};

	struct FireProductionProjectedHeunCoupledStageResult
	{
		FireProductionProjectedHeunStage stage;
		FireProductionProjectionResult projection;
		FireProductionScalarHeunFluxStage flux;
		FireProductionScalarPhysicalFluxPrerequisiteResult endpointPhysicalFlux;
		FireProductionScalarFCTResult scalarAcceptance;
		FireProductionNonpressureMomentumRHSResult nonpressure;
		//! Exact input seal consumed by projection. `target` is the Picard-map
		//! output produced from this projection and the accepted candidate.
		FireProductionScalarProjectionTargetSeal projectionTarget;
		FireProductionScalarProjectionTargetSeal target;
		std::vector<double> picardResidualPerS;
		std::vector<FireProductionProjectedHeunIterationTrace> qualificationIterationTrace;
		std::uint64_t parentCandidateIdentity;
		std::uint64_t acceptedCandidateIdentity;
		std::uint32_t acceptedIterationCount;
		std::uint32_t activeSetCycleLength;
		std::uint32_t activeSetDifferingFaceCount;
		std::uint32_t activeSetCanonicalProjectionCount;
		double maximumActiveSetComplementarityDiscrepancyMPerS;
		double maximumLimiterClassDiscrepancy;
		bool activeSetDiscontinuousClass;
		bool limiterDiscontinuousClass;

		FireProductionProjectedHeunCoupledStageResult() :
			stage(static_cast<FireProductionProjectedHeunStage>(0u)),
			parentCandidateIdentity(0u),acceptedCandidateIdentity(0u),
			acceptedIterationCount(0u),activeSetCycleLength(0u),
			activeSetDifferingFaceCount(0u),activeSetCanonicalProjectionCount(0u),
			maximumActiveSetComplementarityDiscrepancyMPerS(0.0),
			maximumLimiterClassDiscrepancy(0.0),activeSetDiscontinuousClass(false),
			limiterDiscontinuousClass(false) {}
	};

	//! Complete simultaneous host live-set certificate for the staged owner.
	bool FireProductionProjectedHeunCPUOwnerWorkingSetBytes(
		const FireProductionProjectionShape& shape,std::uint64_t& bytes );

	//! r60 permits rounding-scale negative constituent rows.  Gas density is
	//! therefore the signed sum of the six represented gas rows; per-row clamps
	//! would silently change the momentum/projection operand.
	bool ComputeFireProductionGasDensityCPU(
		const FireProductionProjectionShape& shape,
		const std::vector<double>& conservativeValues,
		std::vector<double>& gasDensityKGPerM3,
		std::string* error=0 );

	struct FireProductionProjectedHeunOwnerResult
	{
		std::vector<double> conservativeValues;
		std::array<std::vector<double>,3> momentumKGPerM2S;
		std::array<std::vector<double>,3> velocityMPerS;
		std::vector<double> stepAveragePressurePa;
		FireProductionScalarEOSAcceptanceResult predictorEOS;
		FireProductionScalarEOSAcceptanceResult committedEOS;
		FireProductionScalarHeunFluxStage averagedFlux;
		FireProductionScalarHeunSolveResult heunSolve;
		FireProductionProjectedHeunCoupledStageResult r0,r1,r2;
		std::uint64_t sourcePacketIdentity;
		bool accepted;

		FireProductionProjectedHeunOwnerResult() : sourcePacketIdentity(0u),
			accepted(false),ownerIdentity_(0u) {}

		//! Opaque acceptance seal minted only by the complete owner.  Publication
		//! payloads remain inspectable, but a client cannot re-sign mutated bytes.
		std::uint64_t OwnerIdentity() const { return ownerIdentity_; }

	private:
		std::uint64_t ownerIdentity_;
		friend class FireProductionProjectedHeunCPUOwner;
		friend bool FireProductionProjectedHeunOwnerResultMatches(
			const FireProductionProjectedHeunOwnerResult&,
			const FireProductionFrozenSourcePacketSeal& );
	};

	//! Recomputes the complete publication identity against the exact source
	//! packet expected by the current attempt. The diagnostic struct alone
	//! carries no acceptance power, and a prior attempt cannot be replayed.
	bool FireProductionProjectedHeunOwnerResultMatches(
		const FireProductionProjectedHeunOwnerResult& result,
		const FireProductionFrozenSourcePacketSeal& expectedSource );

	bool FireProductionNonpressureMomentumRHSWorkingSetBytes(
		const FireProductionProjectionShape& shape,
		std::uint64_t& bytes );

	struct FireProductionNonpressureMomentumRHSMetalDiagnostics
	{
		std::uint32_t commandCommitCount;
		std::uint32_t interstageFullGridTransferCount;
		std::uint32_t terminalStagingCount;
		std::uint64_t certifiedWorkingSetBytes;
		std::uint64_t actualMetalAllocationBytes;
		double deviceElapsedMS;

		FireProductionNonpressureMomentumRHSMetalDiagnostics() : commandCommitCount(0u),
			interstageFullGridTransferCount(0u),terminalStagingCount(0u),
			certifiedWorkingSetBytes(0u),actualMetalAllocationBytes(0u),deviceElapsedMS(0.0) {}
	};

	bool FireProductionNonpressureMomentumRHSMetalWorkingSetBytes(
		const FireProductionProjectionShape& shape,
		std::uint64_t& bytes );

	//! One-command Private-buffer stage evaluator.  Inputs upload before the
	//! first kernel and the six published rate/diagnostic fields stage only after
	//! every dependent kernel, so no full-grid host transfer can occur between
	//! setup, Vreman stress, face force, and phase-source composition.
	bool EvaluateFireProductionNonpressureMomentumRHSMetal(
		const FireProductionNonpressureMomentumRHSRequest& request,
		FireProductionNonpressureMomentumRHSResult& result,
		FireProductionNonpressureMomentumRHSMetalDiagnostics& diagnostics,
		std::string* error=0 );

	//! Live Metal counterpart of the complete r190 projected-Heun owner.  The
	//! target-lineage request supplies the canonical device bootstrap operands;
	//! beginning momentum is the sole additional full-grid step input.  The
	//! qualification switches are RED-only and cannot select an alternate live
	//! algorithm.
	struct FireProductionProjectedHeunMetalOwnerRequest
	{
		FireProductionResidentTargetLineageComparatorRequest lineage;
		std::array<std::vector<double>,3> beginningMomentumKGPerM2S;
		double ambientDensityKGPerM3;
		double vremanCoefficient;
		std::array<double,3> gravityMPerS2;
		double projectionTolerancePerS;
		double endpointVelocityToleranceMPerS;
		std::uint32_t maximumPicardIterations;
		bool qualificationStaleCandidate;
		bool qualificationOutOfOrderStage;
		bool qualificationForgedLineage;
		bool qualificationCallbackMutation;
		bool qualificationAtomicPublicationFailure;
		bool qualificationInjectInterstageTransfer;
		bool qualificationDivergentManifoldPolicy;
		bool qualificationStaleTargetPublication;
		bool qualificationUnverifiedPrivateLineageBuffer;
		//! Active-set and limiter control-flow REDs.  A value 1, 2, or 3 forces
		//! the r190 two-class cycle at R0, R1, or R2 respectively; zero is live.
		std::uint32_t qualificationForcedActiveCycleStage;
		bool qualificationDisableCanonicalCycle;
		bool qualificationForceLimiterDiscontinuity;
		bool qualificationDisableLimiterCertification;
		//! RED-only owner mutations.  The first restores the rejected 3/4--1/4
		//! tableau; the second restores the rejected mixed-alpha R0 cache.
		bool qualificationThreeQuarterHeunWeighting;
		bool qualificationReuseR0LimiterAlpha;
		//! Substitutes R1's high candidate for the sealed R0 donor input to the
		//! resident Heun average.  The numerical gate must reject the valid-looking
		//! but semantically wrong parent trajectory.
		bool qualificationWrongAveragedFluxParent;
		//! Restores the rejected R2 schedule defect: physical flux consumes the
		//! sealed projection-input class instead of the force-inclusive
		//! projection's immediately derived endpoint class.
		bool qualificationR2SealedClassPhysicalFlux;
		//! Replaces the class buffer after its device identity was issued.  The
		//! physical-flux authority must refuse it before any publication.
		bool qualificationUnverifiedEndpointClassBuffer;
		bool qualificationCaptureIterationTrace;
		//! Zero uses the certified cap.  A nonzero smaller cap proves that the
		//! complete-owner working set is refused before Metal work begins.
		std::uint64_t qualificationWorkingSetLimitBytes;

		FireProductionProjectedHeunMetalOwnerRequest() : ambientDensityKGPerM3(1.0),
			vremanCoefficient(0.07),projectionTolerancePerS(0.0),
			endpointVelocityToleranceMPerS(0.0),maximumPicardIterations(64u),
			qualificationStaleCandidate(false),qualificationOutOfOrderStage(false),
			qualificationForgedLineage(false),qualificationCallbackMutation(false),
			qualificationAtomicPublicationFailure(false),
			qualificationInjectInterstageTransfer(false),
			qualificationDivergentManifoldPolicy(false),
			qualificationStaleTargetPublication(false),
			qualificationUnverifiedPrivateLineageBuffer(false),
			qualificationForcedActiveCycleStage(0u),
			qualificationDisableCanonicalCycle(false),
			qualificationForceLimiterDiscontinuity(false),
			qualificationDisableLimiterCertification(false),
			qualificationThreeQuarterHeunWeighting(false),
			qualificationReuseR0LimiterAlpha(false),
			qualificationWrongAveragedFluxParent(false),
			qualificationR2SealedClassPhysicalFlux(false),
			qualificationUnverifiedEndpointClassBuffer(false),
			qualificationCaptureIterationTrace(false),
			qualificationWorkingSetLimitBytes(0u)
		{ gravityMPerS2.fill(0.0); }
	};

	struct FireProductionProjectedHeunMetalOwnerResult
	{
		std::vector<double> conservativeValues;
		std::array<std::vector<double>,3> momentumKGPerM2S;
		std::array<std::vector<double>,3> velocityMPerS;
		std::array<std::vector<double>,3> provisionalMomentumKGPerM2S;
		std::array<std::vector<double>,3> heunAdvectionMomentumRateKGPerM2S2;
		std::array<std::vector<double>,3> heunBuoyancyMomentumRateKGPerM2S2;
		std::array<std::vector<double>,3> heunStressMomentumRateKGPerM2S2;
		std::array<std::vector<double>,3> heunPhaseSourceMomentumRateKGPerM2S2;
		std::vector<double> acceptedFaceAlpha;
		std::vector<double> heunEddyKinematicViscosityM2PerS;
		FireProductionProjectionResult projection;
		std::vector<double> temperatureK;
		std::vector<double> representedPressureRatio;
		std::vector<double> absoluteEOSDeviation;
		std::array<std::vector<double>,3> projectionTargetPerS;
		std::array<std::vector<double>,3> acceptedTargetPerS;
		std::array<std::vector<double>,3> picardResidualPerS;
		std::array<std::vector<FireProductionProjectedHeunIterationTrace>,3>
			qualificationIterationTrace;
		std::array<std::uint32_t,3> projectionTargetCorrectionIteration;
		std::array<std::uint32_t,3> acceptedTargetCorrectionIteration;
		std::array<std::uint32_t,3> acceptedPicardIterations;
		std::array<std::uint32_t,3> activeSetCycleLength;
		std::array<std::uint32_t,3> activeSetCanonicalProjectionCount;
		std::array<bool,3> activeSetDiscontinuousClass;
		std::array<bool,3> limiterDiscontinuousClass;
		std::array<std::uint64_t,3> projectionPublicationIdentity;
		std::array<std::uint64_t,3> transportPublicationIdentity;
		std::array<std::uint64_t,3> physicalFluxPublicationIdentity;
		std::array<std::uint64_t,3> candidatePublicationIdentity;
		std::array<std::uint64_t,3> EOSPublicationIdentity;
		std::array<std::uint64_t,3> frozenSourcePublicationIdentity;
		std::array<std::uint64_t,3> targetPublicationIdentity;
		std::uint64_t ownerPublicationIdentity;
		std::uint32_t commandCommitCount;
		std::uint32_t interstageFullGridTransferCount;
		std::uint32_t terminalStagingCount;
		std::uint32_t qualificationTraceStagingCount;
		std::uint32_t residentProjectionInvocationCount;
		std::uint64_t certifiedWorkingSetBytes;
		std::uint64_t actualMetalAllocationBytes;
		double deviceElapsedMS;
		double wallElapsedMS;
		double residentProjectionDeviceElapsedMS;
		double residentNonprojectionDeviceElapsedMS;
		double maximumCommutingResidualKGPerM3;
		double commutingIdentityScaleKGPerM3;
		double commutingIdentityBoundKGPerM3;
		bool commutingIdentityPassed;
		bool accepted;

		FireProductionProjectedHeunMetalOwnerResult() : ownerPublicationIdentity(0u),
			commandCommitCount(0u),interstageFullGridTransferCount(0u),
			terminalStagingCount(0u),qualificationTraceStagingCount(0u),
			residentProjectionInvocationCount(0u),
			certifiedWorkingSetBytes(0u),actualMetalAllocationBytes(0u),
			deviceElapsedMS(0.0),wallElapsedMS(0.0),residentProjectionDeviceElapsedMS(0.0),
			residentNonprojectionDeviceElapsedMS(0.0),maximumCommutingResidualKGPerM3(0.0),
			commutingIdentityScaleKGPerM3(0.0),commutingIdentityBoundKGPerM3(0.0),
			commutingIdentityPassed(false),accepted(false)
		{
			acceptedPicardIterations.fill(0u);projectionPublicationIdentity.fill(0u);
			projectionTargetCorrectionIteration.fill(0u);
			acceptedTargetCorrectionIteration.fill(0u);
			activeSetCycleLength.fill(0u);activeSetCanonicalProjectionCount.fill(0u);
			activeSetDiscontinuousClass.fill(false);limiterDiscontinuousClass.fill(false);
			transportPublicationIdentity.fill(0u);physicalFluxPublicationIdentity.fill(0u);
			candidatePublicationIdentity.fill(0u);EOSPublicationIdentity.fill(0u);
			frozenSourcePublicationIdentity.fill(0u);targetPublicationIdentity.fill(0u);
		}
	};

	bool FireProductionProjectedHeunMetalOwnerWorkingSetBytes(
		const FireProductionProjectionShape& shape,std::uint64_t& bytes );

	bool AttemptFireProductionProjectedHeunMetalOwner(
		const FireProductionProjectedHeunMetalOwnerRequest& request,
		FireProductionProjectedHeunMetalOwnerResult& result,
		std::string* error=0 );

	//! Standalone Metal comparison wrapper for the same beginning-state frozen
	//! fields. Platforms without Metal fail honestly; no CPU fallback is hidden
	//! behind this entry point. The later resident P3 seam reuses these kernels.
	bool BuildFireProductionFrozenForceFieldsMetal(
		const FireProductionFrozenForceRequest& request,
		FireProductionFrozenForceResult& result,
		double& deviceElapsedMS,
		std::string* error=0 );

	struct FireProductionFrozenForceAdvanceResult
	{
		FireProductionFrozenForceResult frozenFields;
		FireProductionViscousSchedule schedule;
		std::array<std::vector<double>,3> momentumKGPerM2S;
		std::array<std::uint64_t,8> intermediateMomentumByteDigests;
		std::uint32_t intermediateMomentumDigestCount;
		std::uint32_t executedViscousSubstepCount;

		FireProductionFrozenForceAdvanceResult() :
			intermediateMomentumDigestCount(0u),executedViscousSubstepCount(0u)
		{
			intermediateMomentumByteDigests.fill(0u);
		}
	};

	//! Strict-binary32 force comparator after the resident preflight has supplied
	//! its outward Lambda scalar. mu_eff and face density stay frozen through all
	//! viscous substeps; relative gravity is added exactly once afterward.
	bool AdvanceFireProductionFrozenForceCPU(
		const FireProductionFrozenForceRequest& request,
		double outwardLambdaPerS,
		FireProductionFrozenForceAdvanceResult& result,
		std::string* error=0 );

	struct FireProductionResidentForceDiagnostics
	{
		double outwardLambdaPerS;
		std::uint32_t scalarDiagnosticTransferCount;
		std::uint32_t substepLoopDeviceToHostTransferCount;
		std::uint32_t terminalStagingCount;
		std::uint32_t commandCommitCount;
		std::uint64_t certifiedWorkingSetBytes;
		std::uint64_t actualMetalAllocationBytes;
		double preflightDeviceElapsedMS;
		double advanceDeviceElapsedMS;
		double deviceStartTimeS;
		double deviceEndTimeS;

		FireProductionResidentForceDiagnostics() : outwardLambdaPerS(0.0),
			scalarDiagnosticTransferCount(0u),substepLoopDeviceToHostTransferCount(0u),
			terminalStagingCount(0u),commandCommitCount(0u),certifiedWorkingSetBytes(0u),
			actualMetalAllocationBytes(0u),preflightDeviceElapsedMS(0.0),
			advanceDeviceElapsedMS(0.0),deviceStartTimeS(0.0),deviceEndTimeS(0.0) {}
	};

	//! Standalone oracle wrapper around the resident force sequence. Full-grid
	//! resources remain Private through every viscous substep and the gravity
	//! update. Optional Private snapshots stage only after command completion.
	bool AdvanceFireProductionFrozenForceMetal(
		const FireProductionFrozenForceRequest& request,
		bool captureIntermediateStates,
		FireProductionFrozenForceAdvanceResult& result,
		FireProductionResidentForceDiagnostics& diagnostics,
		std::string* error=0 );

	//! Oracle wrapper for the no-staging resident-state branch. It performs one
	//! terminal momentum tap after the resident call and leaves the force
	//! diagnostics' terminal-staging count at zero for that measured interval.
	bool AdvanceFireProductionFrozenForceMetalResidentStateComparator(
		const FireProductionFrozenForceRequest& request,
		FireProductionFrozenForceAdvanceResult& result,
		FireProductionResidentForceDiagnostics& diagnostics,
		std::string* error=0 );

#if defined(__OBJC__) && defined(__APPLE__)
	struct FireProductionMetalNonpressureMomentumRHSResidentInput
	{
		FireProductionProjectionShape shape;
		double ambientDensityKGPerM3;
		double vremanCoefficient;
		std::array<double,3> gravityMPerS2;
		std::array<FireProductionProjectionBoundary,6> boundary;
		id<MTLCommandBuffer> commandBuffer;
		id<MTLBuffer> cellGasDensityKGPerM3;
		id<MTLBuffer> molecularKinematicViscosityM2PerS;
		id<MTLBuffer> cellGasPhaseSourceRateKGPerM3S;
		id<MTLBuffer> packedFaceDensityKGPerM3;
		id<MTLBuffer> packedMomentumKGPerM2S;

		FireProductionMetalNonpressureMomentumRHSResidentInput() :
			ambientDensityKGPerM3(1.0),vremanCoefficient(0.07),commandBuffer(nil),
			cellGasDensityKGPerM3(nil),molecularKinematicViscosityM2PerS(nil),
			cellGasPhaseSourceRateKGPerM3S(nil),packedFaceDensityKGPerM3(nil),
			packedMomentumKGPerM2S(nil)
		{
			gravityMPerS2.fill(0.0);boundary.fill(FireProductionProjectionPeriodic);
		}
	};

	struct FireProductionMetalNonpressureMomentumRHSResidentResult
	{
		id<MTLBuffer> eddyKinematicViscosityM2PerS;
		id<MTLBuffer> effectiveDynamicViscosityPaS;
		id<MTLBuffer> buoyancyMomentumRateKGPerM2S2;
		id<MTLBuffer> stressMomentumRateKGPerM2S2;
		id<MTLBuffer> phaseSourceMomentumRateKGPerM2S2;
		id<MTLBuffer> combinedMomentumRateKGPerM2S2;
		// Command-lifetime owners for the intermediates consumed by the rates.
		id<MTLBuffer> faceVelocityMPerS;
		id<MTLBuffer> cellVelocityMPerS;
		id<MTLBuffer> stressTensorPa;
		id<MTLBuffer> parameterBuffer;
		std::uint64_t privateAllocationBytes;

		FireProductionMetalNonpressureMomentumRHSResidentResult() :
			eddyKinematicViscosityM2PerS(nil),effectiveDynamicViscosityPaS(nil),
			buoyancyMomentumRateKGPerM2S2(nil),stressMomentumRateKGPerM2S2(nil),
			phaseSourceMomentumRateKGPerM2S2(nil),combinedMomentumRateKGPerM2S2(nil),
			faceVelocityMPerS(nil),cellVelocityMPerS(nil),stressTensorPa(nil),
			parameterBuffer(nil),
			privateAllocationBytes(0u) {}
	};

	//! Encode the complete stage RHS into a caller-owned command buffer.  Every
	//! input and output is Private; this call neither commits nor stages.
	bool EvaluateFireProductionNonpressureMomentumRHSMetalResident(
		const FireProductionMetalNonpressureMomentumRHSResidentInput& input,
		FireProductionMetalNonpressureMomentumRHSResidentResult& result,
		FireProductionNonpressureMomentumRHSMetalDiagnostics& diagnostics,
		std::string* error=0 );

	struct FireProductionMetalFrozenForceResidentState
	{
		id<MTLBuffer> cellGasDensityKGPerM3;
		id<MTLBuffer> packedFaceDensityKGPerM3;
		id<MTLBuffer> packedMomentumKGPerM2S;
		std::array<std::size_t,3> faceByteOffset;
		FireProductionViscousSchedule schedule;
		FireProductionResidentForceDiagnostics diagnostics;

		FireProductionMetalFrozenForceResidentState() : cellGasDensityKGPerM3(nil),
			packedFaceDensityKGPerM3(nil),packedMomentumKGPerM2S(nil)
		{
			faceByteOffset.fill(0u);
		}
	};

	//! Internal full-grid Private state seam. It executes preflight, every
	//! selected viscous substep, and gravity, then returns the still-resident
	//! density/momentum owners without terminal staging or projection.
	bool AdvanceFireProductionFrozenForceMetalResidentState(
		const FireProductionFrozenForceRequest& request,
		FireProductionMetalFrozenForceResidentState& state,
		std::string* error=0 );
#endif

	struct FireProductionResidentForceProjectionResult
	{
		FireProductionViscousSchedule forceSchedule;
		FireProductionProjectionResult projection;
		FireProductionResidentForceDiagnostics forceDiagnostics;
		std::uint32_t forceToProjectionDeviceToHostTransferCount;
		std::uint32_t residentProjectionInvocationCount;
		std::uint64_t combinedCertifiedWorkingSetBytes;
		std::uint64_t combinedActualMetalAllocationBytes;

		FireProductionResidentForceProjectionResult() :
			forceToProjectionDeviceToHostTransferCount(0u),residentProjectionInvocationCount(0u),
			combinedCertifiedWorkingSetBytes(0u),combinedActualMetalAllocationBytes(0u) {}
	};

	//! Resident production seam: frozen force substeps, gravity, and exactly one
	//! P2 projection without a full-grid host transfer between the operators.
	bool AdvanceFireProductionForceProjectionMetal(
		const FireProductionFrozenForceRequest& forceRequest,
		const std::vector<double>& divergenceTargetPerS,
		FireProductionResidentForceProjectionResult& result,
		std::string* error=0 );

	struct FireProductionResidentStepRequest
	{
		FireProductionFrozenForceRequest force;
		FireProductionCellPalindromeRequest cellTransport;
		FireProductionDualMomentumRequest dualTransport;
		std::vector<double> cellSourceIncrement;
		std::array<std::vector<double>,3> momentumSourceIncrement;
		std::vector<double> divergenceTargetPerS;
		std::vector<double> restorationDivergenceTargetPerS;
		std::vector<double> beginningManifoldDeviationPerCell;
		std::uint32_t physicalOpenProjectionVCycleCount;
		bool monitorManifoldDiagnostics;
		bool enforceManifoldPlateau;
		bool restoreManifoldOutliers;

		FireProductionResidentStepRequest() : physicalOpenProjectionVCycleCount(17u),
			monitorManifoldDiagnostics(true),enforceManifoldPlateau(false),
			restoreManifoldOutliers(true) {}
	};

	//! Stability-class boundary for monitored production.  The ordinary policy
	//! leaves the bulk manifold untouched, drains only the tail beyond 2^-4,
	//! and atomically refuses a beginning state beyond the 2^-2 dynamics bound.
	struct FireProductionManifoldTailTarget
	{
		std::vector<double> divergenceTargetPerS;
		std::uint32_t outlierCellCount;
		double excessSum;
		double drainedVolumeM3;
		double maximumTargetMagnitudePerS;

		FireProductionManifoldTailTarget() : outlierCellCount(0u),excessSum(0.0),
			drainedVolumeM3(0.0),maximumTargetMagnitudePerS(0.0) {}
	};
	bool DeriveFireProductionManifoldTailTarget(
		const std::vector<double>& beginningDeviationPerCell,
		double representedTimeStepS,double cellWidthM,
		FireProductionManifoldTailTarget&,std::string* error=0,
		double engagementThreshold=0x1p-4 );

	class FireProductionAcceptedManifoldObservation;
	struct FireProductionAcceptedCheckpointStateView
	{
		FireProductionProjectionShape shape;
		const std::vector<double>* conservativeValues;
		const std::array<std::vector<double>,3>* momentum;
		const std::array<std::vector<double>,3>* velocity;

		FireProductionAcceptedCheckpointStateView() : conservativeValues(0),momentum(0),velocity(0) {}
	};
	struct FireProductionAcceptedCheckpointLifecycleView
	{
		double simulationTimeS,previousStepS,lastAcceptedStepS;
		std::uint64_t acceptedSteps;
		bool productionState;
		const std::vector<double>* acceptedTimeStepHistoryS;

		FireProductionAcceptedCheckpointLifecycleView() : simulationTimeS(0.0),previousStepS(0.0),
			lastAcceptedStepS(0.0),acceptedSteps(0u),productionState(false),
			acceptedTimeStepHistoryS(0) {}
	};
	class FireProductionCheckpointManifoldAccess final
	{
	public:
		//! Reopens and independently validates the complete v12 checkpoint
		//! payload before restoring its trailing manifold record.  There is no
		//! public raw-tuple restoration seam.
		static bool RestoreValidatedCheckpointFile(
			const std::string&,std::uint64_t,std::uint64_t,std::uint64_t,
			const FireProductionAcceptedCheckpointStateView&,
			const FireProductionAcceptedCheckpointLifecycleView&,
			FireProductionAcceptedManifoldObservation&,std::string* );
	private:
		FireProductionCheckpointManifoldAccess()=delete;
	};
	struct FireProductionStableTimeStep;
	struct FireProductionResidentStepResult;

	class FireProductionAcceptedManifoldObservation
	{
	public:
		FireProductionAcceptedManifoldObservation() : available_(false),timeStepS_(0.0),
			maximumGeneration_(0.0),restorationDrainFraction_(0.0),
			residentPayloadDigest_(0u),acceptedStateDigest_(0u),acceptedStateDigestVersion_(0u),
			bindsResidentPayload_(false) {}
		bool Available() const { return available_; }
		double TimeStepS() const { return timeStepS_; }
		double MaximumGeneration() const { return maximumGeneration_; }
		double RestorationDrainFraction() const { return restorationDrainFraction_; }
		std::uint64_t SerializedAcceptedStateDigest() const { return acceptedStateDigest_; }
		bool MatchesAcceptedResidentPayload(const FireProductionResidentStepResult&) const;
		bool MatchesAcceptedStatePayload(const FireProductionProjectionShape&,
			const std::vector<double>&,const std::array<std::vector<double>,3>&,
			const std::array<std::vector<double>,3>&) const;

	private:
		void Clear() { available_=false;timeStepS_=0.0;maximumGeneration_=0.0;
			restorationDrainFraction_=0.0;residentPayloadDigest_=0u;
			acceptedStateDigest_=0u;acceptedStateDigestVersion_=0u;bindsResidentPayload_=false; }
		bool available_;
		double timeStepS_;
		double maximumGeneration_;
		double restorationDrainFraction_;
		std::uint64_t residentPayloadDigest_;
		std::uint64_t acceptedStateDigest_;
		unsigned int acceptedStateDigestVersion_;
		bool bindsResidentPayload_;
		friend class FireProductionCheckpointManifoldAccess;
		friend bool SelectFireProductionStableTimeStep(
			double,double,double,double,double,
			const FireProductionAcceptedCheckpointStateView&,
			const FireProductionAcceptedManifoldObservation&,
			FireProductionStableTimeStep&,std::string* );
	};

	struct FireProductionStableTimeStep
	{
		double seconds;
		const char* activeLimit;

		FireProductionStableTimeStep() : seconds(0.0),activeLimit(0) {}
	};
	//! Pure r143 predictor arithmetic for diagnostics and the authority-bearing
	//! selector.  It does not confer accepted-observation authority.
	bool DeriveFireProductionManifoldTimeStep(
		double previousStepS,double maximumGeneration,double restorationDrainFraction,
		double& timeStepS,std::string* error=0 );
	//! Predictive production-campaign handoff.  The first Binary32 step uses the
	//! sealed audit observation directly; later steps use the accepted-step
	//! drain-aware predictor above.
	bool DeriveFireProductionInitialManifoldTimeStep(
		double auditTimeStepS,double auditMaximumGeneration,
		double& timeStepS,std::string* error=0 );

	//! Exact scalar topology consumed by the resident predictor/fold kernels.
	//! It replaces the beginning-state target with the predictor-state target.
	bool DeriveFireProductionAdvectiveAnomalyTarget(
		double beginningDeviation,double predictedDeviation,
		double representedTimeStepS,double inheritedTargetPerS,
		double& correctedTargetPerS,std::string* error=0 );

	//! Selects the production step from the CFL family, the 1.1 growth cap, and
	//! the r143 accepted-step manifold observation.  An unavailable observation
	//! is valid only for the first step of a run.
	bool SelectFireProductionStableTimeStep(
		double cellWidthM,
		double maximumVelocityMPerS,
		double maximumPositiveReducedGravityMPerS2,
		double maximumKinematicTransportM2PerS,
		double previousStepS,
		const FireProductionAcceptedCheckpointStateView& currentAcceptedState,
		const FireProductionAcceptedManifoldObservation& previousManifold,
		FireProductionStableTimeStep& result,
		std::string* error=0 );

	struct FireProductionResidentStepResult
	{
		std::vector<double> conservativeValues;
		FireProductionDualMomentumResult transportedDual;
		FireProductionProjectionResult physicalProjection;
		FireProductionProjectionResult projection;
		FireProductionViscousSchedule forceSchedule;
		FireProductionResidentForceDiagnostics forceDiagnostics;
		std::uint32_t cellSubmapCount;
		std::uint32_t dualSubmapCount;
		std::uint32_t sourceCommandCommitCount;
		std::uint32_t residentProjectionInvocationCount;
		std::uint32_t interstageFullGridTransferCount;
		std::uint32_t terminalStagingCount;
		std::uint64_t combinedCertifiedWorkingSetBytes;
		std::uint64_t combinedActualMetalAllocationBytes;
		std::uint64_t projectedHeunOwnerIdentity;
		double deviceElapsedMS;
		double deviceMakespanMS;
		double representedTimeStepS;
		double maximumManifoldGeneration;
		double maximumAcceptedManifoldDeviation;
		double acceptedManifoldDeviationP95;
		double acceptedManifoldDeviationP50;
		bool manifoldGenerationAuthoritative;
		bool manifoldTailRestorationApplied;
		std::uint32_t manifoldTailCellCount;
		double manifoldTailExcessSum;
		double manifoldTailDrainedVolumeM3;
		bool manifoldDynamicsBoundPassed;
		double maximumPredictedAdvectiveManifoldAnomaly;
		std::uint32_t manifoldMapCellCount;
		std::uint32_t manifoldScalarDeviceToHostTransferCount;
		std::uint32_t manifoldFullGridDeviceToHostTransferCount;
		std::uint32_t advectiveAnomalyClosurePassCount;
		std::array<double,3> manifoldStageGeneration;
		double requiredRestorationDrainFraction;
		double deliveredRestorationDrainFraction;
		double restorationResidualBandPerS;
		double suggestedManifoldTimeStepS;
		bool manifoldNextTimeStepAvailable;
		bool manifoldDiagnosticsMonitored;
		bool manifoldPlateauEnforced;
		bool manifoldAllowanceExceeded;
		bool manifoldCeilingExceeded;
		bool manifoldPlateauPassed;
		RISE::FireStateProducerPrecision conservativeProducerPrecision;
		FireProductionProjectionShape acceptedShape;

		FireProductionResidentStepResult() : cellSubmapCount(0u),dualSubmapCount(0u),
			sourceCommandCommitCount(0u),residentProjectionInvocationCount(0u),
			interstageFullGridTransferCount(0u),terminalStagingCount(0u),
			combinedCertifiedWorkingSetBytes(0u),combinedActualMetalAllocationBytes(0u),
			projectedHeunOwnerIdentity(0u),
			deviceElapsedMS(0.0),deviceMakespanMS(0.0),
			representedTimeStepS(0.0),maximumManifoldGeneration(0.0),
			maximumAcceptedManifoldDeviation(0.0),acceptedManifoldDeviationP95(0.0),
			acceptedManifoldDeviationP50(0.0),manifoldGenerationAuthoritative(false),
			manifoldTailRestorationApplied(false),manifoldTailCellCount(0u),
			manifoldTailExcessSum(0.0),manifoldTailDrainedVolumeM3(0.0),
			manifoldDynamicsBoundPassed(false),
			maximumPredictedAdvectiveManifoldAnomaly(0.0),
			manifoldMapCellCount(0u),
			manifoldScalarDeviceToHostTransferCount(0u),manifoldFullGridDeviceToHostTransferCount(0u),
			advectiveAnomalyClosurePassCount(0u),
			manifoldStageGeneration{{0.0,0.0,0.0}},requiredRestorationDrainFraction(0.0),
			deliveredRestorationDrainFraction(0.0),restorationResidualBandPerS(0.0),
			suggestedManifoldTimeStepS(0.0),manifoldNextTimeStepAvailable(false),
			manifoldDiagnosticsMonitored(false),manifoldPlateauEnforced(false),
			manifoldAllowanceExceeded(false),manifoldCeilingExceeded(false),
			manifoldPlateauPassed(false),
			conservativeProducerPrecision(RISE::FireStateProducerPrecision::Unknown) {}

	private:
		friend bool AdvanceFireProductionResidentStepMetal(
			const FireProductionResidentStepRequest&,
			FireProductionResidentStepResult&,
			std::string* );
		friend bool AttemptFireProductionResidentStepMetal(
			const FireProductionResidentStepRequest&,
			FireProductionResidentStepResult&,
			std::string* );
		friend bool AttemptFireProductionProjectedHeunResidentStepMetal(
			const FireProductionProjectedHeunMetalOwnerRequest&,
			FireProductionResidentStepResult&,
			FireProductionProjectedHeunMetalOwnerResult*,std::string* );
	};

	//! Authority-bearing production entry for the resident Section 3.7 owner.
	//! It publishes the ordinary accepted-step token only after the complete
	//! device owner, monitored-manifold diagnostics, and payload identities agree.
	bool AttemptFireProductionProjectedHeunResidentStepMetal(
		const FireProductionProjectedHeunMetalOwnerRequest& request,
		FireProductionResidentStepResult& result,
		FireProductionProjectedHeunMetalOwnerResult* diagnostics=0,
		std::string* error=0 );

	//! Single owner predicate for accepted-token issuance.  Diagnostics alone do
	//! not mint authority; both projection validations are structural inputs.
	bool FireProductionResidentStepEligibleForAcceptedManifoldToken(
		const FireProductionResidentStepResult& );
	bool FireProductionEulerianGenerationHasMaterialAuthority(
		const std::vector<double>& beginningManifoldDeviationPerCell,
		const std::array<std::vector<double>,3>& frozenTransportVelocityMPerS );

	//! Canonical bytes that an accepted production step applies to the next
	//! checkpoint state.  Checkpoint persistence must reproduce this digest;
	//! it cannot transplant a valid observation onto different state bytes.
	inline std::uint64_t FireProductionAcceptedStatePayloadDigest(
		const FireProductionProjectionShape& shape,
		const std::vector<double>& conservativeValues,
		const std::array<std::vector<double>,3>& momentum,
		const std::array<std::vector<double>,3>& velocity )
	{
		std::uint64_t digest=UINT64_C(0x65f07b31c42a98de);
		auto appendWord=[&](const std::uint64_t word) {
			for(unsigned int byte=0u;byte<8u;++byte){
				digest^=static_cast<unsigned char>(word>>(8u*byte));
				digest*=UINT64_C(1099511628211);}
		};
		std::uint64_t fieldTag=0u;
		appendWord(UINT64_C(0x7265736964656e74));
		appendWord(static_cast<std::uint64_t>(shape.nx));
		appendWord(static_cast<std::uint64_t>(shape.ny));
		appendWord(static_cast<std::uint64_t>(shape.nz));
		std::uint32_t widthBits=0u;std::memcpy(&widthBits,&shape.cellWidthM,sizeof(widthBits));
		appendWord(widthBits);
		auto append=[&](const std::vector<double>& values) {
			appendWord(++fieldTag);appendWord(static_cast<std::uint64_t>(values.size()));
			for(const double scalar:values){std::uint32_t bits=0u;
				std::memcpy(&bits,&scalar,sizeof(bits));
				for(unsigned int byte=0u;byte<4u;++byte){
					digest^=static_cast<unsigned char>(bits>>(8u*byte));
					digest*=UINT64_C(1099511628211);}}
		};
		append(conservativeValues);
		for(unsigned int axis=0u;axis<3u;++axis){append(momentum[axis]);append(velocity[axis]);}
		return digest^UINT64_C(0xd64b291e3fa5708c);
	}
	inline std::uint64_t FireProductionAcceptedStatePayloadDigestFast(
		const FireProductionProjectionShape& shape,
		const std::vector<double>& conservativeValues,
		const std::array<std::vector<double>,3>& momentum,
		const std::array<std::vector<double>,3>& velocity )
	{
		std::uint64_t digest=UINT64_C(0x65f07b31c42a98de);
		auto avalanche=[](std::uint64_t word) {
			word^=word>>32u;word*=UINT64_C(0xd6e8feb86659fd93);
			word^=word>>32u;word*=UINT64_C(0xd6e8feb86659fd93);
			return word^(word>>32u);
		};
		auto rotate=[](const std::uint64_t word,const unsigned int bits) {
			return (word<<bits)|(word>>(64u-bits));
		};
		auto appendWord=[&](const std::uint64_t word) {
			digest^=word+UINT64_C(0x9e3779b97f4a7c15)+(digest<<6u)+(digest>>2u);
		};
		std::uint64_t fieldTag=0u;
		appendWord(UINT64_C(0x7265736964656e74));
		appendWord(static_cast<std::uint64_t>(shape.nx));
		appendWord(static_cast<std::uint64_t>(shape.ny));
		appendWord(static_cast<std::uint64_t>(shape.nz));
		std::uint32_t widthBits=0u;std::memcpy(&widthBits,&shape.cellWidthM,sizeof(widthBits));
		appendWord(widthBits);
		auto append=[&](const std::vector<double>& values) {
			appendWord(++fieldTag);appendWord(static_cast<std::uint64_t>(values.size()));
			std::uint64_t ordered=UINT64_C(0x243f6a8885a308d3)^fieldTag;
			for(std::size_t index=0u;index<values.size();++index){std::uint32_t bits=0u;
				std::memcpy(&bits,&values[index],sizeof(bits));
				ordered^=static_cast<std::uint64_t>(bits)+UINT64_C(0x9e3779b97f4a7c15)+
					(static_cast<std::uint64_t>(index)<<32u);
				ordered=rotate(ordered,27u)*UINT64_C(0x3c79ac492ba7b653)+
					UINT64_C(0x1c69b3f74ac4ae35);
			}
			appendWord(avalanche(ordered));
		};
		append(conservativeValues);
		for(unsigned int axis=0u;axis<3u;++axis){append(momentum[axis]);append(velocity[axis]);}
		return avalanche(digest^fieldTag^UINT64_C(0xd64b291e3fa5708c));
	}

	//! Full resident P3 step. Production defaults to one physical P2 projection
	//! plus terminal manifold diagnostics. Absolute-reference restoration and
	//! its timestep limiter remain opt-in instrumentation through
	//! enforceManifoldPlateau.
	bool AdvanceFireProductionResidentStepMetal(
		const FireProductionResidentStepRequest& request,
		FireProductionResidentStepResult& result,
		std::string* error=0 );

	//! Executes one candidate without weakening rejection semantics.  A
	//! plateau refusal returns false but preserves only the computed, tokenless
	//! result and its derived next-step suggestion so the owner may retry from
	//! the unchanged beginning.  Every other failure leaves a default result.
	bool AttemptFireProductionResidentStepMetal(
		const FireProductionResidentStepRequest& request,
		FireProductionResidentStepResult& rejectedOrAcceptedResult,
		std::string* error=0 );

	//! Isolated Section 3.7 candidate seam.  Ordinary production never selects
	//! this operator.  The calibration owner may call it only after independently
	//! validating the sealed checkpoint/case identity; the request copy retains
	//! the five accepted primal gas-mass doses needed by the candidate.
	bool AttemptFireProductionCompatibleMomentumDiagnosticMetal(
		const FireProductionResidentStepRequest& request,
		FireProductionResidentStepResult& rejectedOrAcceptedResult,
		std::string* error=0 );

	//! Identity-bearing status for the isolated single-stage production FCT
	//! candidate. This type deliberately has no accepted-manifold token: a
	//! diagnostic trajectory may not confer ordinary-production authority.
	enum class FireProductionSingleStageFCTDiagnosticPhase : std::uint8_t
	{
		Unavailable=0u,
		Preflight=1u,
		ForceAdvance=2u,
		FCTSolve=3u,
		PhysicalProjection=4u,
		TailProjection=5u,
		Accepted=6u
	};

	//! Prior accepted pressure-open classification consumed only by the isolated
	//! FCT diagnostic. All six side arrays are mandatory and digest-bound with the
	//! accepted predecessor-state payload through the caller-supplied identity,
	//! including on wall and periodic sides.
	struct FireProductionSingleStageFCTBoundaryState
	{
		std::array<std::vector<unsigned char>,6> pressureOpenInflow;
		std::uint64_t statePayloadIdentity;
		std::uint64_t identity;

		FireProductionSingleStageFCTBoundaryState() : statePayloadIdentity(0u),identity(0u) {}
	};

	struct FireProductionSingleStageFCTDiagnosticResult
	{
		std::vector<double> conservativeValues;
		FireProductionProjectionResult physicalProjection;
		FireProductionProjectionResult projection;
		FireProductionViscousSchedule forceSchedule;
		FireProductionResidentForceDiagnostics forceDiagnostics;
		std::uint32_t operatorVersion;
		std::uint64_t operatorIdentity;
		std::uint64_t zeroPhysicalGasFluxIdentity;
		std::uint64_t boundaryStateIdentity;
		std::uint64_t beginningStateIdentity;
		FireProductionSingleStageFCTDiagnosticPhase phase;
		std::uint32_t fluxPairBuildCount;
		std::uint32_t fctSolveCount;
		std::uint32_t compatibleRateApplicationCount;
		std::uint32_t sourceApplicationCount;
		std::uint32_t residentProjectionInvocationCount;
		std::uint32_t interstageFullGridTransferCount;
		std::uint32_t terminalStagingCount;
		std::uint32_t failureBitmap;
		std::uint32_t tailCellCount;
		std::uint64_t certifiedWorkingSetBytes;
		std::uint64_t actualMetalAllocationBytes;
		std::uint64_t alphaIdentity;
		std::uint64_t scalarStageIdentity;
		double maximumCommutingResidual;
		double scalarStageGamma128;
		double maximumScalarStageAbsoluteDifference;
		double maximumScalarStageNormalizedDifference;
		double maximumCompatibleRateAbsoluteDifference;
		double maximumCompatibleRateNormalizedDifference;
		double tailDrainedVolumeM3;
		bool pipelineIdentityComplete;
		bool scalarAdmissible;
		bool scalarStageIdentityPassed;
		bool scalarStageExactZeroPassed;
		bool scalarStageProducerEquivalencePassed;
		bool compatibleRateExactZeroPassed;
		bool compatibleRateProducerEquivalencePassed;
		bool affineIdentityPassed;
		bool commutingIdentityPassed;
		bool accepted;

		FireProductionSingleStageFCTDiagnosticResult() : operatorVersion(0u),
			operatorIdentity(0u),zeroPhysicalGasFluxIdentity(0u),boundaryStateIdentity(0u),
			beginningStateIdentity(0u),
			phase(FireProductionSingleStageFCTDiagnosticPhase::Unavailable),
			fluxPairBuildCount(0u),fctSolveCount(0u),compatibleRateApplicationCount(0u),
			sourceApplicationCount(0u),residentProjectionInvocationCount(0u),
			interstageFullGridTransferCount(0u),terminalStagingCount(0u),failureBitmap(0u),
			tailCellCount(0u),certifiedWorkingSetBytes(0u),actualMetalAllocationBytes(0u),
			alphaIdentity(0u),scalarStageIdentity(0u),maximumCommutingResidual(0.0),
			scalarStageGamma128(0.0),maximumScalarStageAbsoluteDifference(0.0),
			maximumScalarStageNormalizedDifference(0.0),
			maximumCompatibleRateAbsoluteDifference(0.0),
			maximumCompatibleRateNormalizedDifference(0.0),
			tailDrainedVolumeM3(0.0),
			pipelineIdentityComplete(false),scalarAdmissible(false),
			scalarStageIdentityPassed(false),scalarStageExactZeroPassed(false),
			scalarStageProducerEquivalencePassed(false),compatibleRateExactZeroPassed(false),
			compatibleRateProducerEquivalencePassed(false),affineIdentityPassed(false),
			commutingIdentityPassed(false),accepted(false) {}
	};

	//! Explicit tokenless diagnostic seam for production's single-stage schedule
	//! with a coefficient-free §3.7 scalar/momentum FCT operator. It is never
	//! selected by the ordinary resident-step owner. The physical gas diffusion
	//! flux J_g is identity-bearing exact +0 because production owns no such flux.
	bool SealFireProductionSingleStageFCTBoundaryState(
		const FireProductionProjectionShape& shape,
		const std::array<FireProductionProjectionBoundary,6>& boundary,
		FireProductionSingleStageFCTBoundaryState& state,
		std::string* error=0 );
	bool AttemptFireProductionSingleStageFCTDiagnosticMetal(
		const FireProductionResidentStepRequest& request,
		const FireProductionSingleStageFCTBoundaryState& boundaryState,
		FireProductionSingleStageFCTDiagnosticResult& result,
		std::string* error=0 );

	//! Thread-local observed Metal commits, exposed only to bind fail-before-work
	//! owner gates. Unsupported builds return zero.
	std::uint64_t FireProductionResidentStepMetalCommandCommitCount();
}

#endif
