#!/usr/bin/env python
"""Generate src/Library/Utilities/Color/RGBToSpectrumTable_ROMMData.cpp
from extlib/jakob-hanika-luts/romm.coeff.

Bakes the LUT body floats directly into a static const array so the
runtime no longer needs to find romm.coeff on disk (which fails when
the GUI is launched from a shortcut without RISE_MEDIA_PATH set, see
GUI Render Engine for the regression that motivated this).

End-to-end regeneration recipe (run from project root):
  1. Build LUT generator:
       Mac/Linux:  c++ -O3 -std=c++17 -o bin/tools/JakobHanikaLUTGen \\
                       tools/JakobHanikaLUTGen.cpp -lm
       Windows:    msbuild build/VS2022/Tools/JakobHanikaLUTGen.vcxproj \\
                       /p:Configuration=Release /p:Platform=x64
  2. Regenerate the binary LUT (~30-60 sec):
       ./bin/tools/JakobHanikaLUTGen \\
           --output extlib/jakob-hanika-luts/romm.coeff
  3. Run this script (writes the .cpp inline as a static array):
       python tools/GenerateROMMSpectrumLUTHeader.py
  4. Rebuild Library — `Filelist`, `rise_sources.cmake`,
     `Library.vcxproj`, `Library.vcxproj.filters`, and
     `rise.xcodeproj` already register the .cpp + .h pair.  No
     build-file edits needed.

The file format produced by tools/JakobHanikaLUTGen.cpp:
  Header  : 20 bytes  ('RJHL', uint32 version, res, nChannels, nCoeffs)
  Body    : 3 * res^3 * nCoeffs floats (little-endian fp32)

We bake just the body — resolution and version are baked as
compile-time constants alongside.

Output cpp file is large (~32 MB at 64-resolution LUT) but compiles
under a minute on MSVC / clang.  Lives in the same directory as
RGBToSpectrumTable.cpp so MSVC's /MP-parallel build pipelines it
cleanly.

Paths INPUT and OUTPUT below are relative to the current working
directory — this script must be run from the project root.
"""
import struct
import sys
import os

INPUT  = "extlib/jakob-hanika-luts/romm.coeff"
OUTPUT = "src/Library/Utilities/Color/RGBToSpectrumTable_ROMMData.cpp"
FLOATS_PER_LINE = 8

def main():
    if not os.path.exists(INPUT):
        print(f"ERROR: missing {INPUT}", file=sys.stderr)
        sys.exit(1)

    with open(INPUT, "rb") as f:
        blob = f.read()

    if len(blob) < 20:
        print("ERROR: LUT file truncated header", file=sys.stderr)
        sys.exit(1)

    magic = blob[0:4]
    if magic != b"RJHL":
        print(f"ERROR: bad magic {magic!r}", file=sys.stderr)
        sys.exit(1)

    version, res, nChannels, nCoeffs = struct.unpack("<IIII", blob[4:20])
    if nChannels != 3 or nCoeffs != 3:
        print(f"ERROR: unsupported channels/coeffs: {nChannels}/{nCoeffs}", file=sys.stderr)
        sys.exit(1)

    body = blob[20:]
    expected_floats = 3 * res * res * res * nCoeffs
    expected_bytes  = expected_floats * 4
    if len(body) != expected_bytes:
        print(f"ERROR: body size mismatch (got {len(body)}, expected {expected_bytes})",
              file=sys.stderr)
        sys.exit(1)

    floats = struct.unpack(f"<{expected_floats}f", body)

    print(f"Read {INPUT}: res={res} version=0x{version:08x} floats={expected_floats}")

    os.makedirs(os.path.dirname(OUTPUT), exist_ok=True)
    with open(OUTPUT, "w", newline="\n") as out:
        out.write(
"""//////////////////////////////////////////////////////////////////////
//
//  RGBToSpectrumTable_ROMMData.cpp - Baked-in Jakob-Hanika sigmoid
//    coefficient LUT for ROMM RGB targets.
//
//  AUTO-GENERATED by tools/GenerateROMMSpectrumLUTHeader.py from
//  extlib/jakob-hanika-luts/romm.coeff (which itself is produced by
//  tools/JakobHanikaLUTGen.cpp).  DO NOT EDIT BY HAND.  Re-run the
//  generator if the LUT is regenerated:
//
//    python tools/GenerateROMMSpectrumLUTHeader.py
//
//  Why baked in: the lazy std::call_once-protected ROMM() loader used
//  to fopen this file at first spectral painter access.  When the
//  Windows GUI was launched from Explorer (no RISE_MEDIA_PATH env
//  var, cwd = bin/), MediaPathLocator could not resolve the relative
//  'extlib/jakob-hanika-luts/romm.coeff' path before the call_once
//  latched its failed state, and every spectral painter then
//  silently fell back to a constant 0.5 spectrum.  The embedded
//  data path eliminates the runtime file dependency entirely.
//
//////////////////////////////////////////////////////////////////////

#include "pch.h"
#include "RGBToSpectrumTable_ROMMData.h"

namespace RISE
{
""")
        out.write(f"    extern const unsigned int kROMMDataResolution = {res}u;\n")
        out.write(f"    extern const unsigned int kROMMDataNumFloats  = {expected_floats}u;\n\n")
        out.write("    extern const float kROMMDataFloats[] = {\n")

        # Write floats compactly: fp32 has ~7 sig figs, so %.9g preserves
        # bit-exact round-trip via std::strtof on every conforming compiler.
        # `0` formatted with `%.9g` prints as the bare token "0" — we have
        # to force a decimal so the C++ `f` suffix attaches to a float
        # literal (`0.0f`), not an integer (`0f` is invalid C++).
        def fmt(v):
            if v != v:  # NaN
                raise ValueError(f"NaN encountered in LUT body — re-generate romm.coeff")
            if v == float("inf") or v == float("-inf"):
                raise ValueError(f"inf encountered in LUT body — re-generate romm.coeff")
            s = f"{v:.9g}"
            if "." not in s and "e" not in s:
                s += ".0"
            return s + "f"

        for i in range(0, len(floats), FLOATS_PER_LINE):
            chunk = floats[i:i+FLOATS_PER_LINE]
            line = ", ".join(fmt(v) for v in chunk)
            out.write(f"        {line},\n")
        out.write("    };\n")
        out.write("} // namespace RISE\n")

    out_size = os.path.getsize(OUTPUT)
    print(f"Wrote {OUTPUT}: {out_size:,} bytes ({out_size/1024/1024:.1f} MB)")

if __name__ == "__main__":
    main()
