#!/usr/bin/env python3
"""Generate the calibration-only binary64 mirror of the production CPU kernels.

The mirror is deliberately mechanical: it changes the scalar storage type and
namespace while retaining the production expression topology.  Calibration
tests bind both the generator and source digests; hand edits to generated files
are rejected by ``--check``.
"""

from __future__ import annotations

import argparse
import difflib
import hashlib
import pathlib
import re
import sys


ROOT = pathlib.Path(__file__).resolve().parents[1]
SOURCE = ROOT / "src" / "Library" / "Utilities"
DESTINATION = ROOT / "tests" / "fire_production_fp64"
NAMES = (
    "FireProductionAdvection",
    "FireProductionProjection",
    "FireProductionTransport",
    "FireProductionForce",
)
DEPENDENCIES = ("FireSimulationRecords", "FireCase")


def source_manifest() -> str:
    lines = [
        "// GENERATED by tools/generate_fire_production_fp64_mirror.py.\n",
        "#ifndef FIRE_PRODUCTION_FP64_SOURCE_MANIFEST_H\n",
        "#define FIRE_PRODUCTION_FP64_SOURCE_MANIFEST_H\n\n",
        "namespace RISEFireProductionFP64 { namespace SourceManifest {\n",
    ]
    for name in NAMES:
        for suffix in (".h", ".cpp"):
            path = SOURCE / (name + suffix)
            digest = hashlib.sha256(path.read_bytes()).hexdigest()
            identifier = name + ("Header" if suffix == ".h" else "Source")
            lines.append(f'inline constexpr const char* {identifier}="{digest}";\n')
    for name in DEPENDENCIES:
        for suffix in (".h", ".cpp"):
            path = SOURCE / (name + suffix)
            digest = hashlib.sha256(path.read_bytes()).hexdigest()
            identifier = name + ("Header" if suffix == ".h" else "Source")
            lines.append(f'inline constexpr const char* {identifier}="{digest}";\n')
    generator_digest = hashlib.sha256(pathlib.Path(__file__).read_bytes()).hexdigest()
    lines.append(f'inline constexpr const char* Generator="{generator_digest}";\n')
    lines.append("} }\n\n#endif\n")
    return "".join(lines)


def transform(text: str, name: str, suffix: str) -> str:
    if name == "FireProductionForce" and suffix == ".h":
        publication_friend = """\n\t\tfriend bool PublishFireProductionAcceptedManifoldObservation(
\t\t\tdouble,FireProductionResidentStepResult&,
\t\t\tFireProductionAcceptedManifoldObservation&,std::string* );"""
        if text.count(publication_friend) != 1:
            raise RuntimeError("accepted manifold observation friend seam changed")
        text = text.replace(publication_friend, "")
        result_publication_friend = """\n\t\tfriend bool PublishFireProductionAcceptedManifoldObservation(
\t\t\tdouble,
\t\t\tFireProductionResidentStepResult&,
\t\t\tFireProductionAcceptedManifoldObservation&,
\t\t\tstd::string* );"""
        if text.count(result_publication_friend) != 2:
            raise RuntimeError("accepted manifold result friend seam changed")
        text = text.replace(result_publication_friend, "")
        token_begin = text.find("\n\t//! Opaque proof")
        token_end = text.find("\n\t//! Selects the production step", token_begin)
        if token_begin < 0 or token_end < 0:
            raise RuntimeError("accepted manifold token declaration seam changed")
        text = text[:token_begin] + text[token_end:]
        token_field = "\n\t\tFireProductionAcceptedManifoldToken acceptedManifoldToken_;"
        if text.count(token_field) != 1:
            raise RuntimeError("accepted manifold token field seam changed")
        text = text.replace(token_field, "")
        token_accessor = "\n\t\tbool HasAcceptedManifoldToken() const { return acceptedManifoldToken_.Available(); }"
        if text.count(token_accessor) != 1:
            raise RuntimeError("accepted manifold token accessor seam changed")
        text = text.replace(token_accessor, "")
        token_match = """\n\t\t//! Revalidates the producer-owned token against every mutable diagnostic and
\t\t//! payload byte before an owner may classify the attempt as accepted.
\t\tbool AcceptedManifoldTokenMatchesCurrentPayload() const;"""
        if text.count(token_match) != 1:
            raise RuntimeError("accepted manifold token match seam changed")
        text = text.replace(token_match, "")
        disposition_begin = text.find(
            "\n\tenum class FireProductionResidentStepAttemptDisposition")
        disposition_end = text.find("\n\t//! Single owner predicate", disposition_begin)
        if disposition_begin < 0 or disposition_end < 0:
            raise RuntimeError("production retry disposition seam changed")
        text = text[:disposition_begin] + text[disposition_end:]
        begin = text.find("\n\t//! Publishes authenticated accepted-state metadata")
        end = text.find("\n\t//! Full resident P3 step.", begin)
        if begin < 0 or end < 0:
            raise RuntimeError("accepted manifold publication declaration seam changed")
        text = text[:begin] + text[end:]
    if name == "FireProductionForce" and suffix == ".cpp":
        # This owner-only publication seam consumes a completed binary32
        # resident result.  It is outside the same-scheme arithmetic mirror
        # and has no binary64 producer analogue.
        token_match_begin = text.find(
            "\n\tbool FireProductionResidentStepResult::AcceptedManifoldTokenMatchesCurrentPayload() const")
        begin = text.find("\n\tbool PublishFireProductionAcceptedManifoldObservation(")
        end = text.find("\n\tbool EvaluateFireProductionVremanEddyViscosity(", begin)
        if token_match_begin < 0 or begin < 0 or end < 0:
            raise RuntimeError("accepted manifold publication seam changed")
        text = text[:token_match_begin] + text[end:]
    text = text.replace("namespace RISE", "namespace RISEFireProductionFP64")
    text = text.replace(
        '#include "FireSimulationRecords.h"',
        '#include "../../src/Library/Utilities/FireSimulationRecords.h"',
    )
    text = text.replace(
        '#include "FireCase.h"',
        '#include "../../src/Library/Utilities/FireCase.h"',
    )
    text = text.replace("FireStateProducerPrecision", "RISE::FireStateProducerPrecision")
    text = re.sub(r"\bfloat\b", "double", text)
    # Decimal and hexadecimal floating literals use the same expression tree;
    # only their storage suffix changes.
    text = re.sub(r"(?<=[0-9])f\b", "", text)
    # Calibration alone may translate an already authenticated binary32 source
    # packet into binary64 storage.  The live header exposes no such importer;
    # this template exists only in the mechanically generated mirror so the full
    # owner, rather than disconnected kernels, can be compared at matched inputs.
    if name == "FireProductionTransport" and suffix == ".h":
        anchor = "\t\tbool IsSealed() const { return sealed_; }\n\t};\n\n\t//! Recomputes every published-content"
        if text.count(anchor) != 1:
            raise RuntimeError("frozen source seal calibration-import seam changed")
        importer = """\t\tbool IsSealed() const { return sealed_; }
		template<class Binary32Seal>
		static FireProductionFrozenSourcePacketSeal CalibrationImport(
			const Binary32Seal& source )
		{
			FireProductionFrozenSourcePacketSeal result;
			result.shape_.nx=source.Shape().nx;result.shape_.ny=source.Shape().ny;
			result.shape_.nz=source.Shape().nz;
			result.shape_.cellWidthM=static_cast<double>(source.Shape().cellWidthM);
			result.timeStepS_=static_cast<double>(source.TimeStepS());
			result.beginningTimeS_=source.BeginningTimeS();
			result.attemptIdentity_=source.AttemptIdentity();
			result.methaneRecordId_=source.MethaneRecordId();
			result.transportRecordId_=source.TransportRecordId();
			result.opacityRecordId_=source.OpacityRecordId();
			result.caseRecordId_=source.CaseRecordId();
			result.beginningTemperatureK_.assign(source.BeginningTemperatureK().begin(),
				source.BeginningTemperatureK().end());
			result.sourceDelta_.assign(source.SourceDelta().begin(),source.SourceDelta().end());
			result.divergenceTargetPerS_.assign(source.DivergenceTargetPerS().begin(),
				source.DivergenceTargetPerS().end());
			result.reactedFuelKGPerM3_=source.ReactedFuelKGPerM3();
			result.oxidizedCarbonKGPerM3_=source.OxidizedCarbonKGPerM3();
			result.grossCarbonFormedKGPerM3_=source.GrossCarbonFormedKGPerM3();
			result.gasHeatReleaseWPerM3_=source.GasHeatReleaseWPerM3();
			result.sootHeatReleaseWPerM3_=source.SootHeatReleaseWPerM3();
			result.pilotEnergyDeltaJPerM3_=source.PilotEnergyDeltaJPerM3();
			result.pilotExpansionIntegral_=source.PilotExpansionIntegral();
			result.radiativeCoolingWPerM3_=source.RadiativeCoolingWPerM3();
			result.radiationBeta_=source.RadiationBeta();
			result.radiationGamma_=source.RadiationGamma();
			result.radiationEscapeFactor_=source.RadiationEscapeFactor();
			result.maximumScaledExpansion_=source.MaximumScaledExpansion();
			result.beginningStateIdentity_=source.BeginningStateIdentity();
			result.reactionControlIdentity_=source.ReactionControlIdentity();
			result.sourceInputIdentity_=source.SourceInputIdentity();
			result.FinalizeIdentities();return result;
		}
	};

	//! Recomputes every published-content"""
        text = text.replace(anchor, importer)
    if suffix == ".h":
        guards = {
            "FireProductionAdvection": "FIREPRODUCTIONADVECTION_",
            "FireProductionProjection": "FIREPRODUCTIONPROJECTION_",
            "FireProductionTransport": "FIREPRODUCTIONTRANSPORT_",
            "FireProductionForce": "FIRE_PRODUCTION_FORCE_H",
        }
        guard = guards[name]
        text = text.replace(guard, "FP64_" + guard)
    if name == "FireProductionForce" and suffix == ".cpp":
        # The diagnostic hashes binary64 words in the mirror.  It is evidence
        # only, but retaining the binary32 memcpy width would be undefined.
        text = text.replace("std::uint32_t bits=0u;", "std::uint64_t bits=0u;")
        text = text.replace("byte<4u", "byte<8u")
        text = text.replace("binary32 words", "binary64 words")
    banner = (
        "// GENERATED by tools/generate_fire_production_fp64_mirror.py.\n"
        "// Do not edit; run the generator and commit its deterministic output.\n"
    )
    return banner + text


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    options = parser.parse_args()
    failed = False
    if not options.check:
        DESTINATION.mkdir(parents=True, exist_ok=True)
    for name in NAMES:
        for suffix in (".h", ".cpp"):
            source = SOURCE / (name + suffix)
            destination = DESTINATION / (name + suffix)
            expected = transform(source.read_text(encoding="utf-8"), name, suffix)
            if options.check:
                actual = destination.read_text(encoding="utf-8") if destination.exists() else ""
                if actual != expected:
                    failed = True
                    sys.stderr.writelines(
                        difflib.unified_diff(
                            actual.splitlines(True),
                            expected.splitlines(True),
                            fromfile=str(destination),
                            tofile=str(source),
                            n=2,
                        )
                    )
            else:
                destination.write_text(expected, encoding="utf-8")
    manifest = DESTINATION / "SourceManifest.h"
    expected_manifest = source_manifest()
    if options.check:
        actual_manifest = manifest.read_text(encoding="utf-8") if manifest.exists() else ""
        if actual_manifest != expected_manifest:
            failed = True
            sys.stderr.write(f"generated source manifest differs: {manifest}\n")
    else:
        manifest.write_text(expected_manifest, encoding="utf-8")
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
