#!/usr/bin/env python3
"""Generate the calibration-only binary64 mirror of the production CPU kernels.

The mirror is deliberately mechanical: it changes the scalar storage type and
namespace while retaining the production expression topology.  Calibration
tests bind both the generator and source digests; hand edits to generated files
are rejected by ``--check``.
"""

from __future__ import annotations

import argparse
import difflib
import hashlib
import pathlib
import re
import sys


ROOT = pathlib.Path(__file__).resolve().parents[1]
SOURCE = ROOT / "src" / "Library" / "Utilities"
DESTINATION = ROOT / "tests" / "fire_production_fp64"
NAMES = (
    "FireProductionAdvection",
    "FireProductionProjection",
    "FireProductionTransport",
    "FireProductionForce",
)


def source_manifest() -> str:
    lines = [
        "// GENERATED by tools/generate_fire_production_fp64_mirror.py.\n",
        "#ifndef FIRE_PRODUCTION_FP64_SOURCE_MANIFEST_H\n",
        "#define FIRE_PRODUCTION_FP64_SOURCE_MANIFEST_H\n\n",
        "namespace RISEFireProductionFP64 { namespace SourceManifest {\n",
    ]
    for name in NAMES:
        for suffix in (".h", ".cpp"):
            path = SOURCE / (name + suffix)
            digest = hashlib.sha256(path.read_bytes()).hexdigest()
            identifier = name + ("Header" if suffix == ".h" else "Source")
            lines.append(f'inline constexpr const char* {identifier}="{digest}";\n')
    generator_digest = hashlib.sha256(pathlib.Path(__file__).read_bytes()).hexdigest()
    lines.append(f'inline constexpr const char* Generator="{generator_digest}";\n')
    lines.append("} }\n\n#endif\n")
    return "".join(lines)


def transform(text: str, name: str, suffix: str) -> str:
    text = text.replace("namespace RISE", "namespace RISEFireProductionFP64")
    text = re.sub(r"\bfloat\b", "double", text)
    # Decimal and hexadecimal floating literals use the same expression tree;
    # only their storage suffix changes.
    text = re.sub(r"(?<=[0-9])f\b", "", text)
    if suffix == ".h":
        guards = {
            "FireProductionAdvection": "FIREPRODUCTIONADVECTION_",
            "FireProductionProjection": "FIREPRODUCTIONPROJECTION_",
            "FireProductionTransport": "FIREPRODUCTIONTRANSPORT_",
            "FireProductionForce": "FIRE_PRODUCTION_FORCE_H",
        }
        guard = guards[name]
        text = text.replace(guard, "FP64_" + guard)
    if name == "FireProductionForce" and suffix == ".cpp":
        # The diagnostic hashes binary64 words in the mirror.  It is evidence
        # only, but retaining the binary32 memcpy width would be undefined.
        text = text.replace("std::uint32_t bits=0u;", "std::uint64_t bits=0u;")
        text = text.replace("byte<4u", "byte<8u")
        text = text.replace("binary32 words", "binary64 words")
    banner = (
        "// GENERATED by tools/generate_fire_production_fp64_mirror.py.\n"
        "// Do not edit; run the generator and commit its deterministic output.\n"
    )
    return banner + text


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    options = parser.parse_args()
    failed = False
    if not options.check:
        DESTINATION.mkdir(parents=True, exist_ok=True)
    for name in NAMES:
        for suffix in (".h", ".cpp"):
            source = SOURCE / (name + suffix)
            destination = DESTINATION / (name + suffix)
            expected = transform(source.read_text(encoding="utf-8"), name, suffix)
            if options.check:
                actual = destination.read_text(encoding="utf-8") if destination.exists() else ""
                if actual != expected:
                    failed = True
                    sys.stderr.writelines(
                        difflib.unified_diff(
                            actual.splitlines(True),
                            expected.splitlines(True),
                            fromfile=str(destination),
                            tofile=str(source),
                            n=2,
                        )
                    )
            else:
                destination.write_text(expected, encoding="utf-8")
    manifest = DESTINATION / "SourceManifest.h"
    expected_manifest = source_manifest()
    if options.check:
        actual_manifest = manifest.read_text(encoding="utf-8") if manifest.exists() else ""
        if actual_manifest != expected_manifest:
            failed = True
            sys.stderr.write(f"generated source manifest differs: {manifest}\n")
    else:
        manifest.write_text(expected_manifest, encoding="utf-8")
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
