//////////////////////////////////////////////////////////////////////
//
//  GenerateMicrofacetEnergyLUT.cpp - Offline tool to generate the
//    precomputed directional albedo LUT for Kulla-Conty multiscattering
//    energy compensation.
//
//  Outputs: src/Library/Utilities/MicrofacetEnergyLUT.h
//
//  Build (from project root):
//    c++ -O3 -Isrc/Library -o tools/gen_lut tools/GenerateMicrofacetEnergyLUT.cpp -lm
//
//  Run:
//    tools/gen_lut > src/Library/Utilities/MicrofacetEnergyLUT.h
//
//  Author: Aravind Krishnaswamy
//  Date: March 28, 2026
//
//////////////////////////////////////////////////////////////////////

#include <cstdio>
#include <cmath>
#include <cstdlib>

// Inline the math we need rather than pulling in the full library
static const double PI = 3.14159265358979323846;
static const double TWO_PI = 2.0 * PI;

struct Vec3 {
	double x, y, z;
	Vec3() : x(0), y(0), z(0) {}
	Vec3(double x_, double y_, double z_) : x(x_), y(y_), z(z_) {}
};

static Vec3 normalize(const Vec3& v) {
	double len = sqrt(v.x*v.x + v.y*v.y + v.z*v.z);
	if(len < 1e-20) return Vec3(0,0,1);
	return Vec3(v.x/len, v.y/len, v.z/len);
}

static double dot(const Vec3& a, const Vec3& b) {
	return a.x*b.x + a.y*b.y + a.z*b.z;
}

// GGX G1 masking
static double GGX_G1(double alpha, double cosTheta) {
	if(cosTheta < 1e-10) return 0;
	double a2 = alpha * alpha;
	double cos2 = cosTheta * cosTheta;
	return 2.0 * cosTheta / (cosTheta + sqrt(a2 + (1.0 - a2) * cos2));
}

// VNDF sampling (Dupuy-Benyoub spherical cap)
// wi must point away from surface (toward viewer), normal is (0,0,1)
// Returns micronormal in local space
static Vec3 VNDF_Sample_Local(const Vec3& wi, double alpha, double u1, double u2) {
	if(alpha < 1e-6) return Vec3(0, 0, 1);

	// Stretch wi
	Vec3 wi_h = normalize(Vec3(alpha * wi.x, alpha * wi.y, wi.z));

	// Sample spherical cap
	double phi = TWO_PI * u1;
	double z = (1.0 - u2) * (1.0 + wi_h.z) - wi_h.z;
	double sinTheta = sqrt(fmax(0.0, 1.0 - z * z));
	double x = sinTheta * cos(phi);
	double y = sinTheta * sin(phi);

	// Compute micronormal in hemisphere configuration
	Vec3 c(x + wi_h.x, y + wi_h.y, z + wi_h.z);

	// Unstretch
	return normalize(Vec3(alpha * c.x, alpha * c.y, c.z));
}

// Simple LCG random number generator
static unsigned long long rng_state = 1234567890123456789ULL;
static double rand01() {
	rng_state = rng_state * 6364136223846793005ULL + 1442695040888963407ULL;
	return (double)(rng_state >> 11) / (double)(1ULL << 53);
}

static const int LUT_SIZE = 32;
static const int NUM_SAMPLES = 1000000;

int main() {
	double E_ss[LUT_SIZE][LUT_SIZE]; // [alphaIdx][cosThetaIdx]
	double E_avg[LUT_SIZE];

	// Compute E_ss for each (alpha, cosTheta) pair
	for(int ai = 0; ai < LUT_SIZE; ai++) {
		double alpha = (double)(ai + 0.5) / LUT_SIZE; // [0.015625, 0.984375]
		// Map to [0.01, 1.0] range
		alpha = 0.01 + (1.0 - 0.01) * (double)ai / (double)(LUT_SIZE - 1);

		for(int ci = 0; ci < LUT_SIZE; ci++) {
			double cosTheta = (double)(ci + 0.5) / LUT_SIZE;
			// Map to (0, 1] range
			cosTheta = (double)(ci + 0.5) / LUT_SIZE;

			// Construct wi in local coordinates (normal = z-axis)
			double sinTheta = sqrt(fmax(0.0, 1.0 - cosTheta * cosTheta));
			Vec3 wi(sinTheta, 0.0, cosTheta);

			double sum = 0.0;
			int validSamples = 0;

			for(int s = 0; s < NUM_SAMPLES; s++) {
				double u1 = rand01();
				double u2 = rand01();

				Vec3 m = VNDF_Sample_Local(wi, alpha, u1, u2);
				double wiDotM = dot(wi, m);
				if(wiDotM <= 0) continue;

				// Reflect wi about m to get wo
				Vec3 wo(
					2.0 * wiDotM * m.x - wi.x,
					2.0 * wiDotM * m.y - wi.y,
					2.0 * wiDotM * m.z - wi.z
				);
				wo = normalize(wo);

				double cosWo = wo.z; // dot(wo, normal)
				if(cosWo > 0) {
					// With VNDF sampling and F=1, the estimator for E_ss is:
					// E_ss = (1/N) * sum G1(wo)
					sum += GGX_G1(alpha, cosWo);
					validSamples++;
				}
			}

			E_ss[ai][ci] = sum / (double)NUM_SAMPLES;
		}

		// Compute E_avg for this alpha using trapezoidal integration
		// E_avg = 2 * integral_0^1 E_ss(mu) * mu d_mu
		double integral = 0.0;
		for(int ci = 0; ci < LUT_SIZE; ci++) {
			double mu = (double)(ci + 0.5) / LUT_SIZE;
			double dmu = 1.0 / LUT_SIZE;
			integral += E_ss[ai][ci] * mu * dmu;
		}
		E_avg[ai] = 2.0 * integral;

		fprintf(stderr, "alpha=%.4f  E_avg=%.6f\n", alpha, E_avg[ai]);
	}

	// Emit the header
	printf("//////////////////////////////////////////////////////////////////////\n");
	printf("//\n");
	printf("//  MicrofacetEnergyLUT.h - Precomputed directional albedo tables\n");
	printf("//    for Kulla-Conty multiscattering energy compensation.\n");
	printf("//\n");
	printf("//  AUTO-GENERATED by tools/GenerateMicrofacetEnergyLUT.cpp\n");
	printf("//  DO NOT EDIT BY HAND.\n");
	printf("//\n");
	printf("//  References:\n");
	printf("//    - Kulla & Conty, \"Revisiting Physically Based Shading at\n");
	printf("//      Imageworks\", SIGGRAPH 2017 Course\n");
	printf("//    - Turquin, \"Practical Multiple Scattering Compensation for\n");
	printf("//      Microfacet Models\", ILM 2019\n");
	printf("//\n");
	printf("//  LUT resolution: %d x %d\n", LUT_SIZE, LUT_SIZE);
	printf("//  Samples per entry: %d\n", NUM_SAMPLES);
	printf("//  Alpha range: [0.01, 1.0] (uniform %d steps)\n", LUT_SIZE);
	printf("//  CosTheta range: [0.5/%d, (%.1f)/%d] (cell centers)\n", LUT_SIZE, LUT_SIZE - 0.5, LUT_SIZE);
	printf("//\n");
	printf("//  Author: Aravind Krishnaswamy\n");
	printf("//  Date of Birth: March 28, 2026\n");
	printf("//  Tabs: 4\n");
	printf("//\n");
	printf("//  License Information: Please see the attached LICENSE.TXT file\n");
	printf("//\n");
	printf("//////////////////////////////////////////////////////////////////////\n\n");

	printf("#ifndef MICROFACET_ENERGY_LUT_\n");
	printf("#define MICROFACET_ENERGY_LUT_\n\n");
	printf("#include \"Math3D/Math3D.h\"\n");
	printf("#include \"Optics.h\"\n");
	printf("#include \"math_utils.h\"\n\n");

	printf("namespace RISE\n{\n");
	printf("namespace MicrofacetEnergyLUT\n{\n");

	// Emit constants
	printf("\tstatic const int LUT_SIZE = %d;\n\n", LUT_SIZE);

	// Emit E_ss table
	printf("\t/// Directional albedo E_ss(alpha, cosTheta) of GGX single-scatter BRDF with F=1.\n");
	printf("\t/// Indexed as E_ss_TABLE[alphaIdx][cosThetaIdx].\n");
	printf("\t/// Alpha mapped linearly from 0.01 to 1.0, cosTheta from cell centers.\n");
	printf("\tstatic const Scalar E_ss_TABLE[%d][%d] = {\n", LUT_SIZE, LUT_SIZE);
	for(int ai = 0; ai < LUT_SIZE; ai++) {
		printf("\t\t{ ");
		for(int ci = 0; ci < LUT_SIZE; ci++) {
			printf("%.8f", E_ss[ai][ci]);
			if(ci < LUT_SIZE - 1) printf(", ");
		}
		printf(" }");
		if(ai < LUT_SIZE - 1) printf(",");
		printf("\n");
	}
	printf("\t};\n\n");

	// Emit E_avg table
	printf("\t/// Cosine-weighted hemisphere average of E_ss per roughness.\n");
	printf("\t/// E_avg(alpha) = 2 * integral_0^1 E_ss(alpha, mu) * mu d_mu\n");
	printf("\tstatic const Scalar E_avg_TABLE[%d] = {\n\t\t", LUT_SIZE);
	for(int ai = 0; ai < LUT_SIZE; ai++) {
		printf("%.8f", E_avg[ai]);
		if(ai < LUT_SIZE - 1) printf(", ");
		if((ai + 1) % 8 == 0 && ai < LUT_SIZE - 1) printf("\n\t\t");
	}
	printf("\n\t};\n\n");

	// Emit lookup functions
	printf("\t/// Look up E_ss(cosTheta, alpha) with bilinear interpolation.\n");
	printf("\tinline Scalar LookupEss( const Scalar cosTheta, const Scalar alpha )\n");
	printf("\t{\n");
	printf("\t\t// Map alpha from [0.01, 1.0] to [0, LUT_SIZE-1]\n");
	printf("\t\tScalar a = r_max(0.0, r_min(1.0, (alpha - 0.01) / (1.0 - 0.01))) * (LUT_SIZE - 1);\n");
	printf("\t\tint ai0 = (int)a;\n");
	printf("\t\tint ai1 = r_min(ai0 + 1, LUT_SIZE - 1);\n");
	printf("\t\tScalar af = a - ai0;\n\n");
	printf("\t\t// Map cosTheta from cell centers: idx = cosTheta * LUT_SIZE - 0.5\n");
	printf("\t\tScalar c = r_max(0.0, r_min(1.0, cosTheta)) * LUT_SIZE - 0.5;\n");
	printf("\t\tif( c < 0 ) c = 0;\n");
	printf("\t\tint ci0 = (int)c;\n");
	printf("\t\tint ci1 = r_min(ci0 + 1, LUT_SIZE - 1);\n");
	printf("\t\tScalar cf = c - ci0;\n\n");
	printf("\t\t// Bilinear interpolation\n");
	printf("\t\tScalar v00 = E_ss_TABLE[ai0][ci0];\n");
	printf("\t\tScalar v01 = E_ss_TABLE[ai0][ci1];\n");
	printf("\t\tScalar v10 = E_ss_TABLE[ai1][ci0];\n");
	printf("\t\tScalar v11 = E_ss_TABLE[ai1][ci1];\n");
	printf("\t\treturn (1-af) * ((1-cf)*v00 + cf*v01) + af * ((1-cf)*v10 + cf*v11);\n");
	printf("\t}\n\n");

	printf("\t/// Look up E_avg(alpha) with linear interpolation.\n");
	printf("\tinline Scalar LookupEavg( const Scalar alpha )\n");
	printf("\t{\n");
	printf("\t\tScalar a = r_max(0.0, r_min(1.0, (alpha - 0.01) / (1.0 - 0.01))) * (LUT_SIZE - 1);\n");
	printf("\t\tint ai0 = (int)a;\n");
	printf("\t\tint ai1 = r_min(ai0 + 1, LUT_SIZE - 1);\n");
	printf("\t\tScalar af = a - ai0;\n");
	printf("\t\treturn (1-af) * E_avg_TABLE[ai0] + af * E_avg_TABLE[ai1];\n");
	printf("\t}\n\n");

	// Fresnel averaging via Gauss-Legendre quadrature
	printf("\t/// 21-point Gauss-Legendre quadrature nodes on [0,1].\n");
	printf("\tstatic const int GL_N = 21;\n");
	printf("\tstatic const Scalar GL_nodes[21] = {\n\t\t");
	// 21-point GL nodes on [0,1] (transformed from [-1,1])
	double gl_nodes_11[] = {
		-0.9937521706203895, -0.9672268385663063, -0.9200993341504008,
		-0.8533633645833173, -0.7684399634756779, -0.6671388041974123,
		-0.5516188358872198, -0.4243421202074388, -0.2880213168024011,
		-0.1455618541608951, 0.0,
		0.1455618541608951, 0.2880213168024011, 0.4243421202074388,
		0.5516188358872198, 0.6671388041974123, 0.7684399634756779,
		0.8533633645833173, 0.9200993341504008, 0.9672268385663063,
		0.9937521706203895
	};
	double gl_weights_11[] = {
		0.0160172282577743, 0.0369537897708525, 0.0571344254268572,
		0.0761001136283793, 0.0934444234560339, 0.1087972991671484,
		0.1218314160537285, 0.1322689386333375, 0.1398873947910732,
		0.1445244789050542, 0.1460811308764353,
		0.1445244789050542, 0.1398873947910732, 0.1322689386333375,
		0.1218314160537285, 0.1087972991671484, 0.0934444234560339,
		0.0761001136283793, 0.0571344254268572, 0.0369537897708525,
		0.0160172282577743
	};
	for(int i = 0; i < 21; i++) {
		double node_01 = 0.5 * (gl_nodes_11[i] + 1.0);
		printf("%.16f", node_01);
		if(i < 20) printf(", ");
		if((i+1) % 4 == 0) printf("\n\t\t");
	}
	printf("\n\t};\n\n");

	printf("\t/// 21-point Gauss-Legendre quadrature weights on [0,1].\n");
	printf("\tstatic const Scalar GL_weights[21] = {\n\t\t");
	for(int i = 0; i < 21; i++) {
		double weight_01 = 0.5 * gl_weights_11[i];
		printf("%.16f", weight_01);
		if(i < 20) printf(", ");
		if((i+1) % 4 == 0) printf("\n\t\t");
	}
	printf("\n\t};\n\n");

	// ComputeFresnelAvg template function
	printf("\t/// Compute the hemispherical Fresnel average for a conductor:\n");
	printf("\t///   F_avg = 2 * integral_0^1 F(mu) * mu d_mu\n");
	printf("\t/// Uses 21-point Gauss-Legendre quadrature.\n");
	printf("\ttemplate< class T >\n");
	printf("\tinline T ComputeFresnelAvg( const Vector3& n, const T& Ni, const T& Nt, const T& kt )\n");
	printf("\t{\n");
	printf("\t\t// Build a tangent vector for constructing directions\n");
	printf("\t\tVector3 t;\n");
	printf("\t\tif( fabs(n.x) < 0.9 )\n");
	printf("\t\t\tt = Vector3Ops::Normalize( Vector3Ops::Cross( n, Vector3(1,0,0) ) );\n");
	printf("\t\telse\n");
	printf("\t\t\tt = Vector3Ops::Normalize( Vector3Ops::Cross( n, Vector3(0,1,0) ) );\n\n");
	printf("\t\tT sum = 0.0;\n");
	printf("\t\tfor( int i = 0; i < GL_N; i++ )\n");
	printf("\t\t{\n");
	printf("\t\t\tconst Scalar mu = GL_nodes[i];\n");
	printf("\t\t\tconst Scalar sinTheta = sqrt( r_max(0.0, 1.0 - mu*mu) );\n");
	printf("\t\t\t// Direction at angle acos(mu) from normal\n");
	printf("\t\t\tconst Vector3 v = n * (-mu) + t * sinTheta;\n");
	printf("\t\t\tconst T F = Optics::CalculateConductorReflectance<T>( v, n, Ni, Nt, kt );\n");
	printf("\t\t\tsum = sum + F * (2.0 * mu * GL_weights[i]);\n");
	printf("\t\t}\n");
	printf("\t\treturn sum;\n");
	printf("\t}\n\n");

	// ComputeFms
	printf("\t/// Compute the multiscatter Fresnel compensation factor:\n");
	printf("\t///   F_ms = F_avg^2 * E_avg / (1 - F_avg * (1 - E_avg))\n");
	printf("\ttemplate< class T >\n");
	printf("\tinline T ComputeFms( const T& F_avg, const Scalar Eavg )\n");
	printf("\t{\n");
	printf("\t\tconst T denom = 1.0 - F_avg * (1.0 - Eavg);\n");
	printf("\t\tif( ColorMath::MaxValue(denom) < 1e-10 ) return T(0.0);\n");
	printf("\t\treturn F_avg * F_avg * Eavg / denom;\n");
	printf("\t}\n\n");

	// Scalar specialization of MaxValue for the denom check
	printf("\t/// Scalar overload for ComputeFms\n");
	printf("\ttemplate<>\n");
	printf("\tinline Scalar ComputeFms<Scalar>( const Scalar& F_avg, const Scalar Eavg )\n");
	printf("\t{\n");
	printf("\t\tconst Scalar denom = 1.0 - F_avg * (1.0 - Eavg);\n");
	printf("\t\tif( denom < 1e-10 ) return 0.0;\n");
	printf("\t\treturn F_avg * F_avg * Eavg / denom;\n");
	printf("\t}\n");

	printf("}\n}\n\n");
	printf("#endif\n");

	return 0;
}
