// GENERATED by tools/generate_fire_production_roundoff_trace.py.
// Do not edit; regenerate from the strict production CPU arithmetic.
#include "../FireProductionRoundoffTrace.h"
//////////////////////////////////////////////////////////////////////
//
//  FireProductionTransport.h - fp32 production coupled transport
//
//  License Information: Please see the attached LICENSE.TXT file
//
//////////////////////////////////////////////////////////////////////

#ifndef TRACE_FIREPRODUCTIONTRANSPORT_
#define TRACE_FIREPRODUCTIONTRANSPORT_

#include "FireProductionAdvection.h"
#include "FireProductionProjection.h"
#include "../../src/Library/Utilities/FireSimulationRecords.h"

#include <array>
#include <cstddef>
#include <cstdint>
#include <string>
#include <vector>

namespace RISEFireProductionTrace
{
	//! Advection-only P3 oracle surface.  Carrier velocities and boundaries are
	//! frozen from the beginning snapshot; only conservativeValues advances.
	struct FireProductionCellPalindromeRequest
	{
		FireProductionProjectionShape shape;
		std::size_t componentCount;
		FireProductionRoundoffTrace::TraceFloat timeStepS;
		std::array<FireProductionProjectionBoundary,6> boundary;
		std::vector<FireProductionRoundoffTrace::TraceFloat> conservativeValues;
		std::array<std::vector<FireProductionRoundoffTrace::TraceFloat>,3> frozenVelocityMPerS;
		std::vector<FireProductionRoundoffTrace::TraceFloat> ambientValues;
		//! Diagnostic-only retention of the accepted primal gas-mass fluxes used
		//! by the Section 3.7 compatible-momentum comparator.  Ordinary production
		//! leaves this false and pays no buffer, kernel, or working-set cost.
		bool retainAcceptedGasMassDose;

		FireProductionCellPalindromeRequest() : componentCount(0u),timeStepS(0.0f),
			retainAcceptedGasMassDose(false)
		{
			boundary.fill(FireProductionProjectionWall);
		}
	};

	struct FireProductionCellPalindromeResult
	{
		std::vector<FireProductionRoundoffTrace::TraceFloat> conservativeValues;
		//! Accepted, timestep-integrated gas-mass flux on the primal faces for
		//! x/2,y/2,z,y/2,x/2.  Populated for the nine-component production tuple;
		//! empty for generic comparator tuples that do not contain the six gas
		//! constituent rows.
		std::array<std::vector<FireProductionRoundoffTrace::TraceFloat>,5> acceptedGasMassDoseKGPerM2;
		std::uint32_t executedSubmapCount;
		std::uint32_t privateResidentBufferCount;
		std::uint32_t sharedBufferCount;
		std::uint32_t commandCommitCount;
		std::uint32_t interstageFullGridReadbackCount;
		std::uint64_t certifiedWorkingSetBytes;
		std::uint64_t actualTrackedWorkingSetBytes;
		double deviceElapsedMS;

		FireProductionCellPalindromeResult() : executedSubmapCount(0u),
			privateResidentBufferCount(0u),sharedBufferCount(0u),commandCommitCount(0u),
			interstageFullGridReadbackCount(0u),certifiedWorkingSetBytes(0u),
			actualTrackedWorkingSetBytes(0u),deviceElapsedMS(0.0) {}
	};

	//! Dual-grid momentum comparison surface. Face arrays include their positive
	//! publication plane; it is a duplicate only on periodic component-normal axes.
	struct FireProductionDualMomentumRequest
	{
		FireProductionProjectionShape shape;
		FireProductionRoundoffTrace::TraceFloat timeStepS;
		FireProductionRoundoffTrace::TraceFloat ambientDensityKGPerM3;
		std::array<FireProductionProjectionBoundary,6> boundary;
		std::array<std::vector<FireProductionRoundoffTrace::TraceFloat>,3> beginningFaceDensity;
		std::array<std::vector<FireProductionRoundoffTrace::TraceFloat>,3> beginningMomentum;
		std::array<std::vector<FireProductionRoundoffTrace::TraceFloat>,3> frozenVelocityMPerS;

		FireProductionDualMomentumRequest() : timeStepS(0.0f),ambientDensityKGPerM3(1.0f)
		{
			boundary.fill(FireProductionProjectionPeriodic);
		}
	};

	struct FireProductionDualMomentumResult
	{
		std::array<std::vector<FireProductionRoundoffTrace::TraceFloat>,3> auxiliaryFaceDensity;
		std::array<std::vector<FireProductionRoundoffTrace::TraceFloat>,3> momentum;
		std::uint32_t executedSubmapCount;
		std::uint32_t canonicalSeamCopyCount;
		std::uint32_t commandCommitCount;
		std::uint32_t interstageFullGridTransferCount;
		std::uint64_t actualMetalAllocationBytes;
		double deviceElapsedMS;

		FireProductionDualMomentumResult() : executedSubmapCount(0u),
			canonicalSeamCopyCount(0u),commandCommitCount(0u),
			interstageFullGridTransferCount(0u),actualMetalAllocationBytes(0u),
			deviceElapsedMS(0.0) {}
	};

	//! Pure Section 3.7 compatible-flux operator input.  Low and high are the
	//! advective gas-mass flux pair on primal MAC faces.  Physical gas flux is
	//! optional per axis (an empty vector is exact +0).  The shared face alpha
	//! and velocity are frozen operands; this seam computes no evolving state.
	struct FireProductionCompatibleFCTMomentumRequest
	{
		FireProductionProjectionShape shape;
		std::array<FireProductionProjectionBoundary,6> boundary;
		std::array<std::vector<FireProductionRoundoffTrace::TraceFloat>,3> lowGasFluxKGPerM2S;
		std::array<std::vector<FireProductionRoundoffTrace::TraceFloat>,3> highGasFluxKGPerM2S;
		std::array<std::vector<FireProductionRoundoffTrace::TraceFloat>,3> physicalGasFluxKGPerM2S;
		std::array<std::vector<FireProductionRoundoffTrace::TraceFloat>,3> sharedFaceAlpha;
		std::array<std::vector<FireProductionRoundoffTrace::TraceFloat>,3> frozenVelocityMPerS;

		FireProductionCompatibleFCTMomentumRequest()
		{
			boundary.fill(FireProductionProjectionWall);
		}
	};

	struct FireProductionCompatibleFCTMomentumResult
	{
		std::array<std::vector<FireProductionRoundoffTrace::TraceFloat>,3> acceptedGasFluxKGPerM2S;
		std::array<std::vector<FireProductionRoundoffTrace::TraceFloat>,3> advectionRateKGPerM2S2;
	};

	//! Prerequisite-only producer input for the nonadvective Section 3.7 scalar
	//! face tuple.  This is not a projected-Heun owner and advances no state.
	//! Q is component-major [9][cells]; T, D, and k are fixed binary32 stage
	//! operands.  Pressure-open classification is sealed by the caller.
	struct FireProductionScalarPhysicalFluxPrerequisiteRequest
	{
		FireProductionProjectionShape shape;
		std::array<FireProductionProjectionBoundary,6> boundary;
		std::vector<FireProductionRoundoffTrace::TraceFloat> conservativeValues;
		std::vector<FireProductionRoundoffTrace::TraceFloat> temperatureK;
		std::vector<FireProductionRoundoffTrace::TraceFloat> diffusivityM2PerS;
		std::vector<FireProductionRoundoffTrace::TraceFloat> conductivityWPerMK;
		std::array<std::vector<FireProductionRoundoffTrace::TraceFloat>,3> frozenVelocityMPerS;
		std::array<FireProductionRoundoffTrace::TraceFloat,9> ambient;
		FireProductionRoundoffTrace::TraceFloat ambientTemperatureK;
		std::array<std::vector<unsigned char>,6> pressureOpenInflow;

		FireProductionScalarPhysicalFluxPrerequisiteRequest() : ambientTemperatureK(0.0f)
		{
			boundary.fill(FireProductionProjectionWall);ambient.fill(0.0f);
		}
	};

	//! Separately retained f_N and J_g.  Mass is component-major [8][faces];
	//! energy and gas are packed x/y/z face arrays.  The record identity makes
	//! this prerequisite object unsuitable for cross-record composition.
	struct FireProductionScalarPhysicalFluxPrerequisiteResult
	{
		FireProductionProjectionShape shape;
		std::array<FireProductionProjectionBoundary,6> boundary;
		std::array<std::size_t,3> packedFaceOffset;
		std::vector<FireProductionRoundoffTrace::TraceFloat> physicalMassFluxKGPerM2S;
		std::vector<FireProductionRoundoffTrace::TraceFloat> physicalEnergyFluxWPerM2;
		std::array<std::vector<FireProductionRoundoffTrace::TraceFloat>,3> physicalGasFluxKGPerM2S;
		std::string methaneRecordId;
		double maximumFP64ReferenceResidualKGPerM2S;
		double fp64ReferenceForwardErrorBoundKGPerM2S;
		double maximumConstraintResidualKGPerM2S;
		double constraintForwardErrorBoundKGPerM2S;
		bool fp64ReferenceIdentityVerified;

		FireProductionScalarPhysicalFluxPrerequisiteResult() :
			maximumFP64ReferenceResidualKGPerM2S(0.0),
			fp64ReferenceForwardErrorBoundKGPerM2S(0.0),
			maximumConstraintResidualKGPerM2S(0.0),
			constraintForwardErrorBoundKGPerM2S(0.0),
			fp64ReferenceIdentityVerified(false)
		{
			boundary.fill(FireProductionProjectionWall);packedFaceOffset.fill(0u);
		}
	};

	//! Strict-binary32 owner surface for the four scalar stages used by the
	//! isolated full-FCT diagnostic: donor/MC pair, r60 shared alpha, source-
	//! inclusive scalar commit, and the periodic D_i I_i commuting witness.
	//! Cell tuples are component-major [9][cells].  Flux tuples are
	//! component-major over the packed x/y/z primal faces.
	struct FireProductionScalarFCTRequest
	{
		FireProductionProjectionShape shape;
		FireProductionRoundoffTrace::TraceFloat timeStepS;
		std::array<FireProductionProjectionBoundary,6> boundary;
		std::vector<FireProductionRoundoffTrace::TraceFloat> beginning;
		std::vector<FireProductionRoundoffTrace::TraceFloat> sourceDelta;
		std::array<std::vector<FireProductionRoundoffTrace::TraceFloat>,3> frozenVelocityMPerS;
		std::array<FireProductionRoundoffTrace::TraceFloat,9> ambient;
		std::array<std::vector<unsigned char>,6> pressureOpenInflow;
		std::size_t nullity;
		std::vector<FireProductionRoundoffTrace::TraceFloat> nullspaceBasis;
		std::vector<FireProductionRoundoffTrace::TraceFloat> coordinateProjector;
		std::array<FireProductionRoundoffTrace::TraceFloat,14> enthalpyBoundsJPerKG;
		FireProductionRoundoffTrace::TraceFloat feasibilityFactor;
		FireProductionRoundoffTrace::TraceFloat assemblyReserveFactor;

		FireProductionScalarFCTRequest() : timeStepS(0.0f),nullity(0u),
			feasibilityFactor(0.0f),assemblyReserveFactor(0.0f)
		{
			boundary.fill(FireProductionProjectionWall);ambient.fill(0.0f);
			enthalpyBoundsJPerKG.fill(0.0f);
		}
	};

	struct FireProductionScalarFCTResult
	{
		std::array<std::size_t,3> packedFaceOffset;
		std::vector<FireProductionRoundoffTrace::TraceFloat> lowFlux;
		std::vector<FireProductionRoundoffTrace::TraceFloat> fluxDelta;
		std::vector<FireProductionRoundoffTrace::TraceFloat> lowState;
		std::vector<FireProductionRoundoffTrace::TraceFloat> limiterRatio;
		std::array<std::vector<FireProductionRoundoffTrace::TraceFloat>,3> sharedFaceAlpha;
		std::vector<FireProductionRoundoffTrace::TraceFloat> accepted;
		std::array<std::vector<FireProductionRoundoffTrace::TraceFloat>,3> acceptedGasFluxKGPerM2S;
		FireProductionRoundoffTrace::TraceFloat maximumCommutingResidualKGPerM3;
		FireProductionRoundoffTrace::TraceFloat commutingIdentityScaleKGPerM3;
		FireProductionRoundoffTrace::TraceFloat commutingIdentityRestrictedAcceptedKGPerM3;
		FireProductionRoundoffTrace::TraceFloat commutingIdentityAdvancedKGPerM3;
		unsigned int commutingIdentityComponent;
		std::size_t commutingIdentityFace;
		bool commutingIdentityAvailable;

		FireProductionScalarFCTResult() : maximumCommutingResidualKGPerM3(0.0f),
			commutingIdentityScaleKGPerM3(0.0f),
			commutingIdentityRestrictedAcceptedKGPerM3(0.0f),
			commutingIdentityAdvancedKGPerM3(0.0f),commutingIdentityComponent(0u),
			commutingIdentityFace(0u),
			commutingIdentityAvailable(false)
		{
			packedFaceOffset.fill(0u);
		}
	};

	//! The two accepted conservative states that require an EOS gate in the
	//! projected-Heun construction.  Zero is deliberately not a valid role.
	enum class FireProductionScalarEOSStage : std::uint8_t
	{
		QStar=1u,
		QNPlus1=2u
	};

	//! CPU-only prerequisite for accepting one completed scalar state.  This is
	//! intentionally not wired into the projected-Heun owner: the owner and its
	//! Metal-resident equivalent must fail closed until they consume this sealed
	//! result without host substitution.
	struct FireProductionScalarEOSAcceptanceRequest
	{
		FireProductionProjectionShape shape;
		FireProductionRoundoffTrace::TraceFloat timeStepS;
		std::uint64_t attemptIdentity;
		FireProductionScalarEOSStage stage;
		RISE::FireStateProducerPrecision producerPrecision;
		std::string methaneRecordId;
		//! Canonical fire-case-v1 envelope. The gate derives its identity and
		//! inversion bounds from these bytes; caller-authored ceilings are not an
		//! API surface.
		RISE::RISECBOR64::Bytes caseRecordEnvelope;
		std::vector<FireProductionRoundoffTrace::TraceFloat> conservativeValues;

		FireProductionScalarEOSAcceptanceRequest() : timeStepS(0.0f),
			attemptIdentity(0u),stage(static_cast<FireProductionScalarEOSStage>(0u)),
			producerPrecision(RISE::FireStateProducerPrecision::Binary32) {}
	};

	//! Identity-bearing publication from the accepted-state EOS gate.  The
	//! identity covers the exact request state and all attempt/role/bound record
	//! metadata, plus the exact published binary32 temperature field.
	struct FireProductionScalarEOSAcceptanceResult
	{
		FireProductionProjectionShape shape;
		FireProductionRoundoffTrace::TraceFloat timeStepS;
		std::uint64_t attemptIdentity;
		FireProductionScalarEOSStage stage;
		RISE::FireStateProducerPrecision producerPrecision;
		std::string methaneRecordId;
		std::string caseRecordId;
		double lowerTemperatureK;
		double upperTemperatureK;
		std::vector<FireProductionRoundoffTrace::TraceFloat> temperatureK;
		//! Monitored P0-deviation diagnostic. The retired oracle 1e-3 validity
		//! detector is not a production acceptance threshold.
		double maximumEOSResidual;
		std::uint64_t stateDigest;
		std::uint64_t temperatureDigest;
		std::uint64_t acceptanceIdentity;
		bool accepted;

		FireProductionScalarEOSAcceptanceResult() : timeStepS(0.0f),
			attemptIdentity(0u),stage(static_cast<FireProductionScalarEOSStage>(0u)),
			producerPrecision(RISE::FireStateProducerPrecision::Binary32),
			lowerTemperatureK(0.0),upperTemperatureK(0.0),maximumEOSResidual(0.0),
			stateDigest(0u),temperatureDigest(0u),acceptanceIdentity(0u),accepted(false) {}
	};

	//! Identity-bearing donor/MC flux pair for one scalar FCT stage.  The pair
	//! deliberately excludes limiter state: projected Heun averages the two
	//! stage fluxes, then solves one fresh shared limiter for the averaged pair.
	struct FireProductionScalarFCTFluxPair
	{
		FireProductionProjectionShape shape;
		FireProductionRoundoffTrace::TraceFloat timeStepS;
		std::array<FireProductionProjectionBoundary,6> boundary;
		std::array<std::size_t,3> packedFaceOffset;
		std::vector<FireProductionRoundoffTrace::TraceFloat> lowFlux;
		std::vector<FireProductionRoundoffTrace::TraceFloat> fluxDelta;

		FireProductionScalarFCTFluxPair() : timeStepS(0.0f)
		{
			boundary.fill(FireProductionProjectionWall);
			packedFaceOffset.fill(0u);
		}
	};

	enum class FireProductionScalarHeunFluxRole : std::uint8_t
	{
		R0=1u,
		R1=2u,
		HeunAverage=3u
	};

	//! Identity-bearing Section 3.7 scalar-flux stage.  The composite pair is
	//! the exact low-order scalar flux consumed by the FCT solve: donor flux
	//! plus f_N for the eight mass components and donor energy plus the physical
	//! energy flux, with an advective-only antidiffusive delta.  The remaining
	//! twelve face fields retain f_N, J_g, Phi_g^L, and Delta Phi_g separately so
	//! compatible momentum never reconstructs them from a rounded composite.
	//! The persistent payload is exactly 30 packed binary32 face fields.
	struct FireProductionScalarHeunFluxStage
	{
		FireProductionScalarFCTFluxPair compositeFluxPair;
		std::vector<FireProductionRoundoffTrace::TraceFloat> physicalMassFluxKGPerM2S;
		std::vector<FireProductionRoundoffTrace::TraceFloat> physicalEnergyFluxWPerM2;
		std::array<std::vector<FireProductionRoundoffTrace::TraceFloat>,3> physicalGasFluxKGPerM2S;
		std::array<std::vector<FireProductionRoundoffTrace::TraceFloat>,3> advectiveGasLowFluxKGPerM2S;
		std::array<std::vector<FireProductionRoundoffTrace::TraceFloat>,3> advectiveGasFluxDeltaKGPerM2S;
		std::string methaneRecordId;
		std::uint64_t attemptIdentity;
		FireProductionScalarHeunFluxRole role;
		std::uint64_t stageInputIdentity;
		std::uint64_t sharedFCTContractIdentity;
		std::uint64_t fctRequestIdentity;
		std::uint64_t frozenVelocityIdentity;
		std::array<std::uint64_t,2> parentCompositionIdentity;
		std::uint64_t compositionIdentity;
		double physicalConstraintForwardErrorBoundKGPerM2S;
		double physicalGasAveragingForwardErrorBoundKGPerM2S;
		bool fp64ReferenceIdentityVerified;

		FireProductionScalarHeunFluxStage() : attemptIdentity(0u),
			role(static_cast<FireProductionScalarHeunFluxRole>(0u)),stageInputIdentity(0u),
			sharedFCTContractIdentity(0u),fctRequestIdentity(0u),
			frozenVelocityIdentity(0u),compositionIdentity(0u),
			physicalConstraintForwardErrorBoundKGPerM2S(0.0),
			physicalGasAveragingForwardErrorBoundKGPerM2S(0.0),
			fp64ReferenceIdentityVerified(false) { parentCompositionIdentity.fill(0u); }
	};

	//! Identity-bearing fresh-alpha solve for one authenticated HeunAverage stage.
	//! Its alpha cannot be transplanted to a different attempt or R0/R1 parent.
	struct FireProductionScalarHeunSolveResult
	{
		FireProductionScalarFCTResult scalar;
		std::uint64_t attemptIdentity;
		std::uint64_t averageCompositionIdentity;
		std::uint64_t sharedFCTContractIdentity;
		std::array<std::uint64_t,2> parentCompositionIdentity;
		std::uint64_t alphaIdentity;

		FireProductionScalarHeunSolveResult() : attemptIdentity(0u),
			averageCompositionIdentity(0u),sharedFCTContractIdentity(0u),
			alphaIdentity(0u) { parentCompositionIdentity.fill(0u); }
	};

	using FireProductionPeriodicDualMomentumRequest=FireProductionDualMomentumRequest;
	using FireProductionPeriodicDualMomentumResult=FireProductionDualMomentumResult;

	bool ValidateFireProductionCellPalindromeRequest(
		const FireProductionCellPalindromeRequest& request,
		std::string* error=0 );

	bool ValidateFireProductionDualMomentumRequest(
		const FireProductionDualMomentumRequest& request,
		std::string* error=0 );

	//! Complete standalone-comparator peak, including caller request/result,
	//! Shared staging, private resident scratch, all five parameter pairs, and
	//! conservative 16-KiB outward allocation rounding for every Metal buffer.
	bool FireProductionCellPalindromeWorkingSetBytes(
		const FireProductionProjectionShape& shape,
		std::size_t componentCount,
		std::uint64_t& bytes,
		bool retainAcceptedGasMassDose=false );

	//! Strict-binary32 five-pass oracle: x/2,y/2,z,y/2,x/2.
	bool RemapFireProductionCellPalindromeCPU(
		const FireProductionCellPalindromeRequest& request,
		FireProductionCellPalindromeResult& result,
		std::string* error=0 );

	//! One-command Metal comparator for the same five-pass composition.  Full
	//! grids remain private between passes; Shared staging exists only at the
	//! standalone request and publication boundaries.
	bool RemapFireProductionCellPalindromeMetal(
		const FireProductionCellPalindromeRequest& request,
		FireProductionCellPalindromeResult& result,
		std::string* error=0 );

	//! Test/publication wrapper around the Private-buffer resident seam. It
	//! performs boundary upload and terminal staging outside the resident call,
	//! and reports only the resident command/transfer diagnostics.
	bool RemapFireProductionCellPalindromeMetalResidentComparator(
		const FireProductionCellPalindromeRequest& request,
		FireProductionCellPalindromeResult& result,
		std::string* error=0 );

#if defined(__OBJC__) && defined(__APPLE__)
	struct FireProductionMetalCellPalindromeResidentInput
	{
		id<MTLBuffer> conservativeValues;
		std::array<id<MTLBuffer>,3> frozenVelocityMPerS;
		id<MTLBuffer> ambientValues;

		FireProductionMetalCellPalindromeResidentInput() : conservativeValues(nil),
			ambientValues(nil)
		{
			frozenVelocityMPerS.fill(nil);
		}
	};

	struct FireProductionMetalCellPalindromeResidentResult
	{
		id<MTLBuffer> conservativeValues;
		std::array<id<MTLBuffer>,5> acceptedGasMassDoseKGPerM2;
		std::uint32_t executedSubmapCount;
		std::uint32_t commandCommitCount;
		std::uint32_t interstageFullGridTransferCount;
		std::uint64_t actualMetalAllocationBytes;
		double deviceElapsedMS;
		double deviceStartTimeS;
		double deviceEndTimeS;

		FireProductionMetalCellPalindromeResidentResult() : conservativeValues(nil),
			executedSubmapCount(0u),commandCommitCount(0u),
			interstageFullGridTransferCount(0u),actualMetalAllocationBytes(0u),
			deviceElapsedMS(0.0),deviceStartTimeS(0.0),deviceEndTimeS(0.0)
		{
			acceptedGasMassDoseKGPerM2.fill(nil);
		}
	};

	//! Private-buffer production seam. The host request supplies validation and
	//! schedule bytes; the authoritative full-grid operands are the resident
	//! buffers. No full-grid staging or host access is permitted in this call.
	bool RemapFireProductionCellPalindromeMetalResident(
		const FireProductionCellPalindromeRequest& request,
		const FireProductionMetalCellPalindromeResidentInput& input,
		FireProductionMetalCellPalindromeResidentResult& result,
		std::string* error=0 );
#endif

	//! Strict-binary32 periodic MAC oracle.  Each noncollocated momentum
	//! component owns a separate dual tuple and five-pass palindrome.
	bool RemapFireProductionPeriodicDualMomentumCPU(
		const FireProductionPeriodicDualMomentumRequest& request,
		FireProductionPeriodicDualMomentumResult& result,
		std::string* error=0 );

	//! Step-boundary packing oracle for one periodic MAC component. This builds
	//! the common auxiliary-density/momentum cell tuple and its three frozen
	//! dual carriers; resident execution consumes the corresponding Private
	//! buffers without rebuilding or staging them interstage.
	bool BuildFireProductionPeriodicDualCellRequest(
		const FireProductionPeriodicDualMomentumRequest& request,
		unsigned int transportedComponent,
		FireProductionCellPalindromeRequest& dualRequest,
		std::string* error=0 );

	//! Conservative resident periodic-dual peak. It adds all nine borrowed and
	//! six atomically published face arrays to the largest two-channel resident
	//! palindrome certificate.
	bool FireProductionPeriodicDualMomentumResidentWorkingSetBytes(
		const FireProductionProjectionShape& shape,
		std::uint64_t& bytes );

	bool FireProductionDualMomentumResidentWorkingSetBytes(
		const FireProductionProjectionShape& shape,
		const std::array<FireProductionProjectionBoundary,6>& boundary,
		std::uint64_t& bytes );

	//! Section 3.7 compatible dual-grid peak.  The five accepted primal gas
	//! mass-dose fields are already owned by the scalar palindrome; this seam
	//! counts only the dual ping-pong state and its parameter buffer.
	bool FireProductionCompatibleDualMomentumResidentWorkingSetBytes(
		const FireProductionProjectionShape& shape,
		std::uint64_t& bytes );

	//! Standalone oracle wrapper around the periodic Private-buffer resident
	//! dual-grid seam. Boundary uploads and the final tap are outside the
	//! measured resident interval.
	bool RemapFireProductionPeriodicDualMomentumMetal(
		const FireProductionPeriodicDualMomentumRequest& request,
		FireProductionPeriodicDualMomentumResult& result,
		std::string* error=0 );

	//! Strict-binary32 six-side MAC oracle. Component-normal wall planes are
	//! prescribed, open endpoints skip only their normal sweep, and transverse
	//! sweeps consume line-resolved ambient tuples through the shared P1 kernel.
	bool RemapFireProductionDualMomentumCPU(
		const FireProductionDualMomentumRequest& request,
		FireProductionDualMomentumResult& result,
		std::string* error=0 );

	//! Structural preflight for the compatible owner.  Unlike the retired dual
	//! remap validator, this does not inspect frozen carrier fields or construct
	//! an independent two-component limiter that the compatible operator never
	//! consumes.
	bool ValidateFireProductionCompatibleDualMomentumRequest(
		const FireProductionDualMomentumRequest& request,
		std::string* error=0 );

	//! Section 3.7 compatible momentum transport.  Momentum does not own an
	//! independent reconstruction: every dual-control-volume face receives the
	//! boundary-aware I_i restriction of the scalar palindrome's already
	//! shared-alpha-limited gas-mass dose, multiplied by the arithmetic mean of
	//! the adjacent transported-component velocities.
	bool RemapFireProductionCompatibleDualMomentumCPU(
		const FireProductionDualMomentumRequest& request,
		const std::array<std::vector<FireProductionRoundoffTrace::TraceFloat>,5>& acceptedGasMassDoseKGPerM2,
		FireProductionDualMomentumResult& result,
		std::string* error=0 );

	//! Evaluates K_i=I_i(low+alpha*(high-low)+physical)*mean(u) and then D_i K_i.
	//! All-periodic and all-nonperiodic topologies are supported.  Hybrid
	//! periodic/open topology is rejected until it has an authoritative oracle.
	bool EvaluateFireProductionCompatibleFCTMomentumCPU(
		const FireProductionCompatibleFCTMomentumRequest& request,
		FireProductionCompatibleFCTMomentumResult& result,
		std::string* error=0 );

	//! Logical caller-input plus produced-output footprint: 4(12C+11F)+B.
	//! This is query-only and performs no allocation.
	bool QueryFireProductionScalarPhysicalFluxPrerequisiteCPUWorkingSetBytes(
		const FireProductionProjectionShape& shape,
		std::uint64_t& workingSetBytes,
		std::string* error=0 );

	bool BuildFireProductionScalarPhysicalFluxPrerequisiteCPU(
		const FireProductionScalarPhysicalFluxPrerequisiteRequest& request,
		FireProductionScalarPhysicalFluxPrerequisiteResult& result,
		std::string* error=0 );

	//! Exact persistent payload for one composed stage: 30 packed face fields.
	//! Query-only; allocation and payload inspection are forbidden here.
	bool QueryFireProductionScalarHeunFluxStageCPUPayloadBytes(
		const FireProductionProjectionShape& shape,
		std::uint64_t& payloadBytes,
		std::string* error=0 );

	//! Builds and composes one donor/MC pair with its same-stage physical f_N/J_g
	//! directly from authenticated raw operands; mutable prerequisite results are
	//! never accepted as authority.
	//! The operation order is fixed: publish the physical fields, add them once
	//! to the low pair component-by-component, and retain the advective gas sums
	//! independently in ascending species order.  Failure publishes no fields.
	bool ComposeFireProductionScalarHeunFluxStageCPU(
		std::uint64_t attemptIdentity,
		FireProductionScalarHeunFluxRole role,
		const FireProductionScalarFCTRequest& advectiveRequest,
		const FireProductionScalarPhysicalFluxPrerequisiteRequest& physicalRequest,
		FireProductionScalarHeunFluxStage& result,
		std::string* error=0 );

	//! Arithmetic stage average over all 30 retained fields.  No limiter state is
	//! carried or averaged; the returned composite pair requires one fresh r60
	//! shared-alpha solve.
	bool AverageFireProductionScalarHeunFluxStagesCPU(
		const FireProductionScalarHeunFluxStage& first,
		const FireProductionScalarHeunFluxStage& second,
		FireProductionScalarHeunFluxStage& result,
		std::string* error=0 );

	//! Validates the complete averaged-stage lineage and performs the one fresh
	//! shared-alpha solve.  The legacy pair-only solver remains diagnostic and
	//! cannot produce the identity token required by compatible Heun momentum.
	bool SolveFireProductionScalarHeunFluxStageCPU(
		std::uint64_t attemptIdentity,
		const FireProductionScalarFCTRequest& request,
		const FireProductionScalarHeunFluxStage& averagedStage,
		FireProductionScalarHeunSolveResult& result,
		std::string* error=0 );

	//! Direct-delta compatible momentum consumer.  It evaluates exactly
	//! Phi_g^L+alpha*DeltaPhi_g+J_g from the retained stage bytes; it never forms
	//! a high flux and never reconstructs DeltaPhi_g by subtraction.
	bool EvaluateFireProductionCompatibleHeunMomentumCPU(
		const FireProductionScalarHeunFluxStage& stage,
		const FireProductionScalarHeunSolveResult& solve,
		const std::array<std::vector<FireProductionRoundoffTrace::TraceFloat>,3>& frozenVelocityMPerS,
		FireProductionCompatibleFCTMomentumResult& result,
		std::string* error=0 );

	bool EvaluateFireProductionScalarFCTCPU(
		const FireProductionScalarFCTRequest& request,
		FireProductionScalarFCTResult& result,
		std::string* error=0 );

	//! Exact logical payload peak: component-major Q[9][C] plus T[C].
	//! Query-only; allocation and payload inspection are forbidden here.
	bool QueryFireProductionScalarEOSAcceptanceCPUWorkingSetBytes(
		const FireProductionProjectionShape& shape,
		std::uint64_t& workingSetBytes,
		std::string* error=0 );

	//! Allocation-free per-cell record inversion apart from the single published
	//! temperature vector. The authenticated case envelope owns the strict upper
	//! temperature bound; p/P0 deviation is published as a monitored diagnostic.
	bool EvaluateFireProductionScalarEOSAcceptanceCPU(
		const FireProductionScalarEOSAcceptanceRequest& request,
		FireProductionScalarEOSAcceptanceResult& result,
		std::string* error=0 );

	//! Verifies exact request/result provenance without rerunning thermochemistry.
	bool FireProductionScalarEOSAcceptanceMatches(
		const FireProductionScalarEOSAcceptanceRequest& request,
		const FireProductionScalarEOSAcceptanceResult& result );

	//! Builds only the donor/MC flux pair from Q and the frozen carrier.  Source
	//! dose and limiter acceptance are not applied by this stage.
	bool BuildFireProductionScalarFCTFluxPairCPU(
		const FireProductionScalarFCTRequest& request,
		FireProductionScalarFCTFluxPair& result,
		std::string* error=0 );

	//! Arithmetic mean of two stage flux pairs.  Limiter alphas are intentionally
	//! absent: the caller must solve a fresh shared alpha for this averaged pair.
	bool AverageFireProductionScalarFCTFluxPairsCPU(
		const FireProductionScalarFCTFluxPair& first,
		const FireProductionScalarFCTFluxPair& second,
		FireProductionScalarFCTFluxPair& result,
		std::string* error=0 );

	//! Applies one source dose, constructs the low state, solves a fresh r60
	//! shared limiter, and commits the caller-provided flux pair.
	bool SolveFireProductionScalarFCTFluxPairCPU(
		const FireProductionScalarFCTRequest& request,
		const FireProductionScalarFCTFluxPair& fluxPair,
		FireProductionScalarFCTResult& result,
		std::string* error=0 );

#if defined(__APPLE__)
	//! Fail-closed blocker. Metal qualification requires device candidates to be
	//! checked against the fp64 N_C N_C^T forward-error certificate first.
	bool BuildFireProductionScalarPhysicalFluxPrerequisiteMetal(
		const FireProductionScalarPhysicalFluxPrerequisiteRequest& request,
		FireProductionScalarPhysicalFluxPrerequisiteResult& result,
		std::string* error=0 );

	//! Host-published fields produced by the diagnostic Metal acceptance solve.
	//! Accepted gas flux and the commuting witness belong to the later compatible-
	//! momentum stage and are deliberately absent rather than CPU-filled here.
	struct FireProductionScalarFCTMetalAcceptanceStageResult
	{
		std::array<std::size_t,3> packedFaceOffset;
		std::vector<FireProductionRoundoffTrace::TraceFloat> lowFlux;
		std::vector<FireProductionRoundoffTrace::TraceFloat> fluxDelta;
		std::vector<FireProductionRoundoffTrace::TraceFloat> lowState;
		std::vector<FireProductionRoundoffTrace::TraceFloat> limiterRatio;
		std::array<std::vector<FireProductionRoundoffTrace::TraceFloat>,3> sharedFaceAlpha;
		std::vector<FireProductionRoundoffTrace::TraceFloat> accepted;

		FireProductionScalarFCTMetalAcceptanceStageResult()
			{ packedFaceOffset.fill(0u); }
	};

	//! Host-published bootstrap for the diagnostic resident Metal stages.  It is
	//! not an accepted step owner: its only authority is matched-input CPU/Metal
	//! producer equivalence while the complete projected-Heun owner is absent.
	struct FireProductionScalarFCTMetalStageDiagnosticResult
	{
		FireProductionScalarFCTFluxPair firstFluxPair;
		FireProductionScalarFCTFluxPair secondFluxPair;
		FireProductionScalarFCTFluxPair averagedFluxPair;
		FireProductionScalarFCTMetalAcceptanceStageResult firstSolve;
		FireProductionScalarFCTMetalAcceptanceStageResult secondSolve;
		FireProductionScalarFCTMetalAcceptanceStageResult averagedSolve;
		std::array<std::uint32_t,3> failureBitmap;
		std::uint32_t commandCommitCount;

		FireProductionScalarFCTMetalStageDiagnosticResult() : commandCommitCount(0u)
			{ failureBitmap.fill(0u); }
	};

	bool EvaluateFireProductionScalarFCTMetalStageDiagnostic(
		const FireProductionScalarFCTRequest& firstStage,
		const FireProductionScalarFCTRequest& secondStage,
		FireProductionScalarFCTMetalStageDiagnosticResult& result,
		std::string* error=0 );
#endif

	//! Step-boundary oracle for one of the nine dual-grid line layouts.  The
	//! values are disposable packing bytes; carrier and side ambient arrays are
	//! the frozen operands uploaded before the resident interval.
	bool BuildFireProductionDualAxisRequest(
		const FireProductionDualMomentumRequest& request,
		unsigned int transportedComponent,
		unsigned int sweepAxis,
		FireProductionRoundoffTrace::TraceFloat timeStepS,
		const std::vector<FireProductionRoundoffTrace::TraceFloat>& density,
		const std::vector<FireProductionRoundoffTrace::TraceFloat>& momentum,
		FireProductionRemapRequest& lineRequest,
		std::string* error=0 );

	//! Standalone oracle wrapper around the mixed-boundary resident seam.
	//! Upload and final staging are outside the measured resident interval.
	bool RemapFireProductionDualMomentumMetalResidentComparator(
		const FireProductionDualMomentumRequest& request,
		FireProductionDualMomentumResult& result,
		std::string* error=0 );

#if defined(__OBJC__) && defined(__APPLE__)
	//! Private-buffer output of the diagnostic Metal donor/MC stage.  These
	//! operations are reusable building blocks only; they cannot publish an
	//! accepted production step until the complete projected-Heun owner is gated.
	struct FireProductionMetalScalarFCTFluxPairDiagnostic
	{
		FireProductionProjectionShape shape;
		FireProductionRoundoffTrace::TraceFloat timeStepS;
		std::array<FireProductionProjectionBoundary,6> boundary;
		std::array<std::size_t,3> packedFaceOffset;
		id<MTLBuffer> lowFlux;
		id<MTLBuffer> fluxDelta;
		std::uint64_t actualMetalAllocationBytes;
		std::uint32_t commandCommitCount;

		FireProductionMetalScalarFCTFluxPairDiagnostic() : timeStepS(0.0f),
			lowFlux(nil),fluxDelta(nil),
			actualMetalAllocationBytes(0u),commandCommitCount(0u)
			{ boundary.fill(FireProductionProjectionWall);packedFaceOffset.fill(0u); }
	};

	struct FireProductionMetalScalarFCTSolveDiagnostic
	{
		FireProductionProjectionShape shape;
		std::array<std::size_t,3> packedFaceOffset;
		id<MTLBuffer> lowState;
		id<MTLBuffer> limiterRatio;
		id<MTLBuffer> packedFaceAlpha;
		id<MTLBuffer> accepted;
		id<MTLBuffer> failureBitmap;
		std::uint64_t actualMetalAllocationBytes;
		std::uint32_t commandCommitCount;

		FireProductionMetalScalarFCTSolveDiagnostic() : lowState(nil),limiterRatio(nil),
			packedFaceAlpha(nil),accepted(nil),failureBitmap(nil),
			actualMetalAllocationBytes(0u),commandCommitCount(0u)
			{ packedFaceOffset.fill(0u); }
	};

	bool BuildFireProductionScalarFCTFluxPairMetalResidentDiagnostic(
		const FireProductionScalarFCTRequest& request,
		id<MTLBuffer> beginning,
		const std::array<id<MTLBuffer>,3>& frozenVelocityMPerS,
		FireProductionMetalScalarFCTFluxPairDiagnostic& result,
		std::string* error=0 );

	bool AverageFireProductionScalarFCTFluxPairsMetalResidentDiagnostic(
		const FireProductionMetalScalarFCTFluxPairDiagnostic& first,
		const FireProductionMetalScalarFCTFluxPairDiagnostic& second,
		FireProductionMetalScalarFCTFluxPairDiagnostic& result,
		std::string* error=0 );

	bool SolveFireProductionScalarFCTFluxPairMetalResidentDiagnostic(
		const FireProductionScalarFCTRequest& request,
		id<MTLBuffer> beginning,
		id<MTLBuffer> sourceDelta,
		const FireProductionMetalScalarFCTFluxPairDiagnostic& fluxPair,
		FireProductionMetalScalarFCTSolveDiagnostic& result,
		std::string* error=0 );

	struct FireProductionMetalPeriodicDualMomentumResidentInput
	{
		std::array<id<MTLBuffer>,3> beginningFaceDensity;
		std::array<id<MTLBuffer>,3> beginningMomentum;
		std::array<id<MTLBuffer>,3> frozenVelocityMPerS;

		FireProductionMetalPeriodicDualMomentumResidentInput()
		{
			beginningFaceDensity.fill(nil);beginningMomentum.fill(nil);
			frozenVelocityMPerS.fill(nil);
		}
	};

	struct FireProductionMetalPeriodicDualMomentumResidentResult
	{
		std::array<id<MTLBuffer>,3> auxiliaryFaceDensity;
		std::array<id<MTLBuffer>,3> momentum;
		std::uint32_t executedSubmapCount;
		std::uint32_t commandCommitCount;
		std::uint32_t interstageFullGridTransferCount;
		std::uint64_t actualMetalAllocationBytes;
		double deviceElapsedMS;

		FireProductionMetalPeriodicDualMomentumResidentResult() :
			executedSubmapCount(0u),commandCommitCount(0u),
			interstageFullGridTransferCount(0u),actualMetalAllocationBytes(0u),
			deviceElapsedMS(0.0)
		{
			auxiliaryFaceDensity.fill(nil);momentum.fill(nil);
		}
	};

	bool RemapFireProductionPeriodicDualMomentumMetalResident(
		const FireProductionPeriodicDualMomentumRequest& request,
		const FireProductionMetalPeriodicDualMomentumResidentInput& input,
		FireProductionMetalPeriodicDualMomentumResidentResult& result,
		std::string* error=0 );

	struct FireProductionMetalDualAxisStaticState
	{
		id<MTLBuffer> faceVelocityMPerS;
		id<MTLBuffer> lowerAmbientValues;
		id<MTLBuffer> upperAmbientValues;
		std::uint32_t lineLength;
		std::uint32_t lineCount;
		std::uint32_t lowerBoundary;
		std::uint32_t upperBoundary;
		std::uint32_t ambientPerLine;

		FireProductionMetalDualAxisStaticState() : faceVelocityMPerS(nil),
			lowerAmbientValues(nil),upperAmbientValues(nil),lineLength(0u),lineCount(0u),
			lowerBoundary(0u),upperBoundary(0u),ambientPerLine(0u) {}
	};

	struct FireProductionMetalDualMomentumStaticState
	{
		std::array<std::array<FireProductionMetalDualAxisStaticState,3>,3> axis;
		FireProductionProjectionShape shape;
		FireProductionRoundoffTrace::TraceFloat timeStepS;
		std::array<FireProductionProjectionBoundary,6> boundary;
		std::uint32_t uploadCommandCommitCount;
		std::uint64_t actualMetalAllocationBytes;

		FireProductionMetalDualMomentumStaticState() : timeStepS(0.0f),
			uploadCommandCommitCount(0u),actualMetalAllocationBytes(0u)
			{ boundary.fill(FireProductionProjectionWall); }
	};

	struct FireProductionMetalDualMomentumResidentInput
	{
		id<MTLBuffer> packedFaceDensity;
		id<MTLBuffer> packedMomentum;
		std::array<id<MTLBuffer>,5> acceptedGasMassDoseKGPerM2;
		std::array<std::size_t,3> faceByteOffset;

		FireProductionMetalDualMomentumResidentInput() : packedFaceDensity(nil),
			packedMomentum(nil)
		{
			acceptedGasMassDoseKGPerM2.fill(nil);faceByteOffset.fill(0u);
		}
	};

	struct FireProductionMetalDualMomentumResidentResult
	{
		id<MTLBuffer> packedAuxiliaryFaceDensity;
		id<MTLBuffer> packedMomentum;
		std::array<std::size_t,3> faceByteOffset;
		std::uint32_t executedSubmapCount;
		std::uint32_t commandCommitCount;
		std::uint32_t interstageFullGridTransferCount;
		std::uint64_t actualMetalAllocationBytes;
		double deviceElapsedMS;
		double deviceStartTimeS;
		double deviceEndTimeS;

		FireProductionMetalDualMomentumResidentResult() :
			packedAuxiliaryFaceDensity(nil),packedMomentum(nil),executedSubmapCount(0u),
			commandCommitCount(0u),interstageFullGridTransferCount(0u),
			actualMetalAllocationBytes(0u),deviceElapsedMS(0.0),deviceStartTimeS(0.0),
			deviceEndTimeS(0.0) { faceByteOffset.fill(0u); }
	};

	//! Step-boundary upload of the nine frozen carrier/ambient layouts.
	bool PrepareFireProductionDualMomentumMetalStaticState(
		const FireProductionDualMomentumRequest& request,
		FireProductionMetalDualMomentumStaticState& state,
		std::string* error=0 );

	//! Mixed-boundary dual-grid resident seam.  All full-grid and line operands
	//! are Private and no host access or upload occurs in this call.
	bool RemapFireProductionDualMomentumMetalResident(
		const FireProductionDualMomentumRequest& request,
		const FireProductionMetalDualMomentumStaticState& staticState,
		const FireProductionMetalDualMomentumResidentInput& input,
		FireProductionMetalDualMomentumResidentResult& result,
		std::string* error=0 );

	//! Private-buffer Section 3.7 owner.  Five accepted primal mass-dose
	//! buffers are borrowed from the scalar palindrome; five compatible dual
	//! updates execute without host access or an independent momentum limiter.
	bool RemapFireProductionCompatibleDualMomentumMetalResident(
		const FireProductionDualMomentumRequest& request,
		const FireProductionMetalDualMomentumResidentInput& input,
		FireProductionMetalDualMomentumResidentResult& result,
		std::string* error=0 );
#endif
}

#endif
