// GENERATED by tools/generate_fire_production_roundoff_trace.py.
// Do not edit; regenerate from the strict production CPU arithmetic.
#include "../FireProductionRoundoffTrace.h"
//////////////////////////////////////////////////////////////////////
//
//  FireProductionAdvection.cpp - strict-binary32 CPU oracle for production PPM
//
//  License Information: Please see the attached LICENSE.TXT file
//
//////////////////////////////////////////////////////////////////////

#include "FireProductionAdvection.h"
#include "../../src/Library/Utilities/RISECBOR64.h"

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <limits>
#include <array>
#include <future>

namespace RISEFireProductionTrace
{
	bool FireProductionPayloadDigestCPU(const unsigned char* bytes,std::size_t count,
		unsigned int parallelism,FireProductionPayloadDigestV2& result,std::string* error)
	{
		result=FireProductionPayloadDigestV2();
		if((count!=0u&&!bytes)||parallelism==0u||parallelism>256u){
			if(error)*error="digest-v2 invalid bytes or execution width";return false;}
		try {
			using Node=std::array<unsigned char,32>;
			auto append=[](RISE::RISECBOR64::Bytes& out,std::uint64_t value,unsigned int width){
				for(unsigned int i=width;i!=0u;--i)out.push_back(static_cast<unsigned char>(value>>((i-1u)*8u)));};
			auto hash=[](const RISE::RISECBOR64::Bytes& input){Node node;
				const std::string hex=RISE::RISECBOR64::SHA256Hex(input);
				auto digit=[](char c){return c<='9'?c-'0':c-'a'+10;};
				for(std::size_t i=0u;i<node.size();++i)
					node[i]=static_cast<unsigned char>((digit(hex[2u*i])<<4u)|digit(hex[2u*i+1u]));
				return node;};
			auto each=[&](std::size_t size,const auto& operation){
				const unsigned int workers=static_cast<unsigned int>(std::min<std::size_t>(parallelism,size));
				std::vector<std::future<void>> tasks;
				for(unsigned int worker=0u;worker<workers;++worker)
					tasks.push_back(std::async(std::launch::async,[&,worker]{
						for(std::size_t index=worker;index<size;index+=workers)operation(index);}));
				for(auto& task:tasks)task.get();
			};
			const std::size_t leaves=std::max<std::size_t>(1u,count/4096u+(count%4096u!=0u));
			std::vector<Node> nodes(leaves);
			each(leaves,[&](std::size_t index){const std::size_t begin=index*4096u,
				length=std::min<std::size_t>(4096u,count-begin);RISE::RISECBOR64::Bytes preimage;
				preimage.reserve(32u+length);append(preimage,UINT64_C(0x524953454c454146),8u);
				append(preimage,2u,4u);append(preimage,count,8u);append(preimage,index,8u);
				append(preimage,length,4u);if(length)preimage.insert(preimage.end(),bytes+begin,bytes+begin+length);
				nodes[index]=hash(preimage);});
			std::uint32_t level=0u;
			while(nodes.size()>1u){++level;const std::size_t parents=nodes.size()/16u+(nodes.size()%16u!=0u);
				std::vector<Node> next(parents);
				each(parents,[&](std::size_t index){const std::size_t first=index*16u,
					children=std::min<std::size_t>(16u,nodes.size()-first);RISE::RISECBOR64::Bytes preimage;
					append(preimage,UINT64_C(0x524953454e4f4445),8u);append(preimage,2u,4u);
					append(preimage,count,8u);append(preimage,level,4u);append(preimage,index,8u);
					append(preimage,children,4u);
					for(std::size_t child=0u;child<children;++child)preimage.insert(preimage.end(),
						nodes[first+child].begin(),nodes[first+child].end());
					next[index]=hash(preimage);});nodes.swap(next);}
			RISE::RISECBOR64::Bytes root;append(root,UINT64_C(0x52495345524f4f54),8u);
			append(root,2u,4u);append(root,4096u,4u);append(root,16u,4u);
			append(root,count,8u);append(root,leaves,8u);append(root,level,4u);
			root.insert(root.end(),nodes[0].begin(),nodes[0].end());
			result.payloadBytes=count;result.rootSHA256=RISE::RISECBOR64::SHA256Hex(root);
			if(error)error->clear();return true;
		}catch(const std::exception& exception){result=FireProductionPayloadDigestV2();
			if(error)*error=std::string("digest-v2 failure: ")+exception.what();return false;}
	}

#if !defined(__APPLE__)
	bool FireProductionPayloadDigestMetal(const std::vector<unsigned char>&,
		unsigned int,FireProductionPayloadDigestV2& result,double& deviceMS,std::string* error)
	{
		result=FireProductionPayloadDigestV2();deviceMS=0.0;
		if(error)*error="digest-v2 Metal device unavailable on this platform";return false;
	}
#endif
	namespace
	{
		const std::uint64_t MetalAllocationQuantumBytes=UINT64_C(16384);

		FireProductionRemapBoundary LowerBoundary(
			const FireProductionRemapRequest& request )
		{
			return request.asymmetricBoundaries ? request.lowerBoundary : request.boundary;
		}

		FireProductionRemapBoundary UpperBoundary(
			const FireProductionRemapRequest& request )
		{
			return request.asymmetricBoundaries ? request.upperBoundary : request.boundary;
		}

		bool IsPeriodic( const FireProductionRemapRequest& request )
		{
			return LowerBoundary(request)==FireProductionRemapPeriodic&&
				UpperBoundary(request)==FireProductionRemapPeriodic;
		}

		bool Fail( std::string* error, const std::string& message )
		{
			if( error ) *error=message;
			return false;
		}

		bool AddMetalBufferBytes( std::uint64_t requestedBytes,
			std::uint64_t& total )
		{
			if( requestedBytes==0u ) return false;
			const std::uint64_t remainder=requestedBytes%MetalAllocationQuantumBytes;
			if( remainder ) {
				const std::uint64_t increment=MetalAllocationQuantumBytes-remainder;
				if( requestedBytes>std::numeric_limits<std::uint64_t>::max()-increment )
					return false;
				requestedBytes+=increment;
			}
			if( total>std::numeric_limits<std::uint64_t>::max()-requestedBytes ) return false;
			total+=requestedBytes;return true;
		}

		std::size_t ValueIndex( const FireProductionRemapRequest& request,
			std::size_t component, std::size_t line, std::size_t cell )
		{
			return (component*request.lineCount+line)*request.lineLength+cell;
		}

		std::size_t FluxIndex( const FireProductionRemapRequest& request,
			std::size_t component, std::size_t line, std::size_t face )
		{
			return (component*request.lineCount+line)*(request.lineLength+1u)+face;
		}

		FireProductionRoundoffTrace::TraceFloat AmbientValue( const FireProductionRemapRequest& request, bool lower,
			std::size_t component, std::size_t line )
		{
			if( !request.lineSpecificAmbientValues ) return request.ambientValues[component];
			const std::vector<FireProductionRoundoffTrace::TraceFloat>& values=lower?request.lowerAmbientValues:
				request.upperAmbientValues;
			return values[component*request.lineCount+line];
		}

		FireProductionRoundoffTrace::TraceFloat ContinuousInflowValue( const FireProductionRoundoffTrace::TraceFloat nearest, const FireProductionRoundoffTrace::TraceFloat ambient,
			const FireProductionRoundoffTrace::TraceFloat velocity, const bool positiveInflow, const FireProductionRoundoffTrace::TraceFloat cellWidthM,
			const FireProductionRoundoffTrace::TraceFloat timeStepS )
		{
			if( !(timeStepS>0.0f) ) return nearest;
			const FireProductionRoundoffTrace::TraceFloat scale=std::max(FireProductionRoundoffTrace::TraceFloat(0x1p-126f),std::max(std::fabs(velocity),
				std::fabs(cellWidthM/timeStepS)));
			const FireProductionRoundoffTrace::TraceFloat width=0x1p-24f*scale;
			const FireProductionRoundoffTrace::TraceFloat signedVelocity=positiveInflow?velocity:-velocity;
			if( FireProductionRoundoffTrace::EvaluateContinuousInflowJoin(signedVelocity,width,nearest,ambient,true) ) return nearest;
			if( FireProductionRoundoffTrace::EvaluateContinuousInflowJoin(signedVelocity,width,nearest,ambient,false) ) return ambient;
			const FireProductionRoundoffTrace::TraceFloat weight=(signedVelocity+width)/(2.0f*width);
			return nearest+weight*(ambient-nearest);
		}

		FireProductionRoundoffTrace::TraceFloat Sample( const FireProductionRemapRequest& request,
			std::size_t component, std::size_t line, long cell )
		{
			const long count=static_cast<long>(request.lineLength);
			if( IsPeriodic(request) ) {
				long wrapped=cell%count;
				if( wrapped<0 ) wrapped+=count;
				return request.values[ValueIndex(request,component,line,
					static_cast<std::size_t>(wrapped))];
			}
			if( cell<0 ) {
				const FireProductionRoundoffTrace::TraceFloat nearest=request.values[ValueIndex(request,component,line,0u)];
				if( LowerBoundary(request)!=FireProductionRemapPressureOpen ) return nearest;
				return ContinuousInflowValue(nearest,AmbientValue(request,true,component,line),
					request.faceVelocityMPerS[line*(request.lineLength+1u)],true,
					request.cellWidthM,request.timeStepS);
			}
			if( cell>=count ) {
				const FireProductionRoundoffTrace::TraceFloat nearest=request.values[ValueIndex(request,component,line,
					request.lineLength-1u)];
				if( UpperBoundary(request)!=FireProductionRemapPressureOpen ) return nearest;
				return ContinuousInflowValue(nearest,AmbientValue(request,false,component,line),
					request.faceVelocityMPerS[line*(request.lineLength+1u)+request.lineLength],false,
					request.cellWidthM,request.timeStepS);
			}
			return request.values[ValueIndex(request,component,line,static_cast<std::size_t>(cell))];
		}

		void UnlimitedEdges( const FireProductionRemapRequest& request,
			std::size_t component, std::size_t line, std::size_t cell,
			FireProductionRoundoffTrace::TraceFloat& left, FireProductionRoundoffTrace::TraceFloat& right )
		{
			const long i=static_cast<long>(cell);
			const FireProductionRoundoffTrace::TraceFloat im2=Sample(request,component,line,i-2);
			const FireProductionRoundoffTrace::TraceFloat im1=Sample(request,component,line,i-1);
			const FireProductionRoundoffTrace::TraceFloat center=Sample(request,component,line,i);
			const FireProductionRoundoffTrace::TraceFloat ip1=Sample(request,component,line,i+1);
			const FireProductionRoundoffTrace::TraceFloat ip2=Sample(request,component,line,i+2);
			if( FireProductionRoundoffTrace::EvaluateBranch(FireProductionRoundoffTrace::BranchSite::FlatStencil,[&](){ return im2==center&&im1==center&&ip1==center&&ip2==center; }) ) {
				left=center;right=center;return;
			}
			left=(7.0f*(im1+center)-(im2+ip1))/12.0f;
			right=(7.0f*(center+ip1)-(im1+ip2))/12.0f;
		}

		void ParabolaDeviationRange( FireProductionRoundoffTrace::TraceFloat leftDeviation, FireProductionRoundoffTrace::TraceFloat rightDeviation,
			FireProductionRoundoffTrace::TraceFloat& minimum, FireProductionRoundoffTrace::TraceFloat& maximum )
		{
			minimum=std::min(leftDeviation,rightDeviation);
			maximum=std::max(leftDeviation,rightDeviation);
			const FireProductionRoundoffTrace::TraceFloat quadratic=3.0f*(leftDeviation+rightDeviation);
			const FireProductionRoundoffTrace::TraceFloat linear=-4.0f*leftDeviation-2.0f*rightDeviation;
			bool quadraticNonzero=false;
			const FireProductionRoundoffTrace::TraceFloat endpointMinimum=minimum,endpointMaximum=maximum;
			FireProductionRoundoffTrace::BeginPPMBranchEnvelope();
			{ FireProductionRoundoffTrace::BranchSiteScope branchScope(
				FireProductionRoundoffTrace::BranchSite::PPMQuadraticZero);
				quadraticNonzero=quadratic!=0.0f; }
			FireProductionRoundoffTrace::SetPPMQuadraticAmbiguous(
				FireProductionRoundoffTrace::PPMQuadraticZeroObligationPending());
			if( quadraticNonzero ) {
				FireProductionRoundoffTrace::CoveredBranchScope coveredBranch(true,true);
				const FireProductionRoundoffTrace::TraceFloat stationary=-linear/(2.0f*quadratic);
				const bool stationaryPositive=FireProductionRoundoffTrace::EvaluateBranch(
					FireProductionRoundoffTrace::BranchSite::PPMStationaryLower,[&](){ return stationary>0.0f; });
				const bool stationaryBelowOne=stationaryPositive&&FireProductionRoundoffTrace::EvaluateBranch(
					FireProductionRoundoffTrace::BranchSite::PPMStationaryUpper,[&](){ return stationary<1.0f; });
				if( stationaryBelowOne ) {
					const FireProductionRoundoffTrace::TraceFloat value=(quadratic*stationary+linear)*stationary+leftDeviation;
					minimum=std::min(minimum,value);
					maximum=std::max(maximum,value);
				}
			}
			FireProductionRoundoffTrace::ApplyPPMQuadraticZeroCertificate(
				quadratic,linear,endpointMinimum,endpointMaximum,minimum,maximum);
		}

		FireProductionRoundoffTrace::TraceFloat ContinuousSharedLimiterAlpha( const FireProductionRoundoffTrace::TraceFloat alpha, const FireProductionRoundoffTrace::TraceFloat headroom,
			const FireProductionRoundoffTrace::TraceFloat signedConsumption, const FireProductionRoundoffTrace::TraceFloat center, const FireProductionRoundoffTrace::TraceFloat envelope )
		{
			const FireProductionRoundoffTrace::TraceFloat scale=std::max(FireProductionRoundoffTrace::TraceFloat(0x1p-126f),std::max(std::fabs(center),
				std::max(std::fabs(envelope),std::fabs(signedConsumption))));
			const FireProductionRoundoffTrace::TraceFloat width=0x1p-10f*scale;
			const FireProductionRoundoffTrace::TraceFloat numerator=headroom+std::max(FireProductionRoundoffTrace::TraceFloat(0.0f),-signedConsumption);
			const FireProductionRoundoffTrace::TraceFloat denominator=std::max(signedConsumption,width);
			const FireProductionRoundoffTrace::TraceFloat cap=std::min(FireProductionRoundoffTrace::TraceFloat(1.0f),numerator/denominator);
			return std::min(alpha,cap);
		}

		FireProductionRoundoffTrace::TraceFloat CellIntervalIntegral( FireProductionRoundoffTrace::TraceFloat center, FireProductionRoundoffTrace::TraceFloat left, FireProductionRoundoffTrace::TraceFloat right,
			FireProductionRoundoffTrace::TraceFloat beginning, FireProductionRoundoffTrace::TraceFloat end )
		{
			if( FireProductionRoundoffTrace::EvaluateFlatIntegralBranch(left,center,right) ) return (end-beginning)*center;
			const FireProductionRoundoffTrace::TraceFloat q6=6.0f*center-3.0f*(left+right);
			const FireProductionRoundoffTrace::TraceFloat delta=end-beginning;
			return delta*(left+0.5f*(right-left+q6)*(beginning+end)-
				(q6/3.0f)*(beginning*beginning+beginning*end+end*end));
		}

		FireProductionRoundoffTrace::TraceFloat CellTrailingIntegral( FireProductionRoundoffTrace::TraceFloat center, FireProductionRoundoffTrace::TraceFloat left, FireProductionRoundoffTrace::TraceFloat right, FireProductionRoundoffTrace::TraceFloat length )
		{
			if( FireProductionRoundoffTrace::EvaluateFlatIntegralBranch(left,center,right) ) return length*center;
			const FireProductionRoundoffTrace::TraceFloat q6=6.0f*center-3.0f*(left+right);
			return length*(right-0.5f*(right-left-q6)*length-
				(q6/3.0f)*length*length);
		}

		std::size_t WrappedCell( long cell, std::size_t count )
		{
			const long signedCount=static_cast<long>(count);
			long wrapped=cell%signedCount;
			if( wrapped<0 ) wrapped+=signedCount;
			return static_cast<std::size_t>(wrapped);
		}

		FireProductionRoundoffTrace::TraceFloat PeriodicLocalForwardIntegral( const FireProductionRemapRequest& request,
			std::size_t component, std::size_t line, long beginningCell,
			FireProductionRoundoffTrace::TraceFloat beginningFraction, FireProductionRoundoffTrace::TraceFloat length, const std::vector<FireProductionRoundoffTrace::TraceFloat>& left,
			const std::vector<FireProductionRoundoffTrace::TraceFloat>& right )
		{
			FireProductionRoundoffTrace::TraceFloat remaining=length,result=0.0f;
			long cell=beginningCell;
			FireProductionRoundoffTrace::TraceFloat fraction=beginningFraction;
			while( FireProductionRoundoffTrace::EvaluateRemainingPositiveBranch([&](){ return remaining>0.0f; }) ) {
				const FireProductionRoundoffTrace::TraceFloat span=std::min(remaining,1.0f-fraction);
				const std::size_t wrapped=WrappedCell(cell,request.lineLength);
				const std::size_t value=ValueIndex(request,component,line,wrapped);
				result+=CellIntervalIntegral(request.values[value],left[value],right[value],
					fraction,fraction+span);
				remaining-=span;
				fraction=0.0f;
				++cell;
			}
			return result;
		}

		FireProductionRoundoffTrace::TraceFloat PeriodicSweptIntegral( const FireProductionRemapRequest& request,
			std::size_t component, std::size_t line, std::size_t face, FireProductionRoundoffTrace::TraceFloat courant,
			const std::vector<FireProductionRoundoffTrace::TraceFloat>& left, const std::vector<FireProductionRoundoffTrace::TraceFloat>& right,
			const std::vector<FireProductionRoundoffTrace::TraceFloat>& prefix )
		{
			FireProductionRoundoffTrace::LocalTransportBranchScope branchScope;
			const std::size_t profileBase=ValueIndex(request,component,line,0u);
			FireProductionRoundoffTrace::TransportProfileScope profileScope(
				request.values,left,right,profileBase,request.lineLength,0.0f,0.0f);
			const FireProductionRoundoffTrace::TraceFloat count=static_cast<FireProductionRoundoffTrace::TraceFloat>(request.lineLength);
			const FireProductionRoundoffTrace::TraceFloat magnitude=std::fabs(courant);
			const FireProductionRoundoffTrace::TraceFloat localLength=std::fmod(magnitude,count);
			const FireProductionRoundoffTrace::TraceFloat cycles=std::floor((magnitude-localLength)/count);
			const std::size_t base=(component*request.lineCount+line)*(request.lineLength+1u);
			FireProductionRoundoffTrace::TraceFloat result=cycles*prefix[base+request.lineLength];
			if( FireProductionRoundoffTrace::EvaluateCourantSignBranch([&](){ return courant>=0.0f; }) ) {
				const FireProductionRoundoffTrace::TraceFloat whole=std::floor(localLength);
				const FireProductionRoundoffTrace::TraceFloat fractional=localLength-whole;
				const long wholeBeginning=static_cast<long>(face)-static_cast<long>(whole);
				if( FireProductionRoundoffTrace::EvaluateFractionPositiveBranch([&](){ return fractional>0.0f; }) ) {
					const std::size_t wrapped=WrappedCell(wholeBeginning-1l,request.lineLength);
					const std::size_t value=ValueIndex(request,component,line,wrapped);
					result+=CellTrailingIntegral(request.values[value],left[value],right[value],
						fractional);
				}
				result+=PeriodicLocalForwardIntegral(request,component,line,wholeBeginning,
					0.0f,whole,left,right);
				return FireProductionRoundoffTrace::FinalizeTransportBranchEnvelope(result);
			}
			result+=PeriodicLocalForwardIntegral(request,component,line,
				static_cast<long>(face),0.0f,localLength,left,right);
			return FireProductionRoundoffTrace::FinalizeTransportBranchEnvelope(-result);
		}

		FireProductionRoundoffTrace::TraceFloat OpenLocalForwardIntegral( const FireProductionRemapRequest& request,
			std::size_t component, std::size_t line, std::size_t beginningCell,
			FireProductionRoundoffTrace::TraceFloat beginningFraction, FireProductionRoundoffTrace::TraceFloat length, const std::vector<FireProductionRoundoffTrace::TraceFloat>& left,
			const std::vector<FireProductionRoundoffTrace::TraceFloat>& right )
		{
			FireProductionRoundoffTrace::TraceFloat remaining=length,result=0.0f;
			std::size_t cell=beginningCell;
			FireProductionRoundoffTrace::TraceFloat fraction=beginningFraction;
			while( FireProductionRoundoffTrace::EvaluateRemainingPositiveBranch([&](){ return remaining>0.0f; })&&cell<request.lineLength ) {
				const FireProductionRoundoffTrace::TraceFloat span=std::min(remaining,1.0f-fraction);
				const std::size_t value=ValueIndex(request,component,line,cell);
				result+=CellIntervalIntegral(request.values[value],left[value],right[value],
					fraction,fraction+span);
				remaining-=span;
				fraction=0.0f;
				++cell;
			}
			return result;
		}

		FireProductionRoundoffTrace::TraceFloat OpenSweptIntegral( const FireProductionRemapRequest& request,
			std::size_t component, std::size_t line, std::size_t face, FireProductionRoundoffTrace::TraceFloat courant,
			FireProductionRoundoffTrace::TraceFloat faceVelocity, const std::vector<FireProductionRoundoffTrace::TraceFloat>& left,
			const std::vector<FireProductionRoundoffTrace::TraceFloat>& right )
		{
			FireProductionRoundoffTrace::LocalTransportBranchScope branchScope;
			const FireProductionRoundoffTrace::TraceFloat magnitude=std::fabs(courant);
			const FireProductionRoundoffTrace::TraceFloat leftNearest=request.values[ValueIndex(request,component,line,0u)];
			const FireProductionRoundoffTrace::TraceFloat rightNearest=request.values[ValueIndex(request,component,line,
				request.lineLength-1u)];
			const FireProductionRoundoffTrace::TraceFloat leftExtension=LowerBoundary(request)==FireProductionRemapPressureOpen?
				ContinuousInflowValue(leftNearest,AmbientValue(request,true,component,line),
					faceVelocity,true,request.cellWidthM,request.timeStepS):leftNearest;
			const FireProductionRoundoffTrace::TraceFloat rightExtension=UpperBoundary(request)==FireProductionRemapPressureOpen?
				ContinuousInflowValue(rightNearest,AmbientValue(request,false,component,line),
					faceVelocity,false,request.cellWidthM,request.timeStepS):rightNearest;
			const std::size_t profileBase=ValueIndex(request,component,line,0u);
			FireProductionRoundoffTrace::TransportProfileScope profileScope(
				request.values,left,right,profileBase,request.lineLength,
				leftExtension,rightExtension);
			if( FireProductionRoundoffTrace::EvaluateCourantSignBranch([&](){ return courant>=0.0f; }) ) {
				const FireProductionRoundoffTrace::TraceFloat interiorLength=std::min(magnitude,static_cast<FireProductionRoundoffTrace::TraceFloat>(face));
				const FireProductionRoundoffTrace::TraceFloat whole=std::floor(interiorLength);
				const FireProductionRoundoffTrace::TraceFloat fractional=interiorLength-whole;
				const std::size_t wholeBeginning=face-static_cast<std::size_t>(whole);
				FireProductionRoundoffTrace::TraceFloat result=(magnitude-interiorLength)*leftExtension;
				if( FireProductionRoundoffTrace::EvaluateFractionPositiveBranch([&](){ return fractional>0.0f; }) ) {
					const std::size_t value=ValueIndex(request,component,line,wholeBeginning-1u);
					result+=CellTrailingIntegral(request.values[value],left[value],right[value],
						fractional);
				}
				return FireProductionRoundoffTrace::FinalizeTransportBranchEnvelope(result+OpenLocalForwardIntegral(request,component,line,wholeBeginning,
					0.0f,whole,left,right));
			}
			const FireProductionRoundoffTrace::TraceFloat interiorLength=std::min(magnitude,
				static_cast<FireProductionRoundoffTrace::TraceFloat>(request.lineLength-face));
			return FireProductionRoundoffTrace::FinalizeTransportBranchEnvelope(-(OpenLocalForwardIntegral(request,component,line,face,0.0f,
				interiorLength,left,right)+(magnitude-interiorLength)*rightExtension));
		}

		std::size_t NextPowerOfTwo( std::size_t value )
		{
			std::size_t result=1u;
			while( result<value ) result<<=1u;
			return result;
		}

		void BlellochPrefixLine( const FireProductionRemapRequest& request,
			std::size_t component, std::size_t line, std::vector<FireProductionRoundoffTrace::TraceFloat>& prefix )
		{
			const std::size_t width=NextPowerOfTwo(request.lineLength);
			std::vector<FireProductionRoundoffTrace::TraceFloat> scratch(width,0.0f);
			for( std::size_t cell=0;cell<request.lineLength;++cell )
				scratch[cell]=request.values[ValueIndex(request,component,line,cell)];
			for( std::size_t offset=1u;offset<width;offset<<=1u )
				for( std::size_t index=offset*2u-1u;index<width;index+=offset*2u )
					scratch[index]+=scratch[index-offset];
			const FireProductionRoundoffTrace::TraceFloat total=scratch[width-1u];
			scratch[width-1u]=0.0f;
			for( std::size_t offset=width>>1u;offset>0u;offset>>=1u )
				for( std::size_t index=offset*2u-1u;index<width;index+=offset*2u ) {
					const FireProductionRoundoffTrace::TraceFloat below=scratch[index-offset];
					scratch[index-offset]=scratch[index];
					scratch[index]+=below;
				}
			const std::size_t base=(component*request.lineCount+line)*
				(request.lineLength+1u);
			for( std::size_t cell=0;cell<request.lineLength;++cell )
				prefix[base+cell]=scratch[cell];
			prefix[base+request.lineLength]=total;
		}
	}

	bool FireProductionRemapWorkingSetBytes( const FireProductionRemapRequest& request,
		std::uint64_t& bytes )
	{
		bytes=0u;
		std::uint64_t total=0u;
		if( request.lineLength<4u||request.lineLength>1024u||request.lineCount==0u||
			request.componentCount==0u ) return false;
		const std::size_t maximum=std::numeric_limits<std::size_t>::max();
		if( request.lineCount>maximum/request.lineLength||
			request.componentCount>maximum/(request.lineCount*request.lineLength)||
			request.lineCount>maximum/(request.lineLength+1u)||
			request.componentCount>maximum/(request.lineCount*(request.lineLength+1u)) )
			return false;
		const std::uint64_t valueCount=request.componentCount*request.lineCount*
			request.lineLength;
		const std::uint64_t fluxCount=request.componentCount*request.lineCount*
			(request.lineLength+1u);
		const std::uint64_t velocityCount=request.lineCount*(request.lineLength+1u);
		const std::uint64_t alphaCount=request.lineCount*request.lineLength;
		if( valueCount>std::numeric_limits<std::uint32_t>::max()||
			fluxCount>std::numeric_limits<std::uint32_t>::max()||
			request.lineCount>std::numeric_limits<std::uint32_t>::max()||
			request.componentCount>std::numeric_limits<std::uint32_t>::max() ) return false;
		const std::uint64_t ambientCount=request.lineSpecificAmbientValues?
			static_cast<std::uint64_t>(request.componentCount)*request.lineCount:
			request.componentCount;
		for( unsigned int copy=0u;copy<4u;++copy )
			if( !AddMetalBufferBytes(valueCount*sizeof(float),total) ) return false;
		for( unsigned int copy=0u;copy<2u;++copy )
			if( !AddMetalBufferBytes(fluxCount*sizeof(float),total) ) return false;
		if( !AddMetalBufferBytes(velocityCount*sizeof(float),total)||
			!AddMetalBufferBytes(alphaCount*sizeof(float),total)||
			!AddMetalBufferBytes(ambientCount*sizeof(float),total)||
			!AddMetalBufferBytes(ambientCount*sizeof(float),total)||
			!AddMetalBufferBytes(6u*sizeof(std::uint32_t)+2u*sizeof(float),total) )
			return false;
		bytes=total;return true;
	}

	FireProductionRoundoffTrace::TraceFloat FireProductionContinuousSharedLimiterAlpha( const FireProductionRoundoffTrace::TraceFloat alpha,
		const FireProductionRoundoffTrace::TraceFloat headroom, const FireProductionRoundoffTrace::TraceFloat signedConsumption, const FireProductionRoundoffTrace::TraceFloat center,
		const FireProductionRoundoffTrace::TraceFloat envelope ) noexcept
	{
		return ContinuousSharedLimiterAlpha(alpha,headroom,signedConsumption,
			center,envelope);
	}

	FireProductionRoundoffTrace::TraceFloat FireProductionContinuousInflowValue( const FireProductionRoundoffTrace::TraceFloat nearest, const FireProductionRoundoffTrace::TraceFloat ambient,
		const FireProductionRoundoffTrace::TraceFloat velocity, const bool positiveInflow, const FireProductionRoundoffTrace::TraceFloat cellWidthM,
		const FireProductionRoundoffTrace::TraceFloat timeStepS ) noexcept
	{
		return ContinuousInflowValue(nearest,ambient,velocity,positiveInflow,
			cellWidthM,timeStepS);
	}

	bool ValidateFireProductionRemapRequest( const FireProductionRemapRequest& request,
		std::string* error )
	{
		if( request.lineLength<4u||request.lineLength>1024u||request.lineCount==0u||
			request.componentCount==0u )
			return Fail(error,"production remap request shape or schedule is invalid");
		const std::size_t maximum=std::numeric_limits<std::size_t>::max();
		if( request.lineCount>maximum/request.lineLength||
			request.componentCount>maximum/(request.lineCount*request.lineLength)||
			request.lineCount>maximum/(request.lineLength+1u)||
			request.componentCount>maximum/(request.lineCount*(request.lineLength+1u)) )
			return Fail(error,"production remap request dimensions overflow");
		const std::size_t valueCount=request.componentCount*request.lineCount*request.lineLength;
		const std::size_t fluxCount=request.componentCount*request.lineCount*(request.lineLength+1u);
		const std::size_t velocityCount=request.lineCount*(request.lineLength+1u);
		if( valueCount>std::numeric_limits<std::uint32_t>::max()||
			fluxCount>std::numeric_limits<std::uint32_t>::max()||
			request.lineCount>std::numeric_limits<std::uint32_t>::max()||
			request.componentCount>std::numeric_limits<std::uint32_t>::max() )
			return Fail(error,"production remap request exceeds binary32 kernel indexing");
		std::uint64_t workingBytes=0u;
		if( !FireProductionRemapWorkingSetBytes(request,workingBytes) )
			return Fail(error,"production remap working-set calculation failed");
		if( workingBytes>(std::uint64_t(2u)<<30u) )
			return Fail(error,"production remap working set exceeds two GiB");
		if( !(request.cellWidthM>0.0f)||request.timeStepS<0.0f||
			!std::isfinite(request.cellWidthM)||!std::isfinite(request.timeStepS)||
			request.values.size()!=valueCount||request.faceVelocityMPerS.size()!=velocityCount||
			(!request.lineSpecificAmbientValues&&
				request.ambientValues.size()!=request.componentCount)||
			(request.lineSpecificAmbientValues&&
				(request.lowerAmbientValues.size()!=request.componentCount*request.lineCount||
				 request.upperAmbientValues.size()!=request.componentCount*request.lineCount)) )
			return Fail(error,"production remap request shape or schedule is invalid");
		const FireProductionRemapBoundary lower=LowerBoundary(request);
		const FireProductionRemapBoundary upper=UpperBoundary(request);
		if( lower<FireProductionRemapPeriodic||lower>FireProductionRemapWall||
			upper<FireProductionRemapPeriodic||upper>FireProductionRemapWall||
			((lower==FireProductionRemapPeriodic)!=(upper==FireProductionRemapPeriodic)) )
			return Fail(error,"production remap boundary pairing is invalid");
		for( const FireProductionRoundoffTrace::TraceFloat value : request.values ) if( !std::isfinite(value) )
			return Fail(error,"production remap state is nonfinite");
		for( const FireProductionRoundoffTrace::TraceFloat value : request.faceVelocityMPerS ) if( !std::isfinite(value) )
			return Fail(error,"production remap velocity is nonfinite");
		const std::vector<FireProductionRoundoffTrace::TraceFloat>& lowerAmbient=request.lineSpecificAmbientValues?
			request.lowerAmbientValues:request.ambientValues;
		const std::vector<FireProductionRoundoffTrace::TraceFloat>& upperAmbient=request.lineSpecificAmbientValues?
			request.upperAmbientValues:request.ambientValues;
		for( const FireProductionRoundoffTrace::TraceFloat value : lowerAmbient ) if( !std::isfinite(value) )
			return Fail(error,"production remap ambient state is nonfinite");
		for( const FireProductionRoundoffTrace::TraceFloat value : upperAmbient ) if( !std::isfinite(value) )
			return Fail(error,"production remap ambient state is nonfinite");
		for( std::size_t line=0;line<request.lineCount;++line ) {
			const std::size_t base=line*(request.lineLength+1u);
			if( IsPeriodic(request)&&
				FireProductionRoundoffTrace::EvaluateBranch(FireProductionRoundoffTrace::BranchSite::PeriodicSeamEquality,[&](){return request.faceVelocityMPerS[base]!=request.faceVelocityMPerS[base+request.lineLength];}) )
				return Fail(error,"production periodic remap seam velocity is not single-valued");
			double previous=0.0;
			for( std::size_t face=0;face<=request.lineLength;++face ) {
				const FireProductionRoundoffTrace::TraceFloat courant=request.timeStepS*request.faceVelocityMPerS[base+face]/
					request.cellWidthM;
				if( !std::isfinite(courant) )
					return Fail(error,"production remap binary32 Courant number is nonfinite");
				const double departure=static_cast<double>(face)-
					static_cast<double>(courant);
				if( !std::isfinite(departure)||(face>0u&&departure<previous) )
					return Fail(error,"production remap backtraced face map is folded");
				previous=departure;
			}
		}
		return true;
	}

	bool RemapFireProductionCPU( const FireProductionRemapRequest& request,
		FireProductionRemapResult& result, std::string* error )
	{
		result=FireProductionRemapResult();
		if( !ValidateFireProductionRemapRequest(request,error) ) return false;
		std::vector<FireProductionRoundoffTrace::TraceFloat> left(request.values.size()),right(request.values.size());
		result.sharedLimiterAlpha.resize(request.lineCount*request.lineLength,1.0f);
		for( std::size_t line=0;line<request.lineCount;++line ) for( std::size_t cell=0;
			cell<request.lineLength;++cell ) {
			FireProductionRoundoffTrace::TraceFloat alpha=1.0f;
			for( std::size_t component=0;component<request.componentCount;++component ) {
				const std::size_t index=ValueIndex(request,component,line,cell);
				UnlimitedEdges(request,component,line,cell,left[index],right[index]);
				const FireProductionRoundoffTrace::TraceFloat center=request.values[index];
				FireProductionRoundoffTrace::TraceFloat minimumDeviation=0.0f,maximumDeviation=0.0f;
				ParabolaDeviationRange(left[index]-center,right[index]-center,
					minimumDeviation,maximumDeviation);
				const FireProductionRoundoffTrace::TraceFloat envelopeMinimum=std::min(center,std::min(
					Sample(request,component,line,static_cast<long>(cell)-1),
					Sample(request,component,line,static_cast<long>(cell)+1)));
				const FireProductionRoundoffTrace::TraceFloat envelopeMaximum=std::max(center,std::max(
					Sample(request,component,line,static_cast<long>(cell)-1),
					Sample(request,component,line,static_cast<long>(cell)+1)));
				alpha=ContinuousSharedLimiterAlpha(alpha,envelopeMaximum-center,
					maximumDeviation,center,envelopeMaximum);
				alpha=ContinuousSharedLimiterAlpha(alpha,center-envelopeMinimum,
					-minimumDeviation,center,envelopeMinimum);
			}
			alpha=std::max(FireProductionRoundoffTrace::TraceFloat(0.0f),std::min(FireProductionRoundoffTrace::TraceFloat(1.0f),alpha));
			result.sharedLimiterAlpha[line*request.lineLength+cell]=alpha;
			for( std::size_t component=0;component<request.componentCount;++component ) {
				const std::size_t index=ValueIndex(request,component,line,cell);
				const FireProductionRoundoffTrace::TraceFloat center=request.values[index];
				left[index]=center+alpha*(left[index]-center);
				right[index]=center+alpha*(right[index]-center);
			}
		}

		std::vector<FireProductionRoundoffTrace::TraceFloat> prefix(request.componentCount*request.lineCount*
			(request.lineLength+1u),0.0f);
		for( std::size_t component=0;component<request.componentCount;++component )
			for( std::size_t line=0;line<request.lineCount;++line )
				BlellochPrefixLine(request,component,line,prefix);

		result.faceFluxes.resize(request.componentCount*request.lineCount*
			(request.lineLength+1u),0.0f);
		for( std::size_t component=0;component<request.componentCount;++component )
			for( std::size_t line=0;line<request.lineCount;++line )
				for( std::size_t face=0;face<request.lineLength;++face ) {
					const std::size_t flux=FluxIndex(request,component,line,face);
					if( face==0u&&LowerBoundary(request)==FireProductionRemapWall ) {
						result.faceFluxes[flux]=0.0f;
						continue;
					}
					const FireProductionRoundoffTrace::TraceFloat velocity=request.faceVelocityMPerS[line*(request.lineLength+1u)+face];
					const FireProductionRoundoffTrace::TraceFloat courant=request.timeStepS*velocity/request.cellWidthM;
					const FireProductionRoundoffTrace::TraceFloat swept=IsPeriodic(request) ?
						PeriodicSweptIntegral(request,component,line,face,courant,left,right,prefix):
						OpenSweptIntegral(request,component,line,face,courant,velocity,left,right);
					result.faceFluxes[flux]=request.cellWidthM*swept;
				}
		for( std::size_t component=0;component<request.componentCount;++component )
			for( std::size_t line=0;line<request.lineCount;++line ) {
				const std::size_t end=FluxIndex(request,component,line,request.lineLength);
				if( IsPeriodic(request) )
					result.faceFluxes[end]=result.faceFluxes[
						FluxIndex(request,component,line,0u)];
				else if( UpperBoundary(request)==FireProductionRemapWall )
					result.faceFluxes[end]=0.0f;
				else {
					const FireProductionRoundoffTrace::TraceFloat velocity=request.faceVelocityMPerS[
						line*(request.lineLength+1u)+request.lineLength];
					const FireProductionRoundoffTrace::TraceFloat courant=request.timeStepS*velocity/request.cellWidthM;
					result.faceFluxes[end]=request.cellWidthM*OpenSweptIntegral(request,
						component,line,request.lineLength,courant,velocity,left,right);
				}
			}

		result.updatedValues.resize(request.values.size());
		for( std::size_t component=0;component<request.componentCount;++component )
			for( std::size_t line=0;line<request.lineCount;++line )
				for( std::size_t cell=0;cell<request.lineLength;++cell ) {
					const std::size_t value=ValueIndex(request,component,line,cell);
					result.updatedValues[value]=request.values[value]-
						(result.faceFluxes[FluxIndex(request,component,line,cell+1u)]-
						 result.faceFluxes[FluxIndex(request,component,line,cell)])/request.cellWidthM;
				}
		for( const FireProductionRoundoffTrace::TraceFloat value : result.updatedValues ) if( !std::isfinite(value) ) {
			result=FireProductionRemapResult();
			return Fail(error,"production remap produced nonfinite updated state");
		}
		for( const FireProductionRoundoffTrace::TraceFloat value : result.faceFluxes ) if( !std::isfinite(value) ) {
			result=FireProductionRemapResult();
			return Fail(error,"production remap produced nonfinite face flux");
		}
		for( const FireProductionRoundoffTrace::TraceFloat value : result.sharedLimiterAlpha ) if( !std::isfinite(value) ) {
			result=FireProductionRemapResult();
			return Fail(error,"production remap produced nonfinite limiter state");
		}
		if( error ) error->clear();
		return true;
	}
}
