// GENERATED by tools/generate_fire_production_roundoff_trace.py.
// Do not edit; regenerate from the strict production CPU arithmetic.
#include "../FireProductionRoundoffTrace.h"
//////////////////////////////////////////////////////////////////////
//
//  FireProductionProjection.h - one-pass fp32 production MAC projection
//
//  License Information: Please see the attached LICENSE.TXT file
//
//////////////////////////////////////////////////////////////////////

#ifndef TRACE_FIREPRODUCTIONPROJECTION_
#define TRACE_FIREPRODUCTIONPROJECTION_

#include <array>
#include <cstddef>
#include <cstdint>
#include <string>
#include <vector>

#if defined(__OBJC__) && defined(__APPLE__)
#import <Metal/Metal.h>
#endif

namespace RISEFireProductionTrace
{
	enum FireProductionProjectionBoundary
	{
		FireProductionProjectionPeriodic,
		FireProductionProjectionPressureOpen,
		FireProductionProjectionWall
	};

	struct FireProductionProjectionShape
	{
		std::size_t nx,ny,nz;
		FireProductionRoundoffTrace::TraceFloat cellWidthM;

		FireProductionProjectionShape() : nx(0),ny(0),nz(0),cellWidthM(0.0f) {}
		std::size_t CellCount() const {return nx*ny*nz;}
	};

	struct FireProductionProjectionRequest
	{
		FireProductionProjectionShape shape;
		FireProductionRoundoffTrace::TraceFloat timeStepS;
		FireProductionRoundoffTrace::TraceFloat ambientDensityKGPerM3;
		std::array<FireProductionProjectionBoundary,6> boundary;
		std::vector<FireProductionRoundoffTrace::TraceFloat> gasDensityKGPerM3;
		std::array<std::vector<FireProductionRoundoffTrace::TraceFloat>,3> provisionalMomentumKGPerM2S;
		std::vector<FireProductionRoundoffTrace::TraceFloat> divergenceTargetPerS;
		std::uint32_t residentPhysicalOpenVCycleCount;

		FireProductionProjectionRequest() : timeStepS(0.0f),ambientDensityKGPerM3(0.0f),
			residentPhysicalOpenVCycleCount(17u)
		{
			boundary.fill(FireProductionProjectionWall);
		}
	};

	struct FireProductionProjectionResult
	{
		std::array<std::vector<FireProductionRoundoffTrace::TraceFloat>,3> faceDensityKGPerM3;
		std::array<std::vector<FireProductionRoundoffTrace::TraceFloat>,3> velocityMPerS;
		std::array<std::vector<FireProductionRoundoffTrace::TraceFloat>,3> momentumKGPerM2S;
		std::vector<FireProductionRoundoffTrace::TraceFloat> pressurePa;
		std::array<std::vector<unsigned char>,6> pressureOpenInflow;
		FireProductionRoundoffTrace::TraceFloat maximumPreProjectionResidualPerS;
		FireProductionRoundoffTrace::TraceFloat maximumPostProjectionResidualPerS;
		FireProductionRoundoffTrace::TraceFloat validationBandPerS;
		FireProductionRoundoffTrace::TraceFloat maximumOpenComplementarityDiscrepancyMPerS;
		FireProductionRoundoffTrace::TraceFloat removedFineRightHandSideMean;
		std::uint32_t executedVCycleCount;
		std::uint64_t executedJacobiSweepCount;
		std::uint32_t residentUploadStagingCount;
		std::uint32_t residentInterstageDeviceToHostTransferCount;
		std::uint32_t residentTerminalStagingCount;
		std::uint32_t residentCommandCommitCount;
		std::uint32_t residentProjectionInvocationCount;
		std::uint64_t residentCertifiedWorkingSetBytes;
		std::uint64_t residentActualMetalAllocationBytes;
		bool validationPassed;
		double deviceElapsedMS;
		double deviceStartTimeS;
		double deviceEndTimeS;

		FireProductionProjectionResult() : maximumPreProjectionResidualPerS(0.0f),
			maximumPostProjectionResidualPerS(0.0f),validationBandPerS(0.0f),
			maximumOpenComplementarityDiscrepancyMPerS(0.0f),
			removedFineRightHandSideMean(0.0f),executedVCycleCount(0u),
			executedJacobiSweepCount(0u),residentUploadStagingCount(0u),
			residentInterstageDeviceToHostTransferCount(0u),residentTerminalStagingCount(0u),
			residentCommandCommitCount(0u),residentProjectionInvocationCount(0u),
			residentCertifiedWorkingSetBytes(0u),residentActualMetalAllocationBytes(0u),validationPassed(false),
			deviceElapsedMS(0.0),deviceStartTimeS(0.0),deviceEndTimeS(0.0) {}
	};

	std::size_t FireProductionProjectionFaceCount(
		const FireProductionProjectionShape& shape, unsigned int axis );

	bool FireProductionProjectionWorkingSetBytes(
		const FireProductionProjectionShape& shape,
		std::uint64_t& bytes );

	bool FireProductionProjectionResidualWithinBand(
		FireProductionRoundoffTrace::TraceFloat maximumResidualPerS,
		FireProductionRoundoffTrace::TraceFloat maximumVelocityMPerS,
		FireProductionRoundoffTrace::TraceFloat domainLengthM,
		bool& withinBand );

	//! Restoration is independently validated against its own characteristic
	//! divergence scale. It deliberately does not borrow the physical
	//! projection's validation result or U/L scale.
	bool FireProductionRestorationProjectionResidualWithinBand(
		FireProductionRoundoffTrace::TraceFloat maximumResidualPerS,
		FireProductionRoundoffTrace::TraceFloat maximumRestorationTargetPerS,
		bool& withinBand );

	struct FireProductionRestorationPlateauValidation
	{
		double requiredDrainFraction;
		double deliveredDrainFraction;
		double maximumPostResidualPerS;
		bool mechanismPassed;

		FireProductionRestorationPlateauValidation() : requiredDrainFraction(0.0),
			deliveredDrainFraction(0.0),maximumPostResidualPerS(0.0),
			mechanismPassed(false) {}
	};

	//! Certifies that the restoration mechanism does not amplify its residual.
	//! The delivered drain remains a timestep-predictor diagnostic; a regime
	//! campaign separately proves non-secular long-shadow boundedness.
	bool FireProductionRestorationPlateauWithinBand(
		double maximumManifoldGeneration,
		double maximumPreProjectionResidualPerS,
		double maximumPostProjectionResidualPerS,
		FireProductionRestorationPlateauValidation& result );

	bool ValidateFireProductionProjectionRequest(
		const FireProductionProjectionRequest& request,
		std::string* error=0 );

	//! Strict-binary32 comparator implementing the stored P2 schedule.
	bool ProjectFireProductionCPU(
		const FireProductionProjectionRequest& request,
		FireProductionProjectionResult& result,
		std::string* error=0 );

	//! CPU calibration owner for the 17-cycle pressure-open physical pass used
	//! only inside the two-projection resident composition.
	bool ProjectFireProductionResidentPhysicalCPU(
		const FireProductionProjectionRequest& request,
		FireProductionProjectionResult& result,
		std::string* error=0 );

	//! CPU calibration mirror of the correction-only restoration invocation.
	//! The request target is an authored divergence increment, not an absolute
	//! final divergence target.
	bool ProjectFireProductionRestorationCPU(
		const FireProductionProjectionRequest& request,
		FireProductionProjectionResult& result,
		std::string* error=0 );

#if defined(__OBJC__) && defined(__APPLE__)
	struct FireProductionMetalProjectionResidentInput
	{
		id<MTLBuffer> gasDensityKGPerM3;
		std::array<id<MTLBuffer>,3> provisionalMomentumKGPerM2S;
		std::array<std::size_t,3> provisionalMomentumByteOffset;
		id<MTLBuffer> divergenceTargetPerS;

		FireProductionMetalProjectionResidentInput() : gasDensityKGPerM3(nil),
			divergenceTargetPerS(nil)
		{
			provisionalMomentumKGPerM2S.fill(nil);
			provisionalMomentumByteOffset.fill(0u);
		}
	};

	struct FireProductionMetalProjectionResidentState
	{
		id<MTLBuffer> pressurePa;
		id<MTLBuffer> pressureOpenInflow;
		std::array<id<MTLBuffer>,3> faceDensityKGPerM3;
		std::array<id<MTLBuffer>,3> momentumKGPerM2S;
		std::array<id<MTLBuffer>,3> velocityMPerS;
		std::array<id<MTLBuffer>,3> provisionalMomentumKGPerM2S;
		std::array<std::size_t,3> provisionalMomentumByteOffset;
		std::array<std::size_t,3> momentumByteOffset;
		bool restoration;

		FireProductionMetalProjectionResidentState() : pressurePa(nil),
			pressureOpenInflow(nil),restoration(false)
		{
			faceDensityKGPerM3.fill(nil);momentumKGPerM2S.fill(nil);
			velocityMPerS.fill(nil);provisionalMomentumKGPerM2S.fill(nil);
			provisionalMomentumByteOffset.fill(0u);momentumByteOffset.fill(0u);
		}
	};

	//! Internal full-grid Private-buffer seam for the composed resident P3 step.
	bool ProjectFireProductionMetalResident(
		const FireProductionProjectionRequest& request,
		const FireProductionMetalProjectionResidentInput& input,
		FireProductionProjectionResult& result,
		std::string* error=0 );

	//! Main physical projection without full-grid terminal staging. The returned
	//! momentum remains Private and is the sole admissible input to the resident
	//! restoration projection.
	bool ProjectFireProductionMetalResidentState(
		const FireProductionProjectionRequest& request,
		const FireProductionMetalProjectionResidentInput& input,
		FireProductionMetalProjectionResidentState& state,
		FireProductionProjectionResult& result,
		std::string* error=0 );

	//! Terminal resident restoration pass. Its target and validation result are
	//! owned by this invocation and are never shared with the physical pass.
	bool ProjectFireProductionMetalRestorationResident(
		const FireProductionProjectionRequest& request,
		const FireProductionMetalProjectionResidentInput& input,
		id<MTLBuffer> expectedRestorationTargetPerS,
		FireProductionProjectionResult& result,
		std::string* error=0 );

	//! Correction-only restoration solve that retains its complete Private
	//! result for an in-step scalar corrector. No full grid is staged here.
	bool ProjectFireProductionMetalRestorationResidentState(
		const FireProductionProjectionRequest& request,
		const FireProductionMetalProjectionResidentInput& input,
		id<MTLBuffer> expectedRestorationTargetPerS,
		FireProductionMetalProjectionResidentState& state,
		FireProductionProjectionResult& result,
		std::string* error=0 );

	//! Performs the sole terminal staging of an immutable retained restoration
	//! state. Publication and an in-step corrector may consume that state
	//! concurrently; both consumers complete before the owner mutates or
	//! releases any retained buffer.
	bool PublishFireProductionMetalRestorationResidentState(
		const FireProductionProjectionRequest& request,
		const FireProductionMetalProjectionResidentState& state,
		FireProductionProjectionResult& result,
		std::string* error=0 );
#endif

	//! Metal-resident implementation of the same fixed P2 schedule.  Platforms
	//! without Metal provide an honest fail-closed definition; there is no CPU
	//! fallback behind this entry point.
	bool ProjectFireProductionMetal(
		const FireProductionProjectionRequest& request,
		FireProductionProjectionResult& result,
		std::string* error=0 );

}

#endif
