// GENERATED by tools/generate_fire_production_roundoff_trace.py.
// Do not edit; regenerate from the strict production CPU arithmetic.
#include "../FireProductionRoundoffTrace.h"
//////////////////////////////////////////////////////////////////////
//
//  FireProductionAdvection.h - fp32 conservative production remap
//
//  License Information: Please see the attached LICENSE.TXT file
//
//////////////////////////////////////////////////////////////////////

#ifndef TRACE_FIREPRODUCTIONADVECTION_
#define TRACE_FIREPRODUCTIONADVECTION_

#include <cstddef>
#include <cstdint>
#include <string>
#include <vector>

namespace RISEFireProductionTrace
{
	enum FireProductionRemapBoundary
	{
		FireProductionRemapPeriodic,
		FireProductionRemapPressureOpen,
		FireProductionRemapWall
	};

	//! One batch of logically independent uniform-grid lines. Values are SoA:
	//! [component][line][cell], velocities are [line][face], ambient is one
	//! authored value per component.
	struct FireProductionRemapRequest
	{
		std::size_t lineLength;
		std::size_t lineCount;
		std::size_t componentCount;
		FireProductionRoundoffTrace::TraceFloat cellWidthM;
		FireProductionRoundoffTrace::TraceFloat timeStepS;
		FireProductionRemapBoundary boundary;
		bool asymmetricBoundaries;
		FireProductionRemapBoundary lowerBoundary;
		FireProductionRemapBoundary upperBoundary;
		std::vector<FireProductionRoundoffTrace::TraceFloat> values;
		std::vector<FireProductionRoundoffTrace::TraceFloat> faceVelocityMPerS;
		std::vector<FireProductionRoundoffTrace::TraceFloat> ambientValues;
		bool lineSpecificAmbientValues;
		std::vector<FireProductionRoundoffTrace::TraceFloat> lowerAmbientValues;
		std::vector<FireProductionRoundoffTrace::TraceFloat> upperAmbientValues;

		FireProductionRemapRequest() : lineLength(0), lineCount(0),
			componentCount(0), cellWidthM(0.0f), timeStepS(0.0f),
			boundary(FireProductionRemapPeriodic), asymmetricBoundaries(false),
			lowerBoundary(FireProductionRemapPeriodic),
			upperBoundary(FireProductionRemapPeriodic),lineSpecificAmbientValues(false) {}
	};

	struct FireProductionRemapResult
	{
		std::vector<FireProductionRoundoffTrace::TraceFloat> updatedValues;
		std::vector<FireProductionRoundoffTrace::TraceFloat> faceFluxes;
		std::vector<FireProductionRoundoffTrace::TraceFloat> sharedLimiterAlpha;
		double deviceElapsedMS;

		FireProductionRemapResult() : deviceElapsedMS(0.0) {}
	};

	//! Outward-rounded Metal allocation bytes for the request's buffer topology.
	bool FireProductionRemapWorkingSetBytes(
		const FireProductionRemapRequest& request,
		std::uint64_t& bytes );

	bool ValidateFireProductionRemapRequest(
		const FireProductionRemapRequest& request,
		std::string* error=0 );

	//! r124 continuous common-alpha cap. Exposed for independent contract gates.
	FireProductionRoundoffTrace::TraceFloat FireProductionContinuousSharedLimiterAlpha(
		FireProductionRoundoffTrace::TraceFloat alpha, FireProductionRoundoffTrace::TraceFloat headroom, FireProductionRoundoffTrace::TraceFloat signedConsumption,
		FireProductionRoundoffTrace::TraceFloat center, FireProductionRoundoffTrace::TraceFloat envelope ) noexcept;

	//! Binary32 CPU oracle with the same stored intermediates as the Metal path.
	bool RemapFireProductionCPU(
		const FireProductionRemapRequest& request,
		FireProductionRemapResult& result,
		std::string* error=0 );

	//! Metal implementation. Non-Metal builds fail explicitly without CPU fallback.
	bool RemapFireProductionMetal(
		const FireProductionRemapRequest& request,
		FireProductionRemapResult& result,
		std::string* error=0 );
}

#endif
