// GENERATED by tools/generate_fire_production_roundoff_trace.py.
// Do not edit; regenerate from the strict production CPU arithmetic.
#include "../FireProductionRoundoffTrace.h"
//////////////////////////////////////////////////////////////////////
//
//  FireProductionTransport.h - fp32 production coupled transport
//
//  License Information: Please see the attached LICENSE.TXT file
//
//////////////////////////////////////////////////////////////////////

#ifndef TRACE_FIREPRODUCTIONTRANSPORT_
#define TRACE_FIREPRODUCTIONTRANSPORT_

#include "FireProductionAdvection.h"
#include "FireProductionProjection.h"

#include <array>
#include <cstddef>
#include <cstdint>
#include <string>
#include <vector>

namespace RISEFireProductionTrace
{
	//! Advection-only P3 oracle surface.  Carrier velocities and boundaries are
	//! frozen from the beginning snapshot; only conservativeValues advances.
	struct FireProductionCellPalindromeRequest
	{
		FireProductionProjectionShape shape;
		std::size_t componentCount;
		FireProductionRoundoffTrace::TraceFloat timeStepS;
		std::array<FireProductionProjectionBoundary,6> boundary;
		std::vector<FireProductionRoundoffTrace::TraceFloat> conservativeValues;
		std::array<std::vector<FireProductionRoundoffTrace::TraceFloat>,3> frozenVelocityMPerS;
		std::vector<FireProductionRoundoffTrace::TraceFloat> ambientValues;
		//! Diagnostic-only retention of the accepted primal gas-mass fluxes used
		//! by the Section 3.7 compatible-momentum comparator.  Ordinary production
		//! leaves this false and pays no buffer, kernel, or working-set cost.
		bool retainAcceptedGasMassDose;

		FireProductionCellPalindromeRequest() : componentCount(0u),timeStepS(0.0f),
			retainAcceptedGasMassDose(false)
		{
			boundary.fill(FireProductionProjectionWall);
		}
	};

	struct FireProductionCellPalindromeResult
	{
		std::vector<FireProductionRoundoffTrace::TraceFloat> conservativeValues;
		//! Accepted, timestep-integrated gas-mass flux on the primal faces for
		//! x/2,y/2,z,y/2,x/2.  Populated for the nine-component production tuple;
		//! empty for generic comparator tuples that do not contain the six gas
		//! constituent rows.
		std::array<std::vector<FireProductionRoundoffTrace::TraceFloat>,5> acceptedGasMassDoseKGPerM2;
		std::uint32_t executedSubmapCount;
		std::uint32_t privateResidentBufferCount;
		std::uint32_t sharedBufferCount;
		std::uint32_t commandCommitCount;
		std::uint32_t interstageFullGridReadbackCount;
		std::uint64_t certifiedWorkingSetBytes;
		std::uint64_t actualTrackedWorkingSetBytes;
		double deviceElapsedMS;

		FireProductionCellPalindromeResult() : executedSubmapCount(0u),
			privateResidentBufferCount(0u),sharedBufferCount(0u),commandCommitCount(0u),
			interstageFullGridReadbackCount(0u),certifiedWorkingSetBytes(0u),
			actualTrackedWorkingSetBytes(0u),deviceElapsedMS(0.0) {}
	};

	//! Dual-grid momentum comparison surface. Face arrays include their positive
	//! publication plane; it is a duplicate only on periodic component-normal axes.
	struct FireProductionDualMomentumRequest
	{
		FireProductionProjectionShape shape;
		FireProductionRoundoffTrace::TraceFloat timeStepS;
		FireProductionRoundoffTrace::TraceFloat ambientDensityKGPerM3;
		std::array<FireProductionProjectionBoundary,6> boundary;
		std::array<std::vector<FireProductionRoundoffTrace::TraceFloat>,3> beginningFaceDensity;
		std::array<std::vector<FireProductionRoundoffTrace::TraceFloat>,3> beginningMomentum;
		std::array<std::vector<FireProductionRoundoffTrace::TraceFloat>,3> frozenVelocityMPerS;

		FireProductionDualMomentumRequest() : timeStepS(0.0f),ambientDensityKGPerM3(1.0f)
		{
			boundary.fill(FireProductionProjectionPeriodic);
		}
	};

	struct FireProductionDualMomentumResult
	{
		std::array<std::vector<FireProductionRoundoffTrace::TraceFloat>,3> auxiliaryFaceDensity;
		std::array<std::vector<FireProductionRoundoffTrace::TraceFloat>,3> momentum;
		std::uint32_t executedSubmapCount;
		std::uint32_t canonicalSeamCopyCount;
		std::uint32_t commandCommitCount;
		std::uint32_t interstageFullGridTransferCount;
		std::uint64_t actualMetalAllocationBytes;
		double deviceElapsedMS;

		FireProductionDualMomentumResult() : executedSubmapCount(0u),
			canonicalSeamCopyCount(0u),commandCommitCount(0u),
			interstageFullGridTransferCount(0u),actualMetalAllocationBytes(0u),
			deviceElapsedMS(0.0) {}
	};

	using FireProductionPeriodicDualMomentumRequest=FireProductionDualMomentumRequest;
	using FireProductionPeriodicDualMomentumResult=FireProductionDualMomentumResult;

	bool ValidateFireProductionCellPalindromeRequest(
		const FireProductionCellPalindromeRequest& request,
		std::string* error=0 );

	bool ValidateFireProductionDualMomentumRequest(
		const FireProductionDualMomentumRequest& request,
		std::string* error=0 );

	//! Complete standalone-comparator peak, including caller request/result,
	//! Shared staging, private resident scratch, all five parameter pairs, and
	//! conservative 16-KiB outward allocation rounding for every Metal buffer.
	bool FireProductionCellPalindromeWorkingSetBytes(
		const FireProductionProjectionShape& shape,
		std::size_t componentCount,
		std::uint64_t& bytes,
		bool retainAcceptedGasMassDose=false );

	//! Strict-binary32 five-pass oracle: x/2,y/2,z,y/2,x/2.
	bool RemapFireProductionCellPalindromeCPU(
		const FireProductionCellPalindromeRequest& request,
		FireProductionCellPalindromeResult& result,
		std::string* error=0 );

	//! One-command Metal comparator for the same five-pass composition.  Full
	//! grids remain private between passes; Shared staging exists only at the
	//! standalone request and publication boundaries.
	bool RemapFireProductionCellPalindromeMetal(
		const FireProductionCellPalindromeRequest& request,
		FireProductionCellPalindromeResult& result,
		std::string* error=0 );

	//! Test/publication wrapper around the Private-buffer resident seam. It
	//! performs boundary upload and terminal staging outside the resident call,
	//! and reports only the resident command/transfer diagnostics.
	bool RemapFireProductionCellPalindromeMetalResidentComparator(
		const FireProductionCellPalindromeRequest& request,
		FireProductionCellPalindromeResult& result,
		std::string* error=0 );

#if defined(__OBJC__) && defined(__APPLE__)
	struct FireProductionMetalCellPalindromeResidentInput
	{
		id<MTLBuffer> conservativeValues;
		std::array<id<MTLBuffer>,3> frozenVelocityMPerS;
		id<MTLBuffer> ambientValues;

		FireProductionMetalCellPalindromeResidentInput() : conservativeValues(nil),
			ambientValues(nil)
		{
			frozenVelocityMPerS.fill(nil);
		}
	};

	struct FireProductionMetalCellPalindromeResidentResult
	{
		id<MTLBuffer> conservativeValues;
		std::array<id<MTLBuffer>,5> acceptedGasMassDoseKGPerM2;
		std::uint32_t executedSubmapCount;
		std::uint32_t commandCommitCount;
		std::uint32_t interstageFullGridTransferCount;
		std::uint64_t actualMetalAllocationBytes;
		double deviceElapsedMS;
		double deviceStartTimeS;
		double deviceEndTimeS;

		FireProductionMetalCellPalindromeResidentResult() : conservativeValues(nil),
			executedSubmapCount(0u),commandCommitCount(0u),
			interstageFullGridTransferCount(0u),actualMetalAllocationBytes(0u),
			deviceElapsedMS(0.0),deviceStartTimeS(0.0),deviceEndTimeS(0.0)
		{
			acceptedGasMassDoseKGPerM2.fill(nil);
		}
	};

	//! Private-buffer production seam. The host request supplies validation and
	//! schedule bytes; the authoritative full-grid operands are the resident
	//! buffers. No full-grid staging or host access is permitted in this call.
	bool RemapFireProductionCellPalindromeMetalResident(
		const FireProductionCellPalindromeRequest& request,
		const FireProductionMetalCellPalindromeResidentInput& input,
		FireProductionMetalCellPalindromeResidentResult& result,
		std::string* error=0 );
#endif

	//! Strict-binary32 periodic MAC oracle.  Each noncollocated momentum
	//! component owns a separate dual tuple and five-pass palindrome.
	bool RemapFireProductionPeriodicDualMomentumCPU(
		const FireProductionPeriodicDualMomentumRequest& request,
		FireProductionPeriodicDualMomentumResult& result,
		std::string* error=0 );

	//! Step-boundary packing oracle for one periodic MAC component. This builds
	//! the common auxiliary-density/momentum cell tuple and its three frozen
	//! dual carriers; resident execution consumes the corresponding Private
	//! buffers without rebuilding or staging them interstage.
	bool BuildFireProductionPeriodicDualCellRequest(
		const FireProductionPeriodicDualMomentumRequest& request,
		unsigned int transportedComponent,
		FireProductionCellPalindromeRequest& dualRequest,
		std::string* error=0 );

	//! Conservative resident periodic-dual peak. It adds all nine borrowed and
	//! six atomically published face arrays to the largest two-channel resident
	//! palindrome certificate.
	bool FireProductionPeriodicDualMomentumResidentWorkingSetBytes(
		const FireProductionProjectionShape& shape,
		std::uint64_t& bytes );

	bool FireProductionDualMomentumResidentWorkingSetBytes(
		const FireProductionProjectionShape& shape,
		const std::array<FireProductionProjectionBoundary,6>& boundary,
		std::uint64_t& bytes );

	//! Section 3.7 compatible dual-grid peak.  The five accepted primal gas
	//! mass-dose fields are already owned by the scalar palindrome; this seam
	//! counts only the dual ping-pong state and its parameter buffer.
	bool FireProductionCompatibleDualMomentumResidentWorkingSetBytes(
		const FireProductionProjectionShape& shape,
		std::uint64_t& bytes );

	//! Standalone oracle wrapper around the periodic Private-buffer resident
	//! dual-grid seam. Boundary uploads and the final tap are outside the
	//! measured resident interval.
	bool RemapFireProductionPeriodicDualMomentumMetal(
		const FireProductionPeriodicDualMomentumRequest& request,
		FireProductionPeriodicDualMomentumResult& result,
		std::string* error=0 );

	//! Strict-binary32 six-side MAC oracle. Component-normal wall planes are
	//! prescribed, open endpoints skip only their normal sweep, and transverse
	//! sweeps consume line-resolved ambient tuples through the shared P1 kernel.
	bool RemapFireProductionDualMomentumCPU(
		const FireProductionDualMomentumRequest& request,
		FireProductionDualMomentumResult& result,
		std::string* error=0 );

	//! Structural preflight for the compatible owner.  Unlike the retired dual
	//! remap validator, this does not inspect frozen carrier fields or construct
	//! an independent two-component limiter that the compatible operator never
	//! consumes.
	bool ValidateFireProductionCompatibleDualMomentumRequest(
		const FireProductionDualMomentumRequest& request,
		std::string* error=0 );

	//! Section 3.7 compatible momentum transport.  Momentum does not own an
	//! independent reconstruction: every dual-control-volume face receives the
	//! boundary-aware I_i restriction of the scalar palindrome's already
	//! shared-alpha-limited gas-mass dose, multiplied by the arithmetic mean of
	//! the adjacent transported-component velocities.
	bool RemapFireProductionCompatibleDualMomentumCPU(
		const FireProductionDualMomentumRequest& request,
		const std::array<std::vector<FireProductionRoundoffTrace::TraceFloat>,5>& acceptedGasMassDoseKGPerM2,
		FireProductionDualMomentumResult& result,
		std::string* error=0 );

	//! Step-boundary oracle for one of the nine dual-grid line layouts.  The
	//! values are disposable packing bytes; carrier and side ambient arrays are
	//! the frozen operands uploaded before the resident interval.
	bool BuildFireProductionDualAxisRequest(
		const FireProductionDualMomentumRequest& request,
		unsigned int transportedComponent,
		unsigned int sweepAxis,
		FireProductionRoundoffTrace::TraceFloat timeStepS,
		const std::vector<FireProductionRoundoffTrace::TraceFloat>& density,
		const std::vector<FireProductionRoundoffTrace::TraceFloat>& momentum,
		FireProductionRemapRequest& lineRequest,
		std::string* error=0 );

	//! Standalone oracle wrapper around the mixed-boundary resident seam.
	//! Upload and final staging are outside the measured resident interval.
	bool RemapFireProductionDualMomentumMetalResidentComparator(
		const FireProductionDualMomentumRequest& request,
		FireProductionDualMomentumResult& result,
		std::string* error=0 );

#if defined(__OBJC__) && defined(__APPLE__)
	struct FireProductionMetalPeriodicDualMomentumResidentInput
	{
		std::array<id<MTLBuffer>,3> beginningFaceDensity;
		std::array<id<MTLBuffer>,3> beginningMomentum;
		std::array<id<MTLBuffer>,3> frozenVelocityMPerS;

		FireProductionMetalPeriodicDualMomentumResidentInput()
		{
			beginningFaceDensity.fill(nil);beginningMomentum.fill(nil);
			frozenVelocityMPerS.fill(nil);
		}
	};

	struct FireProductionMetalPeriodicDualMomentumResidentResult
	{
		std::array<id<MTLBuffer>,3> auxiliaryFaceDensity;
		std::array<id<MTLBuffer>,3> momentum;
		std::uint32_t executedSubmapCount;
		std::uint32_t commandCommitCount;
		std::uint32_t interstageFullGridTransferCount;
		std::uint64_t actualMetalAllocationBytes;
		double deviceElapsedMS;

		FireProductionMetalPeriodicDualMomentumResidentResult() :
			executedSubmapCount(0u),commandCommitCount(0u),
			interstageFullGridTransferCount(0u),actualMetalAllocationBytes(0u),
			deviceElapsedMS(0.0)
		{
			auxiliaryFaceDensity.fill(nil);momentum.fill(nil);
		}
	};

	bool RemapFireProductionPeriodicDualMomentumMetalResident(
		const FireProductionPeriodicDualMomentumRequest& request,
		const FireProductionMetalPeriodicDualMomentumResidentInput& input,
		FireProductionMetalPeriodicDualMomentumResidentResult& result,
		std::string* error=0 );

	struct FireProductionMetalDualAxisStaticState
	{
		id<MTLBuffer> faceVelocityMPerS;
		id<MTLBuffer> lowerAmbientValues;
		id<MTLBuffer> upperAmbientValues;
		std::uint32_t lineLength;
		std::uint32_t lineCount;
		std::uint32_t lowerBoundary;
		std::uint32_t upperBoundary;
		std::uint32_t ambientPerLine;

		FireProductionMetalDualAxisStaticState() : faceVelocityMPerS(nil),
			lowerAmbientValues(nil),upperAmbientValues(nil),lineLength(0u),lineCount(0u),
			lowerBoundary(0u),upperBoundary(0u),ambientPerLine(0u) {}
	};

	struct FireProductionMetalDualMomentumStaticState
	{
		std::array<std::array<FireProductionMetalDualAxisStaticState,3>,3> axis;
		FireProductionProjectionShape shape;
		FireProductionRoundoffTrace::TraceFloat timeStepS;
		std::array<FireProductionProjectionBoundary,6> boundary;
		std::uint32_t uploadCommandCommitCount;
		std::uint64_t actualMetalAllocationBytes;

		FireProductionMetalDualMomentumStaticState() : timeStepS(0.0f),
			uploadCommandCommitCount(0u),actualMetalAllocationBytes(0u)
			{ boundary.fill(FireProductionProjectionWall); }
	};

	struct FireProductionMetalDualMomentumResidentInput
	{
		id<MTLBuffer> packedFaceDensity;
		id<MTLBuffer> packedMomentum;
		std::array<id<MTLBuffer>,5> acceptedGasMassDoseKGPerM2;
		std::array<std::size_t,3> faceByteOffset;

		FireProductionMetalDualMomentumResidentInput() : packedFaceDensity(nil),
			packedMomentum(nil)
		{
			acceptedGasMassDoseKGPerM2.fill(nil);faceByteOffset.fill(0u);
		}
	};

	struct FireProductionMetalDualMomentumResidentResult
	{
		id<MTLBuffer> packedAuxiliaryFaceDensity;
		id<MTLBuffer> packedMomentum;
		std::array<std::size_t,3> faceByteOffset;
		std::uint32_t executedSubmapCount;
		std::uint32_t commandCommitCount;
		std::uint32_t interstageFullGridTransferCount;
		std::uint64_t actualMetalAllocationBytes;
		double deviceElapsedMS;
		double deviceStartTimeS;
		double deviceEndTimeS;

		FireProductionMetalDualMomentumResidentResult() :
			packedAuxiliaryFaceDensity(nil),packedMomentum(nil),executedSubmapCount(0u),
			commandCommitCount(0u),interstageFullGridTransferCount(0u),
			actualMetalAllocationBytes(0u),deviceElapsedMS(0.0),deviceStartTimeS(0.0),
			deviceEndTimeS(0.0) { faceByteOffset.fill(0u); }
	};

	//! Step-boundary upload of the nine frozen carrier/ambient layouts.
	bool PrepareFireProductionDualMomentumMetalStaticState(
		const FireProductionDualMomentumRequest& request,
		FireProductionMetalDualMomentumStaticState& state,
		std::string* error=0 );

	//! Mixed-boundary dual-grid resident seam.  All full-grid and line operands
	//! are Private and no host access or upload occurs in this call.
	bool RemapFireProductionDualMomentumMetalResident(
		const FireProductionDualMomentumRequest& request,
		const FireProductionMetalDualMomentumStaticState& staticState,
		const FireProductionMetalDualMomentumResidentInput& input,
		FireProductionMetalDualMomentumResidentResult& result,
		std::string* error=0 );

	//! Private-buffer Section 3.7 owner.  Five accepted primal mass-dose
	//! buffers are borrowed from the scalar palindrome; five compatible dual
	//! updates execute without host access or an independent momentum limiter.
	bool RemapFireProductionCompatibleDualMomentumMetalResident(
		const FireProductionDualMomentumRequest& request,
		const FireProductionMetalDualMomentumResidentInput& input,
		FireProductionMetalDualMomentumResidentResult& result,
		std::string* error=0 );
#endif
}

#endif
