// GENERATED by tools/generate_fire_production_roundoff_trace.py.
// Do not edit; regenerate from the strict production CPU arithmetic.
#include "../FireProductionRoundoffTrace.h"
//////////////////////////////////////////////////////////////////////
//
//  FireProductionForce.h - strict-binary32 production force primitives
//
//  License Information: Please see the attached LICENSE.TXT file
//
//////////////////////////////////////////////////////////////////////

#ifndef TRACE_FIRE_PRODUCTION_FORCE_H
#define TRACE_FIRE_PRODUCTION_FORCE_H

#include "FireProductionProjection.h"
#include "FireProductionTransport.h"
#include "../../src/Library/Utilities/FireSimulationRecords.h"

#include <array>
#include <cstdint>
#include <cstring>
#include <string>
#include <vector>

namespace RISEFireProductionTrace
{
	struct FireProductionVremanInput
	{
		std::array<FireProductionRoundoffTrace::TraceFloat,9> velocityGradientPerS;
		std::array<FireProductionRoundoffTrace::TraceFloat,3> directionalWidthsM;
		FireProductionRoundoffTrace::TraceFloat coefficient;

		FireProductionVremanInput() : coefficient(0.07f)
		{
			velocityGradientPerS.fill(0.0f);
			directionalWidthsM.fill(1.0f);
		}
	};

	//! Strict-binary32 transcription of the record Vreman expression. The
	//! caller supplies the coefficient obtained from the certified record.
	bool EvaluateFireProductionVremanEddyViscosity(
		const FireProductionVremanInput& input,
		FireProductionRoundoffTrace::TraceFloat& eddyViscosityM2PerS,
		std::string* error=0 );

	struct FireProductionViscousSchedule
	{
		std::uint32_t substepCount;
		FireProductionRoundoffTrace::TraceFloat substepTimeS;
		double outwardWork;
		double representedProductUpper;

		FireProductionViscousSchedule() : substepCount(0u),substepTimeS(0.0f),
			outwardWork(0.0),representedProductUpper(0.0) {}
	};

	//! Host half of the r90/r91 outward stability certificate. Both inputs are
	//! stored fp32 bytes; selection certifies the represented fp32 dt/N and
	//! rejects a required ninth substep before any physical update.
	bool SelectFireProductionViscousSchedule(
		FireProductionRoundoffTrace::TraceFloat timeStepS,
		FireProductionRoundoffTrace::TraceFloat outwardLambdaPerS,
		FireProductionViscousSchedule& schedule,
		std::string* error=0 );

	struct FireProductionFrozenForceRequest
	{
		FireProductionProjectionShape shape;
		FireProductionRoundoffTrace::TraceFloat timeStepS;
		FireProductionRoundoffTrace::TraceFloat ambientDensityKGPerM3;
		FireProductionRoundoffTrace::TraceFloat vremanCoefficient;
		std::array<FireProductionRoundoffTrace::TraceFloat,3> gravityMPerS2;
		std::array<FireProductionProjectionBoundary,6> boundary;
		std::vector<FireProductionRoundoffTrace::TraceFloat> cellGasDensityKGPerM3;
		std::vector<FireProductionRoundoffTrace::TraceFloat> molecularKinematicViscosityM2PerS;
		std::array<std::vector<FireProductionRoundoffTrace::TraceFloat>,3> faceDensityKGPerM3;
		std::array<std::vector<FireProductionRoundoffTrace::TraceFloat>,3> beginningMomentumKGPerM2S;

		FireProductionFrozenForceRequest() : timeStepS(0.0f),ambientDensityKGPerM3(1.0f),
			vremanCoefficient(0.07f)
		{
			gravityMPerS2.fill(0.0f);
			boundary.fill(FireProductionProjectionPeriodic);
		}
	};

	struct FireProductionFrozenForceResult
	{
		std::vector<FireProductionRoundoffTrace::TraceFloat> eddyKinematicViscosityM2PerS;
		std::vector<FireProductionRoundoffTrace::TraceFloat> effectiveDynamicViscosityPaS;
		std::array<std::vector<FireProductionRoundoffTrace::TraceFloat>,3> beginningViscousMomentumRateKGPerM2S2;
		std::array<std::vector<FireProductionRoundoffTrace::TraceFloat>,3> gravityMomentumIncrementKGPerM2S;
	};

	//! Logical peak of the CPU frozen-force comparator, including caller input,
	//! local work, and the atomically published result payload.
	bool FireProductionFrozenForceWorkingSetBytes(
		const FireProductionProjectionShape& shape,
		std::uint64_t& bytes );

	//! Complete standalone Metal-wrapper peak: live caller/result arrays plus
	//! every MTLBuffer rounded outward to the M4 allocation quantum.
	bool FireProductionFrozenForceMetalWorkingSetBytes(
		const FireProductionProjectionShape& shape,
		std::uint64_t& bytes );

	bool FireProductionResidentForceMetalWorkingSetBytes(
		const FireProductionProjectionShape& shape,
		bool captureIntermediateStates,
		std::uint64_t& bytes );

	//! Conservative force-owned plus resident-P2 peak, including the two target
	//! buffers retained by the composed owner. Used before any Metal allocation.
	bool FireProductionResidentForceProjectionWorkingSetBytes(
		const FireProductionProjectionShape& shape,
		std::uint64_t& bytes );

	bool FireProductionFrozenForceAdvanceWorkingSetBytes(
		const FireProductionProjectionShape& shape,
		std::uint64_t& bytes );

	//! Complete full resident-step certificate. This query is shape/boundary
	//! only so the owner can reject the two-GiB limit before inspecting payloads.
	bool FireProductionResidentStepWorkingSetBytes(
		const FireProductionProjectionShape& shape,
		const std::array<FireProductionProjectionBoundary,6>& boundary,
		std::uint64_t& bytes );

	//! Allocation-free structural and payload preflight shared by every frozen-
	//! force owner. It performs no physical work and publishes no partial state.
	bool ValidateFireProductionFrozenForceRequest(
		const FireProductionFrozenForceRequest& request,
		std::string* error=0 );

	//! Beginning-state, strict-binary32 force field used by the production P3
	//! comparator. Vreman and mu are frozen; viscous rates update only interior
	//! normal faces, relative gravity also owns pressure-open endpoint faces,
	//! and wall-normal endpoints remain prescribed zero.
	bool BuildFireProductionFrozenForceFieldsCPU(
		const FireProductionFrozenForceRequest& request,
		FireProductionFrozenForceResult& result,
		std::string* error=0 );

	//! Standalone Metal comparison wrapper for the same beginning-state frozen
	//! fields. Platforms without Metal fail honestly; no CPU fallback is hidden
	//! behind this entry point. The later resident P3 seam reuses these kernels.
	bool BuildFireProductionFrozenForceFieldsMetal(
		const FireProductionFrozenForceRequest& request,
		FireProductionFrozenForceResult& result,
		double& deviceElapsedMS,
		std::string* error=0 );

	struct FireProductionFrozenForceAdvanceResult
	{
		FireProductionFrozenForceResult frozenFields;
		FireProductionViscousSchedule schedule;
		std::array<std::vector<FireProductionRoundoffTrace::TraceFloat>,3> momentumKGPerM2S;
		std::array<std::uint64_t,8> intermediateMomentumByteDigests;
		std::uint32_t intermediateMomentumDigestCount;
		std::uint32_t executedViscousSubstepCount;

		FireProductionFrozenForceAdvanceResult() :
			intermediateMomentumDigestCount(0u),executedViscousSubstepCount(0u)
		{
			intermediateMomentumByteDigests.fill(0u);
		}
	};

	//! Strict-binary32 force comparator after the resident preflight has supplied
	//! its outward Lambda scalar. mu_eff and face density stay frozen through all
	//! viscous substeps; relative gravity is added exactly once afterward.
	bool AdvanceFireProductionFrozenForceCPU(
		const FireProductionFrozenForceRequest& request,
		FireProductionRoundoffTrace::TraceFloat outwardLambdaPerS,
		FireProductionFrozenForceAdvanceResult& result,
		std::string* error=0 );

	struct FireProductionResidentForceDiagnostics
	{
		FireProductionRoundoffTrace::TraceFloat outwardLambdaPerS;
		std::uint32_t scalarDiagnosticTransferCount;
		std::uint32_t substepLoopDeviceToHostTransferCount;
		std::uint32_t terminalStagingCount;
		std::uint32_t commandCommitCount;
		std::uint64_t certifiedWorkingSetBytes;
		std::uint64_t actualMetalAllocationBytes;
		double preflightDeviceElapsedMS;
		double advanceDeviceElapsedMS;

		FireProductionResidentForceDiagnostics() : outwardLambdaPerS(0.0f),
			scalarDiagnosticTransferCount(0u),substepLoopDeviceToHostTransferCount(0u),
			terminalStagingCount(0u),commandCommitCount(0u),certifiedWorkingSetBytes(0u),
			actualMetalAllocationBytes(0u),preflightDeviceElapsedMS(0.0),
			advanceDeviceElapsedMS(0.0) {}
	};

	//! Standalone oracle wrapper around the resident force sequence. Full-grid
	//! resources remain Private through every viscous substep and the gravity
	//! update. Optional Private snapshots stage only after command completion.
	bool AdvanceFireProductionFrozenForceMetal(
		const FireProductionFrozenForceRequest& request,
		bool captureIntermediateStates,
		FireProductionFrozenForceAdvanceResult& result,
		FireProductionResidentForceDiagnostics& diagnostics,
		std::string* error=0 );

	//! Oracle wrapper for the no-staging resident-state branch. It performs one
	//! terminal momentum tap after the resident call and leaves the force
	//! diagnostics' terminal-staging count at zero for that measured interval.
	bool AdvanceFireProductionFrozenForceMetalResidentStateComparator(
		const FireProductionFrozenForceRequest& request,
		FireProductionFrozenForceAdvanceResult& result,
		FireProductionResidentForceDiagnostics& diagnostics,
		std::string* error=0 );

#if defined(__OBJC__) && defined(__APPLE__)
	struct FireProductionMetalFrozenForceResidentState
	{
		id<MTLBuffer> cellGasDensityKGPerM3;
		id<MTLBuffer> packedFaceDensityKGPerM3;
		id<MTLBuffer> packedMomentumKGPerM2S;
		std::array<std::size_t,3> faceByteOffset;
		FireProductionViscousSchedule schedule;
		FireProductionResidentForceDiagnostics diagnostics;

		FireProductionMetalFrozenForceResidentState() : cellGasDensityKGPerM3(nil),
			packedFaceDensityKGPerM3(nil),packedMomentumKGPerM2S(nil)
		{
			faceByteOffset.fill(0u);
		}
	};

	//! Internal full-grid Private state seam. It executes preflight, every
	//! selected viscous substep, and gravity, then returns the still-resident
	//! density/momentum owners without terminal staging or projection.
	bool AdvanceFireProductionFrozenForceMetalResidentState(
		const FireProductionFrozenForceRequest& request,
		FireProductionMetalFrozenForceResidentState& state,
		std::string* error=0 );
#endif

	struct FireProductionResidentForceProjectionResult
	{
		FireProductionViscousSchedule forceSchedule;
		FireProductionProjectionResult projection;
		FireProductionResidentForceDiagnostics forceDiagnostics;
		std::uint32_t forceToProjectionDeviceToHostTransferCount;
		std::uint32_t residentProjectionInvocationCount;
		std::uint64_t combinedCertifiedWorkingSetBytes;
		std::uint64_t combinedActualMetalAllocationBytes;

		FireProductionResidentForceProjectionResult() :
			forceToProjectionDeviceToHostTransferCount(0u),residentProjectionInvocationCount(0u),
			combinedCertifiedWorkingSetBytes(0u),combinedActualMetalAllocationBytes(0u) {}
	};

	//! Resident production seam: frozen force substeps, gravity, and exactly one
	//! P2 projection without a full-grid host transfer between the operators.
	bool AdvanceFireProductionForceProjectionMetal(
		const FireProductionFrozenForceRequest& forceRequest,
		const std::vector<FireProductionRoundoffTrace::TraceFloat>& divergenceTargetPerS,
		FireProductionResidentForceProjectionResult& result,
		std::string* error=0 );

	struct FireProductionResidentStepRequest
	{
		FireProductionFrozenForceRequest force;
		FireProductionCellPalindromeRequest cellTransport;
		FireProductionDualMomentumRequest dualTransport;
		std::vector<FireProductionRoundoffTrace::TraceFloat> cellSourceIncrement;
		std::array<std::vector<FireProductionRoundoffTrace::TraceFloat>,3> momentumSourceIncrement;
		std::vector<FireProductionRoundoffTrace::TraceFloat> divergenceTargetPerS;
		std::vector<FireProductionRoundoffTrace::TraceFloat> restorationDivergenceTargetPerS;
		std::vector<double> beginningManifoldDeviationPerCell;
		bool enforceManifoldPlateau;

		FireProductionResidentStepRequest() : enforceManifoldPlateau(true) {}
	};

	class FireProductionAcceptedManifoldObservation;
	class FireProductionCheckpointManifoldAccess final
	{
	public:
		//! Reopens and independently authenticates the complete v12 checkpoint
		//! payload before restoring its trailing manifold record.  There is no
		//! public raw-tuple restoration seam.
		static bool RestoreValidatedCheckpointFile(
			const std::string&,std::uint64_t,std::uint64_t,std::uint64_t,
			double,double,std::uint64_t,bool,std::uint64_t,
			FireProductionAcceptedManifoldObservation&,std::string* );
	private:
		FireProductionCheckpointManifoldAccess()=delete;
	};
	struct FireProductionStableTimeStep;
	struct FireProductionResidentStepResult;

	class FireProductionAcceptedManifoldObservation
	{
	public:
		FireProductionAcceptedManifoldObservation() : available_(false),timeStepS_(0.0),
			maximumGeneration_(0.0),restorationDrainFraction_(0.0),
			residentPayloadDigest_(0u),acceptedStateDigest_(0u),bindsResidentPayload_(false) {}
		bool Available() const { return available_; }
		double TimeStepS() const { return timeStepS_; }
		double MaximumGeneration() const { return maximumGeneration_; }
		double RestorationDrainFraction() const { return restorationDrainFraction_; }
		std::uint64_t SerializedAcceptedStateDigest() const { return acceptedStateDigest_; }
		bool MatchesAcceptedResidentPayload(const FireProductionResidentStepResult&) const;

	private:
		void Clear() { available_=false;timeStepS_=0.0;maximumGeneration_=0.0;
			restorationDrainFraction_=0.0;residentPayloadDigest_=0u;
			acceptedStateDigest_=0u;bindsResidentPayload_=false; }
		bool available_;
		double timeStepS_;
		double maximumGeneration_;
		double restorationDrainFraction_;
		std::uint64_t residentPayloadDigest_;
		std::uint64_t acceptedStateDigest_;
		bool bindsResidentPayload_;
		friend class FireProductionCheckpointManifoldAccess;
		friend bool SelectFireProductionStableTimeStep(
			double,double,double,double,double,
			const FireProductionAcceptedManifoldObservation&,
			FireProductionStableTimeStep&,std::string* );
	};

	struct FireProductionStableTimeStep
	{
		double seconds;
		const char* activeLimit;

		FireProductionStableTimeStep() : seconds(0.0),activeLimit(0) {}
	};
	//! Pure r143 predictor arithmetic for diagnostics and the authority-bearing
	//! selector.  It does not confer accepted-observation authority.
	bool DeriveFireProductionManifoldTimeStep(
		double previousStepS,double maximumGeneration,double restorationDrainFraction,
		double& timeStepS,std::string* error=0 );

	//! Selects the production step from the CFL family, the 1.1 growth cap, and
	//! the r143 accepted-step manifold observation.  An unavailable observation
	//! is valid only for the first step of a run.
	bool SelectFireProductionStableTimeStep(
		double cellWidthM,
		double maximumVelocityMPerS,
		double maximumPositiveReducedGravityMPerS2,
		double maximumKinematicTransportM2PerS,
		double previousStepS,
		const FireProductionAcceptedManifoldObservation& previousManifold,
		FireProductionStableTimeStep& result,
		std::string* error=0 );

	struct FireProductionResidentStepResult
	{
		std::vector<FireProductionRoundoffTrace::TraceFloat> conservativeValues;
		FireProductionDualMomentumResult transportedDual;
		FireProductionProjectionResult physicalProjection;
		FireProductionProjectionResult projection;
		FireProductionViscousSchedule forceSchedule;
		FireProductionResidentForceDiagnostics forceDiagnostics;
		std::uint32_t cellSubmapCount;
		std::uint32_t dualSubmapCount;
		std::uint32_t sourceCommandCommitCount;
		std::uint32_t residentProjectionInvocationCount;
		std::uint32_t interstageFullGridTransferCount;
		std::uint32_t terminalStagingCount;
		std::uint64_t combinedCertifiedWorkingSetBytes;
		std::uint64_t combinedActualMetalAllocationBytes;
		double deviceElapsedMS;
		FireProductionRoundoffTrace::TraceFloat representedTimeStepS;
		double maximumManifoldGeneration;
		double maximumAcceptedManifoldDeviation;
		double requiredRestorationDrainFraction;
		double deliveredRestorationDrainFraction;
		double restorationResidualBandPerS;
		bool manifoldPlateauPassed;
		RISE::FireStateProducerPrecision conservativeProducerPrecision;
		FireProductionProjectionShape acceptedShape;

		FireProductionResidentStepResult() : cellSubmapCount(0u),dualSubmapCount(0u),
			sourceCommandCommitCount(0u),residentProjectionInvocationCount(0u),
			interstageFullGridTransferCount(0u),terminalStagingCount(0u),
			combinedCertifiedWorkingSetBytes(0u),combinedActualMetalAllocationBytes(0u),
			deviceElapsedMS(0.0),representedTimeStepS(0.0f),maximumManifoldGeneration(0.0),
			maximumAcceptedManifoldDeviation(0.0),requiredRestorationDrainFraction(0.0),
			deliveredRestorationDrainFraction(0.0),restorationResidualBandPerS(0.0),
			manifoldPlateauPassed(false),
			conservativeProducerPrecision(RISE::FireStateProducerPrecision::Unknown) {}

	private:
		friend bool AdvanceFireProductionResidentStepMetal(
			const FireProductionResidentStepRequest&,
			FireProductionResidentStepResult&,
			std::string* );
	};
	//! Single owner predicate for accepted-token issuance.  Diagnostics alone do
	//! not mint authority; both projection validations are structural inputs.
	bool FireProductionResidentStepEligibleForAcceptedManifoldToken(
		const FireProductionResidentStepResult& );

	//! Canonical bytes that an accepted production step applies to the next
	//! checkpoint state.  Checkpoint persistence must reproduce this digest;
	//! it cannot transplant a valid observation onto different state bytes.
	inline std::uint64_t FireProductionAcceptedStatePayloadDigest(
		const FireProductionProjectionShape& shape,
		const std::vector<FireProductionRoundoffTrace::TraceFloat>& conservativeValues,
		const std::array<std::vector<FireProductionRoundoffTrace::TraceFloat>,3>& momentum,
		const std::array<std::vector<FireProductionRoundoffTrace::TraceFloat>,3>& velocity )
	{
		std::uint64_t digest=UINT64_C(0x65f07b31c42a98de);
		auto appendWord=[&](const std::uint64_t word) {
			for(unsigned int byte=0u;byte<8u;++byte){
				digest^=static_cast<unsigned char>(word>>(8u*byte));
				digest*=UINT64_C(1099511628211);}
		};
		std::uint64_t fieldTag=0u;
		appendWord(UINT64_C(0x7265736964656e74));
		appendWord(static_cast<std::uint64_t>(shape.nx));
		appendWord(static_cast<std::uint64_t>(shape.ny));
		appendWord(static_cast<std::uint64_t>(shape.nz));
		std::uint32_t widthBits=0u;std::memcpy(&widthBits,&shape.cellWidthM,sizeof(widthBits));
		appendWord(widthBits);
		auto append=[&](const std::vector<FireProductionRoundoffTrace::TraceFloat>& values) {
			appendWord(++fieldTag);appendWord(static_cast<std::uint64_t>(values.size()));
			for(const FireProductionRoundoffTrace::TraceFloat scalar:values){std::uint32_t bits=0u;
				std::memcpy(&bits,&scalar,sizeof(bits));
				for(unsigned int byte=0u;byte<4u;++byte){
					digest^=static_cast<unsigned char>(bits>>(8u*byte));
					digest*=UINT64_C(1099511628211);}}
		};
		append(conservativeValues);
		for(unsigned int axis=0u;axis<3u;++axis){append(momentum[axis]);append(velocity[axis]);}
		return digest^UINT64_C(0xd64b291e3fa5708c);
	}

	//! Full resident P3 shadow step: frozen force, cell and dual transport,
	//! explicit source operands, one physical P2 projection, and one deadbeat
	//! manifold-restoration projection. Full-grid host access is limited to the
	//! terminal step-boundary oracle tap after restoration.
	bool AdvanceFireProductionResidentStepMetal(
		const FireProductionResidentStepRequest& request,
		FireProductionResidentStepResult& result,
		std::string* error=0 );

	//! Thread-local observed Metal commits, exposed only to bind fail-before-work
	//! owner gates. Unsupported builds return zero.
	std::uint64_t FireProductionResidentStepMetalCommandCommitCount();
}

#endif
